package com.sacs.PageOjects;

public enum CostingPricingProductCostingEnum {

	COSTINGPRICING("//*[@id='costingpricing']","xpath"),
	PRODUCT_COSTING("//*[@id='productcosting']/a","xpath"),
	PAGE_HEADING("//*[@id='contentHeader']/div[1]/h1","xpath"),
	CREATE_PRODUCT("//*[@id='addNew']","xpath"),
	PRODUCT_NUMBER("//*[@id='ProductNumber']","xpath"),
	DESCRIPTION1("//*[@id='ProductDescription1']","xpath"),
	CUSTOMER_OPEN_POPUP("//*[@id='ProductForm']/div[2]/div[5]/span[1]/a","xpath"),
	CUSTOMER("//*[@id='CustomerCode']","xpath"),
	QUANTITY("//*[@id='ProductCalculationQty']","xpath"),
	UOM("//*[@id='UnitOfMeasure']","xpath"),
	TYPE("//*[@id='ProductTypeCode']","xpath"),
	OK("OK","linkText"),
	BACK_TO_SEARCH("Back to Search","linkText"),
	PRODUCT_NUMBER_GRID_FIRST_ROW_AFTER_SEARCH("//*[@id='prodCostGrid']/table/tbody/tr/td[1]","xpath"),
	ADD_BOM_ITEM("//*[@id='addBomItem']","xpath"),
	T("//*[@id='bomGrid']/div[6]/div/div/div/div[5]","xpath"),
	T_SELECT("//*[@id='bomGrid']/div[6]/div/div/div/div[5]/select","xpath"),
	NUMBER("//*[@id='bomGrid']/div[6]/div/div/div/div[6]","xpath"),
	WFY("//*[@id='ProductWYF']","xpath"),
	NUMBER_SEARCH_ICON("//*[@id='bomGrid']/div[6]/div/div/div/div[6]/a/span","xpath"),
	SEARCH_PRODUCT_NUMBER_POPUP("//*[@id='ShowProductSearch']","xpath"),
	PROD_NUMBER_ON_SEARCH_PRODUCT_NUMBER_POPUP("//*[@id='searchProductGrid']/table/tbody/tr[1]/td[1]","xpath"),
	APPLY_CHANGES("S","linkText"),
	COPY_BUTTON("//*[@id='copyContainer']/a/div","xpath"),
	COPY_POPUP("//*[@id='copyModal']","xpath"),
	CONTINUE_ON_COPY_POPUP("Continue","linkText"),
	TOASTMESSAGE("toast-message","className"),
	DELETE_PRODUCT("//*[@id='removePoLink']/div","xpath"),
	DELETE_POPUP("//*[@id='loadingModal']","xpath"),
	CONTINUE_ON_DELETE_POPUP("//*[@id='loadingModal']/div[2]/a[2]","xpath"),
	NO_DATA_TO_DISPLAY("//*[@id='prodCostGrid']/table/tbody/tr/td","xpath"),
	EDIT("Edit","linkText"), 
	T_ON_UNIT("//*[@id='bomGrid']/div[6]/div/div/div/div[2]","xpath"),
	T_SELECT_ON_UNIT("//*[@id='bomGrid']/div[6]/div/div/div/div[2]/select","xpath"),
	CPC_TAB("//*[@id='nav']/li[3]/a/div","xpath"),
	CPC_APPLYCHANGES("//*[@id='cpcForm']/div[3]/a[2]","xpath"),
	WASH("//*[@id='cpcTable']/div[7]/div/div/div/div[1]","xpath"),
	WASH_N(".//input[@value='N']","xpath"),
	PREP("//*[@id='cpcTable']/div[7]/div/div/div/div[2]","xpath"),
	PREP_MED_P("//input[@data-name='MED P']","xpath"),
	COOK("//*[@id='cpcTable']/div[7]/div/div/div/div[3]","xpath"),
	COOK_SIMPLE_PP(".//input[@data-name='SIM PP']","xpath"),
	SAVE_CHANGES_POPUP("//*[@id='removeAlert']","xpath"),
	SAVE_ON_SAVE_CHANGES_POPUP("//*[@id='removeAlert']/div[3]/a[1]","xpath"),
	PRODUCTION_RUN_RATE("//*[@id='ProductionRunRate']","xpath"),
	PAGETITLE("//*[@id='contentHeader']/div[1]/h1","xpath"),
	SEARCHBAR("//*[@id='articlesearch']","xpath"),
	SEARCHSUBMIT("//img[@class='searchSubmit']","xpath"),
	SHOW_ENTRY_DROPDOWN("//*[@id='gridWrapper']/div[1]/div[3]/span/span[1]/span[1]","xpath"),
	SHOWING_RESULT(".//*[@id='gridWrapper']/div[3]/span","xpath"),
	MENU("//*[@id='nav']/li[4]/div","xpath"),
	SAES_NUMBER("//*[@id='SalesNumber']","xpath"),
	EFF_DATE("//*[@id='EffectiveDate']","xpath"),
	KEY("//*[@id='KeyField']","xpath"),
	ACTIVE_CHECKBOX(".//label[@for='active']//span","xpath"),
	EXCLUDE_RAW_MAT("//label[@for='rawMat']//span","xpath"),
	CPC(".//label[@for='CCP3']//span","xpath"),
	DESCRIPTION_HEADING("//span[@class='toupper']","xpath"),
	ADDLINE_FIRSTROW("//*[@id='bomGrid']//div[contains(@class,'parentElement')]","xpath"),
	PRODUCT_SEARCH_POPTITLE("//*[@id='ShowProductSearch_wnd_title']","xpath"),
	CANCEL("Cancel","linkText"),
	PRODUCT_SEARCH_RESULT("//*[@id='searchProductGrid']/table/tbody/tr[1]/td[1]","xpath"),
	PRODUCT_SEARCHBAR(".//div[@id='productSearchWrapper']//*[@id='articlesearch']","xpath"),
	PRODUCT_SEARCHSUBMIT("//div[@id='ShowProductSearch']//img[@class='searchSubmit']","xpath"),
	NUMBER_TEXTBOX("//*[@id='bomGrid']/div[6]/div/div/div/div[6]/input","xpath"),
	BA_SEARCH_POPTITLE("//*[@id='showBasicArticleSearch_wnd_title']","xpath"),
	BA_SEARCHBAR(".//div[@id='basicArticleStartWithWrapper']//*[@id='articlesearch']","xpath"),
	BA_SEARCHSUBMIT("//div[@id='basicArticleStartWithWrapper']//img[@class='searchSubmit']","xpath"),
	BA_SEARCH_RESULT("//*[@id='basicArticleStartWithGrid']/table/tbody/tr[1]/td[1]","xpath"),
	BA_SEARCH_RESULT_DESC("//*[@id='basicArticleStartWithGrid']/table/tbody/tr[1]/td[2]","xpath"),
	BA_SEARCH_RESULT_UOM("//*[@id='basicArticleStartWithGrid']/table/tbody/tr[1]/td[7]","xpath"),
	ADDLINE_DESC("//*[@id='bomGrid']/div[6]/div/div/div/div[7]","xpath"),
	ADDLINE_UOM("//*[@id='bomGrid']/div[6]/div/div/div/div[8]","xpath"),
	ADDLINE_WFY("//*[@id='bomGrid']/div[6]/div/div/div/div[9]","xpath"),
	ADDLINE_QUANTITY("//*[@id='bomGrid']/div[6]/div/div/div/div[10]","xpath"),
	ADDLINE_QUANTITY_TEXT("//*[@id='bomGrid']/div[6]/div/div/div/div[10]/input","xpath"),
	ADDLINE_SEQ_TEXT("//*[@id='bomGrid']/div[6]/div/div/div/div[11]/input","xpath"),
	ADDLINE_SEQ("//*[@id='bomGrid']/div[6]/div/div/div/div[11]","xpath"),
	ADDLINE_CATERINGUNIT("//*[@id='bomGrid']/div[6]/div/div/div/div[14]","xpath"),
	ADDLINE_COPY("//*[@id='bomGrid']/div[6]/div/div/div/div[1]/span/a","xpath"),
	ADDLINE_DELETE("//*[@id='bomGrid']/div[6]/div/div/div/div[2]/span/a","xpath"),
	EXPAND("//*[@id='bomGrid']/div[6]/div/div/div/div[6]/span[@class='toggle expand']","xpath"),
	COLLAPSE("//*[@id='bomGrid']/div[6]/div/div/div/div[6]/span[@class='toggle collapse']","xpath"),
	EXPAND_ROW_NUM("//*[@id='bomGrid']/div[6]/div/div/div[2]/div[6]","xpath"),
	EXPAND_ROW_QANT("//*[@id='bomGrid']/div[6]/div/div/div[2]/div[10]","xpath"),
	ADDLINE_RC("//*[@id='bomGrid']/div[6]/div/div/div[1]/div[12]/span","xpath"),
	RC_CHECKBOX("//*[@class='editor-checkbox']","xpath"),
	EXPAND_ROW_NUM_TEXTBOX("//*[@id='bomGrid']/div[6]/div/div/div[2]/div[6]/input","xpath"),
	NUMBER_COL("//*[@id='bomGrid']/div[6]/div/div/div[1]/div[6]","xpath"),
	SEARCH_ICON("//span[@class='icon-search']","xpath"),
	DELETE("//*[@id='removePoLink']/div","xpath"),
	DELETE_POPUP_TEXT("//*[@id='loadingModal']/div[1]/div","xpath"),
	RESULT_GRID("//*[@id='prodCostGrid']/table","xpath"),
	COPY_DETAILLINE_CHECKBOX("//*[@id='copyModal']/div[1]/div[2]/label/span","xpath"),
	POPUP_TEXT("//*[@id='copyModal']/div[1]/div[1]","xpath"),
	RECIPE1_TEXT("//*[@id='RecipeText1']","xpath"),
	RECIPE2_TEXT("//*[@id='RecipeText2']","xpath"),
	RECIPE_POPUP("//*[@id='recipeModal']","xpath"),
	PRODUCT_USED_IN_POPUP("//*[@id='productUsedIn']","xpath"),
	PRODUCT_NO_DATA_DISPLAY("//*[@id='UsedInProductGrid']/div[6]/div","xpath"),
	SALES_MENU("//*[@id='menuContainer']/div","xpath"),
	SALES_MENU_CONNECTION("//*[@id='menuContainer']/ul/li[1]/a","xpath"),
	SALES_PRODUCT_COL("//*[@id='menuConnectionGrid']/div[6]/div/div/div/div[4]","xpath"),
	BOX_CODE_POPUP_TITLE("//*[@id='showboxCodeSearch_wnd_title']","xpath"),
	BOXCODE_SEARCHBAR("//*[@id='boxCodesWrapper']//input[@id='articlesearch']","xpath"),
	BOXCODE_SEARCHSUBMITE("//*[@id='boxCodesWrapper']//img[@class='searchSubmit']","xpath"),
	PRODUCT_POPUP_TITLE("//*[@id='showProductNumberSearch_wnd_title']","xpath"),
	PRODUCT_POPUP_SEARCHBAR("//*[@id='productWrapper']//input[@id='articlesearch']","xpath"),
	PRODUCT_SEARCHSUBMITE("//*[@id='productWrapper']//img[@class='searchSubmit']","xpath"),
	RM_PRICE("//*[@id='RMpriceTypes']","xpath"),
	CPC_2("//*[@id='nav']/li[3]/a/div", "xpath"),
	PREPCOOK("//*[@id='cpcForm']/div[1]/div/ul/li[1]", "xpath"),
	SET_EMPTYFIELDS_NONE("//*[@id='cpcForm']/div[3]/a[1]", "xpath"),
	APPLY_CHANGES2("//*[@id='cpcForm']/div[3]/a[2]", "xpath"),
	CONFIRM_SAVE("//*[@id='removeAlert']/div[3]/a[1]", "xpath"),
	BAKE("//*[@id='cpcForm']/div[1]/div/ul/li[2]", "xpath"),
	PORTIONING("//*[@id='cpcForm']/div[1]/div/ul/li[3]", "xpath"),
	TRAYSET("//*[@id='cpcForm']/div[1]/div/ul/li[4]", "xpath"),
	EQUIPMENT("//*[@id='cpcForm']/div[1]/div/ul/li[5]", "xpath"),
	SALESERVING("//*[@id='cpcForm']/div[1]/div/ul/li[6]", "xpath"),
	TRANSPORT("//*[@id='cpcForm']/div[1]/div/ul/li[7]", "xpath"),
	MAKEPACK("//*[@id='cpcForm']/div[1]/div/ul/li[8]", "xpath"),
	ACCLEAN("//*[@id='cpcForm']/div[1]/div/ul/li[9]", "xpath"),
	OTHER("//*[@id='cpcForm']/div[1]/div/ul/li[10]", "xpath"),
	ADDITEM_STARTDATE_CLICK("//*[@id='bomGrid']/div[6]/div/div/div/div[15]", "xpath"),
	ADDITEM_STARTDATE_INPUT("//*[@id='bomGrid']/div[6]/div/div/div/div[15]/span/span/input", "xpath"),
	ADDITEM_STOPDATE_CLICK("//*[@id='bomGrid']/div[6]/div/div/div/div[16]", "xpath"),
	ADDITEM_STOPDATE_INPUT("//*[@id='bomGrid']/div[6]/div/div/div/div[16]/span/span/input", "xpath"),
	LOTSIZE("//*[@id='LotSize']", "xpath"),
	PACKBOWL_CLICK("//*[@id='cpcTable']/div[7]/div/div/div/div[5]", "xpath"),
	PACKBOWL_INPUT("//*[@id='prdCpcWrapper']/div[5]/div/table/tbody/tr[3]/td[2]/input", "xpath"),
	PACKBOWL_INPUT2("//*[@id='cpcGrid']/div[3]/div/table/tbody/tr[3]/td[2]/input", "xpath"),
	LOTALLOWANCE("//*[@id='LotAllowance']", "xpath"),
	ADDITEM_QTYCLICK("//*[@id='bomGrid']/div[6]/div/div/div/div[10]", "xpath"),
	ADDITEM_QTYINPUT("//*[@id='bomGrid']/div[6]/div/div/div/div[10]/input", "xpath"),
	COOK_CLICK("//*[@id='cpcTable']/div[7]/div/div/div/div[3]", "xpath"),
	COOK_SIMPLE_CLICK("//*[@id='prdCpcWrapper']/div[5]/div/table/tbody/tr[3]/td[2]/input", "xpath"),
	PREPCOOK_POINTS("//*[@id='cpcTable']/div[7]/div/div/div/div[4]", "xpath"),
	PORTIONING_PORT_CLICK("//*[@id='cpcTable']/div[7]/div/div/div/div[1]", "xpath"),
	PORTIONING_PORT_INPUT("//*[@id='cpcGrid']/div[3]/div/table/tbody/tr[3]/td[2]/input", "xpath"),
	PROD_DESC_TEXT("//*[@id='prodCostGrid']/table/tbody/tr/td[2]", "xpath"),
	CUSTOMER_SEARCHICON("//*[@id='ProductForm']/div[3]/div[5]/span[1]/a", "xpath"),
	CUSTOMER_SEARCHBOX("//*[@id='showParentCustomerSearch']/div/div/div/span[1]/input", "xpath"),
	CUSTOMER_SEARCH_ICON("//*[@id='showParentCustomerSearch']/div/div/div/span[2]/a/img", "xpath"),
	CUSTOMER_SINGLEROW("//*[@id='parentcustomerSearchGrid']/table/tbody/tr/td[1]", "xpath"),
	CUSTOMER_POPUP_CANCELBTN("//*[@id='parentCustSearchCancel']", "xpath"),
	EDIT_BTN("//*[@id='editContainer']/a", "xpath"),
	EDITPOPUP_CONTINUEBTN("//*[@id='removeAlert']/div[3]/a[1]", "xpath"),
	OK_BTN("//*[@id='saveContainer']/a", "xpath"),
	SALESNUMBERCONN("//*[@id='nav']/li[4]/ul/li[4]/a", "xpath"),
	SALESNUMBER("//*[@id='addSalesNumber']", "xpath"),
	SALESNO_STARTDATE("//*[@id='salesNumberValidityStartDate']", "xpath"),
	SALESNO_ENDDATE("//*[@id='salesNumberValidityEndDate']", "xpath"),
	SALESNOCONN_OKBTN("//*[@id='salesNoConnectionNew']/div[2]/div[5]/a", "xpath"),
	ADDBOMITEM_SAVEICON("//*[@id='nav']/li[5]/a/div", "xpath"),
	TOTALCPC("//*[@id='cpcForm']/div[1]/div/ul/li[11]/span", "xpath"),
	EMM_TAB("//*[@id='nav']/li[3]/a/div", "xpath"),
	ADD_MAN_MINUTES("//*[@id='addLineWrapper']/div[2]/a", "xpath"),
	AMM_STARTDATE_CLICK("//*[@id='addManMinutesGrid']/div[6]/div/div/div/div[2]", "xpath"),
	AMM_STARTDATE_INPUT("//*[@id='addManMinutesGrid']/div[6]/div/div/div/div[2]/span/span/input", "xpath"),
	AMM_ENDDATE_CLICK("//*[@id='addManMinutesGrid']/div[6]/div/div/div/div[3]", "xpath"),
	AMM_ENDDATE_INPUT("//*[@id='addManMinutesGrid']/div[6]/div/div/div/div[3]/span/span/input", "xpath"),
	HOTKIT_CLICK("//*[@id='addManMinutesGrid']/div[6]/div/div/div/div[4]", "xpath"),
	HOTKIT_INPUT("//*[@id='addManMinutesGrid']/div[6]/div/div/div/div[4]/input", "xpath"),
	AMM_APPLYCHANGESBTN("//*[@id='applyChanges']", "xpath"),
	;
	
	
	
	public String element,Identifier;
	private CostingPricingProductCostingEnum(String element){
		 this.element = element;
	 }
	private CostingPricingProductCostingEnum(String element, String Identifier){
		 this.element = element;
		 this.Identifier = Identifier;
	 }
	public String getElementPath(){
		return element;
	}
	public String getElementIdentifier(){
		return Identifier;
	}
}
