package com.sacs.PageOjects;

public enum CostingPricingCPCEnum {
	COSTING_PRICING("//*[@id='costingpricing']","xpath"),
	SEARCH_RECORD("//*[@id='prodCostGrid']/table/tbody/tr/td[1]", "xpath"),
	CPC("//*[@id='nav']/li[3]/a/div", "xpath"),
	PAGE_TITLE("//*[@id='contentHeader']/div[1]/h1", "xpath"),
	OK_BTN("//*[@id='okButton']", "xpath"),
	TOTAL("//*[@id='cpcForm']/div[1]/div/ul/li[11]", "xpath"),
	PREPBOOK("//*[@id='cpcForm']/div[1]/div/ul/li[1]", "xpath"),
	BAKE("//*[@id='cpcForm']/div[1]/div/ul/li[2]", "xpath"),
	PORTIONING("//*[@id='cpcForm']/div[1]/div/ul/li[3]", "xpath"),
	TRAYSET("//*[@id='cpcForm']/div[1]/div/ul/li[4]", "xpath"),
	EQUIPMENT("//*[@id='cpcForm']/div[1]/div/ul/li[5]", "xpath"),
	SALESERVING("//*[@id='cpcForm']/div[1]/div/ul/li[6]", "xpath"),
	TRANSPORT("//*[@id='cpcForm']/div[1]/div/ul/li[7]", "xpath"),
	MAKEPACK("//*[@id='cpcForm']/div[1]/div/ul/li[8]", "xpath"),
	ACCLEAN("//*[@id='cpcForm']/div[1]/div/ul/li[9]", "xpath"),
	OTHER("//*[@id='cpcForm']/div[1]/div/ul/li[10]", "xpath"),
	PREPBOOK_POINT("//*[@id='cpcForm']/div[1]/div/ul/li[1]/span", "xpath"),
	BAKE_POINT("//*[@id='cpcForm']/div[1]/div/ul/li[2]/span", "xpath"),
	PORTIONING_POINT("//*[@id='cpcForm']/div[1]/div/ul/li[3]/span", "xpath"),
	TRAYSET_POINT("//*[@id='cpcForm']/div[1]/div/ul/li[4]/span", "xpath"),
	EQUIPMENT_POINT("//*[@id='cpcForm']/div[1]/div/ul/li[5]/span", "xpath"),
	SALESERVING_POINT("//*[@id='cpcForm']/div[1]/div/ul/li[6]/span", "xpath"),
	TRANSPORT_POINT("//*[@id='cpcForm']/div[1]/div/ul/li[7]/span", "xpath"),
	MAKEPACK_POINT("//*[@id='cpcForm']/div[1]/div/ul/li[8]/span", "xpath"),
	ACCLEAN_POINT("//*[@id='cpcForm']/div[1]/div/ul/li[9]/span", "xpath"),
	OTHER_POINT("//*[@id='cpcForm']/div[1]/div/ul/li[10]/span", "xpath"),
	HEADER_CUSTOMER("//*[@id='cpcInfo']/table/tbody/tr[2]/td[1]", "xpath"),
	HEADER_PRODUCT("//*[@id='cpcInfo']/table/tbody/tr[2]/td[2]", "xpath"),
	HEADER_QTY("//*[@id='cpcInfo']/table/tbody/tr[2]/td[3]", "xpath"),
	HEADER_PRODRUNRATE("//*[@id='ProductionRunRate']", "xpath"),
	HEADER_CALCULATIONDATE("//*[@id='CalculationDate']", "xpath"),
	HEADER_DESCRIPTION("//*[@id='cpcInfo']/table/tbody/tr[4]/td[1]", "xpath"),
	HEADER_UOM("//*[@id='cpcInfo']/table/tbody/tr[4]/td[2]", "xpath"),
	DETAIL_NO("//*[@id='cpcTable']/div[2]/div/div/div[1]", "xpath"),
	DETAIL_DESCRIPTION("//*[@id='cpcTable']/div[2]/div/div/div[2]", "xpath"),
	DETAIL_UOM("//*[@id='cpcTable']/div[2]/div/div/div[3]", "xpath"),
	DETAIL_QTY("//*[@id='cpcTable']/div[2]/div/div/div[4]", "xpath"),
	DETAIL_CATERINGPOINT("//*[@id='cpcTable']/div[3]/div/div/div[4]", "xpath"),
	APPLYCHANGES_BTN("//*[@id='cpcForm']/div[3]/a[2]", "xpath"),
	ADDITEM("//*[@id='addBomItem']", "xpath"),
	ADDITEM_NUMBERCLICK("//*[@id='bomGrid']/div[6]/div/div/div/div[6]", "xpath"),
	ADDDETAIL_NUMBERSEARCHICON("//*[@id='bomGrid']/div[6]/div/div/div/div[6]/a/span", "xpath"),
	PRODNO_FIRSTROW("//*[@id='searchProductGrid']/table/tbody/tr[1]/td[1]", "xpath"),
	ADDITEM_QTYCLICK("//*[@id='bomGrid']/div[6]/div/div/div/div[10]", "xpath"),
	ADDITEM_QTYINPUT("//*[@id='bomGrid']/div[6]/div/div/div/div[10]/input", "xpath"),
	SAVE_ICON("//*[@id='nav']/li[5]/a/div", "xpath"),
	PRODNO_CPC_FIRSTROW("//*[@id='cpcTable']/div[6]/div/div/div/div[1]", "xpath"),
	PRODNO_WASHCLICK("//*[@id='cpcTable']/div[7]/div/div/div/div[1]", "xpath"),
	WASH_MENU("//*[@id='prdCpcWrapper']/div[6]/div", "xpath"),
	PRODNO_DISPOSECLICK("//*[@id='cpcTable']/div[7]/div/div/div/div[2]", "xpath"),
	DISPOSE_MENU("//*[@id='prdCpcWrapper']/div[6]/div", "xpath"),
	PRODNO_DTPCLICK("//*[@id='cpcTable']/div[7]/div/div/div/div[3]", "xpath"),
	DTP_MENU("//*[@id='prdCpcWrapper']/div[6]/div", "xpath"),
	WASH_NONE("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[2]/td[2]/input", "xpath"),
	WASH_MENU_CLOSE("//*[@id='prdCpcWrapper']/div[6]/div/div/a[2]", "xpath"),
	NONE_TEXT("//*[@id='cpcTable']/div[7]/div/div/div/div[1]", "xpath"),
	WASH_MENU_HELP("//*[@id='prdCpcWrapper']/div[6]/div/div/a[1]", "xpath"),
	WASH_MENU_HELP_TITLE("//*[@id='helpModal_wnd_title']", "xpath"),
	WASH_MENU_HELP_CLOSE("//*[@id='helpModal']/div[2]/a", "xpath"),
	WASH_P("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[3]/td[2]/input", "xpath"),
	PREP_CLICK("//*[@id='cpcTable']/div[7]/div/div/div/div[2]", "xpath"),
	PREP_P_MED("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[4]/td[2]/input", "xpath"),
	PREP_MENU_CLOSE("//*[@id='prdCpcWrapper']/div[6]/div/div/a[2]", "xpath"),
	PREP_MENU_TEXT("//*[@id='cpcTable']/div[7]/div/div/div/div[2]", "xpath"),
	PREP_P_COMPLEX("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[5]/td[2]/input", "xpath"),
	PREP_P_EXCLUSIVE("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[6]/td[2]/input", "xpath"),
	PORT_CLICK("//*[@id='cpcTable']/div[7]/div/div/div/div[1]", "xpath"),
	PORT_P_FIRST("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[7]/td[2]/input", "xpath"),
	PORT_MENU_CLOSE("//*[@id='prdCpcWrapper']/div[6]/div/div/a[2]", "xpath"),
	PORT_MENU_TEXT("//*[@id='cpcTable']/div[7]/div/div/div/div[1]", "xpath"),
	T_CLICK("//*[@id='bomGrid']/div[6]/div/div/div/div[5]", "xpath"),
	T_SELECT("//*[@id='bomGrid']/div[6]/div/div/div/div[5]/select", "xpath"),
	BART_POPUP_SEARCHBOX("//*[@id='basicArticleStartWithWrapper']/div[2]/div/span[1]/input", "xpath"),
	BART_POPUP_SEARCHICON("//*[@id='basicArticleStartWithWrapper']/div[2]/div/span[2]/a/img", "xpath"),
	BART_SEARCHRECORD_DESC("//*[@id='basicArticleStartWithGrid']/table/tbody/tr/td[2]", "xpath"),
	BART_POPUP_OKBTN("//*[@id='selectArticleStartWith']", "xpath"),
	WASH_CLICK("//*[@id='cpcTable']/div[7]/div/div/div/div[1]", "xpath"),
	WASH_PP("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[3]/td[3]/input", "xpath"),
	CATERING_POINTS("//*[@id='cpcTable']/div[7]/div/div/div/div[4]", "xpath"),
	BOM_GRID_FIRSTROW_REMOVEICON("//*[@id='bomGrid']/div[6]/div/div/div/div[2]/span/a", "xpath"),
	DELETEBOM_CONTINUEBTN("//*[@id='removeAlert']/div[3]/a[1]", "xpath"),
	PREP_MED_PP("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[4]/td[3]/input", "xpath"),
	PREP_COMPLEX_PP("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[5]/td[3]/input", "xpath"),
	PREP_EXCLUSIVE_PP("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[6]/td[3]/input", "xpath"),
	COOK_CLICK("//*[@id='cpcTable']/div[7]/div/div/div/div[3]", "xpath"),
	COOK_FIRSTCLASS_PP("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[7]/td[5]/input", "xpath"),
	COOK_SIMPLE_K("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[3]/td[4]/input", "xpath"),
	COOK_MEDIUM_K("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[4]/td[4]/input", "xpath"),
	COOK_COMPLEX_K("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[5]/td[4]/input", "xpath"),
	COOK_EXCLUSIVE_K("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[6]/td[4]/input", "xpath"),
	COOK_FIRSTCLASS_K("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[7]/td[4]/input", "xpath"),
	COOK_SIMPLE_KK("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[3]/td[5]/input", "xpath"),
	COOK_MEDIUM_KK("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[4]/td[5]/input", "xpath"),
	COOK_COMPLEX_KK("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[5]/td[5]/input", "xpath"),
	COOK_EXCLUSIVE_KK("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[6]/td[5]/input", "xpath"),
	COOK_FIRSTCLASS_KK("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[7]/td[5]/input", "xpath"),
	COOK_SIMPLE_P("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[3]/td[2]/input", "xpath"),
	COOK_MEDIUM_P("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[4]/td[2]/input", "xpath"),
	PREP_COMPLEX_K("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[5]/td[4]/input", "xpath"),
	PORTIONING_PORT_CLICK("//*[@id='cpcTable']/div[7]/div/div/div/div[1]", "xpath"),
	MARKSAVE_BTN("//*[@id='removeAlert']/div[3]/a[1]", "xpath"),
	TOTAL_CPC_POINTS("//*[@id='cpcForm']/div[1]/div/ul/li[11]/span", "xpath"),
	PREP_COMPLEXX_KK("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[5]/td[5]/input", "xpath"),
	CPTHISLEVEL("//*[@id='ThisCateringPts']", "xpath"),
	LOTSIZE("//*[@id='LotSize']", "xpath"),
	LOT_ALLOWANCE("//*[@id='LotAllowance']", "xpath"),
	BAKE_PORT_CLICK("//*[@id='cpcTable']/div[7]/div/div/div/div[2]", "xpath"),
	BAKE_SIMPLE_P("//*[@id='prdCpcWrapper']/div[6]/div/table/tbody/tr[3]/td[2]/input", "xpath"),
	CATERING_PTS("//*[@id='CateringPts']", "xpath"),
	CPC_RUNRATE("//*[@id='CpcRunRate']", "xpath"),
	TCLICK2("//*[@id='bomGrid']/div[6]/div/div/div[2]/div[5]", "xpath"),
	TSELECT2("//*[@id='bomGrid']/div[6]/div/div/div[2]/div[5]/select", "xpath"),
	ADDITEM_NUMBERCLICK2("//*[@id='bomGrid']/div[6]/div/div/div[2]/div[6]", "xpath"),
	ADDITEM_NUMBERSEARCHICON2("//*[@id='bomGrid']/div[6]/div/div/div[2]/div[6]/a/span", "xpath"),
	ADDITEM_QTYCLICK2("//*[@id='bomGrid']/div[6]/div/div/div[2]/div[10]", "xpath"),
	ADDITEM_QTYINPUT2("//*[@id='bomGrid']/div[6]/div/div/div[2]/div[10]/input", "xpath"),
	WASHCLICK_2("//*[@id='cpcTable']/div[7]/div/div/div[1]/div[1]", "xpath"),
	WASHCLICK_3("//*[@id='cpcTable']/div[7]/div/div/div[2]/div[1]", "xpath"),
	CATERINGPTS_1("//*[@id='cpcTable']/div[7]/div/div/div[1]/div[4]", "xpath"),
	CATERINGPTS_2("//*[@id='cpcTable']/div[7]/div/div/div[2]/div[4]", "xpath"),
	REMOVE_BOM("//*[@id='bomGrid']/div[6]/div/div/div[1]/div[2]/span/a", "xpath"),
	MENU("//*[@id='nav']/li[4]/div", "xpath"),
	SETACTIVITYGROUP("//*[@id='nav']/li[4]/ul/li[1]/a", "xpath"),
	UPDATEOTHERACTIVITIES("//*[@id='nav']/li[4]/ul/li[2]/a", "xpath"),
	HELPSELECTCORRECTACTIVITY("//*[@id='nav']/li[4]/ul/li[3]/a", "xpath"),
	RECIPETEXT("//*[@id='nav']/li[4]/ul/li[4]/a", "xpath"),
	BACK_BTN("//*[@id='backToCpc']", "xpath"),
	NEW_ACTIVITY_BTN("//*[@id='newActivity']", "xpath"),
	NEWACTIVITY_POPUP_TITLE("//*[@id='updateModal_wnd_title']", "xpath"),
	NEWACTIVITY_POPUP_CANCELBTN("//*[@id='frmActivity']/div[7]/a[1]", "xpath"),
	ACTIVITY_DESC_LONG("//*[@id='ActivityText']", "xpath"),
	ACTIVITY_DESC_SHORT("//*[@id='Activity']", "xpath"),
	ACTIVITY_PRIMARY_CAT_PTS("//*[@id='PrimaryCateringPoint']", "xpath"),
	NEWACTIVITY_POPUP_CONTINUEBTN("//*[@id='btnSave']", "xpath"),
	LOTSIZE_EDITICON("//*[@id='cpcInfo']/table/tbody/tr[2]/td[5]/a", "xpath"),
	LOTSIZE_POPUP_TITLE("//*[@id='unitLotSizeWrapper_wnd_title']", "xpath"),
	LOTSIZE_POPUP_CLOSEBTN("//*[@id='closeUnitLot']", "xpath"),
	LOTSIZE_POPUP_CONTINUEBTN("//*[@id='saveUnitLot']", "xpath"),
	COSTPURPOSE_CLICK("//*[@id='lotResults']/div[6]/div/div/div/div[2]", "xpath"),
	COSTING_PURPOSE_INPUT("//*[@id='lotResults']/div[6]/div/div/div/div[2]/input", "xpath"),
	HELPSELECTACTIVITY_POPUP_TITLE("html/body/div[6]/div[1]/span", "xpath"),
	HELPSELECTACTIVITY_POPUP_CLOSEBTN("html/body/div[6]/div[2]/div[6]/a", "xpath"),
	LOW_INGREDIENT("html/body/div[5]/div[2]/div[1]/div[3]/label", "xpath"),
	LOW_COOKING_ATTENDENCE("html/body/div[5]/div[2]/div[2]/div[3]/label", "xpath"),
	LOW_TYPE_OF_INGREDIENT("html/body/div[5]/div[2]/div[3]/div[3]/label", "xpath"),
	LOW_BATCHSIZE("html/body/div[5]/div[2]/div[4]/div[3]/label", "xpath"),
	SELECTED_ACTIVITY("html/body/div[5]/div[2]/div[5]", "xpath"),
	HELPSELECTACTIVITYPOPUP_CLOSEBTN2(" html/body/div[5]/div[2]/div[6]/a", "xpath"),
	BOM_COPYICON_FIRSTROW("//*[@id='bomGrid']/div[6]/div/div/div/div[1]/span/a", "xpath"),
	CPC_QTY("//*[@id='cpcTable']/div[6]/div/div/div/div[4]", "xpath"),
	BOM_CUNIT_CLICK("//*[@id='bomGrid']/div[6]/div/div/div/div[14]", "xpath"),
	BOM_CUNIT_SELECT("//*[@id='bomGrid']/div[6]/div/div/div/div[14]/select", "xpath"),
	PRODUCT_SEARCHBOX("//*[@id='ShowProductSearch']/div/div/div/span[1]/input", "xpath"),
	PRODUCT_SEARCHICON("//*[@id='ShowProductSearch']/div/div/div/span[2]/a/img", "xpath"),
	SEARCH_PRODUCT_DESC_SEARCHRECORD("//*[@id='searchProductGrid']/table/tbody/tr/td[2]", "xpath"),
	SEARCH_PRODUCT_CONTINUEBTN("//*[@id='productSearchWrapper']/div[4]/a[2]", "xpath"),
	PRIMARY_WORKCENTER("//*[@id='cpcTable']/div[6]/div/div/div[1]/div[2]", "xpath"),
	DISHWASHING("//*[@id='cpcTable']/div[6]/div/div/div[1]/div[3]", "xpath"),
	ASSEMBLY("//*[@id='cpcTable']/div[6]/div/div/div[1]/div[4]", "xpath"),
	DEPARTMENT_FIRSTROW("//*[@id='cpcTable']/div[6]/div/div/div[1]/div[1]", "xpath"),
	COSTING_PARAMETER("//*[@id='costingparameter']/a", "xpath"),
	CP_FIRSTROW("//*[@id='results']/table/tbody/tr[1]/td[1]", "xpath"),
	GAT_FIRSTROW("//*[@id='cpcTable']/div[6]/div/div/div[1]/div[7]", "xpath"),
	IPT_FIRSTROW("//*[@id='cpcTable']/div[6]/div/div/div[1]/div[6]", "xpath"),
	PROD_FACTOR_FIRSTROW("//*[@id='cpcTable']/div[6]/div/div/div[1]/div[8]", "xpath"),
	WORKCENTER_DD("//*[@id='WorkCenterCode']", "xpath"),
	ASSIGN_WORKCENTER_BTN("//*[@id='editContainer']/div[2]/a", "xpath"),
	WASHED_STD_BOX("//*[@id='cpcTable']/div[7]/div/div/div/div[10]", "xpath"),
	CPC_TOTAL_1("//*[@id='cpcTable']/div[6]/div/div/div[1]/div[5]", "xpath"),
	CPC_TOTAL_2("//*[@id='cpcTable']/div[6]/div/div/div[3]/div[5]", "xpath"),
	CPC_TOTAL_3("//*[@id='cpcTable']/div[6]/div/div/div[6]/div[5]", "xpath"),
	DISHCATERINGPTS_TOTAL("//*[@id='cpcTable']/div[6]/div/div/div[15]/div[5]", "xpath"),
	STD_TIME_FIRSTROW("//*[@id='cpcTable']/div[6]/div/div/div[1]/div[9]", "xpath"),
	STDTIME_TOTAL("//*[@id='cpcTable']/div[6]/div/div/div[15]/div[9]", "xpath"),
	;
	
	public String element,Identifier;
	private CostingPricingCPCEnum(String element){
		 this.element = element;
	 }
	private CostingPricingCPCEnum(String element, String Identifier){
		 this.element = element;
		 this.Identifier = Identifier;
	 }
	public String getElementPath(){
		return element;
	}
	public String getElementIdentifier(){
		return Identifier;
	}
}
