package com.sacs.PageOjects;

public enum CostingPricingSalesPricingEnum {
	COSTINGPRICING("costingpricing","id"),
	SALESPRICING("salesprice","id"),
	ADD_SALES_PRICE("addNew","id"),
	SALES_NUMBER("SalesNumber","id"),
	DESCRIPTION("Description","id"),
	UOM("UOM","id"),
	MAIN_TURN_OVER_GROUP("MainTurnoverGrpCode","id"),
	SUB_TURN_OVER_GROUP("SubTurnoverGrpCode","id"),
	OK_BUTTON("//div[@id='saveContainer']//a[@id='okButton']","xpath"),
	FIRST_ROW_FIRST_COL(".//*[@id='results']/table/tbody/tr[1]/td[1]","xpath"),
	THIRD_ROW_FIRST_COL(".//*[@id='results']/table/tbody/tr[3]/td[1]","xpath"),
	ADD_LINE_BUTTON("Add Line","linkText"),
	ADD_LINE_CUSTOMER_CODE(".//*[@id='salesPriceGrid']/div[6]/div/div/div/div[4]","xpath"),
	ADD_LINE_START_DATE("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[8]","xpath"),
	ADD_LINE_START_DATE_INPUT("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[8]/span/span/input","xpath"),
	ADD_LINE_STOP_DATE("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[9]","xpath"),
	ADD_LINE_CUSTOMER_CODE_SAERCHICON(".//a[@class='slickSearch']","xpath"),
	CUSTOMER_POPUP_FIRSTROW(".//*[@id='customerSearchGrid']/table/tbody/tr[1]/td[1]","xpath"),
	ADD_LINE_STOP_DATE_INPUT("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[9]/span/span/input","xpath"),
	APPLY_CHANGES("Apply Changes","linkText"),
	BACK_TO_SEARCH("//*[@id='backToSearch']","xpath"),
	EDIT("//*[@id='editContainer']/a","xpath"),
	EDIT_POPUP_CONTINUE(".//*[@id='removeAlert']/div[3]/a[1]","xpath"),
	DELETE_ICON("X","linkText"),
	COPY_ICON("C","linkText"),
	APPLY_CHANGES_ICON("//*[@id='nav']/li[5]/a/div","xpath"),
	PAGETITLE(".//*[@id='contentHeader']/div[1]/h1","xpath"),
	SEARCH_BOX("//*[@id='articlesearch']","xpath"),
	SEARCH_RESULT("//*[@id='results']","xpath"),
	SHOW_ENTERIES("//*[@id='gridWrapper']/div[1]/div[3]/span/span[1]/span[1]","xpath"),
	PAGINATION("//*[@id='gridWrapper']/div[3]/div","xpath"),
	INVERTED_SYMBOL("//*[@id='searchContainer']/div[1]/span[3]/a/img","xpath"),
	SEARCH_CONTAINER("//*[@id='searchContainer']/div[2]","xpath"),
	SALES_NUMBER_CRITERIA("//*[@id='searchContainer']/div[2]/div[1]/label/span","xpath"),
	DESCRIPTION_CRITERIA("//*[@id='searchContainer']/div[2]/div[2]/label[1]/span","xpath"),
	NO_DATA_TO_DISPLAY("//*[@id='results']/table/tbody/tr/td","xpath"),
	SEARCH_SUBMIT("//*[@id='searchContainer']/div[1]/span[2]/a/img","xpath"),
	SEARCH_RESULT_GRID_NEXT_LINK_XPATH("//*[@id='gridWrapper']/div[3]/div/a[3]/span","xpath"),
	SEARCH_RESULT_GRID_PREVIOUS_LINK_XPATH("//*[@id='gridWrapper']/div[3]/div/a[2]/span","xpath"), 
	SEARCH_RESULT_GRID_FIRST_LINK_XPATH("//*[@id='gridWrapper']/div[3]/div/a[1]/span","xpath"), 
	SEARCH_RESULT_GRID_LAST_LINK_XPATH("//*[@id='gridWrapper']/div[3]/div/a[4]/span","xpath"),
	SEARCH_ENTERIES_INVERTER_SYMBOL("//*[@id='gridWrapper']/div[1]/div[3]/span/span[1]/span[2]","xpath"),
	SEARCH_RESULT_GRID_SELECT_ITEMS_PER_PAGE_LIST_CLASS("k-item"),
	FIRST_ROW_SECOND_COL("//*[@id='results']/table/tbody/tr[1]/td[2]","xpath"),
	DESCRIPTION2("//*[@id='Description2']","xpath"),
	CLASS_CODE("//*[@id='ClassCode']","xpath"),
	GST("//*[@id='VATId']","xpath"),
	SURCHARGE("//*[@id='SurchargeId']", "xpath"),
	MENU_TYPE("//*[@id='ProductType']","xpath"),
	SPML_TYPE("//*[@id='SpecialMealType']","xpath"),
	DISTRIBUTION_CODE("//*[@id='DistributionCode']","xpath"),
	MEAL_FACTOR("//*[@id='MealFactor']","xpath"),
	LAST_UPDATED("//*[@id='lastUpdated']","xpath"),
	AIRPORT_FEE_SEARCH_ICON("//*[@id='spForm']/div[2]/div[1]/span/a","xpath"),
	AIRPORT_FEE_POPUP("//*[@id='airportFeePopup']","xpath"),
	AIRPORT_FEE_POPUP_FIRST_ROW("//*[@id='airportFeeGrid']/table/tbody/tr[1]/td[1]","xpath"),
	AIRPORT_FEE_POPUP_OK("//*[@id='selAirFeeContinue']","xpath"),
	DELETE_POPUP_CONTINUE(".//*[@id='loadingModal']/div[2]/a[2]","xpath"),
	ADD_LINE_COPY("//*[@id='bomGrid']/div[6]/div/div/div/div[1]/span/a","xpath"),
	MENU("//*[@id='menuContainer']/div","xpath"),
	EXPORT("//*[@id='addLineContainer']/a[2]","xpath"),
	SALES_PRICE_GRID("//*[@id='salesPriceGrid']","xpath"),
	SALES_GRID_ADD_LINE_HEADING("//*[@id='salesPriceGrid']/div[2]/div[1]","xpath"),
	ADD_LINE_CUST("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[4]","xpath"),
	ERROR_ICON(".//*[@class='errorIcon']","xpath"),
	ERROR_ALERT_POPUP("//*[@id='errorAlert']","xpath"),
	ERROR_ALERT_POPUP_TEXT("//*[@class='alertErrorText']/ul","xpath"),
	OK_ON_ERROR_ALERT("//*[@id='errorAlert']/div[3]/a","xpath"),
	ADD_LINE_CUST_INPUT("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[4]/input","xpath"),
	ADD_LINE_CUST_SEARCH_ICON("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[4]/a/span","xpath"),
	SEARCH_CUSTOMER_POPUP("//*[@id='showCustomerCodeSearch']","xpath"),
	SEARCH_CUSTOMER_POPUP_FIRST_ROW("//*[@id='customerSearchGrid']/table/tbody/tr[1]/td[2]","xpath"),
	ADD_LINE_UNIT("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[5]","xpath"),
	ADD_LINE_UNIT_SELECT("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[5]/select","xpath"),
	ADD_LINE_UNIT_SELECT_FIRST_VALUE("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[5]/select/option[2]","xpath"),
	ADD_LINE_GROUP("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[6]","xpath"),
	ADD_LINE_GROUP_SECLECT_ICON("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[6]/a/span","xpath"),
	ADD_LINE_GROUP_SEARCH_POPUP("//*[@id='showCustomerTurnoverGroupSearch']","xpath"),
	ADD_LINE_GROUP_POPUP_FIRST_ROW("//*[@id='customerTurnoverGroupGrid']/table/tbody/tr[1]/td[1]","xpath"),
	ADD_LINE_PRICE("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[10]","xpath"),
	ADD_LINE_PRICE_INPUT("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[10]/input","xpath"),
	ADD_LINE_CURRENCY("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[10]","xpath"),
	ADD_LINE_CURRENCY_INPUT("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[10]/select","xpath"),
	ADD_LINE_SI("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[11]","xpath"),
	ADD_LINE_SI_INPUT("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[11]/input","xpath"),
	ADD_LINE_CUST_ITEM_NUMBER("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[12]","xpath"),
	ADD_LINE_CUST_ITEM_NUMBER_INPUT("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[12]/input","xpath"),
	ADD_LINE_ROTATION("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[13]","xpath"),
	ADD_LINE_ROTATION_INPUT("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[13]/input","xpath"),
	ADD_LINE_ROTATION_SELECT("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[13]/a/span","xpath"),
	ROTATION_PLAN_POPUP("//*[@id='showRotationPlanSearch']","xpath"),
	ROTATION_PLAN_POPUP_FIRST_ROW("//*[@id='rotPlanSearchgrid']/table/tbody/tr[1]/td[1]","xpath"),
	CONTINUE_ON_ROTATION_PLAN_POPUP("//*[@id='selRotPlanContinue']","xpath"),
	CANCEL_ON_ROTATION_PLAN_POPUP("//*[@id='cancelRotPlan']","xpath"),
	ADD_LINE_N("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[15]","xpath"), 
	ADD_LINE_N_INPUT("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[15]/input","xpath"),
	INFO_ICON_BOX("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[14]","xpath"),
	INFO_ICON("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[14]/span/a","xpath"),
	ROTATION_PLAN_INFO_POPUP("//*[@id='rotCalenderContainer']","xpath"),
	CANCEL_ROTATION_PLAN_INFO_POPUP("//*[@id='cancelPlanCal']","xpath"),
	DISCOUNT("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[16]","xpath"),
	DISCOUNT_SELECT("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[16]/select","xpath"),
	REMOVE_ICON("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[2]/span/a","xpath"),
	REMOVE_POPUP("//*[@id='removeAlert']","xpath"),
	REMOVE_POPUP_CONTINUE("//*[@id='removeAlert']/div[3]/a[1]","xpath"),
	ADD_LINE_COPY_BUTTON("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[1]/span/a","xpath"),
	START_DATE_SECOND_LINE("//*[@id='salesPriceGrid']/div[6]/div/div/div[2]/div[7]","xpath"),
	START_DATE_SECOND_LINE_INPUT("//*[@id='salesPriceGrid']/div[6]/div/div/div[2]/div[7]/span/span/input","xpath"),
	POPUP_TEXT("//*[@id='removeAlert']/div[2]","xpath"),
	MENU_CONNECTIONS(".//*[@id='menuContainer']/ul/li[1]/a","xpath"),
	ADD_LINE_MENU_CONNECTION_PRODUCT("//*[@id='menuConnectionGrid']/div[6]/div/div/div/div[4]","xpath"),
	CUSTCODE_SEARCHPOP_TEXTBOX("//*[@id='showCustomerCodeSearch']/div/div/div[1]/span[1]/input", "xpath"),
	CUSTCODE_SEARCHPOP_SEARCHICON("//*[@id='showCustomerCodeSearch']//img[@class='searchSubmit']", "xpath"),
	SELECT_CUSTOMER("//*[@id='customerSearchGrid']/table/tbody/tr/td[1]", "xpath"),
	USC_GROUP("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[6]", "xpath"),
	USC_GROUPSEARCHICON("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[6]/a/span", "xpath"),
	CTOG_SEARCHPOP_TEXTBOX("//*[@id='customerTurnoverGroupWrapper']/div/div[1]/span[1]/input", "xpath"),
	CTOG_SEARCHPOP_SEARCHICON("//*[@id='customerTurnoverGroupWrapper']//img[@class='searchSubmit']", "xpath"),
	SELECTGROUP("//*[@id='customerTurnoverGroupGrid']/table/tbody/tr/td[1]", "xpath"),
	SINGLEROW("//*[@id='results']/table/tbody/tr/td[1]", "xpath"),
	CUSTOMERS_SEARCHBOX("//*[@id='showCustomerCodeSearch']/div/div/div/span[1]/input", "xpath"),
	CUSTOMERS_SEARCHICON("//*[@id='showCustomerCodeSearch']/div/div/div/span[2]/a/img", "xpath"),
	CUSTOMER_SINGLEROW("//*[@id='customerSearchGrid']/table/tbody/tr/td[1]", "xpath"),
	CUSTOMER_POPUP_CANCELBTN("//*[@id='childCustSearchCancel']", "xpath"),
	MAINTUTRNOVERGROUP("//*[@id='MainTurnoverGrpCode']", "xpath"),
	SUBGROUP("//*[@id='SubTurnoverGrpCode']", "xpath"),
	EDIT_OKBTN("//*[@id='saveContainer']/a", "xpath"),
	OKBTN("//*[@id='loadingModal']/div[2]/a", "xpath"),
	CUST("//*[@id='salesPriceGrid']/div[6]/div/div/div[1]/div[4]", "xpath"),
	MENUCONN_PRODUCTHEADER("//*[@id='dvMenuConnectionGrid']/div/div[2]/div[1]/div/div[4]/span[1]", "xpath"),
	MENUCONN_DESCHEADER("//*[@id='dvMenuConnectionGrid']/div/div[2]/div[1]/div/div[5]/span[1]", "xpath"),
	MENUCONN_UOMHEADER("//*[@id='dvMenuConnectionGrid']/div/div[2]/div[1]/div/div[6]/span[1]", "xpath"),
	MENUCONN_STARTDATEHEADER("//*[@id='dvMenuConnectionGrid']/div/div[2]/div[1]/div/div[7]/span[1]", "xpath"),
	MENUCONN_STOPDATEHEADER("//*[@id='dvMenuConnectionGrid']/div/div[2]/div[1]/div/div[8]/span[1]", "xpath"),
	MENUCONN_RESTITUTIONHEADER("//*[@id='dvMenuConnectionGrid']/div/div[2]/div[1]/div/div[9]/span[1]", "xpath"),
	MENUCONN_REFUNDHEADER("//*[@id='dvMenuConnectionGrid']/div/div[2]/div[1]/div/div[10]/span[1]", "xpath"),
	ADDLINE("//*[@id='addLine']", "xpath"),
	APPLYCHANGES("//*[@id='applyChanges']", "xpath"),
	PRODUCTNO_CLICK("//*[@id='menuConnectionGrid']/div[6]/div/div/div/div[4]", "xpath"),
	PRODUCTNO_INPUT("//*[@id='menuConnectionGrid']/div[6]/div/div/div/div[4]/input", "xpath"),
	PRODUCTNO_SEARCHICON("//*[@id='menuConnectionGrid']/div[6]/div/div/div/div[4]/a/span", "xpath"),
	PRODUCTNO_POPUPTITLE("//*[@id='showProductSearch_wnd_title']", "xpath"),
	PRODUCTNO_POPUP_CANCELBTN("//*[@id='cancelProduct']", "xpath"),
	PRODUCTNO_POPUP_CONTINUEBTN("//*[@id='selProductContinue']", "xpath"),
	PRODCUTNO_FIRSTROW("//*[@id='productSearchGrid']/table/tbody/tr[1]/td[1]", "xpath"),
	PRODUCTNO_DESCRIPTION_CLICK("//*[@id='menuConnectionGrid']/div[6]/div/div/div/div[5]", "xpath"),
	PRODNO_STARTDATE_CLICK("//*[@id='menuConnectionGrid']/div[6]/div/div/div/div[7]", "xpath"),
	PRODNO_STARTDATE_INPUT("//*[@id='menuConnectionGrid']/div[6]/div/div/div/div[7]/span/span/input", "xpath"),
	PRODNO_STOPDATE_CLICK("//*[@id='menuConnectionGrid']/div[6]/div/div/div/div[8]", "xpath"),
	PRODNO_STOPDATE_INPUT("//*[@id='menuConnectionGrid']/div[6]/div/div/div/div[8]/span/span/input", "xpath"),
	PRODNO_DESC_FIRSTROW("//*[@id='productSearchGrid']/table/tbody/tr[1]/td[2]", "xpath"),
	PRODNO_UOM_FIRSTROW("//*[@id='productSearchGrid']/table/tbody/tr[1]/td[8]", "xpath"),
	ADDLINE_PRODNO_UOM_FIRSTROW("//*[@id='menuConnectionGrid']/div[6]/div/div/div/div[6]", "xpath"),
	PRODUCTNO_CLICK2("//*[@id='menuConnectionGrid']/div[6]/div/div/div[2]/div[4]", "xpath"),
	PRODUCTNO_SEARCHICON2("//*[@id='menuConnectionGrid']/div[6]/div/div/div[2]/div[4]/a/span", "xpath"),
	PRODUCTNO_SECONDROW("//*[@id='productSearchGrid']/table/tbody/tr[2]/td[1]", "xpath"),
	ATTENTIONPOPUP("//*[@id='loadingModal_wnd_title']", "xpath"),
	ATTENTIONPOPUP_CANCELBTN("//*[@id='loadingModal']/div[2]/a[1]", "xpath"),
	PRODNO_STARTDATE_CLICK2("//*[@id='menuConnectionGrid']/div[6]/div/div/div[2]/div[7]", "xpath"),
	PRODNO_STARTDATE_INPUT2("//*[@id='menuConnectionGrid']/div[6]/div/div/div[2]/div[7]/span/span/input", "xpath"),
	PRODNO_STOPDATE_CLICK2("//*[@id='menuConnectionGrid']/div[6]/div/div/div[2]/div[8]", "xpath"),
	PRODNO_STOPDATE_INPUT2("//*[@id='menuConnectionGrid']/div[6]/div/div/div[2]/div[8]/span/span/input", "xpath"),
	ATTENTION_POPUP_TEXT("//*[@id='loadingModal']/div[1]/div", "xpath"),
	REFUND_CLICK("//*[@id='menuConnectionGrid']/div[6]/div/div/div/div[10]", "xpath"),
	REFUND_INPUT("//*[@id='menuConnectionGrid']/div[6]/div/div/div/div[10]/input", "xpath"),
	REFUND_CLICK2("//*[@id='menuConnectionGrid']/div[6]/div/div/div[2]/div[10]", "xpath"),
	REFUND_INPUT2("//*[@id='menuConnectionGrid']/div[6]/div/div/div[2]/div[10]/input", "xpath"),
	MENUCONN_COPYICON_FIRSTROW("//*[@id='menuConnectionGrid']/div[6]/div/div/div/div[1]/span/a", "xpath"),
	PRODNO_DESC_CLICK2("//*[@id='menuConnectionGrid']/div[6]/div/div/div[2]/div[5]", "xpath"),
	PRODNO_UOM_CLICK2("//*[@id='menuConnectionGrid']/div[6]/div/div/div[2]/div[6]", "xpath"),
	MENUCONN_REMOVEICON_2("//*[@id='menuConnectionGrid']/div[6]/div/div/div[2]/div[2]/span/a", "xpath"),
	WHEREISSALESNUMBERUSED("//*[@id='menuContainer']/ul/li[2]/a", "xpath"),
	WSNU_POPUP_TITLE("//*[@id='viewWhereSalesNumberUsedIn_wnd_title']", "xpath"),
	WSNU_POPUP_EXPORTBTN("//*[@id='viewWhereSalesNumberUsedIn']/div[1]/a", "xpath"),
	WSNU_POPUP_CLOSEBTN("//*[@id='closeButton']", "xpath"),
	WSNU_POPUP_NODATATODISPLAY("//*[@id='salesNumberUsedInGrid']/table/tbody/tr/td", "xpath"),
	UPDATEPAGE_TITLE("//*[@id='contentHeader']/div[1]/div[1]/h1", "xpath"),
	WSNU_POPUP_DP_FIRSTROW("//*[@id='salesNumberUsedInGrid']/table/tbody/tr/td[2]", "xpath"),
	WHERESALESNUMBERUSED_UNIT("//*[@id='menuContainer']/ul/li[1]/a", "xpath"),
	SALESNUMBERSTATISTICS("//*[@id='menuContainer']/ul/li[2]/a", "xpath"),
	SNS_TITLE("//*[@id='salesNumberStat_wnd_title']", "xpath"),
	SNS_FROMDATE("//*[@id='from']", "xpath"),
	SNS_TODATE("//*[@id='to']", "xpath"),
	SNS_OKBTN("//*[@id='salesNumberStat']/div[2]/a[2]", "xpath"),
	SNS_CANCELBTN("//*[@id='salesNumberStat']/div[2]/a[1]", "xpath"),
	SNS_INCURRENCY("//*[@id='InCurrency']", "xpath"),
	REMOVE_ICON2("//*[@id='removePoLink']/div", "xpath"),
	COPYSALESICON("//*[@id='copyContainer']/a/div", "xpath"),
	COPY_SALESCODE_TITLE("//*[@id='copyModal_wnd_title']", "xpath"),
	COPY_SALESCODE_CANCELBTN("//*[@id='copyModal']/div[2]/a[1]", "xpath"),
	CSN_COPYDETAILSLINES_CHKBOX("//*[@id='copyModal']/div[1]/div[2]/label[1]/span", "xpath"),
	CSN_COPYPRICES_CHKBOX("//*[@id='copyModal']/div[1]/div[2]/label[2]/span", "xpath"),
	COPY_SALESCODE_CONTINUEBTN("//*[@id='continueButton']", "xpath"),
	CSN_OKBTN("//*[@id='okButton']", "xpath"),
	VIEWCOST("//*[@id='menuContainer']/ul/li[3]/a", "xpath"),
	VIEWCOST_PRICES_DROPDOWN("//*[@id='priceTypes']", "xpath"),
	VIEWCOST_DATE("//*[@id='calculateOnDate']", "xpath"),
	VIEWCOST_OKBTN("//*[@id='productCostCalculations']/div/div[2]/span[3]/a", "xpath"),
	COSTCALCULATION("//*[@id='spCostCalInfo']/table[1]/tbody/tr[1]/th", "xpath"),
	SUGGESTEDSALESCODES("//*[@id='spCostCalInfo']/table[2]/tbody/tr[1]/th", "xpath"),
	PRODUCTION_PAPER_PRINTERS("//*[@id='menuContainer']/ul/li[6]/a", "xpath"),
	PPP_PRINTER1("//*[@id='checkSelBox00']", "xpath"),
	PPP_PRINTER2("//*[@id='checkSelBox10']", "xpath"),
	PPP_CANCELBTN("//*[@id='paperPtrModal']/div[3]/a[1]", "xpath"),
	PPP_OKBTN("//*[@id='paperPtrModal']/div[3]/a[2]", "xpath"),
	BASICARTICLE_CONN("//*[@id='menuContainer']/ul/li[5]/a", "xpath"),
	BA_CONN_ADDLINE_BTN("//*[@id='addBaLine']", "xpath"),
	BAC_ARTICLENUMBER_CLICK("//*[@id='articleConnectionGrid']/div[6]/div/div/div/div[2]", "xpath"),
	BAC_ARTNUM_SEARCHICON("//*[@id='articleConnectionGrid']/div[6]/div/div/div/div[2]/a/span", "xpath"),
	BAC_ARTNUM_TEXT("//*[@id='basicArticleGrid']/table/tbody/tr[1]/td[1]/span[1]", "xpath"),
	BAC_ARTNUM_FIRSTROW("//*[@id='basicArticleGrid']/table/tbody/tr[1]/td[1]", "xpath"),
	BAC_APPLYCHANGES("//*[@id='artapplyChanges']", "xpath"),
	BAART_TOPPORTION("//*[@id='viewHeader']/form/div[2]/div[5]/span", "xpath"),
	SALESCODE_DESC_PIC("//*[@id='contentHeader']/div[1]/div[2]/span[2]", "xpath"),
	BLANKCLICK("//*[@id='salesPriceGrid']/div[6]/div/div/div/div[3]", "xpath"),
	;
	public String element,Identifier;
	private CostingPricingSalesPricingEnum(String element){
		 this.element = element;
	 }
	private CostingPricingSalesPricingEnum(String element, String Identifier){
		 this.element = element;
		 this.Identifier = Identifier;
	 }
	public String getElementPath(){
		return element;
	}
	public String getElementIdentifier(){
		return Identifier;
	}
}
