package com.sacs.PageOjects;

public enum DispatchFlightOverviewEnum {
	
	
	DISPATCH("//*[@id='dispatch']", "xpath"),
	FLIGHT_OVERVIEW("//*[@id='flightoverview']/a","xpath"),
	FLIGHT_OVERVIEW_TITLE("//*[@id='contentHeader']/div[1]/h1","xpath"),
	PAGE_TITLE("//*[@id='contentHeader']/div[1]/h1","xpath"),
	OK_ON_LANDING_PAGE("//*[@id='processFtt']","xpath"),
	APPLY_CHANGES("//*[@id='saveGenDetails']","xpath"),
	EXPAND_ARROW(".//*[@id='myGrid']/div[6]/div/div/div[1]/div[3]/span[@class='toggle']","xpath"),
	TRUCK_COLUMN_WITH_EXPAND_ARROW_ON_GRID("//*[@id='myGrid']/div[7]/div/div/div[1]/div[8]/div","xpath"),
	//TRUCK_COLUMN_WITH_EXPAND_ARROW_ON_GRID("//*[@id='myGrid']/div[7]/div/div/div/div[10]/div","xpath"),
	TRUCK_COLUMN_WITH_EXPAND_ARROW_ON_GRID_INPUT("//*[@id='myGrid']/div[7]/div/div/div[1]/div[8]/input","xpath"),
	TRUCK_COLUMN_WITHOUT_EXPAND_ARROW_ON_GRID("//*[@id='myGrid']/div[7]/div/div/div[1]/div[10]/div","xpath"),
	TRUCK_COLUMN_WITHOUT_EXPAND_ARROW_ON_GRID_INPUT("//*[@id='myGrid']/div[7]/div/div/div[1]/div[10]/input","xpath"),
	CONTINUE_POPUP("//*[@id='removeAlert']","xpath"),
	CONTINUE_ON_CONTINUE_POPUP("//*[@id='removeAlert']/div[3]/a[1]","xpath"),
	PAX_OVERVIEW_TAB("//*[@id='paxOverTab']","xpath"),
	FIRST_FLIGHT_A(".//*[@id='myPaxGrid']/div[6]/div/div/div[2]/div[5]","xpath"),
	FIRST_FLIGHT_A_INPUT(".//*[@id='myPaxGrid']/div[6]/div/div/div[2]/div[5]/input","xpath"),
	RETURN_TO_OVERVIEW("//*[@id='backToSearch']","xpath"),
	LAST_ACTUALIZED_DATE("//*[@id='results']/table/tbody/tr[1]/td","xpath"),					
	EDIT_ON_FIRST_ROW("//*[@id='errRow1' and contains(@title, 'Edit Flight Overview')]","xpath"),
	FCP("//*[@id='paxResults']/div[7]/div/div/div[1]/div[3]","xpath"),
	FCP_INPUT("//*[@id='paxResults']/div[7]/div/div/div[1]/div[3]/input","xpath"),
	APPLY_CHANGES_ONSINGLE_PAGE(".//*[@id='applyChanges']","xpath"),
	ACTUALIZED_DATE("//*[@id='ActualizedDate']","xpath"),
	FLIGHT_SEARCH_BUTTON("//*[@id='fovForm']/div[3]/span/a","xpath"),
	INPUT_BOX_ON_FLIGHT_SEARCH_POPUP(".//*[@id='showActFltSearch']/div[1]/div[1]//input[@id='articlesearch']","xpath"),
	INVERTED_SYMBOL_ON_FLIGHT_SEARCH_POPUP("//*[@id='showActFltSearch']/div[1]/div[1]/span[3]/a/img","xpath"),
	SEARCH_SUBMIT_ON_FLIGHT_SEARCH_POPUP("//*[@id='showActFltSearch']/div[1]/div[1]/span[2]/a/img","xpath"),
	START_DATE_ON_FLIGHT_SEARCH_POPUP("//*[@id='actFltStartDate']","xpath"),
	END_DATE_ON_FLIGHT_SEARCH_POPUP("//*[@id='actFltEndDate']","xpath"),
	FIRST_ROW_ON_FLIGHT_SEARCH_POPUP("//*[@id='actFlightsGrid']/table/tbody/tr/td[3]","xpath"),	
	TOAST_MSG("toast-message","className"),
	ADD_FLIGHT(".//*[@id='addNew']","xpath"),
	ADDFLIGHT_RETURN_TO_OVERVIEW("Return to Overview","linkText"),
	OK("OK","linkText"),
	ACTUALIZED_DATE_SEARCH_ICON("//*[@id='actDateSearch']","xpath"),
	SEARCH_BAR_ACTUALIZATION_POPUP("//div[@id='actDatesWrapper']//*[@id='articlesearch']","xpath"),
	CONTINUE("Continue","linkText"),
	CANCEL("Cancel","linkText"),
	FLIGHT_NUM("//*[@id='FlightNumber']","xpath"),
	CUST_CODE("//*[@id='CustomerCode']","xpath"),
	COPY_ACTUALIZED_FLIGHT_SEARCHICON("//*[@id='addForm']/div[8]/div/span/a","xpath"),
									   
	ACTUALIZED_FLIGHT_POPUP("//*[@id='showActFltSearch']","xpath"),
	CANCEL_ACTUALIZED_FLIGHT_POPUP("//*[@id='cancelActFltSearch']","xpath"),
	CONTINUE_ACTUALIZED_FLIGHT_POPUP("//*[@id='selActFltContinue']","xpath"),
	ACTUALIZED_FLIGHT_POPUP_TITLE("//*[@id='showActFltSearch_wnd_title']","xpath"),
	ACTUALIZED_FLIGHT_POPUP_ARTICLE_SEARCH_BOX("//*[@id='showActFltSearch']/div/div[1]/span[1]/input","xpath"),
	ACTUALIZED_FLIGHT_POPUP_ARTICLE_SEARCH_SUBMIT("//*[@id='showActFltSearch']/div/div[1]/span[2]/a/img","xpath"),
	ACTUALIZED_FLIGHT_POPUP_FLIGHT("//*[@id='actFlightsGrid']/table/tbody/tr/td[3]","xpath"),
	START_DATE("//*[@id='fltStartDate']","xpath"),
	END_DATE("//*[@id='fltEndDate']","xpath"),
	COPY_ACTUALIZED_FLIGHT_SEARCHFILTER("//div[@id='fltWrapper']//img[@class='searchFilter']","xpath"),
	SEARCH_BAR(".//div[@id='fltWrapper']//*[@id='articlesearch']","xpath"),
	SEARCH_SUBMIT("//div[@id='fltWrapper']//img[@class='searchSubmit']","xpath"),
	POPUP("//*[@id='showFlightSearch']","xpath"),
	COPY_FLIGHT_SEARCHICON("//*[@id='addForm']/div[7]/span/a","xpath"),
	OPERATING_DATE("//*[@id='fltOpeDate']","xpath"),
	POPUP_TITLE("//*[@id='showFlightSearch_wnd_title']","xpath"),
	FLIGHT_POPUP_FIRSTROW("//*[@id='flightsGrid']/table/tbody/tr[1]/td[1]","xpath"),
	FLIGHT_NUM_TEXTBOX("//*[@id='FltNumberByFtt']","xpath"),
	OK_ON_ATTENTION("//*[@id='errorAlert']/div[3]/a","xpath"),
	EDIT("//*[@id='foheaderWrapper']/div[5]/div[5]/a","xpath"),
	REMOVE_ALERT("//*[@id='removeAlert']","xpath"),
	REMOVE_ALERT_POPUP_TITLE("//*[@id='removeAlert']/div[1]","xpath"),
	CONTINUE_ON_REMOVE_ALERT("//*[@id='removeAlert']/div[3]/a[1]","xpath"),
	CANCEL_ON_REMOVE_ALERET("//*[@id='removeAlert']/div[3]/a[2]","xpath"),
	AIRCRAFT_VERSION("//*[@id='AircraftVersionCode']","xpath"),
	AIRCRAFT_VERSION_DROPDOWN("html/body/ul[1]","xpath"),
	//DEPARTURE_AIRPORT("//*[@id='DepartureAirport']","xpath"),
	//DEPARTURE_AIRPORT_DROPDOWN("html/body/ul[3]","xpath"),
	ARRIVES_FROM("//*[@id='ArrivalFrom']","xpath"),
	ARRIVES_FROM_DROPDOWN("html/body/ul[3]","xpath"),
	LOADING_SETUP("//*[@id='LoadingSetupCode']","xpath"),
	LOADING_SETUP_DROPDOWN("html/body/ul[2]","xpath"),
	COPY_FROM_ANOTHER_ACTUALIZED_FLIGHT("//*[@id='FltNumberByAct']","xpath"),
	CONFIRM_ADD_NEW_FLIGHT_POPUP_TITLE("//*[@id='removeAlert']/div[1]","xpath"),
	OK_ON_ADD_FLIGHT_ATTENTION("//*[@id='errorAlert']/div[3]/a","xpath"),
	PAX_AND_MEAL_CONTAINER("//*[@id='paxandMealContainer']","xpath"),
	PAX_RESULTS(".//*[@id='paxResults']","xpath"),
	CANCEL_IN_HEADER(".//*[@id='editBtns']/a[1]","xpath"),
	OK_IN_HEADER(".//*[@id='editBtns']/a[2]","xpath"),
	AIRCRAFT_VERSION_IN_NON_EDITABLE_FORM("//*[@id='foheaderWrapper']/div[5]/div[1]/div[1]/span","xpath"),
	
	LEG("//*[@id='paxResults']/div[6]/div/div/div/div[2]","xpath"),
	LEG_INPUT("//*[@id='paxResults']/div[6]/div/div/div/div[2]/input","xpath"),
	CLASS("//*[@id='paxResults']/div[6]/div/div/div/div[3]","xpath"),
	CLASS_INPUT("//*[@id='paxResults']/div[6]/div/div/div/div[3]/input","xpath"),
	MAX_PAX("//*[@id='paxResults']/div[7]/div/div/div/div[2]","xpath"),
	MAX_PAX_INPUT("//*[@id='paxResults']/div[7]/div/div/div/div[2]/input","xpath"),
	FCP1("//*[@id='paxResults']/div[7]/div/div/div/div[3]","xpath"),
	FCP1_INPUT("//*[@id='paxResults']/div[7]/div/div/div/div[3]/input","xpath"),
	LUP("//*[@id='paxResults']/div[7]/div/div/div/div[4]","xpath"),
	LUP_INPUT("//*[@id='paxResults']/div[7]/div/div/div/div[4]/input","xpath"),
	LA24("//*[@id='paxResults']/div[7]/div/div/div/div[5]","xpath"),
	LA24_INPUT("//*[@id='paxResults']/div[7]/div/div/div/div[5]/input","xpath"),
	GGFC("//*[@id='paxResults']/div[7]/div/div/div/div[6]","xpath"),
	GGFC_INPUT("//*[@id='paxResults']/div[7]/div/div/div/div[6]/input","xpath"),
	AIRL("//*[@id='paxResults']/div[7]/div/div/div/div[7]","xpath"),
	AIRL_INPUT("//*[@id='paxResults']/div[7]/div/div/div/div[7]/input","xpath"),
	FIRST_MEAL_ORDER("//*[@id='paxResults']/div[7]/div/div/div/div[8]","xpath"),
	FIRST_MEAL_ORDER_INPUT("//*[@id='paxResults']/div[7]/div/div/div/div[8]/input","xpath"),
	TOB("//*[@id='paxResults']/div[7]/div/div/div/div[9]","xpath"),
	TOB_INPUT("//*[@id='paxResults']/div[7]/div/div/div/div[9]/input","xpath"),
	MT1("//*[@id='paxResults']/div[7]/div/div/div/div[10]","xpath"),
	MT1_INPUT("//*[@id='paxResults']/div[7]/div/div/div/div[10]/input","xpath"),
	MT2("//*[@id='paxResults']/div[7]/div/div/div/div[11]","xpath"),
	MT2_INPUT("//*[@id='paxResults']/div[7]/div/div/div/div[11]/input","xpath"),
	MT3("//*[@id='paxResults']/div[7]/div/div/div/div[12]","xpath"),
	MT3_INPUT("//*[@id='paxResults']/div[7]/div/div/div/div[12]/input","xpath"),
	MT4("//*[@id='paxResults']/div[7]/div/div/div/div[13]","xpath"),
	MT4_INPUT("//*[@id='paxResults']/div[7]/div/div/div/div[13]/input","xpath"),
	MT5("//*[@id='paxResults']/div[7]/div/div/div/div[14]","xpath"),
	MT5_INPUT("//*[@id='paxResults']/div[7]/div/div/div/div[14]/input","xpath"),
	AIRCRAFT_CONFIG_POPUP_OPEN_BUTTON(".//*[@class='slick-header-button']","xpath"),
	AIRCRAFT_CONFIG_POPUP("//*[@id='acConfig']","xpath"),
	CANCEL_ON_AIRCRAFT_CONFIG_POPUP("//*[@id='acConfig']/div[4]/a[1]","xpath"),
	CONTINUE_ON_AIRCRAFT_CONFIG_POPUP("//*[@id='acConfig']/div[4]/a[2]","xpath"),
	LEG_FIRST_COLUMN_ON_AIRCRAFT_CONFIG_POPUP(".//*[@id='acConfigGrid']/div[6]/div/div/div[1]/div[2]","xpath"),
	LEG_FIRST_COLUMN_ON_AIRCRAFT_CONFIG_POPUP_INPUT("//*[@id='acConfigGrid']/div[6]/div/div/div[1]/div[2]/input","xpath"),
	MEAL_LIST("html/body/ul[6]","xpath"),
	FIRST_MEAL("html/body/ul[6]/li[1]/a","xpath"),
	PAX_AND_MEAL_EXPAND("//*[@id='paxandMealContainer']/div[1]/a","xpath"),
	AMENDMENTS_EXPAND("//*[@id='amendmentsContainer']/div[1]/a","xpath"),
	AMENDMENTS_NO_DATA("//*[@id='amendmentResults']/table/tbody/tr/td","xpath"),
	AMENDMENTS_QTY("//*[@id='amendmentResults']/table/tbody/tr/td[6]","xpath"),
	DELIVERY_NOTE_EXPAND("//*[@id='delnoteInfoContainer']/div[1]/a","xpath"),
	FLIGHT_TEXT_INFO("//*[@id='FlightInfoText']","xpath"),
	DAILY_OPER_PLAN_INFO("//*[@id='DailyOpenPlanText']","xpath"),
	FLIGHT_REMARKS("//*[@id='FlightRemarksText']","xpath"),
	INVOICE_REMARKS("//*[@id='InvoiceRemarksText']","xpath"),
	AMENDEMNT_RESULTS("//*[@id='amendmentResults']","xpath"),
	CANCEL_ON_CHANGES_POPUP("//*[@id='removeAlert']/div[3]/a[2]","xpath"),
	SPML("//*[@id='nav']/li[2]/a/div","xpath"),
	SPML_RESULTS("//*[@id='spmlResults']","xpath"),
	SPML_RESULTS_LEG("//*[@id='spmlResults']/div[6]/div/div/div/div[1]","xpath"),
	SPML_RESULTS_PAX("//*[@id='spmlResults']/div[6]/div/div/div/div[4]","xpath"),
	SPML_RESULTS_PAX_INPUT("//*[@id='spmlResults']/div[6]/div/div/div/div[4]/input","xpath"),
	SALES_ORDER_LINES("//*[@id='nav']/li[3]/a/div","xpath"),
	SALES_ORDER_GRID("//*[@id='salesOrderGrid']","xpath"),
	CSP("//*[@id='nav']/li[4]/a/div","xpath"),
	DELIVERY_PLANS("//*[@id='nav']/li[5]/a/div","xpath"),
	ADD_DELIVERY_PLAN("//*[@id='deliveryPlanWrapper']/div[3]/div[1]/a[1]","xpath"),
	SEARCHRESULT_FIRST_CHECKBOX("//*[@id='addDeliveryPlans']/table/tbody/tr/td[1]/div/label/span","xpath"),
	ADD_SELECTED("//*[@id='addArticlesWrapper']/div[1]/div[2]/a","xpath"),
	PASSENGER_INFO_BUTTON("//*[@id='spmlResults']/div[6]/div/div/div/div[5]/span/a","xpath"),
	PASSENGER_INFO_POPUP("//*[@id='paxInfoModal']","xpath"),
	CANCEL_ON_PASSENGER_INFO_POPUP("//*[@id='paxInfoModal']/div[3]/a[1]","xpath"),
	CONTINUE_ON_PASSENGER_INFO_POPUP("//*[@id='paxInfoModal']/div[3]/a[2]","xpath"),
	PASSENGER_NAME("//*[@id='paxInfoGrid']/div[6]/div/div/div[1]/div[1]","xpath"),
	PASSENGER_NAME_INPUT("//*[@id='paxInfoGrid']/div[6]/div/div/div[1]/div[1]/input","xpath"),
	SEATING("//*[@id='paxInfoGrid']/div[6]/div/div/div[1]/div[2]","xpath"),
	SEATING_INPUT("//*[@id='paxInfoGrid']/div[6]/div/div/div[2]/div[2]/input","xpath"),
	SELECTED_MENU("//*[@id='navSecond']/li[1]/div","xpath"),
	DELETE_SALES_LINES("//*[@id='navSecond']/li[1]/ul/li[3]/a","xpath"),
	CHANGE_RESTITUTION("//*[@id='navSecond']/li[1]/ul/li[1]/a","xpath"),
	CHANGE_VAT_CODE("//*[@id='navSecond']/li[1]/ul/li[2]/a","xpath"),
	SELECT_ALL_CHECKBOX(".//*[@id='salesOrderGrid']/div[2]/div[1]/div/div[1]/span/input","xpath"),
	DPLAN("//*[@id='salesOrderGrid']/div[6]/div/div/div/div[3]","xpath"),
	SALES_NO("//*[@id='salesOrderGrid']/div[6]/div/div/div/div[4]","xpath"),
	SALES_NUMBER_FIND("//*[@id='salesOrderGrid']/div[6]/div/div/div/div[4]/a/span","xpath"),
	DPLAN_FIND("//*[@id='salesOrderGrid']/div[6]/div/div/div/div[3]/a/span","xpath"),
	SEARCH_DP_POPUP("//*[@id='showDpSalesNoSearch']","xpath"),
	SEARCH_DP_POPUP_SEARCH_BOX(".//*[@id='showDpSalesNoSearch']/div[1]/div[1]/div[1]/span[1]/input","xpath"),
	SEARCH_DP_POPUP_SEARCH_SUBMIT(".//*[@id='showDpSalesNoSearch']/div[1]/div[1]/div[1]/span[2]/a/img","xpath"),
	SEARCH_DP_DP("//*[@id='dpSearchGrid']/table/tbody/tr/td[1]","xpath"),
	CONTINUE_ON_SEARCH_DP_POPUP("//*[@id='dpSolContinue']","xpath"),
	CANCEL_ON_SEARCH_DP_POPUP("//*[@id='cancelDpSol']","xpath"),
	ATTENTION_POPUP("//*[@id='loadingModal']","xpath"),
	CONTINUE_ON_ATTENTION_POPUP("//*[@id='loadingModal']/div[2]/a[2]","xpath"),
	ADD_LINE("//*[@id='addLine']","xpath"),
	SEARCH_DP_NODATA("//*[@id='dpSearchGrid']/table/tbody/tr/td","xpath"),
	SALES_NUMBER_POPUP("//*[@id='showSalesNoSearch']","xpath"),
	SALES_NUMBER_POPUP_SEARCH_BOX(".//*[@id='showSalesNoSearch']/div[1]/div[1]/div[1]/span[1]/input","xpath"),
	SALES_NUMBER_POPUP_SEARCH_SUBMIT("//*[@id='showSalesNoSearch']/div[1]/div[1]/div[1]/span[2]/a/img","xpath"),
	SALES_NUMBER__NODATA("//*[@id='salesNumberSearchGrid']/table/tbody/tr/td","xpath"),
	SALES_NUMBER_POPUP_SN("//*[@id='salesNumberSearchGrid']/table/tbody/tr/td[1]","xpath"),
	SALES_NUMBER_POPUP_DES("//*[@id='salesNumberSearchGrid']/table/tbody/tr/td[2]","xpath"),
	CANCEL_ON_SALES_NUMBER_POPUP("//*[@id='cancelSalesNo']","xpath"),
	CONTINUE_ON_SALES_NUMBER_POPUP("//*[@id='selSalesNoContinue']","xpath"), 
	DESCRIPTION("//*[@id='salesOrderGrid']/div[6]/div/div/div/div[5]","xpath"),
	C("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[3]","xpath"),
	C_DROPDOWN("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[3]/select","xpath"),
	CC("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[4]","xpath"),
	CC_DROPDOWN("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[4]/select"),
	S("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[5]","xpath"),
	S_INPUT("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[5]/input","xpath"),
	V("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[6]","xpath"),
	V_DROPDOWN("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[6]/select","xpath"),
	LR("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[8]","xpath"),
	LR_FIND("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[8]/a/span","xpath"),
	LOAD_RATIO_POPUP("//*[@id='showloadInsSearch']","xpath"),
	LOAD_RATIO_POPUP_SEARCH_BOX(".//*[@id='showloadInsSearch']/div[1]/div[1]/div[1]/span[1]/input","xpath"),
	LOAD_RATIO_POPUP_SEARCH_SUBMIT(".//*[@id='showloadInsSearch']/div[1]/div[1]/div[1]/span[2]/a/img","xpath"),
	CANCEL_ON_LOAD_RATIO_POPUP("//*[@id='cancelLoadIns']","xpath"),
	CONTINUE_ON_LOAD_RATIO_POPUP("//*[@id='selLoadInsContinue']","xpath"),
	LOAD_RATIO_NODATA("//*[@id='loadInsSearchGrid']/table/tbody/tr/td","xpath"),
	LOAD_RATIO_POPUP_LR("//*[@id='loadInsSearchGrid']/table/tbody/tr[1]/td[2]","xpath"),
	QTY("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[9]","xpath"),
	QTY_INPUT("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[9]/input","xpath"),
	DCODE("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[10]","xpath"),
	DCODE_FIND("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[10]/a/span","xpath"),
	DCODE_INPUT("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[10]/input","xpath"),
	DIST_CODE_POPUP("//*[@id='showDistCodeSearch']","xpath"),
	DIST_CODE_POPUP_SEARCH_BOX(".//*[@id='showDistCodeSearch']/div[1]/div[1]/div[1]/span[1]/input","xpath"),
	DIST_CODE_POPUP_SEARCH_SUBMIT(".//*[@id='showDistCodeSearch']/div[1]/div[1]/div[1]/span[2]/a/img","xpath"),
	CANCEL_ON_DIST_CODE_POPUP("//*[@id='cancelDistCode']","xpath"),
	CONTINUE_ON_DIST_CODE_POPUP("//*[@id='selDistCodeContinue']","xpath"),
	DIST_CODE_NODATA("//*[@id='distCodeSearchGrid']/table/tbody/tr/td","xpath"),
	DIST_CODE_POPUP_DC("//*[@id='distCodeSearchGrid']/table/tbody/tr[1]/td[1]","xpath"),
	ERROR_ICON("//*[@id='errRow0']","xpath"),
	ERROR_ALERT("//*[@class='alertErrorText']","xpath"),
	OK_ON_ERROR_ALERT("//*[@id='errorAlert']/div[3]/a","xpath"),
	EDIT_ADD_LBL("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[15]/div/span","xpath"),
	EDIT_ADD_LBL_FIND("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[15]/a/span","xpath"),
	EDIT_ADD_LBL_INPUT("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[15]/input","xpath"),
	ADD_LBL_POPUP("//*[@id='addtlLblArea']","xpath"),
	ADD_LBL_TEXTBOX("//*[@id='addtlLableText']","xpath"),
	CANCEL_ON_ADD_LBL_POPUP("//*[@id='addtlLblArea']/div[2]/a[1]","xpath"),
	OK_ON_ADD_LBL_TEXT("//*[@id='addtlLblArea']/div[2]/a[2]","xpath"),
	L("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[2]","xpath"),
	L_INPUT("//*[@id='salesOrderGrid']/div[7]/div/div/div/div[2]/input","xpath"),
	HOME("//*[@id='nav']/li[1]/a/div","xpath"),
	CHANGE_RESTITUTION_POPUP("//*[@id='changeRest']","xpath"),
	CHANGE_RESTITUTION_POPUP_TITLE("//*[@id='changeRest_wnd_title']","xpath"),
	CHANGE_RESTITUTION_POPUP_RESTITUTION("//*[@id='changeRest']/div[1]/div/label/span","xpath"),
	CANCEL_ON_CHANGE_RESTITUTION_POPUP("//*[@id='changeRest']/div[2]/a[1]","xpath"),
	OK_ON_CHANGE_RESTITUTION_POPUP("//*[@id='changeRest']/div[2]/a[2]","xpath"),
	R("//*[@id='salesOrderGrid']/div[7]/div/div/div[1]/div[7]/input","xpath"),
	CHANGE_VAT_CODE_POPUP_TITLE("//*[@id='changeVAT_wnd_title']","xpath"),
	CHANGE_VAT_CODE_POPUP("//*[@id='changeVAT']","xpath"),
	CHANGE_VAT_CODE_POPUP_VAT_CODE_DROPDOWN("//*[@id='SelVatValue']","xpath"),
	CANCEL_ON_CHANGE_VAT_CODE_POPUP("//*[@id='changeVAT']/div[1]/div[3]/a[1]","xpath"),
	OK_ON_CHANGE_VAT_CODE_POPUP("//*[@id='changeVAT']/div[1]/div[3]/a[2]","xpath"),
	//*****************************************************************************************
	
	CUSTOMER("//*[@id='contentHeader']/div[4]/span[4]","xpath"),
    EFFECTIVE_DATE("//*[@id='contentHeader']/div[4]/span[1]","xpath"),
    REMOVE("X","linkText"),
    CSP_FIRSTROW("//*[@id='cspResults']/div[6]/div/div/div/div[3]","xpath"),
    ADD_CSP("Add CSP(s)","linkText"),
    SEARCH_CSP("//*[@id='addCspsearch']","xpath"),
    SEARCH_SUBMIT_CSP(".//img[@class='addSubmit']","xpath"),
    ADD_SELECTED_CSP("Add Selected","linkText"),
    CLOSE("Close","linkText"),
    CSP_GRID_FIRST_ROW("//*[@id='addCspGrid']/table/tbody/tr[1]/td[2]","xpath"),
    CSP_FIRSTROW_CHECKBOX("//*[@id='addCspGrid']/table/tbody/tr[1]/td[1]/div/label/span","xpath"),
    WARNING_TEXT("//*[@id='acWarning']/div/div[1]","xpath"),
    APPLY_CHANGES_LINKTEXT("Apply Changes","linkText"),
    SELECTED_CSP_FIRSTROW("//*[@id='cspResults']/div[6]/div/div/div[1]/div[3]","xpath"),
    DELETEICON("//*[@id='cspResults']/div[6]/div/div/div[1]/div[8]/span/a","xpath"),
    DP_FIRSTROW("//*[@id='deliveryPlanResults']/div[6]/div/div/div/div[2]","xpath"),
    ADD_DP("Add Delivery Plan(s)","linkText"),
    SEARCH_DP("//*[@id='addDPsearch']","xpath"),
    SEARCH_SUBMIT_DP(".//img[@class='addSubmit']","xpath"),
    DP_GRID("//*[@id='addArticlesWrapper']","xpath"),
    DELIVERYPLANS_GRID("//*[@id='addDeliveryPlans']/table/tbody/tr[1]/td[2]","xpath"),
    REMOVE_DP("//*[@id='deliveryPlanResults']/div[6]/div/div/div[1]/div[5]/span/a","xpath"),
    MENU("//*[@id='nav']/li[6]/div","xpath"),
    CANCEL_FLIGHT("Cancel Flight","linkText"),
    CANCEL_FLIGHT_POPUP("//*[@id='cancelFlight']","xpath"),
    FLIGHT_STATUS("//*[@id='actFlightsGrid']/table/tbody/tr[1]/td[10]","xpath"),
    SEARCH_RESULT("//*[@id='actFlightsGrid']/table/tbody/tr/td","xpath"),
    OPEN_POPUP_TEXT("//*[@id='statusMsgWindow']/div[1]","xpath"),
    OPEN_POPUP_TITLE("//*[@id='statusMsgWindow_wnd_title']","xpath"),
    FLIGHT_STATUS_TEXT("//span[@class='statusText']","xpath"),
    GENERAL_OVERVIEW_TAB("//*[@id='genOverTab']/h1","xpath"),
    GENERAL_OVERVIEW_TABLE("//*[@id='generalOverviewTable']","xpath"),
    EXPORT("//*[@id='nav']/li[7]/a", "xpath"),
	PRINT("//*[@id='nav']/li[7]/ul/li[1]/a", "xpath"),
	DELIVERYSLIP("//*[@id='nav']/li[7]/ul/li[1]/ul/li[1]/a", "xpath"),
	GOVTDELIVERYSLIP("//*[@id='nav']/li[7]/ul/li[1]/ul/li[1]/ul/li[7]/a", "xpath"),
	SLIPNUMBER_CLICK("//*[@id='govtSlipResults']/div[6]/div/div/div/div[3]", "xpath"),
	SLIPNUMBER_INPUT("//*[@id='govtSlipResults']/div[6]/div/div/div/div[3]/input", "xpath"),
	SLIPNUMBER_CHECKBOX("//*[@id='govtSlipResults']/div//div[@class='slick-header-columns slick-header-columns-left ui-sortable']/div[1]/span/input", "xpath"),
	SLIPNUM_PRINT("//*[@id='govtSlipResults']/..//a[contains(text(),'Print')]", "xpath"),
	SUMMARYDELIVERYSLIP("//*[@id='nav']/li[7]/ul/li[1]/ul/li[1]/ul/li[1]/a", "xpath"),
	CLOSEFLIGHT("//*[@id='liClose']/a", "xpath"),
	CLOSEFLIGHT_CONTINUE("//*[@id='removeAlert']/div[3]/a[1]", "xpath"),
	CLOSEFLIGHT_CLOSE("//*[@id='loadingModal']/div[2]/a", "xpath"),
	SEARCHICON("//*[@id='fovForm']/div[2]/span[3]/a", "xpath"),
	ACT_SEARCHBOX("//*[@id='actDatesWrapper']/div/div/span/input", "xpath"),
	ACT_SEARCHICON("//*[@id='actDatesWrapper']/div[1]/div/span[2]/a/img", "xpath"),
	ACT_SINGLEROW("//*[@id='results']/table/tbody/tr/td", "xpath"),
	ACT_CANCEL("//*[@id='cancelActDates']", "xpath"),
	SAVEICON("//div[@class='IconSet']","xpath"),
	SINGLEFLIGHT_OVERVIEWTOB("//div[@id='paxResults']/div[7]/div/div/div/div[9]","xpath"),
	SINGLEFLIGHT_OVERVIEWTOBINPUT("//div[@id='paxResults']/div[7]/div/div/div/div[9]/input","xpath"),
	SAVE_ICON("//*[@id='nav']/li/a/div", "xpath"),
	MENU_CANCEL_FLIGHT("//*[@id='liCancel']/a", "xpath"),
	CANCEL_FLIGHT_ON_BTN("//*[@id='cancelFlight']/div[2]/a[2]", "xpath"),
	FLIGHT_FIRSTROW("//*[@id='actFlightsGrid']/table/tbody/tr[1]/td[3]", "xpath"),
	VIEW_FLIGHT_ACTIVITY_LOG("//*[@id='liFlightActivityLog']/a", "xpath"),
	FLIGHT_ACTIVITY_LOG_POPUP_TITLE("//*[@id='flightActivityLog_wnd_title']", "xpath"),
	FLIGHT_ACTIVITY_LOG_POPUP_OKBTN("//*[@id='flightActivityLog']/div[2]/a", "xpath"),
	DELIVERY_SLIP_TEXT("//*[@id='foheaderWrapper']/div[5]/div[4]/div[1]/span", "xpath"),
	CHANGESTATUS_POPUP_TEXT("//*[@id='statusMsgWindow']/div[1]", "xpath"),
	CHANGESTATUS_POPUP_CANCELBTN("//*[@id='cancelButton']", "xpath"),
	CHANGESSTATUS_POPUP_CONTINUEBTN("//*[@id='continueButton']", "xpath"),
	FREEZEPAXFIGURES_CHECKBOX("//*[@id='updateOptions']/div[3]/label/span", "xpath"),
	CONTINUE_PAX_ATTENTIONPOPUP("//*[@id='contPaxSave']", "xpath"),
	;
	public String element,Identifier;
	private DispatchFlightOverviewEnum(String element){
		 this.element = element;
	 }
	private DispatchFlightOverviewEnum(String element, String Identifier){
		 this.element = element;
		 this.Identifier = Identifier;
	 }
	public String getElementPath(){
		return element;
	}
	public String getElementIdentifier(){
		return Identifier;
	}
	
}
