package com.sacs.PageOjects;

public enum FinancePOApprovalTransferEnum {
	FINANCE("//*[@id='finance']", "xpath"),
	POAPPROVALTRANSFER("//*[@id='poapprovaltransfer']/a","xpath"),
	POAPPROVALTRANSFER_TITLE("//*[@id='title']","xpath"),
	OK("//*[@id='poApprovalTransferOkBtn']","xpath"),
	ORDER_NUMBER_ON_GRID("//*[@id='poTransferResults']/div[6]/div/div/div[1]/div[2]","xpath"),
	SEARCH_ICON("//*[@id='poTransferWrapper']/div[3]/div[2]/span/a","xpath"),
	ORDER_NUMBER_TEXT_BOX("//*[@id='poTransferResults']/div[4]/div[1]/div[2]/div[2]/input","xpath"),
	INVOICE_NUMBER("//*[@id='poTransferResults']/div[6]/div/div/div/div[6]","xpath"),
	INVOICE_NUMBER_INPUT("//*[@id='poTransferResults']/div[6]/div/div/div/div[6]/input","xpath"),
	INVOICE_INFO_POPUP("//*[@id='enterInvoiceInfo']","xpath"),
	ORDER_AMOUNT("//*[@id='OrderAmount']","xpath"),
	GROSS_AMOUNT("//*[@id='InvoiceInfoForm']/div[1]/div[6]/span[2]/span[1]/input","xpath"),
	CONTINUE_ON_INVOICE_INFO_POPUP("//*[@id='InvoiceInfoForm']/div[2]/a[2]","xpath"),
	//*[@id='largebtnSkin action-continue']
	SHOW_ORDERS_FROM("//*[@id='StartDate']","xpath"),
	MENU("//*[@id='nav']/li/div","xpath"),
	TRANSFER_VENDOR_INVOICES("//*[@id='nav']/li/ul/li[3]/a","xpath"),
	PAGE_TITLE("//*[@id='contentHeader']/div/h1","xpath"),
	SEARCH_ICON_ON_APP_VENDOR_INVOICE_PAGE("//*[@id='potVendorInvoicesWrapper']/div[4]/div[1]/span/a","xpath"),
	FIRST_CHECK_BOX("//*[@id='checkSelBox00']","xpath"),
	ORDER_NO_ONAPP_VENDOR_INVOICE_PAGE("//*[@id='appinvoiceResults']/div[6]/div/div/div/div[2]","xpath"),
	TRANSFER_SELECTED_INVOICES("//*[@id='potVendorInvoicesWrapper']/div[2]/div[2]/span[3]/a","xpath"),
	TRANSFER_INVOICE_POPUP("//*[@id='transferInvoice']","xpath"),
	POSTING_DATE("//*[@id='postingDate']","xpath"),
	CONTINUE_ON_TRANSFER_INVOICE_POPUP("//*[@id='transferInvoice']/div[3]/a[2]","xpath"),
	CONFIRM_TRANSFER_POPUP("//*[@id='transFormConfirm']","xpath"),
	YES_ON_CONEIRM_TRANSFER_POPUP(".//*[@id='transFormConfirm']/div[2]/a[1]","xpath"),
	SUCCESS_TITLE("//*[@id='noInvoices_wnd_title']","xpath"),
	OK_ONSUCCESS_POPUP("//*[@id='noInvoices']/div[2]/a","xpath"),
	OK_ON_MISSMATCHED("//*[@id='potVendorInvoicesWrapper']/div[4]/div[4]/span[1]/a","xpath"),
	STARTDATE("//*[@id='StartDate']", "xpath"),
	TITLE("//*[@id='contentHeader']/div[1]/h1", "xpath"),
	INCLUDEORDERRECEIPTED("//*[@id='EndDate']", "xpath"),
	VENDORFIELD("//*[@id='Vendor']", "xpath"),
	VENDOR_LIST("html/body/ul/li", "xpath"),
	SAP_TRANSFER_POPUP_CONTINUEBTN("//*[@id='okButton']", "xpath"),
	APPLYCHANGES_BTN("//*[@id='applyChanges']", "xpath"),
	SAPTRANSFER_POPTITLE("//*[@id='vendorPopup_wnd_title']", "xpath"),
	SAPTRANSFER_POPUP_CANCELBTN("//*[@id='vendorPopup']/div[3]/a[1]", "xpath"),
	RECEIVEDATE_FIRSTROW("//*[@id='poTransferResults']/div[6]/div/div/div[1]/div[4]", "xpath"),
	VENDOR_FIRSTROW("//*[@id='poTransferResults']/div[6]/div/div/div/div[3]", "xpath"),
	ADDITIONALCOSTS("//*[@id='poTransferResults']/div[6]/div/div/div/div[7]/div/span[1]/a", "xpath"),
	CREDIT_DEBIT_NOTE("//*[@id='poTransferResults']/div[6]/div/div/div/div[7]/div/span[2]/a", "xpath"),
	CREATE_PRICE_INQUIRY("//*[@id='poTransferResults']/div[6]/div/div/div/div[7]/div/span[3]/a", "xpath"),
	INVOICEINFO_TITLE("//*[@id='enterInvoiceInfo_wnd_title']", "xpath"),
	INVOICEDATE("//*[@id='InvoiceDate']", "xpath"),
	INVOICEINFO_CANCELBTN("//*[@id='InvoiceInfoForm']/div[2]/a[1]", "xpath"),
	COMMENTS("//*[@id='Remarks']", "xpath"),
	INVOICE_NO_2CLICK("//*[@id='poTransferResults']/div[6]/div/div/div[2]/div[6]", "xpath"),
	INVOICE_NO_2INPUT("//*[@id='poTransferResults']/div[6]/div/div/div[2]/div[6]/input", "xpath"),
	INVOICE_NO_3CLICK("//*[@id='poTransferResults']/div[6]/div/div/div[3]/div[6]", "xpath"),
	INVOICE_NO_3INPUT("//*[@id='poTransferResults']/div[6]/div/div/div[3]/div[6]/input", "xpath"),
	PANEL_ORDERNO("//*[@id='OrderNumberDisp']", "xpath"),
	PANEL_ORDERNET("//*[@id='OrderNetDisp']", "xpath"),
	PANEL_ORDERGST("//*[@id='OrderGstDisp']", "xpath"),
	PANEL_TOTAL("//*[@id='TotalAmtDisp']", "xpath"),
	PANEL_INVOICENO("//*[@id='InvoiceNumberDisp']", "xpath"),
	PANEL_ACTUALINVOICEAMT("//*[@id='ActualInvAmtDisp']", "xpath"),
	PANEL_CALCINVOICEAMT("//*[@id='CalculatedInvAmtDisp']", "xpath"),
	PANEL_DIFFERENCE("//*[@id='DifferenceAmtDisp']", "xpath"),
	ORDERLINK_FIRSTROW("//*[@id='poTransferResults']/div[6]/div/div/div/div/span/a", "xpath"),
	OD_ARTNUM("//*[@id='detailResults']/div[6]/div/div/div/div[2]", "xpath"),
	OD_VENDOR_ART_NO("//*[@id='detailResults']/div[6]/div/div/div/div[3]","xpath"),
	OD_DESCCRIPTION("//*[@id='detailResults']/div[6]/div/div/div/div[4]", "xpath"),
	OD_UOM("//*[@id='detailResults']/div[6]/div/div/div/div[5]", "xpath"),
	OD_COSTCENTER("//*[@id='detailResults']/div[6]/div/div/div/div[6]", "xpath"),
	OD_QTY("//*[@id='detailResults']/div[6]/div/div/div/div[7]", "xpath"),
	OD_PRICE("//*[@id='detailResults']/div[6]/div/div/div/div[8]", "xpath"),
	OD_NETAMOUNT("//*[@id='detailResults']/div[6]/div/div/div/div[10]", "xpath"),
	OD_GSTVAT("//*[@id='detailResults']/div[6]/div/div/div/div[12]", "xpath"),
	COSTCENTER_DROPDOWN("//*[@id='detailResults']/div[6]/div/div/div/div[6]/select", "xpath"),
	DIVIDE_SELECTED("//*[@id='contentHeader']/div[4]/span/a", "xpath"),
	EDIT_ORDERLINES_APPLYCHANGESBTN("//*[@id='contentHeader']/div[1]/div[2]/span[3]/a", "xpath"),
	VAT_DROPDOWN("//*[@id='detailResults']/div[6]/div/div/div/div[12]/select", "xpath"),
	ADD_DEBITCREDIT_NOTE("//*[@id='poTransferResults']/div[6]/div/div/div/div[7]/div/span[2]/a", "xpath"),
	DEBITCREDIT_POPUP_CANCELBTN("//*[@id='AddCreditDebitNoteForm']/div[2]/a[1]", "xpath"),
	DEBITCREDIT_POPUP_CONTINUEBTN("//*[@id='AddCreditDebitNoteForm']/div[2]/a[2]", "xpath"),
	DCBTCRT_TITLE("//*[@id='addCreditDebitNotePopup_wnd_title']", "xpath"),
	DBTCRT_VENDOR("//*[@id='VendorName']", "xpath"),
	DBTCRT_INVOICENO("//*[@id='InvoiceNumber']", "xpath"),
	DBTCRT_INVOICEDATE("//*[@id='InvoiceDateDisp']", "xpath"),
	DBTCRT_SAPGLACCOUNT("//*[@id='GlAccountNumber']", "xpath"),
	DBTCRT_COSTCENTER("//*[@id='CostCenter']", "xpath"),
	DBTCRT_GSTVATAMOUNT("//*[@id='VatAmount']", "xpath"),
	ADDITIONALCOST_ADDLINE("//*[@id='poTransferInvoiceWrapper']/div[1]/div[2]/a", "xpath"),
	ADDCOSTS_SECONDROW_CLICK("//*[@id='invoiceResults']/div[6]/div/div/div[2]/div[1]", "xpath"),
	ADDCOSTS_SECONDROW_COSTTYPEDD("//*[@id='invoiceResults']/div[6]/div/div/div[2]/div[1]/select", "xpath"),
	COSTTYPE_CLICK("//*[@id='invoiceResults']/div[6]/div/div/div/div[1]", "xpath"),
	COSTTYPE_DD("//*[@id='invoiceResults']/div[6]/div/div/div/div[1]/select", "xpath"),
	ADDCOSTS_DESC("//*[@id='invoiceResults']/div[6]/div/div/div/div[2]", "xpath"),
	SAPGLACCOUNT("//*[@id='sapglaccount']/a", "xpath"),
	SAPGLACCOUNT_CLICK("//*[@id='invoiceResults']/div[6]/div/div/div/div[3]", "xpath"),
	ADDCOST_SAPGLACCT_DD("//*[@id='invoiceResults']/div[6]/div/div/div/div[3]/select", "xpath"),
	ADDCOST_COSTCENTER_CLICK("//*[@id='invoiceResults']/div[6]/div/div/div/div[4]", "xpath"),
	ADDCOST_COSTCENTER_DD("//*[@id='invoiceResults']/div[6]/div/div/div/div[4]/select", "xpath"),
	ADDCOST_NETAMOUNT("//*[@id='invoiceResults']/div[6]/div/div/div/div[6]", "xpath"),
	ADDCOST_NETAMT_INPUT("//*[@id='invoiceResults']/div[6]/div/div/div/div[6]/input", "xpath"),
	BACK("//*[@id='backToSearch']", "xpath"),
	ADDCOST_REMOVEICON("//*[@id='invoiceResults']/div[6]/div/div/div/div[8]/span/a", "xpath"),
	CREATEPRICEINQUIRY("//*[@id='poTransferResults']/div[6]/div/div/div/div[7]/div/span[3]/a", "xpath"),
	NPQ_CANCELBTN("//*[@id='priceQueryWindow']/div[3]/a[1]", "xpath"),
	NPQ_TITLE("//*[@id='priceQueryWindow_wnd_title']", "xpath"),
	NPQ_CONTINUEBTN("//*[@id='priceQueryWindow']/div[3]/a[2]", "xpath"),
	PQ_ARTNUM("//*[@id='pqResults']/div[6]/div/div/div/div[1]", "xpath"),
	PQ_DESC("//*[@id='pqResults']/div[6]/div/div/div/div[3]", "xpath"),
	PQ_ORDERPRICE("//*[@id='pqResults']/div[6]/div/div/div/div[6]", "xpath"),
	PQ_VENDORPRICE("//*[@id='pqResults']/div[6]/div/div/div/div[9]", "xpath"),
	PQ_VENDORPRICE_CLICK("//*[@id='pqResults']/div[6]/div/div/div/div[5]", "xpath"),
	PQ_VENDORPRICE_INPUT("//*[@id='pqResults']/div[6]/div/div/div/div[5]/input", "xpath"),
	LISTALLPRICES_CHKBOX("//*[@id='priceQueryWindow']/div[2]/div/label/span", "xpath"),
	PQ_ADDLINE_BTN("//*[@id='poTransferPriceQueryWrapper']/div[1]/div[2]/a", "xpath"),
	PQ_ARTNUM_SECONDROW("//*[@id='pqResults']/div[6]/div/div/div[2]/div[1]", "xpath"),
	PQ_ARTNUM_SEARCHICON("//*[@id='pqResults']/div[6]/div/div/div/div[1]/a/span", "xpath"),
	PQ_SEARCHBASICARTICLE_TITLE("//*[@id='showBasicArticleSearch_wnd_title']", "xpath"),
	PQ_BASICARTICLE_POPUP_CANCELBTN("//*[@id='cancelArticle']", "xpath"),
	PQ_BA_POPUP_ARTNUM("//*[@id='basicArticleGrid']/table/tbody/tr/td[1]", "xpath"),
	PQ_BA_POPUP_DESC("//*[@id='basicArticleGrid']/table/tbody/tr/td[2]", "xpath"),
	PQ_BA_POPUP_OK("//*[@id='selectArticle']", "xpath"),
	PQ_DESC_BLANCLICK("//*[@id='pqResults']/div[6]/div/div/div/div[2]", "xpath"),
	PQ_QUERYDATE_CLICK("//*[@id='pqResults']/div[6]/div/div/div/div[7]", "xpath"),
	PQ_QUERYDATE_INPUT("//*[@id='pqResults']/div[6]/div/div/div/div[7]/span/span/input", "xpath"),
	POSTING_REPORT("//*[@id='nav']/li/ul/li[1]/a", "xpath"),
	MVI_TEXT("//*[@id='potVendorInvoicesWrapper']/div[2]/div[1]", "xpath"),
	MVI_SEARCHBOX("//*[@id='potVendorInvoicesWrapper']/div[4]/div[1]", "xpath"),
	MVI_OKBTN("//*[@id='potVendorInvoicesWrapper']/div[4]/div[4]/span[1]/a", "xpath"),
	CREATEPOSTINREPOTSFORSELECTEDINVOICE("//*[@id='potVendorInvoicesWrapper']/div[4]/div[4]/span[2]/a", "xpath"),
	AUTOBOOKDIFFERENCE("//*[@id='InvoiceInfoForm']/div[1]/div[8]/label/span", "xpath"),
	APPVENDORINVOICES_SELECTALL("//*[@id='appinvoiceResults']/div/div/div/div[1]/span/input", "xpath"),
	ORDERNO_SECONDROW("//*[@id='poTransferResults']/div[6]/div/div/div[2]/div[2]", "xpath"),
	ORDERLINK_SECONDROW("//*[@id='poTransferResults']/div[6]/div/div/div[2]/div/span/a", "xpath"),
	ADD_DEBITCREBIT_NOTE("//*[@id='poTransferResults']/div[6]/div/div/div[1]/div[7]/div/span[2]/a", "xpath"),
	ACDN_DEBITRADIOBTN("//*[@id='AddCreditDebitNoteForm']/div[1]/div[6]/span[2]/span[2]/span[1]/label/span", "xpath"),
	ACDN_CREDITRADIOBTN("//*[@id='AddCreditDebitNoteForm']/div[1]/div[6]/span[2]/span[2]/span[2]/label/span", "xpath"),
	ACDN_CANCELBTN("//*[@id='AddCreditDebitNoteForm']/div[2]/a[1]", "xpath"),
	INVOICENO_FIRSTROW("//*[@id='poTransferResults']/div[6]/div/div/div[1]/div[6]", "xpath"),
	INVOICENO_FISRTROW_INPUT("//*[@id='poTransferResults']/div[6]/div/div/div[1]/div[6]/input", "xpath"),
	ORDERNUM_ONGRID_FIRSTROW("//*[@id='poTransferResults']/div[6]/div/div/div[1]/div[8]", "xpath"),
	DEBITCREDITNOTE_DATE("//*[@id='CreditDebitNoteDate']", "xpath"),
	DCN_VENDOR_REF_NUM("//*[@id='VendorNoteNumber']/span[2]/input", "xpath"),
	DCB_NOTAMOUNT("//*[@id='AddCreditDebitNoteForm']/div/div[6]/span[2]/span[1]/input", "xpath"),
	DCB_GSTVAT_DD("//*[@id='VATId']", "xpath"),
	DCB_CREDITDEBITNOTE_DD("//*[@id='CreditDebitType']", "xpath"),
	ACDN_CONTINUEBTN("//*[@id='btn-vendorContactUpdate']", "xpath"),
	ORDER_THIRDROW("//*[@id='poTransferResults']/div[6]/div/div/div[3]/div[2]", "xpath"),
	INVOICE_THIRDROW("//*[@id='poTransferResults']/div[6]/div/div/div[3]/div[6]", "xpath"),
	ENTER_DOCUMENT("//*[@id='enterInvoiceBtn']", "xpath"),
	VENDOR("//*[@id='Vendor']", "xpath"),
	REFERENCE_NUM("//*[@id='InvoiceNumber']", "xpath"),
	INVOICE_AMOUNT("//*[@id='Amount']", "xpath"),
	SUBMIT_INVOICE_OK_BTN("//*[@id='submitInvoice']", "xpath"),
	ORDER_CHECK_BOX("//*[@id='results']/table/tbody/tr/td[1]/div/label/span", "xpath"),
	ADD_PO_CONTINUE_BTN("//*[@id='action-continue']", "xpath"),
	SAVE_ICON("//*[@id='nav']/li[5]/a/div", "xpath"),
	INV_SEARCH_ICON("//*[@id='poTransferWrapper']/div[2]/div[2]/span/a", "xpath"),
	INOICE_NO_FIELD("//*[@id='poTransferResults']/div[4]/div[1]/div[2]/div[2]/input", "xpath"),
	SEARCHED_INVOICE_NO("//*[@id='poTransferResults']/div[6]/div/div/div/div[2]", "xpath"),
	ORD_INVOICE_CANCELBTN("//*[@id='btn-cancel']", "xpath"),
	BACK_BTN("//*[@id='contentHeader']/div[2]/a", "xpath"),
	ORDER_NO_FIRSTROW("//*[@id='results']/table/tbody/tr/td[2]/span", "xpath"),
	OK_BTN("//*[@id='potVendorInvoicesWrapper']/div[4]/div[3]/span[1]/a", "xpath"),
	INVOICE_NO_SEARCHTEXT("//*[@id='appinvoiceResults']/div[4]/div[1]/div[2]/div[2]/input", "xpath"),
	TRANSFER_SELECT_INVOICE_BTN("//*[@id='potVendorInvoicesWrapper']/div[4]/div[3]/span[3]/a", "xpath"),
	;
	public String element,Identifier;
	private FinancePOApprovalTransferEnum(String element){
		 this.element = element;
	 }
	private FinancePOApprovalTransferEnum(String element, String Identifier){
		 this.element = element;
		 this.Identifier = Identifier;
	 }
	public String getElementPath(){
		return element;
	}
	public String getElementIdentifier(){
		return Identifier;
	}
	
}
