package com.sacs.PageOjects;

public enum InvoiceCorrectInvoiceDataEnum {
	
	INVOICE("//*[@id='invoice']", "xpath"),
	CORRECTINVOICEDATA("//*[@id='correct']/a", "xpath"),
	CID_TITLE("//*[@id='contentHeader']/div/h1", "xpath"),
	OK_BTN("//*[@id='selSourceWrapper']/div[2]/span/a", "xpath"),
	CORRECTFLIGHTDATAINVOICES("//*[@id='correctsection']/div[1]/a/span[1]", "xpath"),
	CORRECTFLIGHTS_LINK("//*[@id='reportStoreMenu']/li[1]/a/span", "xpath"),
	FLIGHT_FIRSTROW("//*[@id='correctFlightsGrid']/table/tbody/tr[1]/td[2]", "xpath"),
	ADDLINE_QTY_FIRSTROW_CLICK("//*[@id='salesOrderGrid']/div[6]/div/div/div[2]/div[22]/span", "xpath"),
	ADDLINE_QTY_FIRSTROW_INPUT("//*[@id='salesOrderGrid']/div[6]/div/div/div[2]/div[22]/input", "xpath"),
	APPLYCHANGES("//*[@id='applyChanges']", "xpath"),
	SELECTSOURCE("//*[@id='InvoiceMonth']", "xpath"),
	REPLACESALESNUMBER_LINK("//*[@id='reportStoreMenu']/li[2]/a/span", "xpath"),
	ADDSALESNUMBERSTOFLIGHT_LINK("//*[@id='reportStoreMenu']/li[3]/a/span", "xpath"),
	DELETESALESNUMBERINFLIGHT_LINK("//*[@id='reportStoreMenu']/li[4]/a/span", "xpath"),
	INVOICEDATAVATCHECK_LINK("//*[@id='reportStoreMenu']/li[5]/a/span", "xpath"),
	SETVATONSALESLINES_LINK("//*[@id='reportStoreMenu']/li[6]/a/span", "xpath"),
	CORRECTINVOICENUMBERDATES_LINK("//*[@id='reportStoreMenu']/li[7]/a/span", "xpath"),
	FIRSTROW_FIRSTCOL("//*[@id='correctFlightsGrid']/table/tbody/tr[1]/td[1]", "xpath"),
	FIRSTROW_SECONDCOL("//*[@id='correctFlightsGrid']/table/tbody/tr[1]/td[2]", "xpath"),
	FIRSTROW_THIRDCOL("//*[@id='correctFlightsGrid']/table/tbody/tr[1]/td[3]", "xpath"),
	FIRSTROW_FOURTHCOL("//*[@id='correctFlightsGrid']/table/tbody/tr[1]/td[4]", "xpath"),
	FIRSTROW_SIXTHCOL("//*[@id='correctFlightsGrid']/table/tbody/tr[1]/td[6]", "xpath"),
	FIRSTROW_SEVENTHCOL("//*[@id='correctFlightsGrid']/table/tbody/tr[1]/td[7]", "xpath"),
	SINGLE_ROW("//*[@id='correctFlightsGrid']/table/tbody/tr/td[1]", "xpath"),
	SEARCH_DD("//*[@id='searchContainer']/div[1]/span[3]/a/img", "xpath"),
	DEAPARTUREDATE_RADIOBTN("//*[@id='searchContainer']/div[2]/div[1]/span[3]/label/span", "xpath"),
	CUSTOMERCODE_RADIOBTN("//*[@id='searchContainer']/div[2]/div[2]/span[1]/label/span", "xpath"),
	SALESNUMBER_RADIOBTN("//*[@id='searchContainer']/div[2]/div[2]/span[2]/label/span", "xpath"),
	DESCRIPTION_RADIOBTN("//*[@id='searchContainer']/div[2]/div[2]/span[3]/label/span", "xpath"),
	FLIGHT_RADIOBTN("//*[@id='searchContainer']/div[2]/div[1]/span[2]/label/span", "xpath"),
	SINGLEROW_SECONDCOL("//*[@id='correctFlightsGrid']/table/tbody/tr/td[2]", "xpath"),
	SINGLEROW_THIRDCOL("//*[@id='correctFlightsGrid']/table/tbody/tr/td[3]", "xpath"),
	SINGLEROW_FOURTHCOL("//*[@id='correctFlightsGrid']/table/tbody/tr/td[4]", "xpath"),
	SINGLEROW_SIXTHCOL("//*[@id='correctFlightsGrid']/table/tbody/tr/td[6]", "xpath"),
	SINGLEROW_SEVENTHCOL("//*[@id='correctFlightsGrid']/table/tbody/tr/td[7]", "xpath"),
	CORRECTFLIGHTDETAILS_ADDLINEBTN("//*[@id='addLine']", "xpath"),
	CORRECTFLIGHTDETAILS_CHANGEBTN("//*[@id='change']", "xpath"),
	REPLACESALESNUMBER_OKBTN("//*[@id='saveContainer']/a", "xpath"),
	RSN_REPLACESEARCHICON("//*[@id='replaceSalesNoHeader']/div[1]/div[3]/span[4]/a", "xpath"),
	RSN_CUSTOMERCODE("//*[@id='CustomerCode']", "xpath"),
	RSN_GRIDFIRSTROW("//*[@id='invSalesNumSearchGrid']/table/tbody/tr[2]/td[1]", "xpath"),
	RSN_SALESNUMBERSEARCHICON("//*[@id='replaceSalesNoHeader']/div[1]/div[4]/span[5]/a", "xpath"),
	RSN_GRIDSECONDROW("//*[@id='salesNumSearchGrid']/table/tbody/tr[2]/td[1]", "xpath"),
	RSN_FLIGHTCHKBOX("//*[@id='checkSelBox00']", "xpath"),
	RSN_APPLYCHANGESBTN("//*[@id='replaceContainer']/a", "xpath"),
	RSN_REPLACESALESNO_TEXTBOX("//*[@id='OldSalesNumber']", "xpath"),
	ASN_NEWSALESNUMBER("//*[@id='NewSalesNumber']", "xpath"),
	RSN_WITHSALESNUMBER_SEARCHBOX("//*[@id='showRepoSalesNumberSearch']/div/div[1]/div[1]/span/input", "xpath"),
	RSN_WITHSALESNUMBER_SEARCHICON("//*[@id='showRepoSalesNumberSearch']/div/div[1]/div[1]/span[2]/a/img", "xpath"),
	ASN_SALESNO_SEARCHBOX("//*[@id='repoSalesNoSearchWrapper']/div[1]/div[1]/span/input", "xpath"),
	ASN_SALESNO_SEARCHICON("//*[@id='repoSalesNoSearchWrapper']/div[1]/div[1]/span[2]/a/img", "xpath"),
	ASN_FLIGHT_SEARCHICON("//*[@id='replaceSalesNoHeader']/div[1]/div[5]/span[4]/a", "xpath"),
	ASN_FLIGHT_FIRSTROW("//*[@id='actFlightsGrid']/table/tbody/tr[2]/td[1]", "xpath"),
	CUSTOMERNUMBER("//*[@id='CustomerNumber']", "xpath"),
	FLIGHT_CHKBOX("//*[@id='checkSelBox00']", "xpath"),
	PAGETITLE("//*[@id='contentHeader']/div[1]/h1", "xpath"),
	HASNOVAT_RBTN("//*[@id='RepSaleNu']/div[3]/label/span", "xpath"),
	VATID_DROPDOWN("//*[@id='VatId']", "xpath"),
	VAT_OKBTN("//*[@id='addLineContainer']/div[2]/a", "xpath"),
	HASVAT_RBTN("//*[@id='RepSaleNu']/div[2]/label/span", "xpath"),
	REPLACESTARTDATE("//*[@id='ReplaceStartDate']", "xpath"),
	REPLACEENDDATE("//*[@id='ReplaceEndDate']", "xpath"),
	SEARCHED_FIRSTROW("//*[@id='invSalesNumSearchGrid']/table/tbody/tr/td[1]", "xpath"),
	WITHSALESNO_SEARCHBOX("//*[@id='showRepoSalesNumberSearch']/div/div/div/span[1]/input", "xpath"),
	WITHSALESNO_SEARCHICON("//*[@id='showRepoSalesNumberSearch']/div/div/div/span[2]/a/img", "xpath"),
	WITHSALESNO_SEARCHROW("//*[@id='salesNumSearchGrid']/table/tbody/tr/td[1]", "xpath"),
	REPLACE_SEARCHBOX("//*[@id='showInvSalesNoSearchPopup']/div/div/div/span[1]/input", "xpath"),
	REPLACE_SEARCHICON("//*[@id='showInvSalesNoSearchPopup']/div/div/div/span[2]/a/img", "xpath"),
	FLIGHT_TEXTBOX("//*[@id='FlightNumber']", "xpath"),
	INVOICEQTY("//*[@id='InvoiceQuantity']", "xpath"),
	CLASSCODE("//*[@id='ClassCode']", "xpath"),
	STARTDATE("//*[@id='openStartDate']", "xpath"),
	ENDDATE("//*[@id='openEndDate']", "xpath"),
	CORRECTFLIGHTEDIT("//div[@id='divViewHeader']/div[4]/div/a","xpath"),
	CORRECTFLIGHTEDIT_ACTYPE("//input[@id='AircraftVersionCode']","xpath"),
	CORRECTFLIGHTEDIT_ACTYPEAUTO("html/body/ul[2]","xpath"),
	CORRECTFLIGHTEDIT_CANCEL("//div[@id='divCancelHeader']/a","xpath"),
	CORRECTFLIGHTEDIT_OK("//div[@id='divOkHeader']/a","xpath"),
	CORRECTFLIGHTEDIT_DEPTIMEICON("//form[@id='CorrectHeader']/div[2]/div[2]/span[2]/span/span/span/span","xpath"),
	CORRECTFLIGHTEDIT_DEPTIMEICON_LAYOUT("html/body/div[4]/div","xpath"),
	CORRECTFLIGHTEDIT_DEPTIMEICON_DROPDOWN("//ul[@id='DepartureTime_timeview']","xpath"),
	CORRECTFLIGHTEDIT_DEPTIME_DROPDOWN_SELECTEDTIME("//ul[@id='DepartureTime_timeview']//li[@id='DepartureTime_option_selected']","xpath"),
	CORRECTFLIGHTEDIT_DEPTIME_DROPDOWN_SELECTEDTIME_PLUSTHIRTY(".//*[@id='DepartureTime_option_selected']/following-sibling::li[1]","xpath"),
	CORRECTFLIGHTEDIT_ACREGINPUT("//input[@id='AircraftRegistration']","xpath"),
	CORRECTFLIGHTEDIT_CUSTOMERNOSELECT("//select[@id='UpdatedChildCustomerId']","xpath"),
	CORRECTFLIGHTEDIT_CUSTOMERNOSELECTOPTION("//select[@id='UpdatedChildCustomerId']","xpath"),
	CORRECTFLIGHTEDIT_CUSTOMERCODE("//input[@id='CustomerCode']","xpath"),
	CORRECTFLIGHTEDIT_DEPARTUREAIRPORTINPUT("//input[@id='DepartureFrom']","xpath"),
	CORRECTFLIGHTEDIT_DEPARTUREAIRPORTINPUT_AUTO("html/body/ul[1]","xpath"),
	CORRECTFLIGHTEDIT_DEPARTUREAIRPORTINPUT_AUTOUL("//ul[@aria-activedescendant='ui-active-menuitem'][1]","xpath"),
	CORRECTFLIGHTEDIT_HAUL("//select[@id='Haul']","xpath"),
	CORRECTFLIGHTEDIT_ADDLINE("//a[@id='addLine']","xpath"),
	CORRECTFLIGHTEDIT_AL_TOTALSALES("//div[@id='salesOrderGrid']/div[6]/div/div/div","xpath"),
	CORRECTFLIGHT_AL_SALESNO("//div[@id='salesOrderGrid']/div[6]/div/div/div[1]/div[3]","xpath"),
	CORRECTFLIGHT_AL_SALESNOSEARCHICON("//div[@id='salesOrderGrid']/div[6]/div/div/div[1]/div[3]/a/span","xpath"),
	CORRECTFLIGHT_AL_SALESNOPOPUPSEARCHINPUT("//div[@id='salesNoSearchWrapper']//input[@id='articlesearch']","xpath"),
	CORRECTFLIGHT_AL_SALESNOPOPUPSEARCHICON("//div[@id='salesNoSearchWrapper']//img[@class='searchSubmit']","xpath"),
	CORRECTFLIGHT_AL_SALESNOPOPUPFIRSTROW("//div[@id='salesNumberSearchGrid']/table/tbody/tr[1]/td[1]","xpath"),
	CORRECTFLIGHT_AL_SALESNOPOPUPFIRSTROW_VAT("//div[@id='salesNumberSearchGrid']/table/tbody/tr[1]/td[5]","xpath"),
	CORRECTFLIGHT_AL_SALESNOPOPUP_CANCEL("//*[@id='cancelSalesNo']","xpath"),
	CORRECTFLIGHT_AL_SALESNOPOPUP_CONTINUE("//*[@id='selSalesNoContinue']","xpath"),
	CORRECTFLIGHT_AL_LEGNUMBER_L("//*[@id='salesOrderGrid']/div[6]/div/div/div[1]/div[7]","xpath"),
	CORRECTFLIGHT_AL_LEGNUMBER_L_INPUT("//*[@id='salesOrderGrid']/div[6]/div/div/div[1]/div[7]/input","xpath"),
	CORRECTFLIGHT_AL_LEG("//div[@id='salesOrderGrid']/div[6]/div/div/div[1]/div[8]","xpath"),
	CORRECTFLIGHT_AL_LEG_INPUT("//input[@id='tags']","xpath"),
	CORRECTFLIGHT_AL_LEG_INPUT_UL("html/body/ul[3]","xpath"),
	CORRECTFLIGHT_AL_LEG_INPUT_UL_LI("html/body/ul[3]/li[1]/a","xpath"),
	CORRECTFLIGHT_AL_CLASS("//div[@id='salesOrderGrid']/div[6]/div/div/div[12]/div[9]","xpath"),
	CORRECTFLIGHT_AL_CLASS_SELECT("//div[@id='salesOrderGrid']/div[6]/div/div/div[12]/div[9]/select","xpath"),
	CORRECTFLIGHT_AL_SERVINGNUMBER("//div[@id='salesOrderGrid']/div[6]/div/div/div[1]/div[11]","xpath"),
	CORRECTFLIGHT_AL_SERVINGNUMBERINPUT("//div[@id='salesOrderGrid']/div[6]/div/div/div[1]/div[11]/input","xpath"),
	CORRECTFLIGHT_AL_RESTITUTION("//div[@id='salesOrderGrid']/div[6]/div/div/div[1]/div[14]/span","xpath"),
	CORRECTFLIGHT_AL_RESTITUTION_INPUT("//input[@id='checkBoxundefined']","xpath"),
	CORRECTFLIGHT_AL_RE("//div[@id='salesOrderGrid']/div[6]/div/div/div[1]/div[18]","xpath"),
	CORRECTFLIGHT_AL_RE_INPUT("//div[@id='salesOrderGrid']/div[6]/div/div/div[1]/div[18]/input","xpath"),
	CORRECTFLIGHT_AL_SEQ("//div[@id='salesOrderGrid']/div[6]/div/div/div[1]/div[19]/input","xpath"),
	CORRECTFLIGHT_AL_QTY("//div[@id='salesOrderGrid']/div[6]/div/div/div[1]/div[20]","xpath"),
	CORRECTFLIGHT_AL_QTY_INPUT("//div[@id='salesOrderGrid']/div[6]/div/div/div[1]/div[20]/input","xpath"),
	CORRECTFLIGHT_AL_COPY("//div[@id='salesOrderGrid']/div[6]/div/div/div[1]/div[22]/span/a","xpath"),
	CORRECTFLIGHT_AL_DELETE("//div[@id='salesOrderGrid']/div[6]/div/div/div[1]/div[23]/span/a","xpath"),
	CORRECTFLIGHT_AL_DELETEALERT("//div[@id='removeAlert']/div[3]/a[1]","xpath"),
	APPLYCHANGES_ICON("//a[@id='saveButton']/div","xpath"),
	LEG_DOWNARROW("//div[@id='salesGrid']/div/div[2]/div/div/div[2]/div[1]","xpath"),
	LEG_DOWNARROW_TEXT("//*[@id='salesOrderGrid']/div[9]/div","xpath"),
	LEGONE_CHECKED("//input[@checked='checked']","xpath"),
	SALESORDER_CHECKBOX("//div[@id='salesOrderGrid']//input[@name='checkSelBox']","xpath"),
	SELECTEDMENU("//ul[@id='navSecond']/li[1]/div/span","xpath"),
	SELECTEDMENU_CHANGERESTITUTION("//ul[@id='navSecond']/li[1]/ul/li[1]/a","xpath"),
	SELECTEDMENU_CHANGERESTITUTION_POPUPCHECKBOX("//div[@id='changeRest']/div[1]/div/label/span","xpath"),
	SELECTEDMENU_CHANGERESTITUTION_POPUPLABEL("//div[@id='changeRest']/div[1]/div/label","xpath"),
	SELECTEDMENU_CHANGERESTITUTION_POPUPCANCEL("//div[@id='changeRest']//a[@id='cancelButton']","xpath"),
	SELECTEDMENU_CHANGERESTITUTION_POPUPOK("//div[@id='changeRest']//a[@id='okButton']","xpath"),
	RES_CHECKED("//*[@id='salesOrderGrid']/div[6]/div/div/div/div[14]/span[@class='icon-CheckboxOn']","xpath"),
	SALES_FIRSTROWCHECKBOX("//div[@id='salesGrid']//input[@id='checkSelBox00']","xpath"),
	SELECTEDMENU_CHANGEVAT("//ul[@id='navSecond']/li[1]/ul/li[2]/a","xpath"),
	SELECTEDMENU_CHANGEVAT_POPUPVATCODESELECT("//select[@id='SelVatValue']","xpath"),
	SELECTEDMENU_CHANGEVAT_POPUPCANCEL("//div[@id='changeVat']//a[@id='cancelButton']","xpath"),
	SELECTEDMENU_CHANGEVAT_POPUPOK("//div[@id='changeVat']//a[@id='okButton']","xpath"),
	SALES_FIRSTVAT("//div[@id='salesOrderGrid']/div[6]/div/div/div[11]/div[12]/div","xpath"),
	SELECTEDMENU_REDUCEPRICEBYPER("//ul[@id='navSecond']/li[1]/ul/li[4]/a","xpath"),
	SELECTEDMENU_REDUCEPRICEBYPER_POPUPINPUT("//input[@id='ReducebyPercentText']","xpath"),
	SELECTEDMENU_REDUCEPRICEBYPER_POPUPCANCEL("//div[@id='ChangeReducePricebyPercent']//a[@id='cancelButton']","xpath"),
	SELECTEDMENU_REDUCEPRICEBYPER_POPUPOK("//div[@id='ChangeReducePricebyPercent']//a[@id='okButton']","xpath"),
	SALES_FIRSTROWPRICEREDUCTIONPERCENT("//div[@id='salesOrderGrid']/div[6]/div/div/div[2]/div[18]","xpath"),
	CORRECTFLIGHTS_MENU("//ul[@id='nav']/li[1]/div","xpath"),
	CORRECTFLIGHTS_MENU_CHANGEPAXCONFIG("//ul[@id='nav']/li[1]/ul/li[1]/a","xpath"),
	CORRECTFLIGHTS_MENU_VIEWACTIVELOG("//ul[@id='nav']/li[1]/ul/li[2]/a","xpath"),
	CORRECTFLIGHTS_MENU_CHANGEPAXCONFIG_PAX("//div[@id='paxConfigResults']/div[6]/div/div/div/div[5]","xpath"),
	CORRECTFLIGHTS_MENU_CHANGEPAXCONFIG_PAXINPUT("//div[@id='paxConfigResults']/div[6]/div/div/div/div[5]/input","xpath"),
	CORRECTFLIGHTS_MENU_CHANGEPAXCONFIG_POPUPCLOSE("//div[@id='paxConfigWrapper']//a[@id='cancelButton']","xpath"),
	CORRECTFLIGHTS_MENU_CHANGEPAXCONFIG_POPUPAPPLYCHANGES("//div[@class='detailsBtns']//a[@id='applyChanges']","xpath"),
	CORRECTFLIGHTS_SEARCH("//input[@id='articlesearch']","xpath"),
	CORRECTFLIGHTSSEARCHICON("//*[@id='searchContainer']/div[1]/span[2]/a/img","xpath"),
	CORRECTFLIGHTSDELETEICON("//li[@id='removeOV']/a","xpath"),
	CORRECTFLIGHTSDELETEICONPOPUPOK("//*[@id='loadingModal']/div[2]/a[2]","xpath"),
	SEARCHBOX("//*[@id='articlesearch']", "xpath"),
	SEARCHICON("//*[@id='searchContainer']/div[1]/span[2]/a/img", "xpath"),
	SALES_GRIDFIRSTROW("//*[@id='invSalesNumSearchGrid']/table/tbody/tr/td[2]", "xpath"),
	;
	
	public String element,Identifier;
	private InvoiceCorrectInvoiceDataEnum(String element){
		 this.element = element;
	 }
	private InvoiceCorrectInvoiceDataEnum(String element, String Identifier){
		 this.element = element;
		 this.Identifier = Identifier;
	 }
	public String getElementPath(){
		return element;
	}
	public String getElementIdentifier(){
		return Identifier;
	}
}
