package com.sacs.PageOjects;

public enum OperationsCSPAddEnum {
	OPERATIONS("operations","id"),
	ADDCSP("//*[@id='addNew']", "xpath"),
	SEARCHFIELD("//*[@id='searchContainer']/div[1]", "xpath"),
	SEARCH_FIELD(".//*[@id='articlesearch']", "xpath"),
	SEARCH_SUBMIT("searchSubmit", "className"),
	SEARCHICON("//*[@id='searchContainer']/div[1]/span[2]/a/img", "xpath"),
	TOAST_MESSAGE("toast-message","className"), 
	CSP_XPATH("//*[@id='cateringstowageplan']/a","xpath"),
	CSP_TITLE("//*[@id='contentHeader']/div[1]/h1","xpath"),
	ADD_BTN("//*[@id='contentHeader']/div[2]/a","xpath"),
	CUSTOMER("//*[@id='ParentCustomerId']","xpath"),
	CSP_CODE("//*[@id='Code']","xpath"),
	AC_VERSION("//*[@id='AirCraftVersionCode']","xpath"),
	AC_VERSION_POPUP("//*[@id='aircraftVersionSearchPopUp']","xpath"),
	OK_ON_AC_VERSION_POPUP("//*[@id='aircraftVersionSearchPopUp']/div[6]/a[2]","xpath"),
	EFFECTIVE_DATE("//*[@id='EffectiveDate']","xpath"),
	DESCRIPTION("//*[@id='Description']","xpath"),
	OK_BTN("//*[@id='cspokContainer']/a","xpath"),
	AC_VERSION_POPUP_OPEN_BTN(".//*[@id='cspForm']/div[1]/div[3]/span[3]/a","xpath"),
	POPUP_FIRST_ROW("//*[@id='aircraftVersionSearchGrid']/table/tbody/tr[1]/td[1]","xpath"),
	PRINT_MODE("//*[@id='PrintMode']","xpath"),
	PAGINATIONLINKS("//*[@id='results']/div", "xpath"),
	BACK_TO_SEARCH("//*[@id='contentHeader']/div[2]/a","xpath"),
	RESULT_GRID_FIRSTCOLUMN_BEFORE_SEARCH("//*[@id='results']/table/tbody/tr[1]/td[2]","xpath"),
	RESULT_GRID_FIRSTCOLUMN_AFTER_SEARCH("//*[@id='results']/table/tbody/tr/td[2]","xpath"), 
	APPLY_CHANGES("//*[@id='nav']/li[2]/a/div","xpath"),
	SHOWENTRIES("//*[@id='gridWrapper']/div[1]/div[2]", "xpath"),
	ADD_LINE("//*[@id='cspGridSection']/a[1]","xpath"),
	DCODE_OUTER("//*[@id='cspGrid']/div[6]/div/div/div/div[4]","xpath"),
	DCODE(".//*[@id='cspGrid']/div[6]/div/div/div/div[4]/input","xpath"),
	DOOR_OUTER(".//*[@id='cspGrid']/div[7]/div/div/div/div[5]","xpath"),
	DOOR("//*[@id='cspGrid']/div[7]/div/div/div/div[5]/input","xpath"),
	GALLERY_OUTER(".//*[@id='cspGrid']/div[7]/div/div/div/div[6]","xpath"),
	GALLERY(".//*[@id='cspGrid']/div[7]/div/div/div/div[6]/input","xpath"),
	LOADING_POS_OUTER(".//*[@id='cspGrid']/div[7]/div/div/div/div[7]","xpath"),
	LOADING_POS(".//*[@id='cspGrid']/div[7]/div/div/div/div[7]/input","xpath"),
	PRINT_SEQ_OUTER(".//*[@id='cspGrid']/div[7]/div/div/div/div[11]","xpath"),
	PRINT_SEQ(".//*[@id='cspGrid']/div[7]/div/div/div/div[11]/input","xpath"),
	PRINTER_OUTER(".//*[@id='cspGrid']/div[7]/div/div/div/div[13]","xpath"),
	PRINTER_DROPDOWN(".//*[@id='cspGrid']/div[7]/div/div/div/div[13]/select","xpath"),
	CANNOT_DELETE_POPUP("//*[@id='attentionModal']","xpath"),
	OK_ON_CANNOT_DELETE_POPUP("//*[@id='attentionModal']/div[2]/a","xpath"),
	DCODE_SEARCH_ICON(".//*[@id='cspGrid']/div[6]/div/div/div/div[4]/a/span","xpath"),
	SEARCH_DISTRIBUTION_CODE_POPUP("//*[@id='showDistCodeSearch']","xpath"),
	SEARCH_DISTRIBUTION_CODE_POPUP_RESULT_FIRST_COLUMN("//*[@id='distCodeSearchGrid']/table/tbody/tr/td[1]","xpath"),
	CONTINUE_ON_SEARCH_DISTRIBUTION_CODE_POPUP("//*[@id='selDistCodeContinue']","xpath"),
	DELETEICON("//*[@id='removeCSPLink']/div", "xpath"),
	POPUPCONTINUE("//*[@id='removeAlert']/div[3]/a[1]", "xpath"),
	NODATATODISPLAY("//*[@id='results']/table/tbody/tr/td", "xpath"),
	CUSTCODE_SEARCHCHK("//*[@id='searchContainer']/div[2]/div[1]/label[1]/span", "xpath"),
	DESC_SEARCHCHK("//*[@id='searchContainer']/div[2]/div[2]/label[1]/span", "xpath"),
	CSP_SEARCHCHK("//*[@id='searchContainer']/div[2]/div[1]/label[2]/span", "xpath"),
	ACVERSION_SEARCHCHK("//*[@id='searchContainer']/div[2]/div[2]/label[2]/span", "xpath"),
	SEARCH_DD("//*[@id='searchContainer']/div[1]/span[3]/a/img", "xpath"),
	SHOWINGENTRIES("//*[@id='gridWrapper']/div[3]/span", "xpath"),
	CUSTOMERFIRSTROW("//*[@id='results']/table/tbody/tr[1]/td[1]", "xpath"),
	DESCRIPTIONFIRSTROW("//*[@id='results']/table/tbody/tr[1]/td[3]", "xpath"),
	ACVERSIONFIRSTROW("//*[@id='results']/table/tbody/tr[1]/td[4]", "xpath"),
	BACKTOSEARCH("Back to Search", "linkText"),
	OK("OK", "linkText"),
	TYPE("//*[@id='Type']", "xpath"),
	APPLYCHANGES("Apply Changes", "linkText"),
	SEARCHACVERSION("//*[@id='aircraftVersionSearchPopUp_wnd_title']", "xpath"),
	SEARCHACVERSION_POPUP_CANCEL("//*[@id='cancelButton']", "xpath"),
	SEARCHACVERSION_TEXT("//*[@id='customerSearchInputs']/span/input", "xpath"),
	SEARCHACVERSIONICON("//*[@id='customerSearchInputs']/span[2]/a/img", "xpath"),
	SELECTACVERSION("//*[@id='aircraftVersionSearchGrid']/table/tbody/tr/td[1]", "xpath"),
	ACVERSIONPOPUP("//*[@id='aircraftVersionSearchGrid']/table/tbody/tr[1]/td[3]", "xpath"),
	DCODE_HEADER("//*[@title='Distribution code no.']/span[1]", "xpath"),
	SEQ_HEADER("//*[@title='Sequence no.']/span[1]", "xpath"),
	GRP_HEADER("//*[@title='Group code no.']/span[1]", "xpath"),
	RULE_HEADER("//*[@title='Stowing rule']/span[1]", "xpath"),
	PRIO_HEADER("//*[@title='Priority no.']/span[1]", "xpath"),
	DOOR_HEADER("//*[@title='Door no.']/span[1]", "xpath"),
	GALLEY_HEADER("//*[@title='Galley no.']/span[1]", "xpath"),
	LPOS_HEADER("//*[@title='Loading position no.']/span[1]", "xpath"),
	LPOSWGHT_HEADER("//*[@title='Loading position weight']/span[1]", "xpath"),
	TLS_HEADER("//*[@title='Truck load sequence']/span[1]", "xpath"),
	MSD_HEADER("//*[@title='Meal service description']/span[1]", "xpath"),
	PRTSQ_HEADER("//*[@title='Print sequence']/span[1]", "xpath"),
	DRW_HEADER("//*[@title='Drawer no.']/span[1]", "xpath"),
	PRT_HEADER("//*[@title='Box label printer code']/span[1]", "xpath"),
	CONT_HEADER("//*[@title='Stowing container no.']/span[1]", "xpath"),
	CAP_HEADER("//*[@title='Stowing capacity of the container no.']/span[1]", "xpath"),
	PEL_HEADER("//*[@title='Print empty label']/span[1]", "xpath"),
	STARTDATE_HEADER("//*[@title='Start date']/span[1]", "xpath"),
	STOPDATE_HEADER("//*[@title='Stop date']/span[1]", "xpath"),
	//ERRORICON("//div[@id='cspGrid']//div[@class='slick-viewport']//div[@class='grid-canvas']/div//div/span/a[@class='errorIcon']", "xpath"),
	ERRORICON("//*[@class='grid-canvas grid-canvas-bottom grid-canvas-left']//div/div[3]/span/a", "xpath"),
	ERRORTXT("//*[@id='errorAlert']/div[2]", "xpath"),
	APPLYCHANGES_BTN("//div[@id='cspGridSection']//a[@id='applyChanges']", "xpath"),
	ERRORPOPOK("//*[@id='errorAlert']/div[3]/a", "xpath"),
	DCODE_CLICK("//*[@id='cspGrid']/div[6]/div/div/div/div[4]", "xpath"),
	DCODE_SEARCHICON("//*[@id='cspGrid']/div[6]/div/div/div/div[4]/a/span", "xpath"),
	DCODE_SEARCHICON2("//*[@id='cspGrid']/div[6]/div/div/div[2]/div[4]/a/span", "xpath"),
	SELECT_FIRST_DCODE("//*[@id='distCodeSearchGrid']/table/tbody/tr[1]/td[1]", "xpath"),
	SELECT_FIRST_BOXCODE("//*[@id='boxCodeGrid']/table/tbody/tr[1]/td[1]", "xpath"),
	SELECT_SECOND_DCODE("//*[@id='distCodeSearchGrid']/table/tbody/tr[2]/td[1]", "xpath"),
	SELECT_DC_CONTINUE("//*[@id='selDistCodeContinue']", "xpath"),
	SELECT_BC_CONTINUE("//*[@id='selBoxCodeContinue']", "xpath"),
	SELECT_DC_CANCEL("//*[@id='cancelDistCode']", "xpath"),
	SELECT_BC_CANCEL("//*[@id='cancelBoxCode']", "xpath"),
	DOOR_CLICK("//*[@id='cspGrid']/div[7]/div/div/div/div[5]", "xpath"),
	DOOR_INPUT("//*[@id='cspGrid']/div[7]/div/div/div/div[5]/input", "xpath"),
	GALLEY_CLICK("//*[@id='cspGrid']/div[7]/div/div/div/div[6]", "xpath"),
	GALLEY_INPUT("//*[@id='cspGrid']/div[7]/div/div/div/div[6]/input", "xpath"),
	LPOS_CLICK("//*[@id='cspGrid']/div[7]/div/div/div/div[7]", "xpath"),
	LPOS_INPUT("//*[@id='cspGrid']/div[7]/div/div/div/div[7]/input", "xpath"),
	PRTSEQ_CLICK("//*[@id='cspGrid']/div[7]/div/div/div/div[11]", "xpath"),
	PRTSEQ_INPUT("//*[@id='cspGrid']/div[7]/div/div/div/div[11]/input", "xpath"),
	BOXLBL_CLICK("//*[@id='cspGrid']/div[7]/div/div/div/div[13]", "xpath"),
	BOXLBL_SELECT("//*[@id='cspGrid']/div[7]/div/div/div/div[13]/select", "xpath"),
	BOXLBL_CLICK2("//*[@id='cspGrid']/div[7]/div/div/div/div[12]", "xpath"),
	BOXLBL_SELECT2("//*[@id='cspGrid']/div[7]/div/div/div/div[12]/select", "xpath"),
	BOXLBL_CLICK_3("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[13]", "xpath"),
	BOXLBL_SELECT_3("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[13]/select", "xpath"),
	SEARCH_DCLICK("//*[@id='results']/table/tbody/tr/td[1]", "xpath"),
	DCODE_POPUP_TITLE("//*[@id='showDistCodeSearch_wnd_title']", "xpath"),
	DCODE_SEARCHBOX("//*[@id='distCodeWrapper']//div[@id='searchContainer']/div[1]/span[1]/input", "xpath"),
	DCODE_SEARCHSUBMIT("//*[@id='distCodeWrapper']//div[@id='searchContainer']/div[1]/span[2]/a/img", "xpath"),
	COPYROWICON("//*[@id='cspGrid']/div[6]/div/div/div/div[1]/span/a", "xpath"),
	DCODE_2_CLICK(" //*[@id='cspGrid']/div[6]/div/div/div[2]/div[4]", "xpath"),
	DCODE_2_INPUT("//*[@id='cspGrid']/div[6]/div/div/div[2]/div[4]/input","xpath"),
	BOXCODE_CLICK("//*[@id='cspGrid']/div[6]/div/div/div/div[4]", "xpath"),
    BOXCODECLICK2("//*[@id='cspGrid']/div[6]/div/div/div[2]/div[4]", "xpath"),
	DCODE_2_SEARCHICON("//*[@id='cspGrid']/div[6]/div/div/div[2]/div[4]/a/span", "xpath"),
	DOOR_2_CLICK("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[5]", "xpath"),
	DOOR_2_INPUT(" //*[@id='cspGrid']/div[7]/div/div/div[2]/div[5]/input", "xpath"),
	GALLEY_2_CLICK("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[6]", "xpath"),
	GALLEY_2_INPUT("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[6]/input", "xpath"),
	LPOS_2_CLICK("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[7]", "xpath"),
	LPOS_2_INPUT("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[7]/input", "xpath"),
	PRTSEQ_2_CLICK("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[11]", "xpath"),
	PRTSEQ_2_INPUT("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[11]/input", "xpath"),
	BOXLBL_2_CLICK("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[13]", "xpath"),
	BOXLBL_2_SELECT("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[13]/select", "xpath"),
	REMOVEICON_FIRSTROW("//*[@id='cspGrid']/div[6]/div/div/div/div[2]/span/a", "xpath"),
	REMOVEPOPUP_TITLE("//*[@id='removeAlert']/div[1]", "xpath"),
	REMOVEPOPUP_CANCEL("//*[@id='removeAlert']/div[3]/a[2]", "xpath"),
	BC_DOOR_CLICK("//*[@id='cspGrid']/div[7]/div/div/div/div[4]", "xpath"),
	BC_DOOR_INPUT("//*[@id='cspGrid']/div[7]/div/div/div/div[4]/input", "xpath"),
	BC_GALLEY_CLICK("//*[@id='cspGrid']/div[7]/div/div/div/div[5]", "xpath"),
	BC_GALLEY_INPUT("//*[@id='cspGrid']/div[7]/div/div/div/div[5]/input", "xpath"),
	BC_LPOS_CLICK("//*[@id='cspGrid']/div[7]/div/div/div/div[6]", "xpath"),
	BC_LPOS_INPUT("//*[@id='cspGrid']/div[7]/div/div/div/div[6]/input", "xpath"),
	BC_TLS_CLICK("//*[@id='cspGrid']/div[7]/div/div/div/div[8]", "xpath"),
	BC_TLS_INPUT("//*[@id='cspGrid']/div[7]/div/div/div/div[8]/input", "xpath"),
	BC_PRTSEQ_CLICK("//*[@id='cspGrid']/div[7]/div/div/div/div[10]", "xpath"),
	BC_PRTSEQ_INPUT("//*[@id='cspGrid']/div[7]/div/div/div/div[10]/input", "xpath"),
	BC_BOXLBL_CLICK("//*[@id='cspGrid']/div[7]/div/div/div/div[12]", "xpath"),
	BC_BOXLBL_SELECT("//*[@id='cspGrid']/div[7]/div/div/div/div[12]/select", "xpath"),
	BOXCODE_POPUPTITLE("//*[@id='showboxCodeSearch_wnd_title']", "xpath"),
	BC_NODATATODISPLAY("//*[@id='boxCodeGrid']/table/tbody/tr/td", "xpath"),
	BC_SEARCHBOX("//*[@id='boxCodesWrapper']//div[@id='searchContainer']/div[1]/span[1]/input", "xpath"),
	BC_SEARCHICON("//*[@id='boxCodesWrapper']//div[@id='searchContainer']/div[1]/span[2]/a/img", "xpath"),
	BC_FIRSTROW("//*[@id='boxCodeGrid']/table/tbody/tr/td[1]", "xpath"),
	BC_DOOR2_CLICK("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[4]", "xpath"),
	BC_DOOR2_INPUT("//*[@id='cspGrid']/div[5]/div/div[2]/div[8]/input", "xpath"),
	BC_GALLEY2_CLICK("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[5]","xpath"),
	BC_GALLEY2_INPUT("//*[@id='cspGrid']/div[5]/div/div[2]/div[9]/input", "xpath"),
	BC_LPOS2_CLICK("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[6]", "xpath"),
	BC_LPOS2_INPUT("//*[@id='cspGrid']/div[5]/div/div[2]/div[10]/input", "xpath"),
	BC_PRTSEQ2_CLICK("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[10]", "xpath"),
	BC_PRTSEQ2_INPUT("//*[@id='cspGrid']/div[5]/div/div[2]/div[14]/input", "xpath"),
	BC_BOXLBL2_CLICK("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[12]", "xpath"),
	BC_BOXLBL2_SELECT("//*[@id='cspGrid']/div[5]/div/div[2]/div[16]/select", "xpath"),
	BLANKCLICK("//*[@id='cspForm']/div[1]/div[2]/label", "xpath"),
	CSP_FIELD("//*[@id='cspForm']/div[1]/div[2]/span[2]", "xpath"),
	CSPFIELD2("//*[@id='Code']", "xpath"),
	ACVERSION_FIELD("//*[@id='cspForm']/div[4]/div[1]/span[2]", "xpath"),
	ACVERSION_FIELD2("//*[@id='AirCraftVersionCode']", "xpath"),
	EFFECTIVEDATE_FIELD("//*[@id='effectiveDate']", "xpath"),
	ADDITIONALINFO_FIELD("//*[@id='AdditionalInfo']", "xpath"),
	COPY_CSP_ICON("//*[@id='nav']/li[3]/a/div", "xpath"),
	COPY_POPUP_CANCEL("//*[@id='loadingModal']/div[2]/a[1]", "xpath"),
	COPY_POPUP_OK("//*[@id='btnCSPCopy']", "xpath"),
	MENU("//*[@id='menuContainer']/div", "xpath"),
	WHERECSPUSED("//*[@id='menuContainer']/ul/li/a", "xpath"),
	WHERECSPUSED_NODATA("//*[@id='cspUsedInGrid']/table/tbody/tr/td", "xpath"),
	WHERECSPUSED_CLOSE("//*[@id='closeButton']", "xpath"),
	BC_DOOR_CLICK3("//*[@id='cspGrid']/div[7]/div/div/div/div[4]", "xpath"),
	BC_DOOR_INPUT3("//*[@id='cspGrid']/div[7]/div/div/div/div[4]/input", "xpath"),
	BC_GALLEY_CLICK3("//*[@id='cspGrid']/div[7]/div/div/div/div[5]", "xpath"),
	BC_GALLEY_INPUT3("//*[@id='cspGrid']/div[7]/div/div/div/div[5]/input", "xpath"),
	BC_LPOS_CLICK3("//*[@id='cspGrid']/div[7]/div/div/div/div[6]", "xpath"),
	BC_LPOS_INPUT3("//*[@id='cspGrid']/div[7]/div/div/div/div[6]/input", "xpath"),
	BC_PRTSEQ_CLICK3("//*[@id='cspGrid']/div[7]/div/div/div/div[10]", "xpath"),
	BC_PRTSEQ_CLICK4("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[10]", "xpath"),
	BC_PRTSEQ_INPUT4("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[10]/input", "xpath"),
	BC_PRTSEQ_INPUT3("//*[@id='cspGrid']/div[7]/div/div/div/div[10]/input", "xpath"),
	BC_BOXLBL_CLICK3("//*[@id='cspGrid']/div[7]/div/div/div/div[12]", "xpath"),
	BC_BOXLBL_CLICK4("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[12]","xpath"),
	BC_BOXLBL_SELECT4("//*[@id='cspGrid']/div[7]/div/div/div[2]/div[12]/select","xpath"),
	BC_BOXLBL_SELECT3("//*[@id='cspGrid']/div[7]/div/div/div/div[12]/select", "xpath"),
	ADDITIONAL_INFO("//*[@id='AdditionalInfo']","xpath"),
	AC_SEARCHPOPUP_SEARCHTEXT("//*[@id='aircraftVersionSearchPopUp']/div/div/span/input", "xpath"),
	AC_SEARCHPOPUP_SEARCHICON("//*[@id='aircraftVersionSearchPopUp']/div/div/span[2]/a/img", "xpath"),
	SEARCHRECORD_SECONDCOL("//*[@id='aircraftVersionSearchGrid']/table/tbody/tr/td[2]", "xpath"),
	GALLEY_INPUT3("//*[@id='cspGrid']/div[7]/div/div/div[3]/div[6]/input", "xpath"),
	REMOVE_ICON_2("//*[@id='cspGrid']/div[6]/div/div/div[2]/div[2]/span/a", "xpath"),
	;
	
	
	public String element,Identifier;
	private OperationsCSPAddEnum(String element){
		 this.element = element;
	 }
	private OperationsCSPAddEnum(String element, String Identifier){
		 this.element = element;
		 this.Identifier = Identifier;
	 }
	public String getElementPath(){
		return element;
	}
	public String getElementIdentifier(){
		return Identifier;
	}
}
