package com.sacs.PageOjects;

public enum OperationsBoxCodesAddEnum {
	
	OPERATIONS("operations","id"),
	BOX_CODES_XPATH("//*[@id='boxcodes']/a","xpath"),
	BOX_CODE_TEXT_BOX("//*[@id='Code']","xpath"),
	DESCRIPTION("//*[@id='Description']","xpath"),
	CUSTOMER_CODE_DROPDOWN("//*[@id='ParentCustomerId']","xpath"),
	NO_OF_SEALS("NbrOfSeals","id"),
	OK_BTN_XPATH("//*[@id='okButton']","xpath"),
	OK_BTN_ID("OK","linkText"),
	FIRST_ROW_THIRD_COL(".//*[@id='addArticles']/table/tbody/tr[1]/td[3]","xpath"),
	ADD_LINE("bcAddLine","id"),
	ADD_LINE_MENU("addLineMenu","className"),
	ADD_BASIC_ARTICLE_GRID("addBasicArticles","id"),
	//ADD_LINE("//*[@id='addLineContainer']/a","xpath"),
	//ADD_LINE_BASIC_ARTICLE("//*[@id='addLineContainer']/ul/li[1]/a","xpath"),
	ADD_LINE_BASIC_ARTICLE("bcAddLineArticles","id"),
	//ADD_LINE_PRODUCT_CALCULATION("//*[@id='addLineContainer']/ul/li[2]/a","xpath"),
	ADD_LINE_PRODUCT_CALCULATION("bcAddLineCalc","id"),
	//ADD_LINE_SALES_NUMBER("//*[@id='addLineContainer']/ul/li[3]/a","xpath"),
	ADD_LINE_SALES_NUMBER("bcAddLineSales","id"),
	BASIC_ARTICLE_CHECK_BOX("//*[@id='addArticles']/table/tbody/tr[1]/td[1]/div/label/span","xpath"),
	PRODUCT_CALCULATION_CHECK_BOX("//*[@id='addProductCalculation']/table/tbody/tr[1]/td[1]/div/label/span","xpath"),
	SALES_NUMBER_CHECK_BOX("//*[@id='addSalesNumber']/table/tbody/tr[1]/td[1]/div/label/span","xpath"),
	//ADD_SELECTED_BA("//*[@id='addBasicArticles']/div[1]/div[2]/a","xpath"),
	ADD_SELECTED_BA("bcArticleAdd","id"),
	//ADD_SELECTED_PC("//*[@id='addProductCalc']/div[2]/a","xpath"),
	ADD_SELECTED_PC("bcCalcAdd","id"),
	ADD_PRODUCT_CALC("addProductCalc","id"),
	//ADD_SELECTED_SN("//*[@id='addSalesNo']/div[2]/a","xpath"),
	ADD_SELECTED_SN("bcSalesAdd","id"),
	ARTICLE_SEARCH("addArticlesearch","id"),
	ARTICLE_SEARCH_SUBMITE("addSubmit","className"),//div[@class='addInput']//a/img[@class='addSubmit']
	ARTICLE_SEARCH_SUBMITE1(".//*[@id='addSalesNo']/div[1]/div[1]/div[1]/span[2]/a/img","xpath"),
	ARTICLE_SEARCH_FILTER(".//*[@id='addSalesNo']/div[1]/div[1]/div[1]/span[3]/a/img","xpath"),
	ADD_BOX_BUTTON("Add Box Code","linkText"),
	SEARCH_FIELD(".//*[@id='articlesearch']", "xpath"),
	SEARCH_SUBMIT("searchSubmit", "className"),
	TOAST_MESSAGE("toast-message","className"), 
	BOX_CODES_TITLE("//*[@id='contentHeader']/div[1]/h1","xpath"), 
	ADD_BTN("//*[@id='addNew']","xpath"), 
	//BACK_TO_SEARCH("//*[@id='contentHeader']/div[3]/a","xpath"),
	BACK_TO_SEARCH("backToSearch","id"),
	//APPLY_CHANGES_BTN("//*[@id='nav']/li[2]/a/div","xpath"), 
	APPLY_CHANGES_BTN("applyChanges","id"),
	RESULT_GRID_FIRSTCOLUMN_AFTER_SEARCH("//*[@id='results']/table/tbody/tr/td[1]","xpath"),
	RESULT_GRID_SECONDCOLUMN_AFTER_SEARCH("//*[@id='results']/table/tbody/tr/td[2]","xpath"),
	RESULT_GRID_FIRSTCOLUMN_BEFORE_SEARCH("//*[@id='results']/table/tbody/tr[1]/td[1]","xpath"),
	DELETEICON("//*[@id='removePoLink']/div", "xpath"),
	POPUPYES("//*[@id='loadingModal']/div[2]/a[1]", "xpath"),
	NODATATODISPLAY("//*[@id='results']/table/tbody/tr/td", "xpath"),
	BOX_CODE_CHECKBOX(".//*[@id='searchContainer']/div[2]/div[1]/div/label[1]/span","xpath"),
	DESCRIPTION_CHECKBOX(".//*[@id='searchContainer']/div[2]/div[1]/div/label[2]/span","xpath"),
	CUSTOMER_CODE_CHECKBOX(".//*[@id='searchContainer']/div[2]/div[2]/label/span","xpath"),
	FIRST_ROW_SEC_COL("//*[@id='results']/table/tbody/tr[1]/td[2]","xpath"),
	PAGE_HEADING(".//*[@id='contentHeader']/div[1]/h1","xpath"),
	ADD_BOX_CODE("addNew","id"),
	BOX_LABEL("PrintBoxCodeTypeList_listbox","id"),
	LISTELEMENT("//*[@id='boxLabels']/span/div/div","xpath"),
	LISTELEMENT_CANCEL("//*[@id='PrintBoxCodeTypeList_taglist']/li/span[2]","xpath"),
	ADDLINE_CONTAINER(".//*[@id='addLineContainer']","xpath"),
	ARTICLE_CHECKBOX(".//*[@id='addArticles']/table/tbody/tr[1]/td[1]/div/label/span","xpath"),
	ADDED_ARTICLE_NAME(".//*[@id='boxCodeGrid']/div[6]/div/div/div/div[4]","xpath"),
	SEQ_FIELD(".//*[@id='boxCodeGrid']/div[6]/div/div/div/div[3]","xpath"),
	SEQ_FIELD_INPUT(".//*[@id='boxCodeGrid']/div[6]/div/div/div/div[3]/input","xpath"),
	QTY_FIELD(".//*[@id='boxCodeGrid']/div[6]/div/div/div/div[6]","xpath"),
	QTY_FIELD_INPUT(".//*[@id='boxCodeGrid']/div[6]/div/div/div/div[6]/input","xpath"),
	RET_QTY_FIELD(".//*[@id='boxCodeGrid']/div[6]/div/div/div/div[7]","xpath"),
	RET_QTY_FIELD_INPUT(".//*[@id='boxCodeGrid']/div[6]/div/div/div/div[7]/input","xpath"),
	START_FIELD(".//*[@id='boxCodeGrid']/div[6]/div/div/div/div[9]","xpath"),
	START_FIELD_INPUT(".//*[@id='boxCodeGrid']/div[6]/div/div/div/div[9]/span/span/input","xpath"),
	END_FIELD(".//*[@id='boxCodeGrid']/div[6]/div/div/div/div[10]","xpath"),
	END_FIELD_INPUT(".//*[@id='boxCodeGrid']/div[6]/div/div/div/div[10]/span/span/input","xpath"),
	ADD_SALES_NUMBER_FIRST_ROW(".//*[@id='addSalesNumber']/table/tbody/tr[1]/td[3]","xpath"),
	ADD_SALES_NUMBER_FIRST_ROW_DESCRIPTION(".//*[@id='addSalesNumber']/table/tbody/tr[1]/td[2]","xpath"),
	DESCRIPTION_ARTICLE_CHECKBOX(".//*[@id='addSalesNo']/div[1]/div[1]/div[2]/div[1]/label[1]/span","xpath"),
	SALES_NUMBER_CHECKBOX(".//*[@id='addSalesNo']/div[1]/div[1]/div[2]/div[1]/label[2]/span","xpath"),
	UNIT_CHECKBOX(".//*[@id='addSalesNo']/div[1]/div[1]/div[2]/div[2]/label/span","xpath"),
	SALE_SEARCH("addSalessearch","id"),
	FIRST_ROW_CHECKBOX(".//*[@id='addSalesNumber']/table/tbody/tr[1]/td[1]/div/label/span","xpath"),
	CLOSE_BUTTON("bcSalesClose","id"),
	ADD_ARTICLE_GRID(".//*[@id='addArticlesWrapper' and @class='addSalesNo dispNone']","xpath"),
	PRODUCT_CALC_SEARCH(".//*[@id='addProductCalc']/div[@class='addArticleTools']//span/input[@id='addProductsearch']","xpath"),
	PRODUCT_CALC_SEARCH_SUBMIT(".//*[@id='addProductCalc']/div[@class='addArticleTools']//span/a[@class='action-searchSubmit']/img[@class='addSubmit']","xpath"),
	PRODUCT_CALC_GRID_FIRST_ROW(".//*[@id='addProductCalculation']/table/tbody/tr/td[3]","xpath"),
	PRODUCT_CALC_GRID_FIRST_ROW_CHECKBOX(".//*[@id='addProductCalculation']/table/tbody/tr[1]/td[1]/div/label/span","xpath"),
	PC_CLOSE_BUTTON("//div[@id='addProductCalc']//*[@id='closeButton']","xpath"),
	LAST_UPDATED(".//*[@id='lastUpdatedContainer']","xpath"),
	DELETE_ROW(".//*[@id='boxCodeGrid']/div[6]/div/div/div/div[11]/span/a","xpath"),
	CONTINUE("Continue","linkText"),
	POPUP_NO(".//*[@id='loadingModal']/div[2]/a[2]","xpath"),
	POPUP_YES(".//*[@id='loadingModal']/div[2]/a[1]","xpath"),
	COPY_BOXCODE("copyContainer","id"),
	COPY_POPUP(".//*[@id='loadingModal']","xpath"),
	COPY_POPUP_CANCEL(".//*[@id='loadingModal']/div[2]/a[1]","xpath"),
	COPY_POPUP_OK("//*[@id='btnBoxCodeCopy']","xpath"),
	MENU(".//*[@id='menuContainer']/div","xpath"),
	MENU_LIST(".//ul[@class='subMenu']","xpath"),
	REPLACE_WITH("ReplaceBoxCode","id"),
	REPLACE_WITH_SEARCH_ICON(".//*[@id='replaceBoxCode']/div[2]/a","xpath"),
	REPLACE_WITH_POPUP_CANCEL(".//div[@id='searchBoxCodes']//div[@class='detailsBtns']/a[@id='cancelButton']","xpath"),
	REPLACE_WITH_POPUP_OK(".//div[@id='searchBoxCodes']//div[@class='detailsBtns']/a[@id='okButton']","xpath"),
	REPLACE_WITH_POPUP_FIRSTROW(".//*[@id='bcSearchGrid']/table/tbody/tr[1]/td[1]","xpath"),
	REPLACE_WITH_POPUP_SHOWING_ENTRIES(".//*[@id='bcSearchGrid']/div/span","xpath"),
	REPLACE_POPUP_LAST_BUTTON(".//*[@id='bcSearchGrid']/div/div/a[4]/span","xpath"),
	REPLACE_POPUP_FIRST_BUTTON(".//*[@id='bcSearchGrid']/div/div/a[1]/span","xpath"),
	REPLACE_POPUP_NEXT_BUTTON(".//*[@id='bcSearchGrid']/div/div/a[3]/span","xpath"),
	REPLACE_POPUP_PREV_BUTTON(".//*[@id='bcSearchGrid']/div/div/a[2]/span","xpath"),
	CHANGE_ON_DATE(".//*[@id='ChangeOnDate']","xpath"),
	REPLACE_PAGE_OK(".//div[@id='saveContainer']//a[@id='okButton']","xpath"),
	REPLACE_BOX_CODE_POPUP_DROPDOWN(".//*[@id='BoxCodeLocationList']","xpath"),
	REPLACE_BOX_CODE_POPUP_CANCEL(".//div[@id='viewReplaceBoxCodeIn']//a[@id='cancelButton']","xpath"),
	REPLACE_BOX_CODE_POPUP_OK(".//*[@id='viewReplaceBoxCodeIn']/div[3]/a[2]","xpath"),
	REPLACE_BOX_CODE_POPUP_FIRST_CHECKBOX(".//*[@id='replaceBoxCodeInGrid']/table/tbody/tr[1]/td[4]/div/label/span","xpath"),
	SEARCH_RESULT(".//*[@id='results']/table/tbody/tr[1]/td[2]","xpath"),
	USED_IN_POPUP(".//*[@id='viewBoxCodeUsedIn_wnd_title']","xpath"),
	USED_IN_POPUP_OK("OK","linkText"),
	NOT_ASSOCIATED_POPUP_OK(".//*[@id='loadingModal']/div[2]/a","xpath"),
	NOT_ASSOCIATED_POPUP_TITLE(".//*[@id='loadingModal']/div[1]/div","xpath"),
	BASIC_ARTICLE("Basic Articles","linkText"),
	ADDLINE("//*[@id='bcAddLine']", "xpath"),
	ADDLINE_SALESNUMBER("//*[@id='bcAddLineSales']", "xpath"),
	ASN_SEARCHBOX("//*[@id='addSalessearch']", "xpath"),
	ASN_SEARCHICON("//*[@id='addSalesNo']/div[1]/div[1]/div[1]/span[2]/a/img", "xpath"),
	ASN_SELECT_SALESNO_CHKBOX("//*[@id='addSalesNumber']/table/tbody/tr/td[1]/div/label/span", "xpath"),
	ASN_ADDSELECTED("//*[@id='bcSalesAdd']", "xpath"),
	ADDLINE_APPLYCHANGES("//*[@id='applyChanges']", "xpath"),
	SALESNO_SEARCHRECORD("//*[@id='addSalesNumber']/table/tbody/tr/td[3]/span", "xpath"),
	WHEREBOXCODEUSED("//*[@id='menuContainer']/ul/li[2]/a", "xpath"),
	REPLACEUSED_POPUP_OKBTN("//*[@class='modalBtn']/a", "xpath"),
	WHEREBOXCODEUSED_UNIT("//*[@id='menuContainer']/ul/li[1]/a", "xpath"),
	;

	public String element,Identifier;
	private OperationsBoxCodesAddEnum(String element){
		 this.element = element;
	 }
	private OperationsBoxCodesAddEnum(String element, String Identifier){
		 this.element = element;
		 this.Identifier = Identifier;
	 }
	public String getElementPath(){
		return element;
	}
	public String getElementIdentifier(){
		return Identifier;
	}

	
}
