package com.sacs.PageOjects;

public enum ProductionPlanningWasteRegistrationEnum {
	PRODUCTION_PLANNING("//*[@id='productionplanning']","xpath"),
	PAGETITILE("//*[@id='contentHeader']/div/h1","xpath"),
	WASTE_REGISTRATION("//*[@id='wasteregistration']/a","xpath"),
	CATEGORY("//*[@id='Category']","xpath"),
	DEPARTMENT("//*[@id='Department']","xpath"),
	DELETE_ON_ROW("//*[contains(@class,'action-DeleteRow')]","xpath"),
	TYPE("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[1]","xpath"),
	TYPE_SELECT("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[1]/select","xpath"),
	NUMBER("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[2]","xpath"),
	NUMBER_SEARCH_ICON("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[2]/a/span","xpath"),
	SEARCH_BA_POPUP("//*[@id='basicArticleSearchPopup']","xpath"),
	SEARCH_BA_POPUP_FIRST_ROW("//*[@id='addBasicArticlesGrid']/table/tbody/tr[1]/td[2]","xpath"),
	REASON("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[7]","xpath"),
	REASON_SELECT("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[7]/select","xpath"),
	QTY("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[9]","xpath"),
	QTY_INPUT("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[9]/input","xpath"),
	APPLY_CHANGES("//*[@id='applyChanges']","xpath"),
	OK("//*[@id='paxOK']","xpath"),
	CONTINUE_ON_DELETE_POPUP("//*[@id='loadingModal']/div[2]/a[2]","xpath"),
	ADD_LINE("//*[@id='addLine']","xpath"),
	SUBSTORE("//*[@id='StoreCode']","xpath"),
	SUBSTORE_LIST("html/body/ul","xpath"),
	SUBSTORE_SELECTED("html/body/ul/li[4]/a","xpath"),
	NUMBER_FOR_SW("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[1]","xpath"),
	NUMBER_SEARCH_ICON_FOR_SW("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[1]/a/span","xpath"),
	REASON_FOR_SW("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[5]","xpath"),
	REASON_SELECT_FOR_SW("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[5]/select","xpath"),
	QTY_FOR_SW("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[6]","xpath"),
	QTY_INPUT_FOR_SW("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[6]/input","xpath"),
	WASTEDATE("//*[@id='WasteDate']", "xpath"),
	SELECT_SALESCODE("//*[@id='addSalesNumberGrid']/table/tbody/tr[1]/td[1]", "xpath"),
	CATEGORY_TEXT("//*[@id='wrReadOnlyHeader']/div/div[2]/span[2]", "xpath"),
	DEPARTMENT_TEXT("//*[@id='wrReadOnlyHeader']/div/div[3]/span[2]", "xpath"),
	SALESNO_DESC_TEXT("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[3]", "xpath"),
	SEARCHPRODUCT_POPUPTITLE("//*[@id='showProductSearch_wnd_title']", "xpath"),
	SEARCHPRODUCT_POPUPCANCELBTN("//*[@id='cancelProduct']", "xpath"),
	SEARCHPRODUCT_POPUPCONTINUEBTN("//*[@id='selProductContinue']", "xpath"),
	SEARCHPRODUCT_POPUPINVERTED("//*[@id='searchContainer']/div[1]/span[3]/a/img", "xpath"),
	SEARCHPRODUCT_DESCRIPTION("//*[@id='searchContainer']/div[2]/div[1]/label[1]/span", "xpath"),
	SEARCHPRODUCT_CUSTOMER("//*[@id='searchContainer']/div[2]/div[2]/label[1]/span", "xpath"),
	SEARCHPRODUCT_PRODUCTNUMBER("//*[@id='searchContainer']/div[2]/div[1]/label[2]/span", "xpath"),
	SEARCHPRODUCT_KEY("//*[@id='searchContainer']/div[2]/div[2]/label[2]/span", "xpath"),
	SEARCHPRODUCT_TYPE("//*[@id='searchContainer']/div[2]/div[1]/label[3]/span", "xpath"),
	SEARCHPRODUCT_ISACCEPTED("//*[@id='searchContainer']/div[2]/div[2]/label[3]/span", "xpath"),
	PRODUCT_DESCRIPTION_FIRSTROW("//*[@id='productSearchGrid']/table/tbody/tr[1]/td[2]", "xpath"),
	SEARCHPRODUCT_TEXTBOX("//div[@id='productWrapper']//*[@class='searchInput']/span/input", "xpath"),
	SEARCHPRODUCT_SEARCHICON("//*[@id='searchContainer']/div[1]/span[2]/a/img", "xpath"),
	PRODUCTSEARCHED_DESCRIPTION("//*[@id='productSearchGrid']/table/tbody/tr/td[2]", "xpath"),
	FIRST_ROW_FIRST_COL("//*[@id='productSearchGrid']/table/tbody/tr[1]/td[1]", "xpath"),
	FIRSTROW_FIRSTCOL("//*[@id='addSalesNumberGrid']/table/tbody/tr/td[1]", "xpath"),
	NEXT("//*[@id='productSearchGrid']/div/div/a[3]/span", "xpath"),
	PREV("//*[@id='productSearchGrid']/div/div/a[2]/span", "xpath"),
	LAST("//*[@id='productSearchGrid']/div/div/a[4]/span", "xpath"),
	FIRST("//*[@id='productSearchGrid']/div/div/a[1]/span", "xpath"),
	SHOW_ENTRIES_POPUP("//*[@id='productSearchGrid']/div/span","xpath"),
	SALESNO_TEXT("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[2]/input", "xpath"),
	SEARCHPRODUCT_UOM("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[4]", "xpath"),
	WCCLICK("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[5]", "xpath"),
	WCSELECT("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[5]/select", "xpath"),
	ADDLINE_CATEGORY("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[6]", "xpath"),
	ADDLINE_REMOVEICON("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[12]/span/a", "xpath"),
	ADDLINE_QUESTIONMARK("//*[@class='ui-widget-content slick-row active even']//*[@class='slick-cell l10 r10']/span/a", "xpath"),
	ERROR_POPUP("//*[@id='errorAlert']/div[2]/ul/li", "xpath"),
	ERROR_POPUP_OK_BTN("//*[@id='errorAlert']/div[3]/a", "xpath"),
	ADDLINE_REMARK("//*[@id='wasteRegGrid']/div[6]/div/div/div/div[10]/div/a", "xpath"),
	REMARK_TEXTBOX("//*[@id='remark']", "xpath"),
	REMARK_CONTINUE("//*[@id='continueButton']", "xpath"),
	REMARK_CANCEL("//*[@id='addRemarksPopup']/div[3]/a[1]", "xpath"),
	REMARKS_TITLE("//*[@id='addRemarksPopup_wnd_title']", "xpath"),
	SEARCH_SALESCODES_POPUPTITLE("//*[@id='salesNoSearchPopup_wnd_title']", "xpath"),
	SEARCH_SALESCODES_CANCELBTN("//*[@id='salesNoSearchPopup']/div[3]/a[1]", "xpath"),
	SEARCH_SALESCODES_CONTINUEBTN("//*[@id='salesNoSearchPopup']/div[3]/a[2]", "xpath"),
	SALESCODES_DESCRIPTION_FIRSTROW("//*[@id='addSalesNumberGrid']/table/tbody/tr/td[2]", "xpath"),
	SALESCODES_POPUP_SEARCHBOX("//*[@id='acarticlesearch']", "xpath"),
	SALESCODES_POPUP_SEARCHICON("//*[@id='salesNoSearchPopup']/div[1]/div/span[2]/a/img", "xpath"),
	SALESCODES_POPUP_NEXT("//*[@id='addSalesNumberGrid']/div/div/a[3]/span", "xpath"),
	SALESCODES_POPUP_PREV("//*[@id='addSalesNumberGrid']/div/div/a[2]/span", "xpath"),
	SALESCODES_POPUP_LAST("//*[@id='addSalesNumberGrid']/div/div/a[4]/span", "xpath"),
	SALESCODES_POPUP_FIRST("//*[@id='addSalesNumberGrid']/div/div/a[1]/span", "xpath"),
	SALESCODES_NOOFENTRIES("//*[@id='addSalesNumberGrid']/div/span", "xpath"),
	BASICARTICLE_NOOFENTRIES("//*[@id='addBasicArticlesGrid']/div/span", "xpath"),
	SALESCODE_UNIT("//*[@id='addSalesNumberGrid']/table/tbody/tr/td[3]", "xpath"),
	SEARCHBASICARTICLE_POPUPTITLE("//*[@id='basicArticleSearchPopup_wnd_title']", "xpath"),
	BASICARTICLE_CANCELBTN("//*[@id='basicArticleSearchPopup']/div[3]/a[1]", "xpath"),
	BASICARTICLE_CONTINUEBTN("//*[@id='basicArticleSearchPopup']/div[3]/a[2]", "xpath"),
	BASICARTICLE_DESC_FIRSTROW("//*[@id='addBasicArticlesGrid']/table/tbody/tr[1]/td[2]", "xpath"),
	BASICARTICLE_SEARCHBOX("//*[@id='basicArticleSearchPopup']/div/div/span[1]/input", "xpath"),
	BASICARTICLE_SEARCHICON("//*[@id='basicArticleSearchPopup']/div[1]/div/span[2]/a/img", "xpath"),
	BASICARTICLE_DESC_SINGLEROW("//*[@id='addBasicArticlesGrid']/table/tbody/tr/td[2]", "xpath"),
	BA_FIRSTROW_FIRSTCOL("//*[@id='addBasicArticlesGrid']/table/tbody/tr[1]/td[1]", "xpath"),
	BASICARTICLE_POPUP_NEXT("//*[@id='addBasicArticlesGrid']/div/div/a[3]/span", "xpath"),
	BASICARTICLE_POPUP_PREV("//*[@id='addBasicArticlesGrid']/div/div/a[2]/span", "xpath"),
	BASICARTICLE_POPUP_FIRST("//*[@id='addBasicArticlesGrid']/div/div/a[1]/span", "xpath"),
	BASICARTICLE_POPUP_LAST("//*[@id='addBasicArticlesGrid']/div/div/a[4]/span", "xpath"),
	BASICARTICLE_FIRSTROW_UOM("//*[@id='addBasicArticlesGrid']/table/tbody/tr[1]/td[4]", "xpath"),
	STORECODE("//*[@id='StoreCode']", "xpath"),
	STORECODE_TEXT1("//*[@id='formBody']/div[4]/span[2]", "xpath"),
	STORECODE_TEXT2("//*[@id='formBody']/div[4]/span[3]", "xpath"),
	STORECODE_BA_SEARCHBOX("//*[@id='basicArticleSearchPopup']/div[1]/div/span[1]/input", "xpath"),
	STORECODE_BA_SEARCHICON("//*[@id='basicArticleSearchPopup']/div[1]/div/span[2]/a/img", "xpath"),
	STORECODE_BA_CANCELBTN("//*[@id='cancelButton']", "xpath"),
	WASTEREASON_ENTRIES("//*[@id='gridWrapper']/div[3]/span", "xpath"),
	BACKTOMODULE("//*[@id='subNav-system']/span/sup", "xpath"),
	STORECODE_QUESTIOMARK("//*[@id='wasteRegGridSection']/div/div[2]/div/div[6]/div/div/div/div[7]/span/a", "xpath"),
	STORECODE_ERRORPOPUPTEXT("//*[@id='errorAlert']/div[2]/ul/li[2]", "xpath"),
	CATEGORY_DD("//*[@id='Category']", "xpath"),
	;
	
	
	public String element,Identifier;
	private ProductionPlanningWasteRegistrationEnum(String element){
		 this.element = element;
	 }
	private ProductionPlanningWasteRegistrationEnum(String element, String Identifier){
		 this.element = element;
		 this.Identifier = Identifier;
	 }
	public String getElementPath(){
		return element;
	}
	public String getIdentifier(){
		return Identifier;
	}
}
