package com.sacs.PageOjects;

public enum PurchaseBasicArticlesSearchEnum {
	
	BASIC_ARTICLES_LINK(".//*[@id='basicarticle']/a", "xpath"),
	BASIC_ARTICLES_TITLE(".//*[@id='contentHeader']/div[1]/h1", "xpath"),
	UPDATE_BASIC_ARTICLES_TITLE(".//*[@id='contentHeader']/div[1]/h1", "xpath"),
	SEARCH_FIELD(".//*[@id='articlesearch']", "xpath"),
	SEARCH_SUBMIT("searchSubmit", "className"),
	SEARCH_DROPDOWN(".//*[@id='searchContainer']/div[1]/span[3]/a/img", "xpath"),
	SHOW_ENTRIES_DROP_DOWN("k-select", "className"),
	SHOWING_ENTRIES(".//*[@id='pager_top']/span", "xpath"),
	GRID_ART_NUMBER_HEADING(".//*[@id='results']/table/thead/tr/th[1]/a", "xpath"),
	GRID_FIRST_ROW(".//*[@id='results']/table/tbody/tr[1]/td[2]", "xpath"),
	GRID_SECOND_ROW(".//*[@id='results']/table/tbody/tr[3]/td[2]", "xpath"),
	NO_DATA_TO_DISPLAY(".//*[@id='results']/table/tbody/tr/td", "xpath"),
	GRID_FIRST_ROW_ARTICLE_NO_VALUE(".//*[@id='results']/table/tbody/tr[1]/td[1]", "xpath"),
	GRID_FIRST_ROW_ARTICLE_NANE_VALUE(".//*[@id='results']/table/tbody/tr[1]/td[2]", "xpath"),
	GRID_FIRST_ROW_PRIMARY_VENDOR_VALUE(".//*[@id='results']/table/tbody/tr[1]/td[6]", "xpath"),
	GRID_FIRST_ROW_ARTICLE_GROUP_VALUE(".//*[@id='results']/table/tbody/tr[1]/td[4]", "xpath"),
	GRID_FIRST_ROW_VENDOR_ARTICLE_NO_VALUE(".//*[@id='results']/table/tbody/tr[1]/td[7]", "xpath"),
	GRID_FIRST_ROW_SUB_STORE_CODE_VALUE(".//*[@id='results']/table/tbody/tr[1]/td[4]", "xpath"),
	
	
	ADD_ARTICLE_BTN(".//*[@id='contentHeader']/div[2]/a", "xpath"),
	ADD_BASIC_ARTICLE_TITLE(".//*[@id='contentHeader']/div[1]/h1", "xpath"),
	BACK_TO_SEARCH(".//*[@id='contentHeader']/div[3]/a", "xpath"),
	BACK_TO_SEARCH_AT_UNIT("//*[@id='backToSearch']", "xpath"),
	PRIMARY_DESC(".//*[@id='PrimaryDesc']", "xpath"),
	DESCRIPTION_2(".//*[@id='AdditionalDesc']", "xpath"),
	ARTICLE_GROUP(".//*[@id='ArticleGroupCode']", "xpath"),
				   
	PURCHASE_UOM(".//*[@id='PurchaseUOM']", "xpath"),
	PURCHASE_TO_STORE_UOM(".//*[@id='PurchaseToStoreUOC']", "xpath"),
	STORE_UOM(".//*[@id='StoreUOM']", "xpath"),
	MENU_UOM(".//*[@id='MenuUOM']", "xpath"),
	CATEGORY_CODE("CategoryCode", "id"),
	DEPARTMENT_CODE("DepartmentCode", "id"),
	//APPLY_CHANGES(".//*[@id='saveContainer']/a", "xpath"),
	APPLY_CHANGES("//*[@id='applyChanges']", "xpath"),
	SUBSTORE_COLLAPSE("//div[contains(text(),'Sub Store Codes')]/a", "xpath"),
	UI_MENU_ITEMS("ui-menu-item", "className"),
	TOAST_MESSAGE("toast-message","className"),
	COMMODITY_PERCENT(".//*[@id='CommodityPercent']", "xpath"),
	COMMODITY_FIXED(".//*[@id='CommodityFixValue']", "xpath"),
	ACTIVE_CHK_BOX(".//*[@id='formBody']/div[1]/div[14]/label/span", "xpath"),
	STORE_RESTITUTION_UOM(".//*[@id='RestitutionUOM']", "xpath"),
	RESTITUTION_GROUP(".//*[@id='RestitutionGroupId']", "xpath"),
	RESTITUTION_NUMBER(".//*[@id='RestitutionNumber']", "xpath"),
	REFOUND(".//*[@id='RestitutionRefundAmt']", "xpath"),
	COUNTRY_OF_ORIGIN(".//*[@id='CountryOfOrigin']", "xpath"),
	EXCISE_DUTY_NUMBER(".//*[@id='ExciseDutyNumber']", "xpath"),
	TAX_CODE(".//*[@id='TaxCode']", "xpath"),
	EXCISE_DUTY_RATE(".//*[@id='ExciseDutyCostPrice']", "xpath"),
	
	VENDOR_NAME_01("//*[@id='VendorName_0']", "xpath"),
	VENDOR_NAME_02("//*[@id='VendorName_1']", "xpath"),
//	ADD_NEW_VENDOR_BTN(".//*[@id='vendorContainer']/div[5]/a", "xpath"),
	ADD_NEW_VENDOR_BTN(".//*[@id='vendorContainer']/div[2]/div[3]/a", "xpath"),
	ADD_SUB_STORE_BTN(".//*[@id='subStoreContainer']/div[2]/div[2]/a", "xpath"),
	SUB_STORE_CODE_0(".//*[@id='StoreCode_0']", "xpath"),
	SUB_STORE_CODE_1(".//*[@id='StoreCode_1']", "xpath"),
	SUB_STORE_POSITION_0(".//*[@id='storePosition_0']", "xpath"),
	SUB_STORE_POSITION_1(".//*[@id='storePosition_1']", "xpath"),
	UI_ACTIVE_MENUITEM("ui-active-menuitem", "id"),
	ARTICLE_OWNER("//*[@id='CustomerCode']", "xpath"),
	VENDOR_ARTICLE_NO(".//*[@id='vendorArticle_0']", "xpath"),
	DEPARTMENT("//*[@id='DepartmentCode']","xpath"),
	GRID_SEARCH_RESULT("//*[@id='results']/table/tbody/tr/td[1]","xpath"),
	REORDER_TIME(".//*[@id='VendorReorderTime_0']", "xpath"),
	LEAD_TIME(".//*[@id='VendorLeadTime_0']", "xpath"),
	SET_AS_PRIMARY(".//*[@id='vendorContainer']/div[2]/div[1]/div[3]/label/span", "xpath"),
	SET_AS_PRIMARY_ID("vendor_0", "id"),
	SET_AS_PRIMARY_BA_ID("subStore_0", "id"),
	REMOVE_ICON("g", "linkText"),
	NOTES_ID("AdditionalInfo", "id"),

	
	UOM_DROPDOWN("html/body/ul[2]/li","xpath"),
	ARTICLE_GROUP_DROPDOWN("html/body/ul[1]/li","xpath"),
	SUB_STORE_CODE_DROPDOWN("html/body/ul[9]", "xpath"),
	ADD_VENDOR_DROPDOWN_1("html/body/ul[8]", "xpath"),
	ADD_VENDOR_DROPDOWN_2("html/body/ul[9]", "xpath"),
	GRID_LAST_LINK_(".//*[@id='gridWrapper']/div[3]/div/a[4]/span", "xpath"),
	PAGINATION_OPTION(".//div[@class='pagContainerTop']", "xpath"),
	SEARCH_RESULT_GRID(".//*[@id='results']/table", "xpath"),
	MENU_TOOLBAR(".//*[@id='results']/table/tbody/tr[1]/td[9]", "xpath"),
	COPY_LINK("C", "linkText"),
	REMOVE_LINK("X", "linkText"),
	EDIT_LINK("p", "linkText"),
	ARTICLE_NO_CHKBOX(".//*[@id='searchContainer']/div[2]/div[1]/label[1]/span", "xpath"),
	PRIMARY_VENDOR_CHKBOX(".//*[@id='searchContainer']/div[2]/div[2]/label[1]/span", "xpath"),
	ARTICLE_NAME_CHKBOX(".//*[@id='searchContainer']/div[2]/div[1]/label[2]/span", "xpath"),
	SUB_STORE_CODE_CHKBOX(".//*[@id='searchContainer']/div[2]/div[2]/label[2]/span", "xpath"),
	ARTICLE_GROUP_CHKBOX(".//*[@id='searchContainer']/div[2]/div[1]/label[3]/span", "xpath"),
	SHOW_INACTIVE_CHKBOX(".//*[@id='searchContainer']/div[2]/div[2]/label[3]/span", "xpath"),
	VENDOR_ARTICLE_NO_CHKBOX(".//*[@id='searchContainer']/div[2]/div[1]/label[4]/span", "xpath"),
	SEARCH_GRID_SELECT_ITEMS_PER_PAGE_LIST_CLASS("k-item","className"),
	ARTICLENUMBER_CLASS("articlenumber", "className"),
	COPY_BASIC_ARTICLE_POPUP_HEADING(".//*[@id='copyAlert']/div[1]", "xpath"),
	COPY_BASIC_ARTICLE_POPUP_CONTINUE_BTN("//*[@id='copyAlert']/div[5]/a[2]", "xpath"),
	COPY_BASIC_ARTICLE_POPUP_CANCEL_BTN(".//*[@id='copyAlert']/div[5]/a[1]", "xpath"),
	REMOVE_BASIC_ARTICLE_POPUP_HEADING(".//*[@id='removeAlert']/div[1]", "xpath"),
	REMOVE_BASIC_ARTICLE_POPUP_CONTINUE_BTN(".//*[@id='removeAlert']/div[3]/a[1]", "xpath"),
	REMOVE_BASIC_ARTICLE_POPUP_CANCEL_BTN(".//*[@id='removeAlert']/div[3]/a[2]", "xpath"),
	NEXT_PAGE_LINK("//*[@id='gridWrapper']/div[3]/div/a[3]/span", "xpath"),
	LAST_PAGE_LINK("//*[@id='gridWrapper']/div[3]/div/a[4]/span", "xpath"),
	PRIVIOUS_PAGE_LINK("//*[@id='gridWrapper']/div[3]/div/a[2]/span", "xpath"),
	FIRST_PAGE_LINK("//*[@id='gridWrapper']/div[3]/div/a[1]/span", "xpath"),
	
	STORE_TO_RESTUOM(".//*[@id='StoreToRestUOC']", "xpath"),
	DAY_PRICE(".//*[@id='DayPrice']", "xpath"),
	VENDOR_ARTICLE_NUMBER_ON_GRID("//*[@id='results']/table/tbody/tr[1]/td[6]","xpath"),
	MINIMUM_STOCK_LEVEL(".//*[@id='MinimumStockLevel']", "xpath"),
	MAXIMUM_STOCK_LEVEL(".//*[@id='MaximumStockLevel']", "xpath"),
	VAT_CODE(".//*[@id='VATId']", "xpath"),
	TITLE_CLASS("title", "className"),
	COPY_DAY_PRICE(".//*[@id='copyAlert']/div[3]/label[1]/span", "xpath"),
	COPY_DAY_PRICE_ID("copyPrice", "id"),
	COPY_RESTITUTION_INFO(".//*[@id='copyAlert']/div[3]/label[2]/span", "xpath"),
	COPY_RESTITUTION_INFO_ID("copyInformation", "id"),
	COPY_BASIC_ARTICLE_TITLE(".//*[@id='contentHeader']/div[1]/h1", "xpath"),
	UI_MENU_ITEMS1("html/body/ul[9]/li","xpath"),
	UI_MENU_ITEMS2("html/body/ul[10]/li","xpath"),
	UI_MENU_ITEMS_XPATH("//li[@class='ui-menu-item']/a","xpath"),
	CANCEL("Cancel","linkText"),
	CONTINUE("Continue","linkText"),
	UOMLIST("html/body/ul[2]", "xpath"),
	STOREUOMLIST("html/body/ul[3]", "xpath"),
	MENUUOMLIST("html/body/ul[4]", "xpath"),
	REMOVE_VENDOR_ASSOCIATION("//*[@id='vendorContainer']/div[2]/div[1]/div[3]/div/a", "xpath"),
	SAVE_ICON("//div[@class='IconSet']","xpath"),
	VENDOR_DESC("//*[@id='VendorDescription']", "xpath"),
	FINANCE_ACCOUNT_GROUP("//input[@id='ArticleFinanceGroupNumber']","xpath"),
	FAGLIST("html/body/ul[2]","xpath"),
	ARTICLEFINANCEGROUP("//*[@id='ArticleFinanceGroupNumber']", "xpath"),
	ARTICLEGROUP("//input[@id='ArticleGroupCode']", "xpath"),
	AG_LIST("html/body/ul[1]", "xpath"),
	SETTING_ICON("//*[@role='rowgroup']/tr[1]/td[9]/a", "xpath"),
	GLOBAL_DESC("//*[@id='searchContainer']/div[2]/div[2]/label[4]/span", "xpath"),
	VENDOR_ARTNO_CHKBOX("//*[@id='searchContainer']/div[2]/div[2]/label[4]/span", "xpath"),
	VENDORS_LIST("html/body/ul[10]", "xpath"),
	REMOVEVENDOR_CONTINUEBTN("//*[@id='removeVendorAlert']/div[2]/a[1]", "xpath"),
	SAVE_ICON2("//*[@id='nav']/li[8]/a/div", "xpath"),
	UOM_ALERT_OKBTN("//*[@id='uomAlertOk']", "xpath"),
	GRIDROW_SUBSTORE("//*[@id='results']/table/tbody/tr[1]/td[5]", "xpath"),
	SHOWENTRIES_DD_2("//*[@id='gridWrapper']/div[1]/div[2]/span/span[1]/span[2]", "xpath"),
	STOREISSUE_UOM("//*[@id='StoreIssueUOM']", "xpath"),
	SAVE_ICON3("//*[@id='nav']/li[6]/a/div", "xpath"),
	SHOW_ENTRIES_DD("//*[@id='formBody']/div[2]/div[2]/span/span[1]/span[1]", "xpath"),
	ARTICLETYPE_AIRLINE("//*[@id='divArticletype']/span[3]/label/span", "xpath"),
	ARTICLE_NUMBER("//*[@id='ArticleNumber']", "xpath"),
	ACTIVE_CHKBOX("//*[@id='formBody']/div[1]/div[16]/label/span", "xpath"),
	VENDOR_CONTAINER("//*[@id='vendorContainer']/div[2]/div[1]/div[1]/div[1]/span/label", "xpath"),
	;
	
	public String element, identifier;
	
	private PurchaseBasicArticlesSearchEnum(String element){
		 this.element = element;
	 }
	
	private PurchaseBasicArticlesSearchEnum(String element, String identifier){
		 this.element = element;
		 this.identifier = identifier;
	 }
	
	public String getElementPath(){
		return element;
	}
	public String getElementIdentifier(){
		return identifier;
	}
}
