package com.sacs.PageOjects;

public enum PurchaseOrderRegistrationEnums {
	
	PURCHASE("purchase","id"),
	ORDER_REGISTRATION_TITLE(".//*[@id='contentHeader']/div[1]/h1", "xpath"),
	ORDER_REGISTRATION_LINK("//*[@id='purchaseorder']/a", "xpath"),
	CREATE_NEW_PURCHASE_ORDER_LINK("//*[@id='searchExistingVendor']/div/div", "xpath"),
	SEARCH_FIELD(".//*[@id='articlesearch']", "xpath"),
	ADD_ARTICLE_SEARCH("//*[@id='addArticlesearch']","xpath"),
	SEARCH_SUBMIT("searchSubmit", "className"),
	ADD_SUBMIT("addSubmit", "className"),
	GRID_VENDOR_NAME_FIRST_COLUMN_VALUE(".//*[@id='results']/table/tbody/tr[1]/td[2]", "xpath"),
	GRID_ARTICLE_DESC_COLUMN_VALUE(".//*[@id='myGrid']/div[5]/div/div/div[2]", "xpath"),
	GRID_ORDER_NO_COLUMN_VALUE(".//*[@id='results']/table/tbody/tr/td[1]", "xpath"),
	SEARCH_EXISTING_ORDER("//*[@id='addNew']", "xpath"),
	CREATE_ORDER(".//*[@id='contentHeader']/div[2]/a", "xpath"),
	VENDOR_TITLE(".//*[@id='vendorTitle']/span", "xpath"),
	GET_ARTICLE(".//*[@id='PoSource']", "xpath"),
	GET_ARTICLE_ID("PoSource","id"),
	OK_BTN(".//*[@id='btnContainer']/a[2]", "xpath"),
	CANCEL_BTN(".//*[@id='btnContainer']/a[1]", "xpath"),
	BACK_BTN("//*[@id='contentBody']/section/div/div[3]/a", "xpath"),
	ORDER_QUANTITY(".//*[@id='myGrid']/div[7]/div/div/div/div[4]", "xpath"),
	ORDER_QUANTITY_INPUT(".//*[@id='myGrid']/div[7]/div/div/div/div[4]/input", "xpath"),
	APPLY_CHANGES(".//*[@id='applyChanges']", "xpath"),
	APPLY_CHANGES_BTN("//*[contains(text(),'Apply Changes')]", "xpath"),
	TOAST_MESSAGE("toast-message", "className"),
	SUBMIT_ORDER(".//*[@id='submitOrder']", "xpath"),
	SUBMIT_CONTINUE(".//*[@id='submitOrderContainer']/a[2]", "xpath"),
	SUBMIT_PURCHASE_ORDER_POPUP(".//*[@id='poSubmitDetails']", "xpath"),
	SUBMIT_OK_BTN(".//*[@id='poConfirmInfo']/div/a[3]", "xpath"),
	ORDER_RECEIPT_LINK(".//*[@id='orderreceipt']/a", "xpath"),
	SEARCH_FOR_ORDER_BY_VENDOR_LINK("//*[@id='searchExistingVendor']/div/div", "xpath"),
	SEARCH_FOR_ALL_EXISTING_ORDERS_LINK("//*[@id='searchExistingOrder']/div/div", "xpath"),
	RECEIVE_WITHOUT_PO_BTN(".//*[@id='contentHeader']/div[2]/a", "xpath"),
	RECEIPT_OK_BTN(".//*[@id='receiptbtnContainer']/a", "xpath"),
	DELIVERY_NOTE_NUMBER_BTN(".//*[@id='DeliveryNoteNumber']", "xpath"), 
	RESULT_GRID_FIRST_COLUMN_BEFORE_SEARCH("//*[@id='results']/table/tbody/tr[1]/td[1]","xpath"),
	RESULT_GRID_FIRST_COLUMN_THIRD_ROW_BEFORE_SEARCH("//*[@id='results']/table/tbody/tr[3]/td[1]","xpath"),
	RESULT_GRID_SECOND_COLUMN_THIRD_ROW_BEFORE_SEARCH("//*[@id='results']/table/tbody/tr[3]/td[2]","xpath"),
	RESULT_GRID_FIRST_COLUMN_AFTER_SEARCH("//*[@id='results']/table/tbody/tr/td[1]","xpath"),
	RESULT_GRID_FIRST_COLUMN_AFTER_SEARCH1(".//*[@id='results']/table/tbody/tr[1]/td[3]","xpath"),
	SEARCH_CONTAINER_LABEL("//*[@id='searchContainer']/label","xpath"),
	BACK_BUTTON("//*[@id='contentHeader']/div[2]/a","xpath"),
	ORDER_FORMS("//*[@id='orderFormHeader']/div[1]","xpath"),
	ORDER_FORMS_DETAILS_CANCEL("//*[@id='poDetilasContainer']/div/div[3]/a[1]","xpath"),
	ORDER_FORM_DETAILS_POP_UP("//*[@id='poDetilasContainer']","xpath"),
	CREATE_ORDER_ON_ORDER_FORM_DETAILS_POPUP("//*[@id='createOrderByForm']","xpath"),
	ADD_ARTICLE("//*[@id='gridWrapper']/div[5]/div/a","xpath"),
	SEARCH_RESULT_GRID_NEXT_LINK_XPATH("//*[@id='gridWrapper']/div[3]/div/a[3]/span","xpath"), 
	SEARCH_RESULT_GRID_PREVIOUS_LINK_XPATH("//*[@id='gridWrapper']/div[3]/div/a[2]/span","xpath"),
	SEARCH_RESULT_GRID_LAST_LINK_XPATH("//*[@id='gridWrapper']/div[3]/div/a[4]/span","xpath"),
	SEARCH_RESULT_GRID_FIRST_LINK_XPATH("//*[@id='gridWrapper']/div[3]/div/a[1]/span","xpath"),
	CHANGE_VENDOR("//*[@id='contentBody']/section/div[3]/a","xpath"),
	CHANGE_VENDOR_ONCREATE_ORDER_PAGE("//*[@id='contentBody']/section/div[4]/a","xpath"),
	SEARCH_FILTER("searchFilter","className"),
	SEARCH_CONTAINER("//*[@id='searchContainer']/div[2]","xpath"),
	RESULTS("results","id"), 
	ORDER_NUMBER("//*[@id='results']/table/thead/tr/th[1]/a","xpath"), 
	ORDER_DATE("//*[@id='results']/table/thead/tr/th[2]/a","xpath"), 
	ITEMS("//*[@id='results']/table/thead/tr/th[3]/a","xpath"), 
	STATUS("//*[@id='results']/table/thead/tr/th[4]","xpath"),
	NO_DATA_TO_DISPLAY("//*[@id='results']/table/tbody/tr/td","xpath"),
	PENDING_CRITERIA("//*[@id='searchContainer']/div[2]/div[1]/label[1]/span","xpath"),
	SUBMITTED_CRITERIA("//*[@id='searchContainer']/div[2]/div[1]/label[2]/span","xpath"),
	CLOSED_CRITERIA("//*[@id='searchContainer']/div[2]/div[1]/label[3]/span","xpath"),
	CANCELED_CRITERIA("//*[@id='searchContainer']/div[2]/div[2]/label[1]/span","xpath"),
	RECEIVED_CRITERIA("//*[@id='searchContainer']/div[2]/div[2]/label[2]/span","xpath"),
	APPROVED_CRITERIA("//*[@id='searchContainer']/div[2]/div[2]/label[3]/span","xpath"),
	SEARCH_EXISTING_ORDERS_ON_CREATE_ORDER_PAGE(".//*[@id='contentHeader']/div[2]/a","xpath"),
	BASE_ORDER_ON_PURCHASE_ORDER_PROPOSAL("//*[@id='poSourceForm']/div/label[1]/span","xpath"),
	BASE_ORDER_ON_PURCHASE_ORDER_PROPOSAL_Id("IsPoProposal","id"),
	CALCULATE_PROPOSAL_FROM("//*[@id='PoProposalFromDate']","xpath"),
	CALCULATE_PROPOSAL_TO("//*[@id='PoProposalToDate']","xpath"),
	CONSIDER_PRODUCTION_DEAD_LINE("//*[@id='poSourceForm']/div[1]/label/span","xpath"),
	CONSIDER_PRODUCTION_DEAD_LINE_ID("IsProductionDeadLine","id"),
	CONSIDER_NPT_REQUIREMENTS("//*[@id='poSourceForm']/div/label[3]/span","xpath"),
	CONSIDER_NPT_REQUIREMENTS_ID("IsConsiderNpt","id"),
	ONLY_NPT_REQUIREMENTS("//*[@id='poSourceForm']/div/label[4]/span","xpath"),
	ONLY_NPT_REQUIREMENTS_ID("IsNptOnly","xpath"),
	CANCEL_SELECTED("//*[@id='gridWrapper']/div[1]/div[1]/a","xpath"),
	MENU_ON_PO_DETAIS_PAGE("//*[@id='nav']/li[1]/div","xpath"),  
	SET_ALL_TO_ZERO("//*[@id='resetQty']/a","xpath"),
	ORDER_STATUS_DESCRIPTION("//*[@id='OrderStatusDescp']","xpath"),
	ORDER_NUMBER_VALUE("//*[@id='OrderNumber']","xpath"),
	ARTICLE_NUMBER_HEADING("//*[@id='slickgrid_613735anumber']","xpath"),
	DESCRIPTION_HEADING("//*[@id='slickgrid_613735desc']","xpath"),
	VENDOR_ARTICLE_NUMBER_HEADING("//*[@id='slickgrid_613735vanumber']","xpath"),
	UOM_HEADING("//*[@id='slickgrid_613735uom']","xpath"),
	PURC_UNIT_DAY_PRICE_HEADING("//*[@id='slickgrid_613735dppur']","xpath"),
	ORDER_QTY_HEADING("//*[@id='slickgrid_613735oqty']","xpath"),
	TOTAL_AMT_HEADING("//*[@id='slickgrid_613735tlamt']","xpath"),
	STOCK_LEVEL_HEADING("//*[@id='slickgrid_613735slevel']","xpath"),
	MIN_STOCK_LEVEL_HEADING("//*[@id='slickgrid_613735mslevel']","xpath"),
	SURPLUS_DAYS_HEADING("//*[@id='slickgrid_613735sdays']","xpath"),
	ARTICLE_REBATE_HEADING("//*[@id='slickgrid_613735arebate']","xpath"),
	VENDOR_REBATE_HEADING("//*[@id='slickgrid_613735vrebate']","xpath"),
	SAVE_ORDER_FORM_CONTAINER_POPUP("//*[@id='saveOrderFormContainer']","xpath"),
	SAVE_ORDER_FORM_BUTTON_ON_POPUP("//*[@id='saveOrderForm']","xpath"),
	CANCEL_ORDER_FORM_BUTTON_ON_POPUP("//*[@id='cancelOrderForm']","xpath"),
	ORDER_QTY_FIRST_COLUMN_INPUT("//*[@id='myGrid']/div[7]/div/div/div[1]/div[4]/input","xpath"),
	ORDER_QTY_FIRST_COLUMN("//*[@id='myGrid']/div[7]/div/div/div[1]/div[4]","xpath"),
	TOTAL_AMT(".//*[@id='TotalAmount']","xpath"),
	DAY_PRICE_FIRST_COLUMN("//*[@id='myGrid']/div[7]/div/div/div[1]/div[3]","xpath"),
	VENDOR_REBATE_FIRST_COLUMN("//*[@id='myGrid']/div[7]/div/div/div[1]/div[10]","xpath"),
	ARTICLE_REBATE_FIRST_COLUMN("//*[@id='myGrid']/div[7]/div/div/div[1]/div[9]","xpath"),
	VENDOR_REBATE_FIRST_COLUMN2("//*[@id='myGrid']/div[7]/div/div/div[1]/div[11]","xpath"),
	ARTICLE_REBATE_FIRST_COLUMN2("//*[@id='myGrid']/div[7]/div/div/div[1]/div[10]","xpath"),
	ORDER_FORM_NAME_ON_POPUP("//*[@id='orderFormName']","xpath"),
	ORDER_FORM_REPLACE_POPUP("//*[@id='removeAlert']","xpath"),
	CONTINUE_ON_ORDER_FORM_REPLACE(".//*[@id='removeAlert']/div[3]/a[1]","xpath"),
	ADD_ARTICLE_GRID("//*[@id='addArticlesWrapper']","xpath"),
	DESCRIPTION_OF_FIRST_ARTICLE("//*[@id='myGrid']/div[5]/div/div[1]/div[2]","xpath"),
	ARTICLE_NUMBER_CHECK_BOX("//*[@id='addArticles']/table/tbody/tr[1]/td[1]/div/label/span","xpath"),
	ADD_SELECTED("//*[@id='addArticlesWrapper']/div[1]/div[2]/a","xpath"),
	DESCRIPTION_CHANGED_XPATH("//*[@id='myGrid']/div[5]/div/div[1]/div[2]","xpath"),
	DELETE_PO("//*[@id='removePoLink']","xpath"),
	REMOVE_CONFIRMATION_POP_UP("//*[@id='removeAlert']","xpath"),
	CONTINUE_ON_REMOVE_PO_POPUP("Continue","linkText"),
	   	
	CANCEL_ON_REMOVE_PO_POPUP("//*[@id='removeAlert']/div[3]/a[2]","xpath"),
	NOTES("//*[@id='AdditionalInfo']","xpath"),
	DELIVERY_DATE("//*[@id='ExpectedDeliveryDate']","xpath"),
	DELIVERY_TIME("//*[@id='ExpectedDeliveryTime']","xpath"),
	DELIVERITIME("//*[@id='ExpectedDeliveryFromTime']", "xpath"),
	TIME_ICON("//span[@class='k-icon k-i-clock']","xpath"),
	TIME_DROPWOWN("//*[@id='ExpectedDeliveryTime_timeview']","xpath"),
	CANCEL_ON_VENDOR_INCIDENT_POPUP("//*[@id='noRecVendInfo']","xpath"),
	YES_ON_VENDOR_INCIDENT_POPUP("//*[@id='openRecVendInfo']","xpath"),
	VENDOR_INCIDENT_POPUP("//*[@id='recordVendorIncident']","xpath"),
	VENDOR_INCIDENT_DETAILS_POPUP(".//*[@id='recordVendorInfo']","xpath"),
	CANCEL_ON_INCIDENT_DETAILS_POPUP("//*[@id='vinfoClose']","xpath"),
	ADD_INCIDENT_ON_INCIDENT_DETAILS_POPUP(".//*[@id='action-addIncident']","xpath"),
	INCIDENT_TYPE("//*[@id='IncidentType']","xpath"),
	DESCRIPTION("//*[@id='Description']","xpath"),
	VENDOR_INCIDENT_PAGE_DROPDOWN("html/body/ul[1]","xpath"),
	VENDOR_INCIDENT_PAGE_DROPDOWN2("html/body/ul[2]","xpath"),
	RELATED_TO_CUSTOMER("//*[@id='CustomerCode']","xpath"),
	VIEW_LINK("//*[@id='viewLink']","xpath"),
	VIEW_POPUP("//*[@id='vendorIncidents']","xpath"),
	CANCEL_ON_VIEW_POPUP("//*[@id='vendorIncidents']/div[2]/a","xpath"),
	VIEW_INCIDENT_LINK(".//*[@id='viewIncidentDetail']","xpath"),
	VENDOR_INCIDENT_INFO_POPUP("//*[@id='incidentView']","xpath"),
	CANCEL_ON_VENDORINCIDENT_INFO_POPUP("//*[@id='viewInfoClose']","xpath"),
	ORDER_NUMBER_HEADING_ON_SEARCH_ALL_PAGE("//*[@id='results']/table/thead/tr/th[3]","xpath"),
	VENDOR_NAME_HEADING_ON_SEARCH_ALL_PAGE("//*[@id='results']/table/thead/tr/th[4]","xpath"),
	ORDER_DATE_HEADING_ON_SEARCH_ALL_PAGE("//*[@id='results']/table/thead/tr/th[5]","xpath"),
	ITEMS_HEADING_ON_SEARCH_ALL_PAGE("//*[@id='results']/table/thead/tr/th[7]","xpath"),
	STATUS_HEADING_ON_SEARCH_ALL_PAGE("//*[@id='results']/table/thead/tr/th[8]","xpath"),
	
	ORDERNUMBER_CRITERIA_ON_SEARCH_ALL_PAGE("//*[@id='searchContainer']/div[2]/div[1]/label[1]/span","xpath"),
	PENDING_CRITERIA_ON_EXPECTEDDELIVERYDATE("//*[@id='searchContainer']/div[2]/div[1]/label[2]/span","xpath"),
	PENDING_CRITERIA_ON_SEARCH_ALL_PAGE("//*[@id='searchContainer']/div[2]/div[1]/label[3]/span","xpath"),
	SUBMITTED_CRITERIA_ON_SEARCH_ALL_PAGE("//*[@id='searchContainer']/div[2]/div[1]/label[4]/span","xpath"),
	CLOSED_CRITERIA_ON_SEARCH_ALL_PAGE("//*[@id='searchContainer']/div[2]/div[1]/label[4]/span","xpath"),
	RESEND_CRITERIA_ON_SEARCH_ALL_PAGE("//*[@id='searchContainer']/div[2]/div[1]/label[6]/span","xpath"),
	VENDORNAME_CRITERIA_ON_SEARCH_ALL_PAGE("//*[@id='searchContainer']/div[2]/div[2]/label[1]/span","xpath"),
	CANCELLED_CRITERIA_ON_SEARCH_ALL_PAGE("//*[@id='searchContainer']/div[2]/div[2]/label[2]/span","xpath"),
	INTRANSIT_CRITERIA_ON_SEARCH_ALL_PAGE("//*[@id='searchContainer']/div[2]/div[2]/label[5]/span","xpath"),
	RECEIVED_CRITERIA_ON_SEARCH_ALL_PAGE("//*[@id='searchContainer']/div[2]/div[2]/label[3]/span","xpath"),
	APPROVED_CRITERIA_ON_SEARCH_ALL_PAGE("//*[@id='searchContainer']/div[2]/div[2]/label[4]/span","xpath"),
	ORDER_DATE_FIRST_ROW("//*[@id='results']/table/tbody/tr[1]/td[5]","xpath"),
	ORDER_NUMBER_FIRST_ROW("//*[@id='results']/table/tbody/tr[1]/td[3]","xpath"),
	SEARCH_ENTERIES_INVERTER_SYMBOL("//*[@id='gridWrapper']/div[1]/div[3]/span/span[1]/span[2]","xpath"),
	SEARCH_RESULT_GRID_SELECT_ITEMS_PER_PAGE_LIST_CLASS("k-item" ,"className"),
	ROW_COUNT_XPATH("//*[@class='k-selectable']/tbody/tr/td[2]","xpath"),
	FIRST_CHECK_BOX("//*[@id='results']/table/tbody/tr[1]/td[1]/div/div[1]/label/span","xpath"),
	SECOND_CHECK_BOX("//*[@id='results']/table/tbody/tr[2]/td[1]/div/div[1]/label/span","xpath"),
	DO_NOT_CANCEL_ON_CANCEL_PO_POPUP("//*[@id='batchcancelClose']","xpath"),
	CONTINUE_ON_CANCEL_PO_POPUP("//*[@id='cancelOk']","xpath"),
	CANCEL_PO_POPUP("//*[@id='batchCancel']","xpath"),
	REASON_POPUP("//*[@id='cancelReasonContainer']","xpath"),
	DO_NOT_CANCEL_ON_REASON_POPUP("//*[@id='closeReason']","xpath"),
	CONTINUE_ON_REASON_POPUP("//*[@id='cancelPo']","xpath"),
	VIEW_ORDER_INFO("//*[@id='poViewOrderContainer']/a","xpath"),
	VIEW_ORDER_INFO_POPUP("//*[@id='poSubmitDetails']/div[1]/div[2]","xpath"),
	OK_ON_VIEW_ORDER_INFO_POPUP("//*[@id='poConfirmInfo']/div/a[2]","xpath"),
	RESULT_GRID_FIRST_COLUMN(".//*[@id='results']/table/tbody/tr[1]/td[1] ","xpath"),
	SEARCHVENDOR_LINK("//*[@id='searchExistingVendor']/div/div", "xpath"),
	SEARCH_ORDER("//*[@id='results']/table/tbody/tr/td[3]", "xpath"),
	ORDER_QTY1_CLICK("//*[@id='myGrid']/div[7]/div/div/div[1]/div[4]", "xpath"),
	ORDER_QTY1_INPUT("//*[@id='myGrid']/div[7]/div/div/div[1]/div[4]/input", "xpath"),
	ORDER_QTY2_CLICK("//*[@id='myGrid']/div[7]/div/div/div[2]/div[4]", "xpath"),
	ORDERQTY2_INPUT("//*[@id='myGrid']/div[7]/div/div/div[2]/div[4]/input", "xpath"),
	CREATE_MULTIPLE_ORDERS_BTN("//*[@id='oRegistrationWrapper']/a[3]/div/div", "xpath"),
	PURCHASE_ORDER_PROPOSAL("//*[@id='reportStatistics']/li[2]/a", "xpath"),
	MULTIPLEPO_OKBTN("//*[@id='setSelectedListButton']", "xpath"),
	ORDERNO_FIRSTROW("//*[@id='results']/table/tbody/tr[1]/td[1]/span", "xpath"),
	RESULTGRID_ORDERCOLUMN("//*[@id='results']/table/tbody/tr[1]/td[3]/span", "xpath"),
	VENDORGRID_ORDERCOLUMN("//*[@id='results']/table/tbody/tr/td[1]/span", "xpath"),
	SEARCH_EXISTINGORDER("//*[@id='contentHeader']/div[3]/a", "xpath"),
	CANCEL_SEARCHEDROW("//*[@id='results']/table/tbody/tr/td[1]/div/div[2]/a", "xpath"),
	ORDER_STATUS("//*[@id='results']/table/tbody/tr/td[8]/div", "xpath"),
	ORDER_SAVEICON("//*[@id='nav']/li[3]/a", "xpath"),
	SAVECHANGES_CONTINUEBTN("//*[@id='confirmChangesAlert']/div[2]/a[1]", "xpath")
	;
	
	public String element, identifier;
	private PurchaseOrderRegistrationEnums(String element){
		 this.element = element;
	 }
	private PurchaseOrderRegistrationEnums(String element, String identifier){
		 this.element = element;
		 this.identifier = identifier;
	 }
	public String getElementPath(){
		return element;
	}
	public String getElementIdentifier(){
		return identifier;
	}

}
