package com.sacs.PageOjects;

public enum PurchaseOrderReceiptEnums {
	
	ORDER_RECEIPT_TITLE(".//*[@id='contentHeader']/div/h1", "xpath"),
	SEARCH_FIELD(".//*[@id='articlesearch']", "xpath"),
	SEARCH_SUBMIT("searchSubmit", "className"),
	GRID_VENDOR_NAME_FIRST_COLUMN_VALUE(".//*[@id='results']/table/tbody/tr[1]/td[2]", "xpath"),
	TOAST_MESSAGE("toast-message", "className"),
	TOAST_CLOSE_BTN("//button[@class='toast-close-button']", "xpath"),
	SEARCH_LABEL("//*[@id='searchContainer']/label","xpath"),
	
	STORES_LINK(".//*[@id='stores']", "xpath"),
	ORDER_RECEIPT_LINK(".//*[@id='orderreceipt']/a", "xpath"),
	SEARCH_FOR_ORDER_BY_VENDOR_LINK(".//*[@id='searchExistingVendor']", "xpath"),
	SEARCH_FOR_ALL_EXISTING_ORDERS_LINK(".//*[@id='searchExistingOrder']", "xpath"),
	RECEIVE_WITHOUT_PO_BTN(".//*[@id='contentHeader']/div[2]/a", "xpath"),
	RECEIPT_OK_BTN(".//*[@id='receiptbtnContainer']/a", "xpath"),
	DELIVERY_NOTE_NUMBER(".//*[@id='DeliveryNoteNumber']", "xpath"),
	
	STORE_CODE_LINK(".//*[@id='storecode']/a", "xpath"),
	SUB_STORE_CODE_LINK(".//*[@id='subNav-system']/li[15]/a", "xpath"),
	STORE_CODE_TITLE(".//*[@id='contentHeader']/div[1]/h1", "xpath"),
	ADD_MAINSTORE_CODE_BTN(".//*[@id='contentHeader']/div[2]/a", "xpath"),
	ADD_MAINSTORE_CODE_TITLE(".//*[@id='contentHeader']/div[1]/h1", "xpath"),
	MAIN_STORECODE_ID(".//*[@id='Code']", "xpath"),
	STORE_DESCRIPTION(".//*[@id='Description']", "xpath"),
	CLOSING_DAY(".//*[@id='ClosingDay']", "xpath"),
	OPEN_DATE(".//*[@id='OpenDate']", "xpath"),
	APPLY_CHANGES(".//*[@id='applyMainStoreCode']", "xpath"),
	
	SYSTEM_LINK(".//*[@id='system']", "xpath"),
	
	ADD_SUBSTORE_CODE_BTN(".//*[@id='contentHeader']/div[2]/a", "xpath"),
	SUBSTORE_CODE(".//*[@id='Code']", "xpath"),
	MAIN_STORECODE_DROPDOWN("//*[@id='MainStoreCode']", "xpath"),
	MAIN_STORECODE_DROPDOWN_ID("MainStoreCode", "id"),
	APPLY_CHANGES_SUBSTORE_CODE(".//*[@id='saveContainer']/a", "xpath"),
	ADD_SUBSTORE_CODE_TITLE(".//*[@id='contentHeader']/div[1]/h1", "xpath"),
	GRID_VENDOR_ID_COLUMN_VALUE_XPATH(".//*[@id='results']/table/tbody/tr[1]/td[1]", "xpath"),
	GRID_ORDER_NO_COLUMN_VALUE_XPATH(".//*[@id='results']/table/tbody/tr/td[1]", "xpath"),
	VENDOR_NAME(".//*[@id='vendorTitle']/span", "xpath"),
	CORRECT_ORDER_RECEIPT_TITLE(".//*[@id='title']", "xpath"),
	TITLE(".//*[@id='title']", "xpath"),
	GRID_STORE_QTY_RECEIVED(".//*[@id='myGrid']/div[5]/div/div/div[5]", "xpath"),
	GRID_STORE_QTY_RECEIVED_INPUT(".//*[@id='myGrid']/div[5]/div/div/div[5]/input", "xpath"),
	CORRECT_ORDER_BTN(".//*[@id='correctOrder']", "xpath"),
	SUBMIT_RECEIPT_BTN(".//*[@id='submitOrder']", "xpath"),
	QUANTITY_RECEIVED(".//*[@id='myGrid']/div[5]/div/div/div[6]", "xpath"),
	QUANTITY_RECEIVED_INPUT("//*[@id='myGrid']/div[5]/div/div/div[6]/input","xpath"),
	EXPIRY_DATE(".//*[@id='myGrid']/div[7]/div/div/div/div[6]", "xpath"),
	EXPIRY_DATE_INPUT(".//*[@id='myGrid']/div[7]/div/div/div/div[6]/span/span/input", "xpath"),
	//SUBMIT_ORDER_RECEIPT_POPUP_TITLE(".//*[@id='titleInfo']", "xpath"),
//	SUBMIT_ORDER_RECEIPT_POPUP_TITLE(".//*[@id='detailsTitle']", "xpath"),
	SUBMIT_ORDER_RECEIPT_POPUP_TITLE(".//*[@id='poReceiptDetails_wnd_title']", "xpath"),
	SUBMIT_ORDER_RECEIPT_POPUP_CONTINUE_BTN(".//*[@id='submitOrderContainer']/a[2]", "xpath"),
	ORDER_RECEIPT_CONFIRMATION_POPUP_TITLE(".//*[@id='titleInfo']", "xpath"),
	ORDER_RECEIPT_CONFIRMATION_POPUP_OK_BTN(".//*[@id='poConfirmInfo']/div/a[2]", "xpath"),
	YES_ON_VENDOR_INCIDENT_POPUP("//*[@id='openRecVendInfo']","xpath"),
	BACK_TO_SEARCH_BTN(".//*[@id='contentHeader']/div[3]/a", "xpath"),
	DESCRIPTION_CHECKBOX(".//*[@id='searchContainer']/div[3]/div[1]/label[1]/span","xpath"),
	MAIN_STORE_CHECBOX(".//*[@id='searchContainer']/div[3]/div[1]/label[2]/span","xpath"),
	SEARCH_CRITERIA("//*[@id='searchContainer']/div[2]/span[3]/a/img","xpath"),
	SEARCH_BUTTON(".//*[@id='searchContainer']/div[2]/span[2]/a/img","xpath"),
	SEARCH_RESULT(".//*[@id='results']/table/tbody/tr/td[2]","xpath"),
	ROW_TO_UPADTE("//*[@id='results']/table/tbody/tr[4]/td[2]","xpath"),
	ROW_TO_UPDATE("//*[@id='results']/table/tbody/tr[3]/td[2]","xpath"),
	ROW_TO_UPADTE2("//*[@id='results']/table/tbody/tr[5]/td[2]","xpath"),
	ROW_TO_UPDATE_DESC("//*[@id='results']/table/tbody/tr[4]/td[1]","xpath"),
	ROW_TO_UPDATE_DESC3("//*[@id='results']/table/tbody/tr[3]/td[1]","xpath"),
	ROW_TO_UPDATE_DESC2("//*[@id='results']/table/tbody/tr[5]/td[1]","xpath"),
	SEARCH_RESULT_GRID_NEXT_LINK_XPATH("//*[@id='gridWrapper']/div[3]/div/a[3]/span","xpath"), 
	SEARCH_RESULT_GRID_PREVIOUS_LINK_XPATH("//*[@id='gridWrapper']/div[3]/div/a[2]/span","xpath"), 
	SEARCH_RESULT_GRID_LAST_LINK_XPATH("//*[@id='gridWrapper']/div[3]/div/a[4]/span","xpath"), 
	SEARCH_RESULT_GRID_FIRST_LINK_XPATH("//*[@id='gridWrapper']/div[3]/div/a[1]/span","xpath"),
	INVERTED_SYMBOL("//*[@id='searchContainer']/div[1]/span[3]/a/img","xpath"),
	VENDOR_NAME_SEARCH_CRITERIA("//*[@id='searchContainer']/div[2]/div[1]/label[2]/span","xpath"),
	CANCEL_ON_VENDOR_INCIDENT_POPUP("//*[@id='noRecVendInfo']","xpath"),
	CLOSE_ON_ORDER_RECEIPT_SUBMITTED_POPUP("//*[@id='closeOrder']","xpath"), 
	CLOSE_PARTIAL("//*[@id='closePartial']","xpath"),
	BACK_BTN_ON_ORDER_SEARCH_PAGE("//*[@id='contentHeader']/div[2]/a","xpath"),
	SEARCH_ENTERIES_INVERTER_SYMBOL("k-select","className"),
	SEARCH_RESULT_GRID_SELECT_ITEMS_PER_PAGE_LIST_CLASS("k-item"),
	SEARCH_RESULT_GRID_COLUMN_CLASS("articlenumber"),
	VENDOR_ID_SEARCH_CRITERIA("//*[@id='searchContainer']/div[2]/div/div/label[1]/span","xpath"),
	VENDOR_NAME_SEARCH_CRITERIA_ON_VENDOR_PAGE("//*[@id='searchContainer']/div[2]/div/div/label[2]/span","xpath"), 
	CHANGE_VENDOR("//*[@id='contentBody']/section/div[3]/a","xpath"),
	ORDER_NUMBER("//*[@id='OrderNumber']","xpath"),
	STOCK_DATE("//*[@id='StockDate']","xpath"),
	ORDER_DATE("//*[@id='OrderDate']","xpath"),
	POP_UP("//*[@id='removeAlert']","xpath"),
	POP_UP_TEXT("//*[@id='removeAlert']/div[2]","xpath"),
	CANCEL_ON_STOCK_DATE_POPUP("//*[@id='removeAlert']/div[3]/a[2]","xpath"),
	CONTINUE_ON_STOCK_DATE_POPUP("//*[@id='removeAlert']/div[3]/a[1]","xpath"),
	CUSTOMER_REFERENCE_NUMBER("//*[@id='CustomsRefNumber']","xpath"),
	ADD_ARTICLE("//*[@id='gridWrapper']/div[5]/a","xpath"),
	ADD_ARTICLE_SEARCH("//*[@id='add']","xpath"),
	ADD_ARTICLE_CHECK_BOX("//*[@id='addArticles']/table/tbody/tr/td[1]/label/span","xpath"),
	ADD_ARTICLE_CHECK_BOX2("//*[@id='addArticles']/table/tbody/tr/td[1]/div/label/span", "xpath"),
	ADD_SELECTED("//*[@id='addArticlesWrapper']/div[1]/div[2]/a","xpath"),
	ADD_ARTICLE_ARTICLE_NAME("//*[@id='addArticles']/table/tbody/tr/td[3]/span","xpath"),
	SELECTED_ARTICLE_NAME("//*[@id='myGrid']/div[5]/div/div/div[3]","xpath"),
	SELECTED_ARTICLE_NAME2("//*[@id='myGrid']/div[7]/div/div/div/div[1]", "xpath"),
	CLOSE_BUTTON("//*[@id='addArticlesWrapper']/div[1]/div[3]/a","xpath"),
	CANCEL_ON_SUBMIT_ORDER_RECEIPT_POPUP(".//*[@id='submitOrderContainer']/a[1]","xpath"),
	RECORD_VENDOR_INCIDENT_POPUP("//*[@id='showRecordVendorInc']","xpath"),
	INCIDENT_TYPE("//*[@id='IncidentType']","xpath"),
	DESCRIPTION("//*[@id='Description']","xpath"),
	INCIDENT_TYPE_MENUITEM("//*[@id='ui-active-menuitem']","xpath"),
	ADD_INCIDENT_BUTTON("//*[@id='action-addIncident']","xpath"),
	STATUS_COLUMN("//*[@id='results']/table/tbody/tr/td[7]","xpath"),
	INCIDENT_TYPE_DROPDOWN("html/body/ul[1]","xpath"),
	CREATE_ORDER("//*[@id='createOrder']","xpath"),
	CHECKBOX_ON_CREATE_NEW_ORDER_POPUP("//*[@id='resultsPartial']/div[5]/div/div/div[1]/label/span","xpath"),
	SAVE_PARTIAL_ORDER_CONTINUE_BTN("//*[@id='savePartialOrder']","xpath"),
	VIEW_LINKED_ORDER("//*[@id='poDetailList']/div[5]/a[1]","xpath"),
	VIEW_LINKED_ORDER_POPUP("//*[@id='viewLinkedOrders']","xpath"),
	CANCEL_ON_VIEW_LINKED_ORDER_POPUP("//*[@id='submitOrderContainer']/a","xpath"),
	CANCEL_ORDER("//*[@id='removePoLink']/div","xpath"),
	CANCEL_REASON_CONTINUE("//*[@id='cancelPo']","xpath"),
	APPLY_CHANGES_ICON(".//*[@id='nav']/li[3]/a/div","xpath"),
	CANCEL_BTN_ON_PO_DETAILS_PAGE("//*[@id='poDetailList']/div[5]/a[2]","xpath"),
	ORDER_QTY(".//*[@id='myGrid']/div[6]/div/div/div/div[5]", "xpath"),
	ORDER_QTY_INPUT(".//*[@id='myGrid']/div[6]/div/div/div/div[5]/input", "xpath"),
	NEW_STOCK_DATE("//*[@id='newPoStockDate']","xpath"),
	NOTES("//*[@id='AdditionalInfo']","xpath"),
	EXPECTED_DELIVERY_DATE("//*[@id='ExpectedDeliveryDate']","xpath"),
	CANCEL_BTN_ON_WITHOUT_PO_PAGE("//*[@id='orderRegInfoSubmitted']/div/a[1]","xpath"),
	EXPIRY_DATE_ON_WITHOUT_PO(".//*[@id='myGrid']/div[5]/div/div/div[8]", "xpath"),
	EXPIRY_DATE_INPUT_ON_WITHOUT_PO(".//*[@id='myGrid']/div[5]/div/div/div[8]/span/span/input", "xpath"),
	SUBMIT_ORDER_POPUP_TITLE(".//*[@id='poSubmitDetails']/div/div[2]", "xpath"),		
	CLOSE_ON_SUBMIT_PO_POPUP("//*[@id='divClose']/a","xpath"),
	MENU("//*[@id='nav']/li[1]/div","xpath"),
	REFRESH_DAY_PRICE("//*[@id='nav']/li[1]/ul/li[4]/a","xpath"),
	REFRESH_POPUP("//*[@id='refreshAlert']","xpath"),
	CONTINUE_ON_REFRESH_POPUP("//*[@id='refreshAlert']/div[3]/a[1]","xpath"),
	CANCEL_ON_REFRESH_POPUP("//*[@id='refreshAlert']/div[3]/a[2]","xpath"),
	ORDER_RECEIPT("//*[@id='nav']/li[1]/ul/li[1]/a","xpath"),
	ORDER_RECEIPT_CORRECTION("//*[@id='nav']/li[1]/ul/li[2]/a","xpath"),
	PRINT_BATCH_CONTROL_FORMS("//*[@id='nav']/li[1]/ul/li[3]/a","xpath"),
	ORDER_RECEIPT_HISTORY("//*[@id='nav']/li[1]/ul/li[5]/a","xpath"),
	DELETE_SUB_STORE("//*[@id='removeArticleGrp']/a","xpath"),
	DELETE_SUB_STORE_POPUP("//*[@id='removeSCAlert']","xpath"),
	CONTINUE_ON_SUB_STORE_POPUP("//*[@id='removeSCAlert']/div[3]/a[1]","xpath"),
	LOTEXPIRYDATE("//*[@id='myGrid']/div[7]/div/div/div/div[5]/span/a", "xpath"),
	LOTEXPIRYDATE2("//*[@id='myGrid']/div[6]/div/div/div/div[6]/span/a", "xpath"),
	QTYREC_CLICK("//*[@id='PoLotResults']/div[6]/div/div/div/div[2]", "xpath"),
	QTYREC_INPUT("//*[@id='PoLotResults']/div[6]/div/div/div/div[2]/input", "xpath"),
	LOTNO_CLICK("//*[@id='PoLotResults']/div[6]/div/div/div/div[3]", "xpath"),
	LOTNO_INPUT("//*[@id='PoLotResults']/div[6]/div/div/div/div[3]/input", "xpath"),
	EXPDATE_CLICK("//*[@id='PoLotResults']/div[6]/div/div/div[2]/div[4]", "xpath"),
	EXPDATE_INPUT("//*[@id='PoLotResults']/div[6]/div/div/div[2]/div[4]/span/span/input", "xpath"),
	CONTINUELOTPOPUP("//*[@id='continuepoLotPopup']", "xpath"),
	STOREQTYREC("//*[@id='myGrid']/div[7]/div/div/div/div[3]", "xpath"),
	CONFIRMORDERRECEIPT_CONTINUE("//*[@id='correctAlert']/div[3]/a[1]", "xpath"),
	STORES("//*[@id='stores']/p", "xpath"),
	ORDERRECEIPT("//*[@id='orderreceipt']/a", "xpath"),
	SEARCH_VENDORS("//*[@id='searchExistingVendor']/li/div", "xpath"),
    ORDERQTY_CLICK("//*[@id='myGrid']/div[6]/div/div/div/div[5]", "xpath"),
    ORDERQTY_INPUT("//*[@id='myGrid']/div[6]/div/div/div/div[5]/input", "xpath"),
    BLANKCLICK("//*[@id='myGrid']/div[6]/div/div/div/div[7]", "xpath"),
    LOTEXPIRYICON("//*[@id='myGrid']/div[6]/div/div/div/div[6]/span/a", "xpath"),
    PURQTYREC_CLICK("//*[@id='PoLotResults']/div[6]/div/div/div[1]/div[2]", "xpath"),
    PURQTYREC_INPUT("//*[@id='PoLotResults']/div[6]/div/div/div[1]/div[2]/input", "xpath"),
    LOTNO_CLICK2("//*[@id='PoLotResults']/div[6]/div/div/div[1]/div[3]", "xpath"),
    LOTNO_INPUT2("//*[@id='PoLotResults']/div[6]/div/div/div[2]/div[3]/input", "xpath"),
    EXPIRYDATE_CLICK2("//*[@id='PoLotResults']/div[6]/div/div/div[2]/div[4]", "xpath"),
    EXPIRYDATE_INPUT2("//*[@id='PoLotResults']/div[6]/div/div/div[2]/div[4]/span/span/input", "xpath"),
    APPLYCHANGES_CONTINUE("//*[@id='confirmChangesAlert']/div[2]/a[1]", "xpath"),
    SAVEICON("//*[@id='saveSubstoreCode']/a", "xpath"),
    POARTICLE_CANCELBTN("//*[@id='PoLabelArticleReportClose']", "xpath"),
    PUR_ORDQTY1("//*[@id='myGrid']/div[7]/div/div/div[1]/div[3]", "xpath"),
    PUR_ORDQTY2("//*[@id='myGrid']/div[7]/div/div/div[2]/div[3]", "xpath"),
    LOT_EXPIRYDATE1("//*[@id='myGrid']/div[7]/div/div/div[1]/div[5]/span/a", "xpath"),
    LOT_EXPIRYDATE2("//*[@id='myGrid']/div[7]/div/div/div[2]/div[5]/span/a", "xpath"),
    POLABEL_OKBTN("//*[@id='PoLabelArticleReportOK']", "xpath"),
    ORDER_NO("//*[@id='contentBody']/section/div[3]/div[1]/span[2]", "xpath"),
    ARTNUM_FIRSTROW("//*[@id='myGrid']/div[6]/div/div/div/div[2]/span[1]", "xpath"),
    PO_POPUP_CANCELBTN("//*[@id='cancelPoLotPopup']", "xpath"),
    LOT_POPUP_REMOVEICON("//*[@id='PoLotResults']/div[6]/div/div/div[1]/div[5]/span/a", "xpath"),
    SEARCHORDER_STATUS("//*[@id='results']/table/tbody/tr[1]/td[7]", "xpath"),
    PUR_QTY_RCD_CLICK("//*[@id='myGrid']/div[7]/div/div/div/div[4]", "xpath"),
    PUR_QTY_RCD_INPUT("//*[@id='myGrid']/div[7]/div/div/div/div[4]/input", "xpath"),
    CREATEORDER_POPUP_ARTCHKBOX("//*[@id='checkSelBox00']", "xpath"),
    ORDER_SEARCH_FIRSTROW("//*[@id='results']/table/tbody/tr/td[1]/span[1]", "xpath"),
    VIEW_LINK_ORDER("//*[@id='poDetailList']/div[5]/a[1]/u/span", "xpath"),
    VIEW_LINK_TITLE("//*[@id='viewLinkedOrders_wnd_title']", "xpath"),
    VIEW_LINK_POPUP_CANCEL("//*[@id='submitOrderContainer']/a", "xpath"),
    NODATATODISPLAY("//*[@id='results']/table/tbody/tr/td", "xpath"),
    STOREQTYRECVD2("//*[@id='myGrid']/div[6]/div/div/div/div[4]", "xpath"),
    ADD_ARTICLESEARCH("//*[@id='addArticlesearch']", "xpath"),
    						
;
	
	public String element, identifier;
	private PurchaseOrderReceiptEnums(String element){
		 this.element = element;
	 }
	private PurchaseOrderReceiptEnums(String element, String identifier){
		 this.element = element;
		 this.identifier = identifier;
	 }
	public String getElementPath(){
		return element;
	}
	public String getElementIdentifier(){
		return identifier;
	}

}
