package com.sacs.PageOjects;

public enum PurchaseVendorPriceAgreementEnums {
	
	PURCHASE("purchase","id"),
	VENDOR_PRICE_AGREEMENT_LINK(".//*[@id='vendorpriceagreement']/a", "xpath"),
	VENDOR_PRICE_AGREEMENT_TITLE(".//*[@id='contentHeader']/div[1]/h1", "xpath"),
	ADD_AGREEMENT_BTN(".//*[@id='contentHeader']/div[2]/a", "xpath"),
	BACK_BUTTON(".//*[@id='contentHeader']/div[2]/a","xpath"),
	SEARCH_LABLE(".//*[@id='searchContainer']/label[2]","xpath"),
	SEARCH_LABLE_AGREEMENT_PAGE(".//*[@id='searchContainer']/label","xpath"),
	INVOICE_PRICE_QUERY("//*[@id='contentHeader']/div[3]/a","xpath"),
	SEARCH_FIELD(".//*[@id='articlesearch']", "xpath"),
	SEARCH_SUBMIT("searchSubmit", "className"),
	SEARCH_RESULT(".//*[@id='results']/table/tbody/tr/td[1]","xpath"),
	GRID_VENDOR_NAME_FIRST_ROW11(".//*[@id='results']/table/tbody/tr[1]/td[1]","xpath"),
	GRID_VENDOR_NAME_FIRST_ROW(".//*[@id='results']/table/tbody/tr[2]/td[2]", "xpath"),
	GRID_VENDOR_NAME_FIRST_ROW1(".//*[@id='results']/table/tbody/tr[2]/td[1]","xpath"),
	VENDOR_NAME_HEADING(".//*[@id='vpaheaderContainer']/div[1]", "xpath"),
	DESCRIPTION(".//*[@id='Description']", "xpath"),
	START_DATE(".//*[@id='StartDate']", "xpath"),
	END_DATE(".//*[@id='EndDate']", "xpath"),
	OK_BTN(".//*[@id='btn-ok']", "xpath"),
	ADD_NEW_PRICE_AGREEMENT_DROPDOWN(".//*[@id='ReadArticles']", "xpath"),
	APPLY_CHANGES(".//*[@id='saveArt']/div", "xpath"),
	TOAST_MESSAGE("toast-message", "className"),
	PRICE_CLICK_XPATH("//*[@id='connectedArticlesResults']/div[6]/div/div/div/div[6]","xpath"),
	PRICE_XPATH(".//*[@id='connectedArticlesResults']/div[6]/div/div/div/div[6]/input","xpath"),
	AGREEMENT_CODE("//*[@id='vpaForm']/div[2]/span[4]","xpath"), 
	GRID_SECOND_COLUMN_AFTER_SEARCH("//*[@id='results']/table/tbody/tr/td[2]","xpath"),
	GRID_SECOND_COLUMN_BEFORE_SEARCH("//*[@id='results']/table/tbody/tr[1]/td[2]","xpath"),
	VENDOR_NAME_CHECKBOX(".//*[@id='searchContainer']/div[3]/div[1]/label[1]/span","xpath"),
	VENDOR_NUMBER_CHECKBOX(".//*[@id='searchContainer']/div[3]/div[1]/label[2]/span","xpath"),
	DESCRIPTION_CHECKBOX(".//*[@id='searchContainer']/div[3]/div[2]/label/span","xpath"),
	VENDOR_NAME_TABLEHEADING(".//*[@id='results']/table/thead/tr/th[1]/a","xpath"),
	VENDOR_NUMBER_HEADING(".//*[@id='results']/table/thead/tr/th[2]","xpath"),
	DESCRIPTION_HEADING(".//*[@id='results']/table/thead/tr/th[3]","xpath"),
	STARTDATE_HEADING(".//*[@id='results']/table/thead/tr/th[4]","xpath"),
	ENDDATE_HEADING(".//*[@id='results']/table/thead/tr/th[5]","xpath"),
	NO_DATA_TO_DISPLAY(".//*[@id='results']/table/tbody/tr/td","xpath"),
	FIRST_ROW_SECOND_COL(".//*[@id='results']/table/tbody/tr[1]/td[2]","xpath"),
	FIRST_ROW_THIRD_COL(".//*[@id='results']/table/tbody/tr[1]/td[3]","xpath"),
	VENDOR_NUMBERCHECKBOX(".//*[@id='searchContainer']/div[2]/div[1]/label/span","xpath"),
	VENDOR_NAMECHECKBOX(".//*[@id='searchContainer']/div[2]/div[2]/label/span","xpath"),
	VENDORNAME(".//*[@id='vpaheaderContainer']/div[1]","xpath"),
	PURCHASE_UNIT(".//*[@id='PriceUnitList']","xpath"),
	CURRENCY_CODE(".//*[@id='CurrencyCode']","xpath"),
	CHANGE_VENDOR(".//*[@id='vpaheaderContainer']/div[2]/a","xpath"),
	ADD_NEW_PRICE_AGREEMENT(".//*[@id='formBody']/div[1]/label","xpath"),
	READONLY_DISCRIPTION(".//*[@id='vpaForm']/div[1]/span[2]","xpath"),
	READONLY_CURRENCY(".//*[@id='vpaForm']/div[3]/span[2]","xpath"),
	READONLY_VALIDPERIOD(".//*[@id='vpaForm']/div[1]/span[4]","xpath"),
	EDIT_BTN(".//*[@id='btn-restart']","xpath"),
	ADD_NEW_PRICE_DROPDOWN(".//*[@id='ReadArticles']","xpath"),
	EXISTING_AGREEMENT(".//*[@id='dropdown']/h2[2]","xpath"),
	PURCHASE_UNIT_VALUE(".//*[@id='vpaForm']/div[2]/span[2]","xpath"),
	//SELECTED_UNIT(".//*[@id='vpaForm']/div[3]/div/span[2]","xpath"),
	CONFIRMATION_POPUP_TEXT(".//*[@id='removeAlert']/div[1]","xpath"),
	CONFIRMATION_POPUP_CANCEL(".//*[@id='removeAlert']/div[3]/a[2]","xpath"),
	CONFIRMATION_POPUP_CONTINUE(".//*[@id='removeAlert']/div[3]/a[1]","xpath"),
	AGREEMENT_GRID(".//*[@id='nav']","xpath"),
	REMOVE_BUTTON(".//*[@id='toolsContainer']/div[1]/a","xpath"),
	ADD_BUTTON(".//*[@id='toolsContainer']/div[2]/a","xpath"),
	SEARCH_RESULT_CHECKBOX(".//*[@id='addArticles']/table/tbody/tr/td[1]/label/span","xpath"),
	EXPORT_BUTTON(".//*[@id='printAgreement']","xpath"),
	MENU_BUTTON(".//*[@id='nav']/li[1]/div","xpath"),
	SAVE_ICON("S","linkText"),
	APPLY_CHANGES_BUTTON("articleSave","className"),
	
	ARTICLE_HEADING(".//*[@id='slickgrid_370528articlenumber']","xpath"),
	DESCRIPTION__HEADING(".//*[@id='slickgrid_370528desc']","xpath"),
	UOM_HEADING(".//*[@id='slickgrid_370528uom']","xpath"),
	PRICE_HEADING(".//*[@id='slickgrid_370528price']","xpath"),
	START_HEADING(".//*[@id='slickgrid_370528startdate']","xpath"),
	END_HEADING(".//*[@id='slickgrid_370528enddate']","xpath"),
	PRICE_GRID_COL("//*[@id='connectedArticlesResults']/div[6]/div/div/div/div[6]","xpath"),
    PRICE_GRID_COL1(".//*[@id='connectedArticlesResults']/div[5]/div/div[2]/div[6]","xpath"),
	PRICE_GRID_COL_TEXTBOX1("//div[@id='connectedArticlesResults']//input[@class='editor-text']","xpath"),
	ARTICLE_NAME_GRID_COL(".//*[@id='connectedArticlesResults']/div[5]/div/div[2]/div[3]","xpath"),
	START_DATE_COL("//*[@id='connectedArticlesResults']/div[6]/div/div/div/div[7]","xpath"),
	END_DATE_COL("//*[@id='connectedArticlesResults']/div[6]/div/div/div/div[8]","xpath"),
	PRICE_GRID_COL_TEXTBOX("//div[@id='connectedArticlesResults']//input[@class='editor-text']","xpath"),
	START_DATE_COL_TEXTBOX("//*[@id='connectedArticlesResults']/div[6]/div/div/div/div[7]/span/span/input","xpath"),
	END_DATE_COL_TEXTBOX("//*[@id='connectedArticlesResults']/div[6]/div/div/div/div[8]/span/span/input","xpath"),
	ADD_ARTICLE_GROUP_GRID(".//*[@id='addArticles']/table/thead/tr/th[3]","xpath"),
	ADD_SELECTED(".//*[@id='addArticlesWrapper']/div[1]/div[2]/a","xpath"),
	ADD_ARTICLE_SEARCH(".//*[@id='addArticlesearch']","xpath"),
	ADD_SUBMITE("addSubmit","className"),
	ADD_ARTICLE_CLOSE(".//*[@id='addArticlesWrapper']/div[1]/div[3]/a","xpath"),
	ADD_NO_DATA_TO_DISPLAY(".//*[@id='addArticles']/table/tbody/tr/td","xpath"),
	SEARCH_ADD_FILTER("searchaddFilter","className"),
	ARTICLE_NUMBER_GRID(".//*[@id='addArticlesWrapper']/div[1]/div[1]/div[2]/div[1]/label[1]/span","xpath"),
	ARTICLE_NAME_GRID(".//*[@id='addArticlesWrapper']/div[1]/div[1]/div[2]/div[1]/label[2]/span","xpath"),
	ARTICLE_GROUP_GRID(".//*[@id='addArticlesWrapper']/div[1]/div[1]/div[2]/div[1]/label[3]/span","xpath"),
	VENDOR_ARTICLE_NUMBER_GRID(".//*[@id='addArticlesWrapper']/div[1]/div[1]/div[2]/div[1]/label[4]/span","xpath"),
	PRIMARY_VENDOR_GRID(".//*[@id='addArticlesWrapper']/div[1]/div[1]/div[2]/div[1]/label[4]/span","xpath"),
	SUB_STORE_GRID(".//*[@id='addArticlesWrapper']/div[1]/div[1]/div[2]/div[2]/label[2]/span","xpath"),
	SHOW_INACTIVE_GRID(".//*[@id='addArticlesWrapper']/div[1]/div[1]/div[2]/div[2]/label[3]/span","xpath"),
	ARTICLE_NUMBER_GRID_FIRSTCOL(".//*[@id='addArticles']/table/tbody/tr[1]/td[2]","xpath"),
	ARTICLE_NUMBER_GRID_FIRSTCOL_CHECKBOX(".//*[@id='addArticles']/table/tbody/tr[1]/td[1]/label/span","xpath"),
	ARTICLE_NUMBER_GRID_FIRSTCOL_CHECKBOX2("//*[@id='addArticles']/table/tbody/tr/td[1]/div/label/span", "xpath"),
	MULTIROW_CHECKBOX(".//div[@class='checkBoxStyle']","xpath"),
	ADDED_ARTICLE_FIRST("//*[@id='connectedArticlesResults']/div[6]/div/div/div/div[3]/span[1]","xpath"),
	INFO("i","linkText"),
	INFO_FORM(".//*[@id='inventoryRegInfo']","xpath"),
	INFO_CLOSE_BUTTON(".//*[@id='secondInfo']/div[3]/a","xpath"),
	CONFIRMATION_POPUP(".//*[@id='messageWindow']/div[2]/a[2]","xpath"),
	START_DATE_COL1(".//*[@id='connectedArticlesResults']/div[5]/div/div[2]/div[7]","xpath"),
	START_DATE_COL_TEXTBOX1("//*[@id='connectedArticlesResults']//input[@class='k-input']","xpath"),
	CONFIRMATION_POPUP_YES(".//*[@id='validityPeriod']/div[3]/a[1]","xpath"),
	SET_GENERAL_DAY_PRICE(".//*[@id='nav']/li[1]/ul/li/a","xpath"),
	SET_PRICE_POPUP(".//*[@id='selLinkUnit']","xpath"),
	TEXT_FILE_UPLOAD_POPUP(".//*[@id='upLoadFiles']/div[2]/a[1]","xpath"),
	TEXT_FILE_UPLOAD_POPUP_IMPORT(".//*[@id='upload']","xpath"),
	SHOW_ENTRY_DROPDOWN("//*[@id='gridWrapper']/div[1]/div[3]/span/span[1]/span[1]","xpath"),
	SAVEICON("//*[@id='saveContainer']/a/span", "xpath"),
	ATTENTION_POPUP_NO("//*[@id='messageWindow']/div[2]/a[1]", "xpath"),
	SEARCHRECORD("//*[@id='results']/table/tbody/tr/td[2]/div/div[1]", "xpath"),
	REMOVEICON_ARTICLE("//*[@id='connectedArticlesResults']/div[6]/div/div/div/div[2]/span/a", "xpath"),
	CHECKBOX_ARTICLE_SINGLEROW("//*[@id='addArticles']/table/tbody/tr/td[1]/div/label/span", "xpath"),
	APPLYCHANGES_BTN("//*[@id='saveContainer']/a", "xpath"),
	SELECTALL_CHECKBOX("checkSelBox", "name"),
	ADDARTICLE_SECONDROW_STARTDATE_CLICK("//*[@id='connectedArticlesResults']/div[6]/div/div/div[2]/div[7]", "xpath"),
	ADDARTICLE_SECONDROW_ENDDATE_CLICK("//*[@id='connectedArticlesResults']/div[6]/div/div/div[2]/div[8]", "xpath"),
	ADDARTICLE_SECONDROW_STARTDATE_INPUT("//*[@id='connectedArticlesResults']/div[6]/div/div/div[2]/div[7]/span/span/input", "xpath"),
	ADDARTICLE_SECONDROW_ENDDATE_INPUT("//*[@id='connectedArticlesResults']/div[6]/div/div/div[2]/div[8]/span/span/input", "xpath"),
	ADDART_ENDDATE_FIRSTROW("//*[@id='connectedArticlesResults']/div[6]/div/div/div[1]/div[8]", "xpath"),
	ADDAGREEMENT_BTN2("//*[@id='addNew']", "xpath"),
	MULTIROW_CHECKBOX2("//div[@id='connectedArticlesResults']/div/div/div/div/span/input", "xpath"),
	IMPORTTEXTFILE_TITLE("//*[@id='upLoadFiles_wnd_title']", "xpath"),
	IMPORTTEXTFILE_POPUP_CANCELBTN("//*[@class='uploadButtons']/a[1]", "xpath"),
	IMPORTTEXTFILE_POPUP_IMPORTBTN("//*[@class='uploadButtons']/a[2]", "xpath"),
	PRICECLICK_FIRSTROW("//*[@id='connectedArticlesResults']/div[6]/div/div/div[1]/div[6]", "xpath"),
	PRICEINPUT_FIRSTROW("//*[@id='connectedArticlesResults']/div[6]/div/div/div[1]/div[6]/input", "xpath"),
	PRICECLICK_SECONDROW("//*[@id='connectedArticlesResults']/div[6]/div/div/div[2]/div[6]", "xpath"),
	PRICEINPUT_SECONDROW("//*[@id='connectedArticlesResults']/div[6]/div/div/div[2]/div[6]/input", "xpath"),
	;
	
	public String element, identifier;
	private PurchaseVendorPriceAgreementEnums(String element){
		 this.element = element;
	 }
	private PurchaseVendorPriceAgreementEnums(String element, String identifier){
		 this.element = element;
		 this.identifier = identifier;
	 }
	public String getElementPath(){
		return element;
	}
	public String getElementIdentifier(){
		return identifier;
	}

}
