package com.sacs.PageOjects;

public enum ReturnsCloseDateCorrectionEnum {

	 RETURNS("returns","id"),
	 CLOSE_DATE_CORRECTION("//*[@id='closedatescorrections']/a","xpath"),
	 PAGE_TITLE("//*[@id='contentHeader']/div/h1","xpath"),
	 INVERTED_SYMBOL("//*[@id='searchContainer']/div[1]/span[3]/a/img","xpath"),
	 SEARCH_CONTAINER("//*[@id='searchContainer']/div[2]","xpath"),
	 REF_NO_CRITERIA("//*[@id='searchContainer']/div[2]/div[1]/div[1]/label/span","xpath"),
	 FLIGHT_CRITERIA("//*[@id='searchContainer']/div[2]/div[1]/div[2]/label/span","xpath"),
	 OPEN_CRITERIA("//*[@id='searchContainer']/div[2]/div[1]/div[3]/label/span","xpath"),
	 CANCELLED_CRITERIA("//*[@id='searchContainer']/div[2]/div[2]/div[2]/label/span","xpath"),
	 CHECKED_OUT_CRITERIA("//*[@id='searchContainer']/div[2]/div[2]/div[3]/label/span","xpath"),
	 SEARCH_SUBMIT("//*[@id='searchContainer']/div[1]/span[2]/a/img","xpath"),
	 GRID_FIRST_ROW_FLIGHT("//*[@id='results']/table/tbody/tr[1]/td[2]","xpath"),
	 EDIT_BTN("//*[@id='editButton']", "xpath"),
	 AC_REGISTRATION("//*[@id='AircraftRegistration']", "xpath"),
	 OK_BTN("//*[@id='saveContainer']/a", "xpath"),
	 SEARCHBOX("//*[@id='articlesearch']", "xpath"),
	 SHOWENTRIES_DD("//*[@id='gridWrapper']/div[1]/div[3]/span/span[1]/span[1]", "xpath"),
	 SEARCH_RESULT_GRID("//*[@id='results']/table", "xpath"),
	 PAGINATION("//*[@id='results']/div", "xpath"),
	 SEARCH_DD("//*[@id='searchContainer']/div[1]/span[3]/a/img", "xpath"),
	 SEARCHOPTION_REFERENCENO("//*[@id='searchContainer']/div[2]/div[1]/div[1]/label/span", "xpath"),
	 SEARCHOPTION_FLIGHT("//*[@id='searchContainer']/div[2]/div[1]/div[2]/label/span", "xpath"),
	 SEARCHOPTION_OPEN("//*[@id='searchContainer']/div[2]/div[1]/div[3]/label/span", "xpath"),
	 SEARCHOPTION_DELIVERYSLIPNO("//*[@id='searchContainer']/div[2]/div[1]/div[4]/label/span", "xpath"),
	 SEARCHOPTION_CLOSED("//*[@id='searchContainer']/div[2]/div[2]/div[1]/label/span", "xpath"),
	 SEARCHOPTION_CANCELLED("//*[@id='searchContainer']/div[2]/div[2]/div[2]/label/span", "xpath"),
	 SEARCHOPTION_CHECKOUT("//*[@id='searchContainer']/div[2]/div[2]/div[3]/label/span", "xpath"),
	 SEARCHOPTION_STARTDATE("//*[@id='openStartDate']", "xpath"),
	 SEARCHOPTION_ENDDATE("//*[@id='openEndDate']", "xpath"),
	 H1("//*[@id='results']/table/thead/tr/th[1]/a", "xpath"),
	 H2("//*[@id='results']/table/thead/tr/th[2]/a", "xpath"),
	 H3("//*[@id='results']/table/thead/tr/th[3]/a", "xpath"),
	 H4("//*[@id='results']/table/thead/tr/th[4]/a", "xpath"),
	 H5("//*[@id='results']/table/thead/tr/th[5]", "xpath"),
	 H6("//*[@id='results']/table/thead/tr/th[6]", "xpath"),
	 H7("//*[@id='results']/table/thead/tr/th[7]", "xpath"),
	 H8("//*[@id='results']/table/thead/tr/th[8]", "xpath"),
	 H9("//*[@id='results']/table/thead/tr/th[9]", "xpath"),
	 FLIGHT_FIRSTROW("//*[@id='results']/table/tbody/tr[1]/td[3]", "xpath"),
	 DETAILPAGE_FLIGHT("//*[@id='rCloseDateWrapper']/div/div/div/div[2]/span[3]", "xpath"),
	 EDITBTN("//*[@class='editContainer']/a", "xpath"),
	 CATERINGUNIT("//*[@id='CateringUnits']", "xpath"),
	 RETURN_FLIGHT("//*[@id='updateFlightForm']/div[4]/div[2]/div[2]/span[2]/input", "xpath"),
	 ACTYPE("//*[@id='AircraftVersionCode']", "xpath"),
	 ACREG("//*[@id='AircraftRegistration']", "xpath"),
	 DEPARTTO("//*[@id='DepartsTo']", "xpath"),
	 SEGMENT("//*[@id='FlightSegment']", "xpath"),
	 CLOSE("html/body/div[2]/div[1]/div[1]/div[2]/div[5]/ul/li[7]/ul/li[3]/a", "xpath"),
	 SEARCHICON("//*[@id='searchContainer']/div/span[2]/a/img", "xpath"),
	 CLOSEDATE_ICON("//*[@id='editCheckout']", "xpath"),
	 CLOSEDATE_POPUP_CONTINUEBTN("//*[@id='removeAlert']/div[3]/a[1]", "xpath"),
	 SEARCHEDROW("//*[@id='results']/table/tbody/tr/td[1]", "xpath"),
	 ACTYPE_UPDATEGRID("//*[@id='rCountHeaderWrapper']/div[4]/div[1]/div[2]/span", "xpath"),
	 EDIT_TITLE("//*[@id='editFlightWrapper']/div/div/h1", "xpath"),
	 ADD_MENU("//*[@id='rCloseDateDetailWrapper']/div[3]/div[1]/ul/li/div", "xpath"),
	 ADD_SALESNO("//*[@id='addSalesButton']", "xpath"),
	 ADD_ARTICLE("//*[@id='addArticleButton']", "xpath"),
	 ADD_SELECTED("//*[@id='coSalesAdd']", "xpath"),
	 SALESNO_FIRSTROW("//*[@id='addSalesNumberGrid']/table/tbody/tr[1]/td[2]/span", "xpath"),
	 SALESNO_FIRSTROW_CHECKBOX("//*[@id='addSalesNumberGrid']/table/tbody/tr[1]/td[1]/div/label/span", "xpath"),
	 ADD_SALESNO_ROW("//*[@id='resultsDetails']/div[6]/div/div/div[1]/div[2]", "xpath"),
	 SALESNO_SEARCHFIELD("//*[@id='addSalesNoSearch']", "xpath"),
	 SALESNO_SEARCHICON("//*[@id='addSalesNo']/div[1]/div[1]/div[1]/span[2]/a/img", "xpath"),
	 SALESNO_SEARCHEDRECORD("//*[@id='addSalesNumberGrid']/table/tbody/tr/td[2]/span", "xpath"),
	 SALESNO_SAVEICON("//*[@id='nav']/li[4]/a", "xpath"),
	 SAVECHANGESTOFLIGHT_CONTINUEBTN("//*[@id='continueCDCPopup']", "xpath"),
	 SALESNO_SEARCHED_CHECKBOX("//*[@id='addSalesNumberGrid']/table/tbody/tr/td[1]/div/label/span", "xpath"),
	 BART_FIRSTROW("//*[@id='resultsDetails']/div[6]/div/div/div[1]/div[3]", "xpath"),
	 SALESNO_DESCRIPTION_FIRSTROW("//*[@id='addSalesNumberGrid']/table/tbody/tr[1]/td[3]", "xpath"),
	 DESC_FIRSTROW("//*[@id='resultsDetails']/div[6]/div/div/div[1]/div[5]", "xpath"),
	 BART_FIRSTROW_CHECK("//*[@id='addBasicArticlesGrid']/table/tbody/tr[1]/td[1]/div/label/span", "xpath"),
	 BART_ARTNO_FIRSTROW("//*[@id='addBasicArticlesGrid']/table/tbody/tr[1]/td[2]/span[1]", "xpath"),
	 BART_ADDSELECTED("//*[@id='bcArticleAdd']", "xpath"),
	 ADD_ARTICLE_SEARCHBOX("//*[@id='addArticlesearch']", "xpath"),
	 ADD_ARTICLE_SEARCHICON("//*[@id='addBasicArticles']/div[1]/div[1]/div[1]/span[2]/a/img", "xpath"),
	 ADD_ARTICLE_SEARCHEDDATA("//*[@id='addBasicArticlesGrid']/table/tbody/tr/td[1]/div/label/span", "xpath"),
	 ARTICLE_DESC_FIRSTROW("//*[@id='addBasicArticlesGrid']/table/tbody/tr[1]/td[3]/span", "xpath"),
	 DPLAN_CLICK_FIRSTROW("//*[@id='resultsDetails']/div[6]/div/div/div[1]/div[4]", "xpath"),
	 DPLAN_DD_FIRSTROW("//*[@id='resultsDetails']/div[6]/div/div/div[1]/div[4]/select", "xpath"),
	 ARTICLE_FIRSTROW("//*[@id='resultsDetails']/div[6]/div/div/div[5]/div[3]", "xpath"),
	 DPLAN_FIRSTROW_SELECTED("//*[@id='resultsDetails']/div[6]/div/div/div[5]/div[4]/div", "xpath"),
	 CLASS_CLICK_FIRSTROW("//*[@id='resultsDetails']/div[6]/div/div/div[6]/div[7]/div", "xpath"),
	 CLASS_DD_FIRSTROW("//*[@id='resultsDetails']/div[6]/div/div/div[6]/div[7]/select", "xpath"),
	 LOADTQTY_CLICK("//*[@id='resultsDetails']/div[6]/div/div/div[3]/div[8]", "xpath"),
	 LOADQTY_INPUT("//*[@id='resultsDetails']/div[6]/div/div/div[3]/div[8]/input", "xpath"),
	 SAVECHANGES_CANCELBTN("//*[@id='cancelCDCPopup']", "xpath"),
	 LOADQTY_TEXT("//*[@id='resultsDetails']/div[6]/div/div/div[8]/div[8]", "xpath"),
	 RETQTY_CLICK("//*[@id='resultsDetails']/div[6]/div/div/div[3]/div[9]", "xpath"),
	 RETQTY_INPUT("//*[@id='resultsDetails']/div[6]/div/div/div[3]/div[9]/input", "xpath"),
	 WASTEOB_CLICK("//*[@id='resultsDetails']/div[6]/div/div/div[1]/div[11]", "xpath"),
	 WASTEOB_INPUT("//*[@id='resultsDetails']/div[6]/div/div/div[11]/div[11]/input", "xpath"),
	 LOADTQTY_CLICK2("//*[@id='resultsDetails']/div[6]/div/div/div[1]/div[8]", "xpath"),
	 LOADQTY_INPUT2("//*[@id='resultsDetails']/div[6]/div/div/div[1]/div[8]/input", "xpath"),
	 WASTESTORE_CLICK("//*[@id='resultsDetails']/div[6]/div/div/div[1]/div[10]", "xpath"),
	 WASTESTORE_INPUT("//*[@id='resultsDetails']/div[6]/div/div/div[1]/div[10]/input", "xpath"),
	 WASTESTORE_TEXT("//*[@id='resultsDetails']/div[6]/div/div/div[10]/div[10]", "xpath"),
	 MENU("//*[@id='nav']/li[3]/div", "xpath"),
	 CHANGECUSTNUMBER_OPT1("//*[@id='nav']/li[3]/ul/li[1]/a", "xpath"),
	 VIEWCORRECTSTOCKDATES("//*[@id='correctStockDates']", "xpath"),
	 CORRECTSEALNUMBERS("//*[@id='correctSealNumbers']", "xpath"),
	 CORRECTBARNUMBERS("//*[@id='correctBarNumbers']", "xpath"),
	 CHANGECUSTNO_CONTINUEBTN("//*[@id='returnCustomerChangePopup']/div[2]/a[2]", "xpath"),
	 PAGETITLE("//*[@id='contentHeader']/div[1]/h1", "xpath"),
	 NEWSTOCKDATE_CLICK("//*[@id='sdResults']/div[6]/div/div/div[1]/div[4]", "xpath"),
	 NEWSTOCKDATE_INPUT("//*[@id='sdResults']/div[6]/div/div/div[1]/div[4]/span/span/input", "xpath"),
	 TRANSACTION_ICON_FIRSTROW("//*[@id='sdResults']/div[6]/div/div/div[1]/div[6]/div/a", "xpath"),
	 TRANSACTIONPOPUP_TITLE("//*[@id='viewStockTransactions_wnd_title']", "xpath"),
	 TRANSACTION_POPUP_CLOSEBTN("//*[@id='closeButton']", "xpath"),
	 DELIVERYPLAN_TAB("//*[@id='DeliveryPlan']", "xpath"),
	 ADD_DELIVERYPLAN_BTN("//*[@id='addButton']", "xpath"),
	 DELIVERYPLAN_FIRSTROW("//*[@id='addDeliveryPlansGrid']/table/tbody/tr[1]/td[2]", "xpath"),
	 DELIVERYPLAN_SEARCHBOX("//*[@id='addDeliveryPlanSearch']", "xpath"),
	 DELIVERYPLAN_SEARCHICON("//*[@id='addArticlesWrapper']/div[1]/div[1]/div[1]/span[2]/a/img", "xpath"),
	 DELIVERYPLAN_DD("//*[@id='addArticlesWrapper']/div[1]/div[1]/div[1]/span[3]/a/img", "xpath"),
	 DELIVERYPLAN_SEARCHOPITON1("//*[@id='addArticlesWrapper']/div[1]/div[1]/div[2]/div[1]/label/span", "xpath"),
	 DESCRIPTION_SEARCHOPTION2("//*[@id='addArticlesWrapper']/div[1]/div[1]/div[2]/div[2]/label/span", "xpath"),
	 DPLAN_CHK1("//*[@id='addDeliveryPlansGrid']/table/tbody/tr[1]/td[1]/div/label/span", "xpath"),
	 DPLAN_CHK2("//*[@id='addDeliveryPlansGrid']/table/tbody/tr[3]/td[1]/div/label/span", "xpath"),
	 DPLAN_CHK3("//*[@id='addDeliveryPlansGrid']/table/tbody/tr[4]/td[1]/div/label/span", "xpath"),
	 DPLAN_ADDSELECTED("//*[@id='addArticlesWrapper']/div[1]/div[2]/a", "xpath"),
	 SELECTED_DPLAN_FIRSTROW("//*[@id='deliveryPlanResults']/div[6]/div/div/div[2]/div[2]", "xpath"),
	 REMOVE_DPLAN_SECONDROW("//*[@id='deliveryPlanResults']/div[6]/div/div/div[2]/div[4]/span/a", "xpath"),
	 REMOVE_DPLAN_TEXT("//*[@id='removeAlert']/div[2]", "xpath"),
	 REMOVE_DPLAN_CONTINUEBTN("//*[@id='removeAlert']/div[3]/a[1]", "xpath"),
	 DPLAN_APPLYCHANGES_BTN("//*[@id='saveContainer']/div/a", "xpath"),
	 CHECKBOX("//*[@id='checkSelBox00']", "xpath"),
	 REMOVE_SELECTED("//*[@id='rCloseDateDetailWrapper']/div[1]/div[3]/a", "xpath"),
	 DELETE_DPLAN_TEXT("//*[@id='removeAlert']/div[2]", "xpath"),
	 DELETE_DPLAN_CONTINUEBTN("//*[@id='removeAlert']/div[3]/a[1]", "xpath"),
	 DELETE_DPLAN_CANCELBTN("//*[@id='removeAlert']/div[3]/a[2]", "xpath"),
	 BARNO_CLICK("//*[@id='bnResults']/div[6]/div/div/div/div[3]", "xpath"),
	 BARNO_INPUT("//*[@id='bnResults']/div[6]/div/div/div/div[3]/input", "xpath"),
	 ;
		
	 public String element, identifier;
	 	
	 	private ReturnsCloseDateCorrectionEnum(String element){
	 		 this.element = element;
	 	 }
	 	
	 	private ReturnsCloseDateCorrectionEnum(String element, String identifier){
	 		 this.element = element;
	 		 this.identifier = identifier;
	 	 }
	 	
	 	public String getElementPath(){
	 		return element;
	 	}
	 	public String getElementIdentifier(){
	 		return identifier;
	 	}
}
