package com.sacs.PageOjects;

public enum ReturnsCheckOutEnum {

	
	 RETURNS("returns","id"),
	 CHECKOUT("//*[@id='checkout']/a","xpath"),
	 PAGE_TITLE("//*[@id='contentHeader']/div/h1","xpath"),
	 EDIT_CHECKOUT("//*[@id='editCheckout']","xpath"),
	 EDIT_FLIGHT_DETAILS(".//*[@id='coDateResults']/div[6]/div/div/div/div[13]/span/a","xpath"),
	 HASH_TOTAL_POPUP("//*[@id='hashPopup']","xpath"),
	 CHECK_SUM_TEXT_BOX_ON_POPUP("//*[@id='checkSum']","xpath"),
	 CONTINUE_ON_HASH_POPUP("//*[@id='hashPopup']/div[2]/a[2]","xpath"),
	 QTY("//*[@id='resultsDetails']/div[7]/div/div/div/div[8]","xpath"),
	 QTY_INPUT("//*[@id='resultsDetails']/div[7]/div/div/div/div[8]/input","xpath"),
	 RS("//*[@id='resultsDetails']/div[7]/div/div/div/div[7]","xpath"),
	 CHECK_OUT_BTN("//*[@id='checkOutButton']","xpath"),
	 FIRST_FLIGHT_CHECK_BOX("//*[@id='coDateResults']/div[6]/div/div/div/div[1]/label/span","xpath"),
	 CHECK_OUT_SELECTED("//*[@id='checkOutButtonbm']","xpath"),
	 FLIGHT_CHECKOUT_POPUP("//*[@id='flightCheckOutWrapper']","xpath"),
	 STORE_CODE_ON_FLIGHT_CHECKOUT_POPUP(".//*[@id='flightCheckOutWrapper']/div/div[1]//input[@id='SubStoreCode']","xpath"),
	 STOCK_DATE_ON_FLIGHT_CHECKOUT_POPUP(".//*[@id='flightCheckOutWrapper']/div/div[2]/span/span//input[@id='coStockDate']","xpath"),
	 CONTINUE_ON_CHECK_OUT_POPUP("//*[@id='continueCOPopup']","xpath"),
	 CHECK_ALL_FLIGHTS(".//div[@id='coDateResults']//div[starts-with(@class, 'slick-header-columns')]//input[@type='checkbox']","xpath"),
	 SEARCHBOX("//*[@id='articlesearch']", "xpath"),
	 SEARCH_ICON("//*[@id='gridWrapper']/div[1]/div/span[2]/a/img", "xpath"),
	 NODATATODISPLAY("//*[@id='results']/table/tbody/tr/td", "xpath"),
	 GRID_FIRSTROW("//*[@id='results']/table/tbody/tr/td[1]", "xpath"),
	 FLIGHTCHECKOUT_POPUP_SEARCHICON("//*[@id='enterStoreCode']/span/a", "xpath"),
	 SUBSTORECODE_FIRSTROW("//*[@id='subStoreCodeSearchGrid']/table/tbody/tr[1]/td[1]", "xpath"),
	 FLIGHTCHECKOU_POPUP_CONTINUEBTN("//*[@id='continueCOPopup']", "xpath"),
	 CHECKBOX("//*[@id='checkSelBox00']", "xpath"),
	 SUBSTORE_TEXTBOX("//*[@id='flightCheckOutWrapper']/div[1]/div[1]/span[1]/input", "xpath"),
	 STOCK_DATE("//*[@id='coStockDate']", "xpath"),
	 DATE_FIRSTROW("//*[@id='results']/table/tbody/tr[1]/td[1]", "xpath"),
	 USERNAME_FIRSTROW("//*[@id='results']/table/tbody/tr[1]/td[2]", "xpath"),
	 EDITICON_FIRSTROW("//*[@id='results']/table/tbody/tr[1]/td[5]/a", "xpath"),
	 CHANGEDATE("//*[@id='changeDate']", "xpath"),
	 CANCEL_ICON("//*[@id='removeOV']/a", "xpath"),
	 CANCEL_POPUP_CONTINUEBTN("//*[@id='removeAlert']/div[3]/a[1]", "xpath"),
	 CANCELLED_STOCKDATE("//*[@id='cancelStockDate']", "xpath"),
	 CANCELFLIGHT_POPUP_CONTINUEBTN("//*[@id='continueStockDatePopup']", "xpath"),
	 FLIGHT_REMARK_TITLE("//*[@id='remarksPopUp_wnd_title']", "xpath"),
	 FLIGHT_REMARK_POPUP_OKBTN("//*[@id='remarksPopUp']/div[2]/a", "xpath"),
	 CHECKOUT_TITLE("//*[@id='contentHeader']/div[1]/h1", "xpath"),
	 BAR_NO_INFOICON("//*[@id='checkOutHeaderWrapper']/div[4]/div[1]/div[5]/a", "xpath"),
	 VIEW_BAR_TITLE("//*[@id='viewflightBarNumbers_wnd_title']", "xpath"),
	 BARNO_POPUP_CLOSEBTN("//*[@id='viewflightBarNumbers']/div[3]/a[1]", "xpath"),
	 BARNO_POPUP_EDITBTN("//*[@id='viewflightBarNumbers']/div[3]/a[2]", "xpath"),
	 SEALNO_INFOICON("//*[@id='checkOutHeaderWrapper']/div[4]/div[2]/div[5]/a", "xpath"),
	 SEALNO_POPUP_TITLE("//*[@id='viewflightSealNumbers_wnd_title']", "xpath"),
	 SEAL_POPUP_CLOSEBTN("//*[@id='viewflightSealNumbers']/div[3]/a[1]", "xpath"),
	 MENU("//*[@id='nav']/li[4]/div", "xpath"),
	 ADD_DROPDOWN("//*[@id='nav']/li[1]/div", "xpath"),
	 ADD_SALESNUMBER("//*[@id='addSalesButton']", "xpath"),
	 ADD_ARTICLE("//*[@id='addArticleButton']", "xpath"),
	 IMPORTBOXCODE("//*[@id='importButton']", "xpath"),
	 ADDSALES_THIRDROW("//*[@id='resultsDetails']/div[6]/div/div/div[3]/div[2]/input", "xpath"),
	 SN_SEARCHICON_THIRDROW("//*[@id='resultsDetails']/div[6]/div/div/div[3]/div[2]/a/span", "xpath"),
	 SALESNO_POPUP_TITLE("//*[@id='showSalesNoSearchPopup_wnd_title']", "xpath"),
	 SALESNO_POPUP_CANCELBTN("//*[@id='cancelSalesNo']", "xpath"),
	 SALESNO_POPUP_CONTINUEBTN("//*[@id='selSalesNoContinue']", "xpath"),
	 SALESNO_POPUP_FIRSTROW("//*[@id='salesNumberSearchGrid']/table/tbody/tr[1]/td[1]", "xpath"),
	 SALESNO_SELECT_THIRDROW("//*[@id='resultsDetails']/div[6]/div/div/div[3]/div[2]", "xpath"),
	 ARTICLENO_SECONDROW("//*[@id='resultsDetails']/div[6]/div/div/div[2]/div[3]", "xpath"),
	 ARTICLENO_SEARCICON_SECROW("//*[@id='resultsDetails']/div[6]/div/div/div[2]/div[3]/a/span", "xpath"),
	 ARTICLENO_SEARCHICON_THIRDROW("//*[@id='resultsDetails']/div[6]/div/div/div[3]/div[3]/a/span", "xpath"),
	 ARTICLENO_INPUT_THIRDROW("//*[@id='resultsDetails']/div[6]/div/div/div[3]/div[3]/input", "xpath"),
	 SAVE_ICON("//*[@id='saveChanges']/div", "xpath"),
	 SEARCH_BASIC_ARTICLE_POPUPTITLE("//*[@id='showBasicArticleSearch_wnd_title']", "xpath"),
	 SBA_POPUP_CANCELBTN("//*[@id='cancelArticle']", "xpath"),
	 SBA_POPUP_OKBTN("//*[@id='selectArticle']", "xpath"),
	 SBA_POPUP_FIRTSROW("//*[@id='basicArticleGrid']/table/tbody/tr[1]/td[1]/span[1]", "xpath"),
	 SBA_SEARCHBOX("//*[@id='showBasicArticleSearch']/div/div[2]/div[1]/span[1]/input", "xpath"),
	 SBA_SEARCHICON("//*[@id='showBasicArticleSearch']/div/div[2]/div[1]/span[2]/a/img", "xpath"),
	 SBA_POPUP_SEARCHROW("//*[@id='basicArticleGrid']/table/tbody/tr/td/span[1]", "xpath"),
	 SBA_DESC_FIRSTROW("//*[@id='basicArticleGrid']/table/tbody/tr[1]/td[2]", "xpath"),
	 ARTNO_THIRDROW("//*[@id='resultsDetails']/div[6]/div/div/div[3]/div[3]", "xpath"),
	 INPORTBOXCODE_BACKBTN("//*[@id='backToSearch']", "xpath"),
	 ADDBOXCODE("//*[@id='checkoutbcWrapper']/div[3]/div[1]/a", "xpath"),
	 ADDBOXCODE_ADDSELECTEDBTN("//*[@id='addSelectedBoxCodes']", "xpath"),
	 ADDBOXCODE_CLOSEBTN("//*[@id='closeButton']", "xpath"),
	 ADDBOXCODE_APPLYCHANGESBTN("//*[@id='saveContainer']/a", "xpath"),
	 ADDBOXCODE_GRID_FIRSTROW("//*[@id='boxCodeGrid']/table/tbody/tr[1]/td[2]", "xpath"),
	 ADDBOXCODE_GRID_SEARCHBOX("//*[@id='articlesearch']", "xpath"),
	 ADDBOXCODE_GRID_SEARCHICON("//*[@id='searchContainer']/div[1]/span[2]/a/img", "xpath"),
	 ADDBOXCODE_GRID_SEARCHRECORD("//*[@id='boxCodeGrid']/table/tbody/tr/td[2]", "xpath"),
	 ADDBOXCODE_FIRSTROW_CHECKBOX("//*[@id='boxCodeGrid']/table/tbody/tr[1]/td[1]/div/label/span", "xpath"),
	 SELECTEDBOXCODE_FIRSTROW("//*[@id='bcResults']/div[6]/div/div/div/div[1]", "xpath"),
	 ADDBOXCODE_QTY_CLICK("//*[@id='bcResults']/div[6]/div/div/div/div[3]", "xpath"),
	 ADDBOXCODE_QTY_INPUT("//*[@id='bcResults']/div[6]/div/div/div/div[3]/input", "xpath"),
	 MENU1_VIEWCORRECTSTOCKDATES("//*[@id='correctStockDates']", "xpath"),
	 MENU2_SEALNUMBERS("//*[@id='enterSealNumbers']", "xpath"),
	 MENU3_ENTERBARNUMBERS("//*[@id='enterBarNumbers']", "xpath"),
	 BARNO_DELIVERYPLAN_HEADING("//*[@id='bnResults']/div[2]/div/div/div[1]/span[1]", "xpath"),
	 BARNO_DESC_HEADER("//*[@id='bnResults']/div[2]/div/div/div[2]/span[1]", "xpath"),
	 BARNO_BAR_HEADER("//*[@id='bnResults']/div[2]/div/div/div[3]/span[1]", "xpath"),
	 BARNO_CLICK1("//*[@id='bnResults']/div[6]/div/div/div/div[3]", "xpath"),
	 BARNO_INPUT1("//*[@id='bnResults']/div[6]/div/div/div/div[3]/input", "xpath"),
	 DELIVERYPLAN_TAB("//*[@id='nav']/li[3]/a/div", "xpath"),
	 DP_HEADING("//*[@id='formBody']/div[1]/div[1]", "xpath"),
	 ADD_DELIVERYPLAN("//*[@id='addButton']", "xpath"),
	 DP_GRID_CLOSEBTN("//*[@id='addArticlesWrapper']/div[1]/div[3]/a", "xpath"),
	 DP_GRID_FIRSTROW("//*[@id='addDeliveryPlansGrid']/table/tbody/tr[1]/td[2]", "xpath"),
	 DP_GRID_SEARCHBOX("//*[@id='addDeliveryPlanSearch']", "xpath"),
	 DP_GRID_SEARCHICON("//*[@id='addArticlesWrapper']/div[1]/div[1]/div[1]/span[2]/a/img", "xpath"),
	 DP_GRID_SEARCHEDRECORD("//*[@id='addDeliveryPlansGrid']/table/tbody/tr/td[2]", "xpath"),
	 DP_GRID_CHECKBOX_FIRSTROW("//*[@id='addDeliveryPlansGrid']/table/tbody/tr[1]/td[1]/div/label/span", "xpath"),
	 DP_GRID_ADDSELECTED("//*[@id='addArticlesWrapper']/div[1]/div[2]/a", "xpath"),
	 DP_SELECTED("//*[@id='deliveryPlanResults']/div[6]/div/div/div[2]/div[2]", "xpath"),
	 DP_GRID_APPLYCHANGESBTN("//*[@id='applyChanges']", "xpath"),
	 DP_REMOVEICON_FIRSTROW("//*[@id='deliveryPlanResults']/div[6]/div/div/div[1]/div[4]/span/a", "xpath"),
	 DP_FIRSTROW("//*[@id='deliveryPlanResults']/div[6]/div/div/div[1]/div[2]", "xpath"),
	 DP_DELETEPOPUP_TEXT("//*[@id='removeAlert']/div[2]", "xpath"),
	 DELETE_POPUP_CONTINUEBTN("//*[@id='removeAlert']/div[3]/a[1]", "xpath"),
	 DELETE_POPUP_CANCELBTN("//*[@id='removeAlert']/div[3]/a[2]", "xpath"),
	 DP_GRID_FIRSTROW1("//*[@id='deliveryPlanResults']/div[6]/div/div/div/div[2]", "xpath"),
	 DP_REMOVEICON_ONLYROW("//*[@id='deliveryPlanResults']/div[6]/div/div/div/div[4]/span/a", "xpath"),
	 CSPS_TAB("//*[@id='nav']/li[2]/a/div", "xpath"),
	 CSP_TAB_TEXT("//*[@id='checkoutWrapper']/div[2]/div[1]/div[1]", "xpath"),
	 ADD_CSPs_BTN("//*[@id='checkoutWrapper']/div[2]/div[1]/a[1]", "xpath"),
	 ADDCSP_FIRSTROW_CHECKBOX("//*[@id='addCspGrid']/table/tbody/tr[1]/td[1]/div/label/span", "xpath"),
	 ADDCSP_ADDSELECTEDBTN("//*[@id='addArticlesWrapper']/div[1]/div[2]/a", "xpath"),
	 ADDCSP_CLOSEBTN("//*[@id='addArticlesWrapper']/div[1]/div[3]/a", "xpath"),
	 ATTENTION_POPUP_CONTINUEBTN("//*[@id='btnContinue']", "xpath"),
	 ADDCSP_CSPHEADER("//*[@id='cspResults']/div/div/div/div[2]", "xpath"),
	 ADDCSP_DESC_HEADER("//*[@id='cspResults']/div/div/div/div[3]", "xpath"),
	 ADDCSP_ACVERSION_HEADER("//*[@id='cspResults']/div/div/div/div[4]", "xpath"),
	 ADDCSP_EFFECTIVEDATE_HEADER("//*[@id='cspResults']/div/div/div/div[5]", "xpath"),
	 ADDCSP_TYPE_HEADER("//*[@id='cspResults']/div/div/div/div[6]", "xpath"),
	 ADDCSP_FIRSTROW("//*[@id='addCspGrid']/table/tbody/tr[1]/td[2]", "xpath"),
	 ADDCSP_SEARCHBOX("//*[@id='addCspsearch']", "xpath"),
	 ADDCSP_SEARCHICON("//*[@id='addArticlesWrapper']/div[1]/div[1]/div[1]/span[2]/a/img", "xpath"),
	 ADDCSP_SEARCHRECORD("//*[@id='addCspGrid']/table/tbody/tr[1]/td[2]", "xpath"),
	 ADDCSP_CHECKBOX_SEARCHRECORD("//*[@id='addCspGrid']/table/tbody/tr/td[1]/div/label/span", "xpath"),
	 ADDCSP_WARNING_POPUP_TITLE("//*[@id='cspWarning_wnd_title']", "xpath"),
	 ATTENTION_POPUP_CANCELBTN("//*[@id='btnCancel']", "xpath"),
	 ADDCSP_SECONDROW_CHECKBOX("//*[@id='addCspGrid']/table/tbody/tr[2]/td[1]/div/label/span", "xpath"),
	 ADDCSP_SECONDROW_CSP("//*[@id='addCspGrid']/table/tbody/tr[2]/td[2]", "xpath"),
	 ADDCSP_SECONDROW_SELECTED("//*[@id='cspResults']/div[6]/div/div/div[2]/div[2]", "xpath"),
	 ADDCSPS_DELETEICON_ONLYROW("//*[@id='cspResults']/div[6]/div/div/div/div[7]/span/a", "xpath"),
	 ADDCSPS_TEXT("//*[@id='checkoutWrapper']/div[2]/div[5]/span", "xpath"),
	;
	
public String element, identifier;
	
	private ReturnsCheckOutEnum(String element){
		 this.element = element;
	 }
	
	private ReturnsCheckOutEnum(String element, String identifier){
		 this.element = element;
		 this.identifier = identifier;
	 }
	
	public String getElementPath(){
		return element;
	}
	public String getElementIdentifier(){
		return identifier;
	}
}
