package com.sacs.PageOjects;

public enum StoresRequisitionOrderEnums {
	
	SEARCH_FIELD(".//*[@id='articlesearch']", "xpath"),
	SEARCH_SUBMIT("searchSubmit", "className"),
	REQUISITION_ORDER_LINK(".//*[@id='requisitionorder']/a", "xpath"),
	REQUISITION_ORDER_TITLE(".//*[@id='contentHeader']/div/h1", "xpath"),
	CREATE_REQUISITION_ORDER_LINK(".//*[@id='createRequisitionOrder']", "xpath"),
	FROM_SUB_STORE_CODE(".//*[@id='SubStoreCode']", "xpath"),
	REQUIRED_BY(".//*[@id='ReqSubStoreCode']", "xpath"),
	OK_BTN(".//*[@id='btn-ok']", "xpath"),
	GRID_ART_NO_COLUMN_VALUE_XPATH(".//*[@id='resultsroEditGrid']/div[5]/div/div/div[2]", "xpath"),
	GRID_ORDER_QUANTITY(".//*[@id='resultsroEditGrid']/div[6]/div/div/div[1]/div[8]", "xpath"),
	GRID_ORDER_QUANTITY_INPUT(".//*[@id='resultsroEditGrid']/div[6]/div/div/div[1]/div[8]/input", "xpath"),
	GRID_ORDER_QUANTITY1(".//*[@id='resultsroEditGrid']/div[6]/div/div/div[1]/div[8]", "xpath"),
	GRID_ORDER_QUANTITY_INPUT1(".//*[@id='resultsroEditGrid']/div[6]/div/div/div[1]/div[8]/input", "xpath"),
	APPLY_CHANGES("Apply Changes", "linkText"),
	STATUS(".//*[@id='regStatusContainer']/div[2]/span", "xpath"),
	NOTES(".//*[@id='AdditionalInfo']", "xpath"),
	GENERATE_ORDER_BTN(".//*[@id='generateOrder']", "xpath"),
	GENERATE_REQUISITION_ORDER_POPUP_HEADING(".//*[@id='requisitionOrderInfo_wnd_title']", "xpath"),
	GENERATE_REQUISITION_ORDER_POPUP_CONTINUE_BTN(".//*[@id='generateRO']", "xpath"),
	CLOSE_BTN(".//*[@id='closeInfoWindow']", "xpath"),
	//
	STORES("//*[@id='stores']", "xpath"),
	INTERNALREQORDER("//*[@id='requisitionorder']/a", "xpath"),
	REQORDERTITLE("//*[@id='contentHeader']/div/h1", "xpath"),
	CREATEORDER("//*[@id='createRequisitionOrder']/li/div", "xpath"),
	SUBSTORE("//*[@id='SubStoreCode']", "xpath"),
	REQUIREDBY("//*[@id='ReqSubStoreCode']", "xpath"),
	RO_OK("//*[@id='btn-ok']", "xpath"),
	//ENTERORDERQTY1CLICK(".//*[@id='resultsroEditGrid']/div[4]/div[3]/div/div[1]/div[8]", "xpath"),
	//ENTERORDERQTY1("//*[@id='resultsroEditGrid']/div[4]/div[3]/div/div[1]/div[8]/input", "xpath"),
						
	ENTERORDERQTY1CLICK(".//*[@id='resultsroEditGrid']/div[6]/div/div/div[1]/div[8]", "xpath"),
	ENTERORDERQTY1(".//*[@id='resultsroEditGrid']/div[6]/div/div/div[1]/div[8]/input", "xpath"),
	ENTERORDERQTY2CLICK("//*[@id='resultsroEditGrid']/div[5]/div/div[2]/div[8]", "xpath"),
	ENTERORDERQTY2("//*[@id='resultsroEditGrid']/div[5]/div/div[2]/div[8]/input", "xpath"),
	APPLYCHANGES("Apply Changes", "linkText"),
	APPLYCHANGES1("//*[@id='regOrdersCreateWrapper']/div[15]/a[1]","xpath"),
	REQ_ORDER_NO("//*[@id='regStatusContainer']/div[1]", "xpath"),
	CONFIRMCONTINUE("//*[@id='confirmChangesAlert']/div[2]/a[1]", "xpath"),
	SEARCHEXISTINGORDER("//*[@id='searchExistingOrder']/li/div", "xpath"),
	DELICON("//*[@id='resultsReqO']/table/tbody/tr/td[2]/span/a", "xpath"),
			FIRSTROW(".//*[@id='resultsReqO']/table/tbody/tr/td[3]", "xpath"),
	DELICON2("//*[@id='resultsReqO']/table/tbody/tr[1]/td[2]/span/a", "xpath"),
			DELETEICON3("//*[@id='resultsReqO']/table/tbody/tr/td[2]/span/a", "xpath"),
	DELCONFIRMCONTINUE("//*[@id='removeAlert']/div[3]/a[1]", "xpath"),
	POPUP_DELETE_CANCEL("//*[@id='removeAlert']/div[3]/a[2]","xpath"),
	SEARCHNODATADISPLAY("//*[@id='resultsReqO']/table/tbody/tr/td", "xpath"),
	SEARCHEXISTINGORDERBACK("//*[@id='searchExistingOrder']", "xpath"),
	SEARCHFROMSTORESFIRSTROW(".//*[@id='resultsReqO']/table/tbody/tr[1]/td[3]", "xpath"),
	GENERATEORDER("//*[@id='generateOrder']", "xpath"),
	GENERATEORDERCONTINUE("//*[@id='generateRO']", "xpath"),
	GENERATEORDDERCLOSE("//*[@id='closeInfoWindow']", "xpath"),
	CANCELLED("//*[@id='resultsReqO']/table/tbody/tr[1]/td[10]", "xpath"),
	CANCELLED2("//*[@id='resultsReqO']/table/tbody/tr/td[11]", "xpath"),
	BACKTOSEARCH("//*[@id='contentHeader']/div[3]/a", "xpath"),
	SEARCHRESULT_LABLE(".//*[@id='gridWrapper']/div[1]/div[2]","xpath"),
	REQUISITIONORDER_LABEL(".//*[@id='orderFormHeader']/div[1]","xpath"),
	ORDERSTATUS_LABLE(".//*[@id='regStatusContainer']/div[1]/span[@class='orderState']","xpath"),
	FORM_NAME(".//*[@id='results']/table/tbody/tr[1]/td[1]","xpath"),
	SEARCHBAR(".//*[@id='articlesearchForm']","xpath"),
	SEARCHRESULT_FIRSTROW_FIRSTCOL(".//*[@id='results']/table/tbody/tr/td[1]","xpath"),
	FIRSTROW_LASTCOL(".//*[@id='results']/table/tbody/tr[1]/td[3]","xpath"),
	CREATE_ORDER_ICON(".//*[@id='results']/table/tbody/tr[1]/td[4]/span/a","xpath"),
	CANCEL(".//*[@id='regOrdersCreateWrapper']/div[12]/a[1]","xpath"),
	POPUP_CANCEL("//*[@id='removeAlert']/div[3]/a[2]","xpath"),
	POPUP_CONTINUE("//*[@id='removeAlert']/div[3]/a[1]","xpath"),
	READARTICLE("ReadArticles","id"),
	ADD_ARTICLE_BUTTON("//*[@id='regOrdersCreateWrapper']/div[10]/div[2]/span[2]/a","xpath"),
	GRID_FIRSTARTICLE("//*[@id='addArticles']/table/tbody/tr/td[1]/div/label/span","xpath"),
	GRID_TITLE(".//*[@id='orderFormHeader']/div[1]","xpath"),
	ADD_SELECTED(".//*[@id='addArticlesWrapper']/div[1]/div[2]/a","xpath"),
	REMOVE_SELECTED("Remove Selected","linkText"),
	GRID_CHECKBOX(".//*[@id='resultsroEditGrid']//div[@class='ui-state-default slick-header-column' and @title='Select/Deselect All']","xpath"),
	GRID_FIRSTARTICLENAME("//*[@id='resultsroEditGrid']/div[6]/div/div/div/div[2]","xpath"),
	ORDER_QTY("//*[@id='resultsroEditGrid']/div[6]/div/div/div/div[7]","xpath"),
	ORDER_QTY_INPUT("//*[@id='resultsroEditGrid']/div[6]/div/div/div/div[7]/input","xpath"),
	CLOSE_BUTTON(".//*[@id='addArticlesWrapper']/div[1]/div[3]/a","xpath"),
	ADD_GRID(".//*[@id='addArticlesWrapper']","xpath"),
	ORDER_STATUS(".//*[@id='regStatusContainer']/div[2]/span","xpath"),
	DELIVERYDATE(".//*[@id='ExpectedDeliveryDate']","xpath"),
	DELIVERYTIME_ICON(".//span[@class='k-select' and @aria-controls='ExpectedDeliveryTime_timeview']","xpath"),
	DELIVERYTIME(".//*[@id='ExpectedDeliveryTime']","xpath"),
	REASON(".//*[@id='OrderReason']","xpath"),
	FLIGHTNUMBER(".//*[@id='FlightNumber']","xpath"),
	DELIVERYDATE_POPUP(".//*[@id='details']/div/div[8]/span","xpath"),
	DELIVERYTIME_POPUP(".//*[@id='details']/div/div[9]/span","xpath"),
	REASON_POPUP(".//*[@id='details']/div/div[12]/div/span","xpath"),
	FLIGHTNUMBER_POPUP(".//*[@id='details']/div/div[10]/div/span","xpath"),
	GENERATE_POPUP_CANCEL(".//*[@id='generateOrderContainer']/a[1]","xpath"),
	GENERATE_POPUP_CONTINUE(".//*[@id='generateOrderContainer']/a[2]","xpath"),
	POPUP_TITLE(".//*[@id='requisitionOrderInfo_wnd_title']","xpath"),
	POPUP_CLOSE(".//*[@id='closeInfoWindow']","xpath"),
	VIEW_ORDER_INFO_BTN("View Order Information","linkText"),
	BACKTOSEARCH_BUTTON("Back to Search","linkText"),
	GRIDROW(".//*[@id='results']/table/tbody/tr[2]/td[3]","xpath"),
	IRO_HEADING(".//*[@id='regStatusContainer']/div[1]","xpath"),
	GRID_DATE_COL("//*[@id='resultsReqO']/table/tbody/tr/td[7]/div","xpath"),
	GRID_TIME_COL("//*[@id='resultsReqO']/table/tbody/tr/td[8]/div","xpath"),
	DROPDOWN("k-select","className"),
	FIRST_ROW_FIRST_COL("//*[@id='resultsReqO']/table/tbody/tr[1]/td[3]/span","xpath"),
	DATA_TO_SEARCH("//*[@id='resultsReqO']/table/tbody/tr[6]/td[3]/span","xpath"),
	SELECTALL_CHECKBOX(".//th[@class='k-header']//label[@for='checkAll']","xpath"),
	CANCEL_SELECTED("Cancel Selected","linkText"),
	CANCEL_SELECTED_POPUP(".//*[@id='batchCancel_wnd_title']","xpath"),
	DO_NOT_CANCEL(".//*[@id='batchcancelClose']","xpath"),
	CONTINUE(".//*[@id='cancelOk']","xpath"),
	SEARCHRESULT_CHECKBOX_COL("//*[@id='resultsReqO']/table/tbody/tr/td[1]/div/label/span","xpath"),
	DELETE_ICON(".//*[@id='results']/table/tbody/tr/td[1]/div/span/a","xpath"),
	POP_UP_TITLE(".//*[@id='removeAlert']/div[1]","xpath"),
	POP_UP_CANCEL("Cancel","linkText"),
	POP_UP_CONTINUE("Continue","linkText"),
	NO_DATA_TO_DIPLAY("//*[@id='resultsReqO']/table/tbody/tr/td","xpath"),
	CANCEL_SUBMITTED("X","linkText"),
	MENU("//*[@id='nav']/li/div","xpath"),
	MENU_OPTION(".//*[@id='nav']/li/ul/li/a","xpath"),
	SELECT_ALL(".//div[@class='checkBoxStyle']","xpath"),
	POP_UP_CANCEL_BTN(".//*[@id='windowClose']","xpath"),
	OK("OK","linkText"),
	REQUISITION_FORM_NAME("//*[@id='requisitionOrderformName']","xpath"),
	GRID_FIRSTARTICLENAME1("//*[@id='addArticles']/table/tbody/tr/td[3]/span","xpath"),
	SEARCH_EXISTING(".//*[@id='searchExistingOrder']","xpath"),
	POPUP_TEXT(".//*[@id='removeAlert']/div[1]","xpath"),
	REQUITION_HEADER_TITLE("//*[@id='poSearchContent']/div[1]/div[1]", "xpath"),
	SAVE_REQUISITION_FORM("//*[@id='nav']/li/ul/li[1]/a", "xpath"),
	SAVE_REQ_FORM_OK_BTN("//*[@id='requisitionOrderformNameOK']", "xpath"),
	ORDERFORM_CREATEORDER_ICON("//*[@id='results']/table/tbody/tr[1]/td[4]/span[1]/a", "xpath"),
	CREATEORDER_CANCELBTN("//*[@id='regOrdersCreateWrapper']/div[14]/a[1]", "xpath"),
	GRID_CHECKBOX2("//*[@id='checkSelBox00']", "xpath"),
	SAVE_ICON("//*[@id='applyChanges']", "xpath"),
	ORDERQTY_CLICK("//*[@id='resultsroEditGrid']/div[6]/div/div/div/div[8]", "xpath"),
	QRDERQTY_INPUT("//*[@id='resultsroEditGrid']/div[6]/div/div/div/div[8]/input", "xpath"),
	REMOVE_SELECTED2("//*[@id='regOrdersCreateWrapper']/div[10]/div[2]/span[1]/a", "xpath"),
	GRID_ARTNAME("//*[@id='resultsroEditGrid']/div[6]/div/div/div/div[3]", "xpath"),
	PAGE_TITLE("//*[@id='contentHeader']/div[1]/h1", "xpath"),
	GRID_ROW2("//*[@id='resultsReqO']/table/tbody/tr[1]/td[3]/span", "xpath"),
	ORDER_NO("//*[@id='regStatusContainer']/div[1]/span", "xpath"),
	;
	
	public String element, identifier;
	private StoresRequisitionOrderEnums(String element){
		 this.element = element;
	 }
	private StoresRequisitionOrderEnums(String element, String identifier){
		 this.element = element;
		 this.identifier = identifier;
	 }
	public String getElementPath(){
		return element;
	}
	public String getElementIdentifier(){
		return identifier;
	}

}
