package com.sacs.PageOjects;

public enum SystemUserMaintenanceEnum {
	SYSTEM("system","id"),
	USERMAINTENANCE("//*[@id='usermaintenance']/a","xpath"),
	PAGE_TITLE("//*[@id='contentHeader']/div[1]/h1","xpath"),
	ADDUSER("//*[@id='addNew']", "xpath"),
	SEARCHBOX("//*[@id='articlesearch']", "xpath"),
	SEARCHICON("//*[@id='searchContainer']/div[1]/span[2]/a/img", "xpath"),
	SEARCHRECORD("//*[@id='results']/table/tbody/tr/td[1]", "xpath"),
	DOMAIN("//*[@id='Domain']", "xpath"),
	USER("//*[@id='UserId']", "xpath"),
	FIRSTNAME("//*[@id='FirstName']", "xpath"),
	LASTNAME("//*[@id='LastName']", "xpath"),
	EMAILADDRESS("//*[@id='EmailAddress']", "xpath"),
	MANAGEUNITS("//*[@id='manageUnits']", "xpath"),
	LINKSTOUNIT_CHKBOX("//*[@id='linkToUnitsGrid']/div/div/div/div/span/input", "xpath"),
	CONTINUE_BTN("//*[@id='continueButton']", "xpath"),
	OK_BTN("//*[@id='umForm']/div/div[5]/a", "xpath"),
	DEFAULTUNIT("//*[@id='DefaultUnitId']", "xpath"),
	REMOVE_ICON("//*[@id='nav']/li[1]/a/div", "xpath"),
	REMOVEUSER_CONTINUE("//*[@id='loadingModal']/div[2]/a[2]", "xpath"),
	REMOVEUSER_CANCEL("//*[@id='loadingModal']/div[2]/a[1]", "xpath"),
	NODATATODISPLAY("//*[@id='results']/table/tbody/tr/td", "xpath"),
	SEARCH_GRID("//*[@id='results']/table", "xpath"),
	SHOWENTRIES("//*[@id='gridWrapper']/div[1]/div[3]/span/span[1]/span[1]", "xpath"),
	PAGINATION_CONTROLS("//*[@id='gridWrapper']/div[3]/div", "xpath"),
	SHOW_ENTRY_DROPDOWN("//*[@id='gridWrapper']/div[1]/div[3]/span/span[1]/span[1]", "xpath"),
	SEARCHEDEMAILRECORD("//*[@id='results']/table/tbody/tr/td[2]", "xpath"),
	EMAILFIRSTROW("//*[@id='results']/table/tbody/tr[1]/td[2]", "xpath"),
	REGIONFIRSTROW("//*[@id='results']/table/tbody/tr[1]/td[3]", "xpath"),
	LANGUAGE_DD("//*[@id='Language']", "xpath"),
	CULTURE_DD("//*[@id='Culture']", "xpath"),
	TIMEZONE_DD("//*[@id='TimeZone']", "xpath"),
	MANAGEUNIT_TITLE("//*[@id='linkToUnitsModal_wnd_title']", "xpath"),
	LINKUNITS_CANCELBTN("//*[@id='cancelButton']", "xpath"),
	LINKUNITS_CONTINUEBTN("//*[@id='continueButton']", "xpath"),
	LINKTOUNIT_TEXTBOX("//*[@id='LinkedToUnits']", "xpath"),
	EDITUSERICON("//*[@id='results']/table/tbody/tr[1]/td[4]/span[1]/a", "xpath"),
	USERNAME_FIRSTROW("//*[@id='results']/table/tbody/tr[1]/td[1]", "xpath"),
	MANAGEROLES("//*[@id='mangeroles']", "xpath"),
	ROLES_TEXT("//*[@id='UserMaintenanceWrapper']/div[5]/div[1]/div[1]/span[1]", "xpath"),
	MANAGEROLE_ICON("//*[@id='results']/table/tbody/tr/td[4]/span[3]/a", "xpath"),
	SETROLESFORUNIT("//*[@id='UnitId']", "xpath"),
	ASSIGNROLES("//*[@id='UserMaintenanceWrapper']/div[5]/div[1]/div[1]/span[2]/a", "xpath"),
	ASSIGNROLES_POPUP("//*[@id='gridRoles_wnd_title']", "xpath"),
	ASSIGNROLESPOPUP_CANCELBTN("//*[@id='gridRoles']/div[3]/a[1]", "xpath"),
	ASSIGNROLESPOPUP_CONTINUEBTN("//*[@id='gridRoles']/div[3]/a[2]", "xpath"),
	FIRSTROLE_CHKBOX("//*[@id='checkSelBox00']", "xpath"),
	ROLENAME_FIRSTROW("//*[@id='gridResults']/div[6]/div/div/div[1]/div[2]", "xpath"),
	ROLEADDED("//*[@id='userRoles']/ul/li/div/span[2]", "xpath"),
	EXPANDALL("//*[@id='UserMaintenanceWrapper']/div[5]/div[1]/div[2]/a[1]", "xpath"),
	COLLAPSEALL("//*[@id='UserMaintenanceWrapper']/div[5]/div[1]/div[2]/a[2]", "xpath"),
	EXPANDICON("//*[@id='userRoles']/ul/li/div/span[1]", "xpath"),
	USERSYMBOL("//*[@id='userRoles']/ul/li/div/span[2]/span[1]", "xpath"),
	CALENDERICON("//*[@id='userRoles']/ul/li/div/span[2]/span[2]", "xpath"),
	REMOVEICON("//*[@id='userRoles']/ul/li/div/span[2]/span[3]", "xpath"),
	SECONDROLE_CHKBOX("//*[@id='checkSelBox10']", "xpath"),
	ROLENAME_SECONDROW("//*[@id='gridResults']/div[6]/div/div/div[2]/div[2]", "xpath"),
	SECOND_ROLEADDED("//*[@id='userRoles']/ul/li[2]/div/span[2]", "xpath"),
	SECONDROLE_REMOVEICON("//*[@id='userRoles']/ul/li[2]/div/span[2]/span[3]", "xpath"),
	REMOVEPOPUP_CONTINUEBTN("//*[@id='userUpdates']/div[3]/a[2]", "xpath"),
	SUBMODULE("//*[@id='userRoles']/ul/li/ul/li[1]/div/span[2]", "xpath"),
	SETROLEENDDATE_POPUP("//*[@id='userUpdates_wnd_title']", "xpath"),
	SETROLEENDDATE_CANCELBTN("//*[@id='userUpdates']/div[3]/a[1]", "xpath"),
	SETROLEENDDATE_CONTINUEBTN("//*[@id='userUpdates']/div[3]/a[2]", "xpath"),
	ROLEENDDATE("//*[@id='roleEndDate']", "xpath"),
	EXCLUDETASKICON("//*[@id='4 _3']", "xpath"),
	ADDEXCLUSION_POPUPTITLE("//*[@id='loadingModal_wnd_title']", "xpath"),
	ADDEXCLUSION_POPUP_CANCELBTN("//*[@id='loadingModal']/div[2]/a[1]", "xpath"),
	ADDEXCLUSION_POPUP_CONTINUEBTN("//*[@id='loadingModal']/div[2]/a[2]", "xpath"),
	SUPERUSER_CHK("//*[@id='checkSelBox290']", "xpath"),
	SUPERUSER_CHKTEXT("//*[@id='gridResults']/div[6]/div/div/div[18]/div[2]", "xpath"),
	ROLEPOPUP_THIRDCOL("//*[@id='gridResults']/div[6]/div/div/div[8]/div[3]", "xpath"),
	SUPERUSER_ALLMODULES("//*[@id='userRoles']/ul/li/ul/li/div/span[2]", "xpath"),
	SUPERUSER_ALLSUBMODULES("//*[@id='userRoles']/ul/li/ul/li/ul/li/div/span[2]", "xpath"),
	SUPERUSER_ALLTASKS("//*[@id='userRoles']/ul/li/ul/li/ul/li/ul/li/div/span", "xpath"),
	COPYROLESTONEWUSER_ICON("//*[@id='nav']/li[4]/a/div", "xpath"),
	COPYALERT_TITLE("//*[@id='copyAlert_wnd_title']", "xpath"),
	COPYALERT_CANCELBTN("//*[@id='copyAlert']/div[5]/a[1]", "xpath"),
	COPYICON_SEARCHGRID("//*[@id='results']/table/tbody/tr/td[4]/span[2]/a", "xpath"),
	COPYALERT_CONTINUEBTN("//*[@id='copyAlert']/div[5]/a[2]", "xpath"),
	COPYROLESTONEWUSER_TITLE("//*[@id='copyUser']/div[1]/div/div[1]", "xpath"),
	SELECTUNIT_CONTINUEBTN("//*[@id='linkToUnitsModal']/div[2]/a[2]", "xpath"),
	COPYUSER_DEFAULTUNIT("//*[@id='DefaultUnit']", "xpath"),
	COPYUSER_OKBTN("//*[@id='umCopyForm']/div/div[5]/a", "xpath"),
	MENU("//*[@id='nav']/li[1]/div", "xpath"),
	MENU_OPTION1("//*[@id='nav']/li[1]/ul/li[1]/a", "xpath"),
	SETCUL_LAN_TIME_POPUPTITLE("//*[@id='userSect_wnd_title']", "xpath"),
	SETCUL_LAN_TIME_CANCELBTN("//*[@id='cultForm']/div[2]/a[1]", "xpath"),
	SCLT_LANGUAGE_DD("//*[@id='cultForm']/div/div[1]/span[2]/span/select", "xpath"),
	SCLT_CULTURE_DD("//*[@id='cultForm']/div/div[2]/span[2]/span/select", "xpath"),
	SCLT_TIMEZONE_DD("//*[@id='cultForm']/div/div[3]/span[2]/span/select", "xpath"),
	SETCUL_LAN_TIME_CONTINUEBTN("//*[@id='cultForm']/div[2]/a[2]", "xpath"),
	MENUOPTION_2("//*[@id='nav']/li[1]/ul/li[2]/a", "xpath"),
	COPYROLESTOUNITS_TITLE("//*[@id='gridUnits_wnd_title']", "xpath"),
	COPYROLETOUNIT_CANCELBTN("//*[@id='gridUnits']/div[4]/a[1]", "xpath"),
	COPYROLETOUNIT_CONTINUEBTN("//*[@id='gridUnits']/div[4]/a[2]", "xpath"),
	COPYROLETOUNIT_UNITCHKBOX("//*[@id='Results']/table/thead/tr/th[1]/div/label/span", "xpath"),
	MENUOPTION_3("//*[@id='nav']/li[1]/ul/li[3]/a", "xpath"),
	COPYUSERACCESS_TITLE("//*[@id='copyAccessUser_wnd_title']", "xpath"),
	COPYUSERACCESS_CANCELBTN("//*[@id='copyAccessUser']/div[6]/a[1]", "xpath"),
	COPYUSERACCESS_SEARCHICON("//*[@id='copyAccessUser']/div[2]/div[1]/span[2]/a/img", "xpath"),
	COPYUSERACCESS_SEARCHRECORD("//*[@id='userResults']/table/tbody/tr/td[1]", "xpath"),
	COPYUSERACCESS_CONTINUEBTN("//*[@id='copyAccessUser']/div[6]/a[2]", "xpath"),
	REMOVEICON_SEARCHGRID("//*[@id='results']/table/tbody/tr/td[4]/span[4]/a", "xpath"),
	;
	
	
	public String element,Identifier;
	private SystemUserMaintenanceEnum(String element){
		 this.element = element;
	 }
	private SystemUserMaintenanceEnum(String element, String Identifier){
		 this.element = element;
		 this.Identifier = Identifier;
	 }
	public String getElementPath(){
		return element;
	}
	public String getElementIdentifier(){
		return Identifier;
	}
}
