package com.sacs.funUtils;

public interface SACSSetup {
		 String SBROWSER="chrome";
	    // String SURL="https://sacsqa.gategroup.com/sacsqaemea/";
	     //String SURL="https://sacsuat.gategroup.com/sacsuatemea/";
	     String SURL="https://sacsqa.gategroup.com/sacsqaemea/";
	     String mainurl="https://azu0sacfs05p.emea.gg.group/sacs6/";
		 String SUSERNAME="USERNAME";
		 String SPASSWORD="PASSWORD";
		 String SCOUNTRYLEVEL="UK-MASTER ";
		 String SCOUNTRYCODE="UK-LBA 3298";
		 String SMAINSTORE="1 - MAIN/AMBIENT";
		 String SUNITID="";
		 String SSUITENAME="testng.xml";
		 String SPROJECT="SACS";
		 String SHTMLREPORTPATH="/Reports";
		 String screenSnapsPath="";
		 String sCUSTOMERCODE="AF - AIR FRANCE";
		 String CHROMEPATH ="/src/test/resources/BrowserBinaries/Chrome/chromedriver.exe"; 
		// String CHROMEPATHCIRCLECI="/usr/local/bin/chromedriver";
		 int LABEL=1,BUTTON=2,A=3,H4=4,SPAN=5,DIV=6,STAR=7,XPATH=8;
		 String sRandomData="YES";
		 String sEnvironment="Automation";
		 String seleniumjar="3.0.1";
		 String defaultEmailID="rohith.kakumani@compugain.com";
		 String stestcasefile = "/testng.xml";
		 String grid ="";
		 String sEMAILCONFIG="/src/main/resources/EmailConfig/EmailConfiguration.properties";
		 String sSOURCE_REPORTSFOLDER="/test-output/html";
		 String sOUTPUT_ZIP_FILE_REPORTS = "/BackupReports";
		 String sOUTPUT_ZIP_FILE = sOUTPUT_ZIP_FILE_REPORTS +"/SACS_AutomationReports.txt";
		 String FAILEDCASES="/src/test/resources/FailedCases.csv";
		 String PASSEDCASES="/src/test/resources/PassedCases.csv";
		 String SKIPPEDCASES="/src/test/resources/SkippedCases.csv";
		 String sPIECHARTLOCATION="/src/test/resources/ExecutionReport.jpeg";
		 String sXMLFILE="";
		 String DOWNLOADSPATH="/src/test/Downloads";
		 String IEPATH = "/src/test/resources/Browsers_Binaries/IE/IEDriverServer32.exe";
		 String FIREFOXPATH ="/src/test/resources/Browsers_Binaries/Firefox/geckodriver.exe"; 
		 String EXECUTIONSTATUS="/src/test/resources/ExecutionStatus.csv";
		 String sUPLOADDOCUMENTFILE="/src/test/resources/Documents/sacs.JPG";
		 String SCHROMETASKKILL="/src/test/resources/Taskkill/Chrome Driver.bat";
		String testcasefile = "/SACS_UIAutomation";
		String EMAILCONFIG="/src/main/resources/EmailConfig/EmailConfiguration.properties";
}
