package com.sacs.utils;


public enum ElementNamesEnum {
	
	// Australia Data
	MAIN_STORE_CODE_VALUE("1 - FOOD STORES"),
	MAIN_STORE_CODE_ZERO("0 - PRODUCTION AREA"),
	BASIC_ARTICLE_DEPARTMENT_VALUE("B-COLD KITCHEN"),
	CURRENCY_CODE_VALUE("AUD - AUSTRALIAN DOLLAR"),
	ARTICLEGROUP_FINANCE_PRODUCT_VALUE("400007 - Dairy products"),
	ARTICLEGROUP_COST_CENTER_VALUE("340 - PURCHASE PRICE VAR"),
	ARTICLEGROUP_CCP1_BEHAVIOUR_VALUE("1 - Always use CCP1"),
	DROPDOWN("dropdown"),
	SELECTPRICEAGREEDD("Select Price Agreement Drop Down"),
	INPUTFIELD("input"),
	MAIN_STORE_CODE_TEST("DUC"),
	COST_CENTER_VALUE("100000"),
	VENDOR_NAME_FOR_ADDRESS("Vendor Name"),
	DEFAULT_PRODUCT_ID("118000"),
	DEFAULT_COMBINED_CLASS("AS"),
	BOUNDED_ARTICLE_GROUP("DIM SUM"),
	POR("Purchase Order Registration"),
	VENDORS("Vendors"),
	ADDVENDOR("Add Vendor"),
	ADDVENDORLINK("Add Vendor Link"),
	APPLYCHANGES("Apply Changes"),
	TBGRID("Truck and Bay Grid"),
	ERRORICON("Error Icon"),
	ERRORTEXT("Error Text"),
	BACKTOSEARCH("Back To Search"),
	VENDORSEARCHFIELD("Search Field"),
	SEARCHRECORD("Search Record"),
	REMOVEVENDORLINK("Remove Vendor Link"),
	DELDAYS("Aircraft Delete Days"),
	DELPOPUPTEXT("Delete Pop Up Text"),
	CPYPOPUPTEXT("Copy Pop Up Text"),
	REMOVEVENDOR_POPUP("Remove Vendor Popup"),
	CONTINUE("Continue"),
	SEARCHORDERBYVENDOR("Search Order By Vendor"),
	LINK_TO_SELECT("Link To Select"),
	VENDORNAME("Vendor Name"),
	VENDORACCOUNTNAME("Vendor Account Name"),
	EDITVENDORLINK("Edit Vendor Link"),
	ACCOUNTOWNER("Account Owner"),
	ORDERDESC("Order Description"),
	COUSTOMER("Customer"),
	PAYMENTDAYS("Payment Days"),
	VATCODE("Vat Code"),
	LOGOUTSETTINGS("Logout Setting Link"),
	SETTINGICON("Settings Icon"),
	SEARCHSUBMIT("Search Submit"),
	SEARCHVALUE("Search Value"),
	SEARCH_DD("Search Down Arrow"),
	LOGOUT("Logout"),
	EDITAGREEMENTICON("Edit Agreement Icon"),
	GRIDNEXTLINK("Next"), ITEMSPERPAGE("Items Per Page"),
	REGADDNUMPOPUP("Add Registration Number Popup"),
	REGNUMLIST("Registration Number List"),
	PURCHASE("Purchase"),
	SEARCHGRIDFIRSTROW("Search Grid First Row"), LOGIN("Login"), BATCHCONTROL("Batch Control"),
	SEARCHFILTER("Search Filter"), VENDORID("Vendor Id"), GRIDVENDORID("Grid Vendor Id Heading"),
	SEARCHFILTER_DROPDOWN("Search Filter Dropdown"),
	GRIDVENDORNAME("Grid Vendor Name Heading"), GRIDFIRSTROW("Grid First Row"),
	AGREEMENTDETAILSTXT("Agreement Details Text"),
	SEARCHALLORDERS("Search All Existing Order"),
	VIEWLINK("View Link"),
	WHERELOADRATIOUSED("Where Is Load Ratio Used"),
	COPYEFFECTIVEDATE("Copy Effective Date"),
	INCEDENTDESCTEXT("Incident Description"),
	COPYVENDORLINK("Copy Vendor Link"), CANCEL("Cancel"),
	SEARCHORDER("Search Order"),
	FIRSTROWTEXT("First Row Text"),
	SECONDROWTEXT("Second Row Text"),
	STARTDATELABEL("Start Date Label"),
	VIEWLOADRATIO("View Load Ratio"),
	ATTACHETOINCIDENT("Attach To Incident"),
	GRIDPREVIOUSLINK("Previous"), GRIDLASTLINK("Last Page"),
	GRIDFIRSTPAGE("First Page"), VENDORREBATE("Rebate"), PAGENATION("PagiNation Div"),
	TOASTMSG("Toast Message"), ADDVENDORTTILE("Add Vendor Title"), AREACODE("Area/Category"),
	VENDORSTITLE("Vendors Title"), SHOWENTRIES("Show Entries Div"), COPYVENDORTITLE("Copy Vendor Popup Title"), 
	REMOVEVENDORTITLE("Remove Vendor Popup Title"), LOGINSUBMIT("Login Submit"), 
	NOELEMENTSTODISPLAY("No data to display"),
	TOTALPAGEENTRIES("Total Page Entries"), SEARCHFILTER_VENDORID("Vendor Id"),
	SEARCHFILTER_VENDORNAME("Vendor Name"), USERNAME("User Name"),
	LOGINERRORMSG("Login Error Message"), ARTICLENUMBER("Article Number"),
	HOMEPAGE("Home Page"), VENDORSGRID("Vendor Grid"),
	LOGINPAGE("Login Page"),
	ADDVENDORPAGE("Add Vendor Page"),
	SEARCHRESULT("Search Results"),
	UPDATEVENDORPAGE("Update Vendor Page"),
	VENDORSEARCHPAGE("Vendor Search Page"),
	NEXTPAGE("Grid Next Page"),
	PREVIOUSPAGE("Grid Previous Page"),
	PAGELINK("Page Link"),
	LASTPAGE("Grid Last Page"),
	CLASSDESC("Class Description"),
	CONFIGDESC("Config Description"),
	FIRSTPAGE("Grid First Page"), UPDATEVENDORSTITLE("Update Vendor"),
	WORKIGNUNIT("Working Unit"), LANDINGPAGE_TITLE("Home Page Title"),
	WORKCENTER("Work Center"),
	SYSTEM_MENUITEM("System"), SYSTEM_ARTICALGROUPS("Article Groups"), 
	ARTICLEGROUP_SEARCHPAGE("Article Groups Search Page"), 
	SYSTEM_ADD_ARTICLEGROUP("Add Article Group"), 
	SYS_ADDARTICLEGROUP_PAGETITLE("Add Article Group"),  
	ORD_DESC_ERROR_MSG("Order Description Error Message"),
	VENDORADDRESS("Vendor Address"),
	VENDORCONTACTS("Vendor Contacts"),
	REMOVEVENDOR("Remove Vendor"),
	COPYVENDOR("Copy Vendor"),
	VENDOR_CONTRACT_START_DATE("Vendor Contract Start Date"),
	VENDOR_CONTRACT_END_DATE("Vendor Contract End Date"),
	ARTICLEGROUP("Article Group"), 
	ARTICLEGROUPDESC("Article Group Description"),
	PAYMENTTERMS("Payment Terms"),
	CURRENCYCODE("Currency Code"),
	ACCOUNTNUMBER("Account Number"),
	FINANCE_SYS_ID("Finance System Id"), 
	NOTES_ID("Vendor Notes"), 
	LAST_AUDIT_DATE("Last Audit Date"), 
	AUDIT_BY_ID("Audit By"), AUDIT_COMMENTS("Audit Comments"),
	VIEWINCIDENT("View Incidents Link"),
	
	MATERIALMGMT("Material Management"),
	UPDATEARTICLETITLE("Update Article Group"),
	ARTICLEGRID("Article Grid"),
	ARTICLEGROUPID("Article Group ID"),
	FINANCEPRODUCTID("Finace Product ID"),
	COSTCENTER("Cost Center"),
	NONMATERIALCOST("Non Material Cost"), 
	RESTITUTION("Restitution"),
	INFLATIONRATE("Inflation Rate"), 
	CPP1BEHAVIOUR("CCP1 behaviour"), 
	CONNECTED_PANEL("Connected Panel"),
	CONNECTEDBASICARTICLES("Connected Basic Articles Panel"),
	MENU("Menu"), 
	WHERECSPUSED("Where CSP Used"),
	REPLACE_GROUP_ARTICLE("Replace Group in Article"), 
	REMOVE("Remove Icon"), CONFIRMATION_POPUP("Confirmation Popup"), 
	MENU_NAV_ARROW("Back to Menu Items"), 
	BASICARTICLE("Basic Articles"),
	UPDATEBASICARTICLE("Update Basic Article"), 
	RESTITUTION_UOM("Restitution UOM"),
	RESTITUTION_NUMBER("Restitution Number"),
	REFUND("Refund"),
	COUNTRY_OF_ORIGIN("Country of Origin"),
	EXCISE_DUTY_NUMBER("Excise Duty Number"),
	TAX_CODE("Tax Code"),
	EXCISE_DUTY_RATE("Excise Duty Rate"), RESTITUTION_GROUP("Restitution Group"), 
	CONNECTEDPANEL("Connected Panel"),
	RESTITUTION_GROUP_PAGE("Restitution Group Page"),
	UPDATE_RESTITUTION_ORDER_PAGE("Update Restitution Group Page"),
	RESTITUTION_REMOVAL_POP_TITLE("Restitution Group Remove Popup"),
	
	
	/** Purchase Vendor Address */
	BIILINGADDRESS_TITLE("Billing Address"),
	VENDORADDRESS_PAGE("Vendor Address Page"),
	BILLING_ADDRESS("Billing Address1"),
	BILLING_CITY("Billing City"),
	BILLING_STATE("Billing State"),
	BILLING_COUNTRY("Billing Country"),
	BILLING_ZIPCODE("Billing Zip Code"),
	
	ORDERING_ADDRESS("Ordering Address1"),
	ORDERING_CITY("Ordering City"),
	ORDERING_STATE("Ordering State"),
	ORDERING_COUNTRY("Ordering Country"),
	ORDERING_ZIPCODE("Ordering Zip Code"),
	
	RETURNS_ADDRESS("Returns Address1"),
	RETURNS_CITY("Returns City"),
	RETURNS_STATE("Returns State"),
	RETURNS_COUNTRY("Returns Country"),
	RETURNS_ZIPCODE("Returns Zip Code"),
	ORDERING_CHECKBOX("Ordering Checkbox"),
	RETURNS_CHECKBOX("Returns Checkbox"), 
	OK("OK"), COST_CENTER("Cost Center"),
	ADD_COST_CENTER("Add Cost Center"), 
	COST_CENTER_ID("Cost Center ID"),
	COST_CENTER_DESC("Cost Center Description"),
	ORDERNO("Order Number"),
	CANCELICON("Cancel Icon"),
	
	/** Loading Setup */
	
	ADDLINE("ADD Line"),
	PAX("PAX"),
	U_QTYPAX("Qty Pax"),
	FIXEDQTY("Fixed Qty"),
	ROUNDING("Rounding"),
	ROUNDINGDD("Rounding Drop Down"),
	FACTOR("Factor"),
	MAXQTY("MAX QTY"),
	MAXPAXQTY("Maximum Pax"),
	DELPLANSEARCHICON("Delivery Plan Search Icon"),
	AVSEARCHICON("A/C Version Search Icon"),
	ADD_LINE_CONTAINER("Add Line Container"),
	UPDATE_BUTTON("Update Button"), 
	WHERE_LOADING_SETUP_USED("Where Loading Setup Used"),
	
	
	/** Purchase Vendor Contacts page */
	VENDOR_CONTACTS_PAGE("Vendor Conatacts Page"),
	VENDOR_CONTACTS_BTN("Vendor Conatacts"),
	ADD_CONTACT_BTN("Add Contact"),
	SET_PREFERRED_PANEL("Set Preferred Panel"),
	SET_PREFERRED_PANEL_TEXT("Set Preferred Panel Text"),
	CONATCT_NAME("Name"),
	TELEPHONE("Telephone"),
	FAX_NO("Fax"),
	EMAIL("Email"),
	FAX_SEND_OREDERS("Fax Send Orders"),
	EMAIL_SEND_ORDERS("Email Send Orders"),
	ADD_CONTACT_POPUP("Add New Contact Pop up"),
	EDIT_CONTACT_POPUP("Edit Contact Pop up"),
	EDIT_CONTACT("Edit Contact"),
	REMOVE_CONTACT("Remove Contact"),
	BILLING("Billing"),
	ORDERING("Ordering"),
	RETURN("Return"),
	CANNOT_DELETE("Cannot Delete Contact"),
	REMOVE_CONTACT_TITLE("Remove Contact Title"), 
	
	/** Purchase Connect Basic Articles page */
	BASIC_ARICLES_LINK("Basic Articles Link"),
	BASIC_ARICLES_TITLE("Basic Articles Title"),
	BASIC_ARICLES_PAGE("Basic Articles Page"),
	UPDATE_BASIC_ARTILCE_TITLE("Update Basic Article Title"),
	UPDATE_BASIC_ARTILCE_PAGE("Update Basic Article Page"),
	ADD_NEW_VENDOR("Add Vendor"),
	SETASPRIMARY("Set As Primary"),
	ACTIVE("Active"),
	
	/** Menu- Replace vendor in articles */
	REPLACE_VENDOR_ARTICLE("Replace vendor in articles"), 
	
	/** Cost Center Connection To Vendor */
	COST_CENTER_PAGE("Cost Center Page"), 
	ADD_COST_CENTER_TITLE("Add Cost Center"), 
	SAP_COSTCENTER("SAP Cost Center"), 
	TOAST_CLOSE_BTN("Close Button"),
	USED_IN("Used in"), 
	UPDATE_COST_CENTER_TITLE("Update Cost Center"),
	UPDATE_COST_CENTER_PAGE("Update Cost Center Page"),
	
	POPTITLE("Pop Up Title"),
	STORECODE("Store Code"), 
	ADD_MAINSTORE_CODE("Add Mainstore Code"), 
	MAIN_STORE_CODE("Main Store Code"), 
	DESCRIPTION("Description"),
	DA("Description Head Arrow"),
	FLIGHTNUMBER("Flight Number"),
	CUSTOMERNO("Customer No"),
	CLOSING_DAY("Closing Day"), 
	REPLACE_SUBSTORE("Replace SubStore"),
	UPDATE_MAINSTORE_CODE("Update Mainstore Code"), UOM("UOM"), UNITOFMEASURE("Unit of Measure"), ADD_UOM_BTN("Add UOM"), 
	DEPARTMENT("Department"), ADD_DEPARTMENT("Add Department"), 
	CODE("Code"), UPDATE_DEPARTMENT("Update Department"), ADD_RESTITUTION_GROUP("Add Restitution Group"),
	UPDATE_RESTITUTION_GROUP("Update Restitution Group"),
	ADD("Add"),
	ACTIONTAKEN("Action Taken"),
	OUTCOME("Outcome"),
	SELECTARTICLE("Select Article"),
	/** Basic Articles */
	ADD_ARTICLE_BTN("Add Article"), 
	ADD_BASIC_ARTICLE_PAGE("Add Basic Article Page"),
	ARTICLE_GROUP("Article Group"),
	SELECTARTCLETABLE("Select Article Grid"),
	STORE_UOM("Store UOM"),
	PURCHASE_UOM("Purchase UOM"),
	PURCHASE_TO_STORE_UOM("Purchase To Store UOM"),
	MENU_UOM("Menu UOM"),
	GRID_FIRST_ROW_ARTICLE_NO_VALUE("Article Number"),
	GRID_FIRST_ROW_ARTICLE_NANE_VALUE("Article Name"),
	DEPARTMENT_GROUP("Department Group"),
	UPDATE_BASIC_ARTICLES_PAGE("Update Basic Article Page"),
	UPDATE_BASIC_ARTICLES_TITLE("Update Basic Article Title"),
	STORE_RESTITUTION_UOM("Store Restitution UOM"),
	REFOUND("Refound"), 
	ADD_SUB_STORE_BTN("Add Sub Store"),
	SUB_STORE_CODE("Sub Store Code"),
	COMMODITY_PERCENT("Commodity Percent"),
	MENU_TOOLBAR("Menu Bar"),
	REMOVE_ARTICLE("Remove Article Link"),
	EDIT_ARTICLE("Edit Article Link"),
	PRIMARY_VENDOR("Primary Vendor"),
	COPY_ARTICLE("Copy Article Link"),
	ARTICLE_NAME("Article Name"),
	SHOW_INACTIVE("Show Inactive"),
	VENDOR_ARTICLENUMBER("Vendor Article number"),
	BASIC_ARTICLE_NO("Basic Article Number"),
	BASIC_ARTICLE_NAME("Basic Article Name"),
	COPY_BASIC_ARTICLE_POPUP("Copy Basic Article Popup"),
	REMOVE_BASIC_ARTICLE_POPUP("Remove Basic Article Popup"),
	COPY_BASIC_ARTICLE_POPUP_HEADING("Copy Basic Article Popup Heading"),
	REMOVE_BASIC_ARTICLE_POPUP_HEADING("Remove Basic Article Popup Heading"),
	ACTIVE_CHK_BOX("Active"),
	TOASTCLOSE("Toast Close"),
	STORE_TO_RESTUOM("Store>Restitution UOM"),
	REORDER_TIME("Reorder Time"),
	LEAD_TIME("Lead Time"),
	SET_AS_PRIMARY("Set as Primary"),
	CUSTOMER_PRICE("Customer Price"),
	VENDOR_REBATE("Vendor Rebate"),
	ARTICLE_REBATE("Article Rebate"),
	FIXED_PRICE_REBATE("Fixed Price Rebate"),
	WY_FACTOR("W/Y-Factor"),
	COMMODITY_FIX_VALUE("Commodity Fix Value"),
	INFLATION_RATE("Inflation Rate"),
	DAY_PRICE("Day Price"),
	COPY_DAY_PRICE("Copy Day Price"),
	COPY_RESTITUTION_INFO("Copy Restitution Information"),
	MINIMUM_STOCK_LEVEL("Min Stock Level"),
	MAXIMUM_STOCK_LEVEL("Max Stock Level"),
	ARTICLE_OWNER("Article Owner"),
	STANDARD_PRICE("Standard Price"),
	UPLOAD_PHOTO_ICON("Upload Photo Icon"),
	ALLERGENS_ICON("Allergens Icon"),
	ALLERGENS_INFO("Allergens Information Page"),
	REPORTS_ICON("Reports Icon"),
	SUB_STORE_POSITION("Sub Store Position"),
	DESCRIPTION_2("Description 2"),
	CATEGORY("Category"),
	WYFACTOR("WY Factor"),
	SETINFLATIONVALUES("Set Inflation Values"),
	IMPORTWYFACTORINFLATION("Import W/Y-Factor & Inflation"),
	EDIT_ALLERGENS_BTN("Edit Allergens"),
	LIST_OF_ALLERGENS_GRID("List of Allergens"),
	ALLERGENS_INFO_TEXT("Allergens Information Text"),
	COPY_BASIC_ARTICLE_PAGE("Copy Basic Article Page"),
	IMAGE_UPLOAD_BTN("Image Upload Button"),
	UPLOAD_PDF_BTN("Upload PDF button"),
	IMAGE_DETAILS_NOTES("Image Details Text Area"),
	UPLOAD_BASIC_ARTICLE_IMG_POPUP("Upload Basic Article popup"),
	CHOOSE_BTN("Choose Button"),
	UPLOAD_BTN("Upload Button"),
	BASIC_ARTICLE_IMG("Basic Article Img"),
	UPLOAD_FILE("Upload File"),
	JPEG("C:\\Users\\Public\\Pictures\\Sample Pictures\\Tulips.jpg"),
	JPEG_1("C:\\Users\\Public\\Pictures\\Sample Pictures\\Chrysanthemum.jpg"),
	JPEG_2("C:\\Users\\Public\\Pictures\\Sample Pictures\\Desert.jpg"),
	JPEG_3("C:\\Users\\Public\\Pictures\\Sample Pictures\\Hydrangeas.jpg"),
	JPEG_4("C:\\Users\\Public\\Pictures\\Sample Pictures\\Jellyfish.jpg"),
	TEXT("C:\\Users\\Public\\Pictures\\Sample Pictures\\New_Text_Document.txt"),
	PDF("C:\\Users\\Public\\Pictures\\Sample Pictures\\PDF_Document.pdf"),
	REMOVE_IMAGE("Remove Image Link"),
	REMOVE_PDF("Remove PDF Link"),
	UPLOADED_PDF("Uploaded PDF file"),
	REMOVE_IMAGE_POPUP("Remove Image Popup"),
	REMOVE_PDF_POPUP("Remove PDF Popup"),
	UPLOADED_PDF_FILE("Uploaded PDF File"),
	
	
	
	/** Vendor Price Agreement */
	VENDOR_PRICE_AGREEMENT_LINK("Vendor Price Agreement"), 
	VENDOR_PRICE_AGREEMENT_PAGE("Vendor Price Agreement Page"),
	VENDOR_PRICE_AGREEMENT_TITLE("Vendor Price Agreement Title"),
	ADD_AGREEMENT_BTN("Add Agreement"),
	ADD_AGREEMENT_PAGE("Add Agreement Page"), 
	VALID_START_DATE("Valid Start Date"),
	VALID_END_DATE("Valid End Date"),
	STOPDATE("Stop Date"),
	FROMDATE("From Date"),
	LOGDATE("Log Date"),
	TODATE("To Date"),
	POPUPTEXT("Pop Up Text"),
	DEPARTUREDATE("Departure Date"),
	ADD_NEW_PRICE_AGREEMENT_DROPDOWN("Add New Price Agreement"),
	PRICE_TEXTBOX("Price TextBox"),
	 AGREEMENT_CODE("Agreement Code"),
	 COPYAGREEMENTICON("Copy Agreement Icon"),
	 NOTICETIME("Notice Time"),
	 REMOVEALLCHK("Select All Check Box"),
	
	/** Order Registration */
	ORDER_REGISTRATION_LINK("Order Registration"), 
	ORDER_REGISTRATION_PAGE("Order Registration Page"),
	ORDER_REGISTRATION_TITLE("Order Registration Title"), 
	CREATE_NEW_PURCHASE_ORDER_LINK("Create New Purchase Order"), 
	CREATE_ORDER("Create Order"), GET_ARTICLE("Get Articles"),
	GRID_ARTICLE_DESC_COLUMN_VALUE("Grid First Row"),
	ORDER_QUANTITY("Order Quantity"),
	SUBMIT_ORDER("Submit Order"),
	SELECTINGARTICLE("Selecting Article"),
	ARTNUMBER("Art Number"),
	SUBMIT_PURCHASE_ORDER_POPUP("Submit Order Popup"), 
	ORDER_RECEIPT_LINK("Order Receipt Link"), 
	STORE_CODES_PAGE("Store Codes Page"), 
	ADD_MAINSTORE_CODE_PAGE("Add Mainstore Code Page"), 
	OPEN_DATE("Open Date"),
	ADD_SUBSTORE_CODE_PAGE("Add Substore Code Page"), 
	ORDER_RECEIPT_PAGE("Order Receipt Page"),
	SEARCH_FOR_ORDER_BY_VENDOR_LINK("Search orders by vendor"), 
	DELIVERY_NOTE_NUMBER("Delivery Note Number"), 
	DELIVERYNOTE("Delivery Note"),
	EXPIRY_DATE("Expiry Date"), 
	ARTICLEINFOICON("Article Info Icon"),
	CORRECT_ORDER_BTN("Correct Order"),
	SUBMIT_ORDER_RECEIPT_POPUP("Submit Order Receipt Popup"), 
	SUBMIT_RECEIPT_BTN("Submit Receipt"), 
	SEARCH_ALL_EXISTING("Search all Existing"),
	ORDER_FORMS("Order Forms"), 
	ORDER_FORM_DETAILS_POP_UP("Order Form PopUp"),
	//PENDING("Pending Criteria"),
	//SUBMITTED("Submitted Criteria"),
	//CLOSED("Closed Criteria"),
	CANCELLED("Cancelled Criteria"),
	RECEIVED("Received Criteria"),
	APPROVED("Approved Criteria"),
	ORDER_NUMBER_CRITERIA("Order Number Criteria"),
	BASE_ORDER_ON_PURCHASE_ORDER_PROPOSAL("Base order on purchase order proposal check box"),
	CALCULATE_PROPOSAL_FROM("Calculate Proposal From Calender"),
	CALCULATE_PROPOSAL_TO("Calculate Proposal to Calender"),
	CONSIDER_PRODUCTION_DEAD_LINE("Consider production dead line check box"), 
	CONSIDER_NPT_REQUIREMENTS("Consider NPT Requirements check box"),
	ONLY_NPT_REQUIREMENTS("Only NPT Reqirements check box"),
	BACK("BACK"),
	CANCEL_SELECTED("Cancel Selected"),
	ARTICLE_NUMBER_HEADING("Article Number Heading"),
	VENDOR_ARTICLE_NUMBER_HEADING("Vendor Article Number Heading"),
	UOM_HEADING("UOM Heading"),
	PURC_UNIT_DAY_PRICE_HEADING("Purchase unit Day Price Heading"),
	ORDER_QTY_HEADING("Order Qty Heading"),
	TOTAL_AMT_HEADING("Total Amt Heading"),
	STOCK_LEVEL_HEADING("Stock Level Heading"),
	MIN_STOCK_LEVEL_HEADING("Min. Stock Level Heading"),
	SURPLUS_DAYS_HEADING("Surplus Days Heading"),
	ARTICLE_REBATE_HEADING("Article Rebate Heading"),
	VENDOR_REBATE_HEADING("Vendor Rebate Heading"),
	SAVE_ORDER_FORM_CONTAINER_POPUP("Save Order Form Contianer Pop Up"), 
	SAVE_ORDER_FORM_REPLACE_POPUP("Save Order Form Contianer Replace Pop Up"),
	SAVE_BUTTON("Save Button"),
	SALESORDER("Sales Order"),
	LABELSREPRINT("Labels Reprinted"),
	MISSINGTELEX("Missing Telex"),
	 ALREADY_SELECTED_ARTICLE("Already Selected Article"), 
	 DELIVERY_DATE("Delivery Date"),
	 DELIVERY_TIME("Delivery Time"),
	 NOTES("Notes"),
	 TIME_ICON("Time Icon"),
	 VENDOR_INCIDENT_POPUP("Vendor Incident Pop Up"), 
	 VENDOR_INCIDENT_DETAILS_POPUP("Vendor incident details pop up"),
	 YES("yes"),
	 NO("No"),
	 VIEW("view"),
	 VIEW_INCIDENT_LINK("View Incident Link"),
	 VENDOR_INCIDENT_INFO_POPUP("Vendor Incident Info PopUp"),
	 CANCEL_PO_POPUP("Cancel Popup"),
	 REASON_POPUP("Reason Popup"),
	 DONOT_CANCEL("Do not Cancel"),
	 VIEW_ORDER_POPUP("view order popup"),
	 BLANCLICK("Blank Click"),
	 DETAILWRAP("Detail Wrapper Icon"),
	 CUSTOMER_REFERENCE_NO("Customer reference number"), 
	 QUANTITY_RECEIVED("Order Quantity Received"), 
	 VIEW_LINKED_ORDER("View Linked Order"), 
	 VIEW_LINKED_ORDER_POPUP("View Linked Order PopUp"),
	 CANCEL_ORDER("Cancel Order"),
	 RECEIVE_WITHOUT_PO("Receive Without PO"), 
	 
	 
	
	UOM_ID("UOM ID"),
	RC_UNIT_UOM("Recipe Card Conversion UOM"),
	UPDATE_UOM("Update UOM"),
	FINANCE_PRODUCT("SAP GL ACCOUNT"),
	ADD_FINANCE_PRODUCT("Add SAP GL ACCOUNT"), 
	UPDATE_FINANCE_PRODUCT("Update SAP GL ACCOUNT"), 
	TAXES_AND_FEES("Taxes and Fees"), 
	ADD_TAX_CODE("Add Tax Code"), 
	TYPE("Type"), 
	APGL_ACCOUNT("APGL Account"),
	ARGL_ACCOUNT("APGL Account"), ADD_SUBSTORE_CODE("Add Substore Code"),
	UPDATE_SUBSTORE_CODE("Update Substore Code"), 
	ADD_BASIC_ARTICLE_TITLE("Add Basic Article"),
	
	/** Additional Purchases */
	ADDITIONAL_PURCHASES_LINK("Additional Purchases Link"), 
	ADDITIONAL_PURCHASES_TITLE("Additional Purchases Title"),
	ADDITIONAL_PURCHASES_PAGE("Additional Purchases Page"), 
	CURRENCY_DROPDOWN("Currency"), 
	ORDER_STATUS("Order Status"), 
	ACTSTATUS("Actualization Status"),
	
	/** Requisition Order */
	REQUISITION_ORDER_LINK("Requisition Order Link"), 
	REQUISITION_ORDER_TITLE("Requisition Order Title"),
	REQUISITION_ORDER_PAGE("Requisition Order Page"), 
	CREATE_REQUISITION_ORDER_PAGE("Add Requisition Order Page"), 
	REQUIRED_BY("Required By"), 
	STATUS("Status"), 
	GENERATE_ORDER_BTN("Generate Order Button"), 
	GENERATE_REQUISITION_ORDER_POPUP("Generate Requisition Order Popup"), 
	CLOSE_BTN("Close Button"),
	ORDERQTY("Order Quantity"),
	
	
	UPDATE_ARTICLE_GROUP_PAGE_TITLE("Update Article Group"),
	UOM_DROPDOWN("UOM dropdown"),
	ARTICLE_GROUP_DROPDOWN("Article group Dropdown"), 
	INVERTED_SYMBOL("Inverted Symbol"),
	SEARCH_CONTAINER("Inverted Symbol Container"), 
	
	/** Finance Products */
	SYSTEM_FINANCE_PRODUCTS("Finance Products"), 
	SEARCHBAR("Search Bar"), 
	ADD_FINANCE_PRODUCT_BUTTON("Add Finance Product Button"),
	PAGINATION_OPTION("Pagination Option"),
	SELECTCUST("Select Customer"),
	SELECTCSP("Select CSP"),
	EXISTINGAGREEMENT("Search Existing Agreements"),
	RESULT_GRID("Result Grid"), 
	VALIDPERIOD("Valid Period"),
	
	SEARCH_CRITERIA_PANEL("Search Criteria Panel"), 
	PRODUCT_ID("Product id"),
	BACK_TO_SEARCH_BUTTON("Back to Search Button"),
	EIDTINCIDENT("Edit Incident"),
	REMOVEINCIDENT("Remove Incident"),
	REMOVEINCIDENTTXT("Remove Incident Text"),
	VIEWEXISTINGINCIDENT("View Existing Incident"),
	FINANCEPRODUCTS_SEARCH_FIELD("Finance Products search Field"),
	SEARCH_BUTTON("Search Button"),
	NO_DATA_TO_DISPLAY("No data to display"),
	SHOWINGENTRIES("Showing Entries"),
	FIRSTROW_FIRSTVALUE_DESC("First row First value Description"),
	FIRSTROW_SECOND_VALUE_PID("First row second value Product ID"),
	FIRST_LINK("First Link"),
	NEXT_LINK("Next Link"),
	PREVIOUS_LINK("Previous link"),
	LAST_LINK("Last Link"),
	BELOW_PAGINATION("Below Pagination"),
	SHOW_ENTRIES_OPTION_BUTTON("Show entries options button"), 
	SHOW_DROPDOWN_ENTRIES_OPTION("Show dropdown entries option"), 
	COLUMN_HEADING_PRODUCTID("Column Heading Product Id"),
	FINANCE_PRODUCTS_ARTICLE_NUMBER("Finance Products Article Number"), 
	DESCRIPTION_CHECKBOX("Description checkbox"),
	PRODUCT_ID_CHECKBOX("Product Id Checkbox"),
	CHECKBOX_ERROR_MESSAGE("Please select one search criterion"), 
	PRODUCT_ID_TEXTFIELD("Product ID text field"),
	DESCRIPTION_TEXTFIELD("Description text field"),
	FINANCE_PRODUCT_ID_ALREADY_PRESENT("Finance Product ID already exists"), 
	FINANCE_PRODUCT_ID_ALREADY_PRESENT_CROSS_SYMBOL("Finance Product ID already exists dix cross symbol"),
	APPLY_CHANGES_BUTTON("Apply Changes Button"), 
	CREATED_SUCCESSFULLY("Created successfully"),
	UPDATED_SUCCESSFULLY("Updated Successfully"),
    APPLY_CHANGES_CONTINUE_BUTTON("Continue Button"),
    GROUP_ID("Group Id"),
    CHECKBOXA("Check Box"),
    REMOVE_NONREVELANTDATA("Remove Non Relevant Data"),
    DEADLINE_HEADER("Deadline Header"),
    DAYSAHEAD_HEADER("Days Ahead Header"),
    DAYSAHEAD("Days Ahead"),
    EXCS_HEADER("Excs Header"),
    
    /** Add Finance Product */
    USED_IN_PANEL("Used in Panel"), 
    REQUIRED_FIELD_VALIDATION("Required Field Validation"), 
    INVALID_NUMBER("Invalid Number"),
    NO_VATACCNO_TEXTFIELD("No Vat Account Number text field"), 
    VAT1_ACCNO_TEXTFIELD("VAT 1 Account Number text field"),
    VAT2_ACCNO_TEXTFIELD("VAT 2 Account Number text field"),
    VAT3_ACCNO_TEXTFIELD("VAT 3 Account Number text field"),
	
    ROW_TO_DOUBLE_CLICK("Result Row"),
    UPDATE_COST_CENTER_DES("Description Box"),
    UPDATE_COST_CENTER_SAP("SAP Box"),
    SEARCH_RESULT_ROW("Result"),
    UPDATE_SUCCESS("Updated Sucessfully"),
    SUBMIT_BUTTON("Apply Change Button"),
    APPLYBTN("Apply"),
    CONFIRM_REPLACE("Confirm Replacement"),
    REMOVE_COST_CENTER_LINK("Remove Button"),
    CONFIRMATION_BOX("Confirmation Box"),
    CONFIRMATION_BOX_CONTINUE_BUTTON("Continue Button"),
    COST_CENTER_PAGE_HEADING("Cost Center"),
    REQUIRED_FIELD_ID("ID Required Field"),
    REQUIRED_FIELD_DES("DES Required Field"),
    SAP_FIELD("SAP TextBox"),
    COST_CENTER_DISPLAY_PANEL("Display Panel"),
    COST_CENTER_DISPLAY_PANEL_MESSAGE("Display Panel Message"),
    
    SYSTEM_COST_CENTER_BTN("system add cost center button"),
    SYSTEM_COST_CENTER_SEARCH("system cost center search"),
    SYSTEM_COST_CENTER_DROPDOWN("system cost center DropDown"),
    SYSTEM_COST_CENTER_RESULT_GRID("System cost center result grid"),
    SYSTEM_COST_CENTER_SEARCH_BUTTON("Cost Center search Button"),
    SYSTEM_COST_CENTER_SEARCH_OPTION("Search options are displayed"),
    SYSTEM_ADD_COST_CENTER_PAGE("Add Cost Center Page"),
    SYSTEM_BACK_COST_CENTER_PAGE("Back Cost Center Page"),
    SYSTEM_COST_CENTER_PAGE("cost center page"),
    SYSTEM_BACK_COST_CENTER_BTN("system back cost center button"),
    SYSTEM_SEARCH_BOX_VALUE("Search box "),
    SYSTEM_SEARCH_RESULT_GRID("No data to display message is displayed"),
    SYSTEM_SEARCH_RESULT_GRID_FIRST_ROW("First page result is displayed"),
    SYSTEM_SEARCH_RESULT_GRID_FIRST_ROW_AFTER_CLICK("First page result after click is displayed"),
    SYSTEM_SEARCH_RESULT_GRID_FIRST_TEXT("First row Text"),
    SYSTEM_RESULT_NAVIGATION_NEXT_BUTTON("Next button"),
    SYSTEM_RESULT_NAVIGATION_PREV_BUTTON("PREV button"),
    SYSTEM_RESULT_NAVIGATION_LAST_BUTTON("Last button"),
    SYSTEM_RESULT_NAVIGATION_FIRST_BUTTON("First button"),
    SYSTEM_SEARCH_RESULT_GRID_NEXT_PAGE_FIRST_ROW("Next Page result grid row is displayed"),
    SYSTEM_SEARCH_RESULT_GRID_PREV_PAGE_FIRST_ROW("Prev Page result grid row is displayed"),
    SYSTEM_SEARCH_RESULT_GRID_LAST_PAGE_FIRST_ROW("Last Page result grid row is displayed"),
    SYSTEM_SHOW_ENTITY_ARROW_BUTTON("Show entity button"),
    SYSTEM_SEARCH_RESULT_GRID_DES_HEADING("Description Heading"),
    SYSTEM_SEARCH_RESULT_GRID_ID_HEADING("ID Heading"),
    SYSTEM_ADD_COST_CENTER_TEXTBOX_DISPLAY("Textbox"),
    SYSTEM_ADD_COST_CENTER_TEXTBOX_VALUE_INSERT("ID"),
    SYSTEM_ADD_COST_CENTER_TEXTBOX_DES_INSERT("DES"),
    SUCCESS_MESSAGE("Added Sucessfully"),
    MESSAGE("Message"),
    PAGE3("Page 3 Link"),
    ID_ALREADY_EXIST("ID Already Exist"),
    COST_CENTER_DES_CHECKBOX("DES CheckBox"),
    COST_CENTER_ID_CHECKBOX("ID CheckBox"),
    PLEASE_SELECT_ONE_CRITERIA("Please select one search criterion"),
    RESULT_ROW("Row"),
    CONFIRMATION_BOX_CANCEL_BTN("Cancel"),
    REPLACEVERSION("REPLACEVERSION"),
    TOAST_MSG_CANCEL("Toast Cancel"),
    VENDOR_PAGE_COST_CENTER_DROPDOWN("DropDown"),
    VENDOR_ROW_TO_UPDATE("record"),
    SYSTEM_COST_CENTER_TITLE("add cost center"),
    
    SYSTEM("System"),
    CURRENCY_CODES_AND_RATES("Currency Codes and Rates"),
    CURRENCY_CODES_AND_RATES_TITLE("Currency Codes and Rates"),
    UPDATE_CURRENCY_CODE_TITLE("Update Currency Code"),
    SEARCH_BAR("Search Bar"),
    SEARCHDD("Search Drop Down"),
    Add_Button("Add Button"),
    SEARCH_RESULT_GRID("Result Grid"),
    ADD_CURRENCY_CODE_TITLE("Add Currency Code"),
    SEARCH_BOX("Search"),
    SEARCH_ENTER_BUTTON("Search Enter Button"),
    NO_DATA_DISPLAY("No Data To Display"),
    SEARCH_RESULT_GRID_FIRST_COLUMN("Search Grid First Column"),
    DESCRIPTION_HEADING("Description Heading"),
    SEARCH_CONTAINER_CURRENCY_CODE_CHECKBOX("Currency code checkBox"),
    SEARCH_CONTAINER_DESCRIPTION_CHECKBOX("Description checkBox"),
    TOAST_CONTAINER("Taost container"),
    CURRENCY_UNIT("Currency Unit"),
    REPORT_DECIMALS("Report Decimals"),
    BASE_CURRENCY("Base Currency"),
    VALIDATOR("Validator"),
    APPLY_CHANGES("Apply changes"),
    EFFECTIVE_DATE("Effective Date"),
    MAXPAX("Max Pax"),
    TO_BASE_RATE("To base Rate"),
    FROM_BASE_RATE("From Base Rate"),
    ADD_EXCHANGE_BUTTON("Add Exchange Button"),
    ADD_NEW_EXCHANGE_RATE("Add new exchannge rate"),
    TOASTMESSAGE("toast-message"),
    TOASTMESSAGE_CLASS("className"),
    PAGETITLE("Page Title"),
    RESTITUTION_GROUP_CHECK_BOX("Restitution Group check box"),
    DESCRIPTION_CHECK_BOX("Description check box"),
    SEARCHVENDOR("Search Vendor"),
    FIRST_ITEM("First Item"),
    
    REQUIRED_FIELD_MSG("Required Field Msg"),
    CPC_DROPDOWN("CPC Dropdown"),
    SEARCH_OPTION_BUTTON("Search Option Button"),
    CODE_CHECKBOX("Code CheckBox"),
    SEARCH_CRITERIA_OPTION("Search Criteria"),
    EDIT_BUTTON("Edit Button"),
    EDITICON("Edit Icon"),
    NTP_CHECKBOX("NTP CheckBox"),
    ADD_WORKCENTER("Add WorkCenter"),
    DONE_BUTTON_FIRST("Done"),
    
    /** Flight Timetable */
    ADDFLIGHT("Add Flight"),
    FLIGHT("Flight"),
    CONFIRMATION_MSG("Confirmation Message"),
    CUSTOMER("Customer"),
    ARRIVALDEPARTURE("Arrival/Departure"),
    HAUL("Haul"),
    OPDAYS("Operation Days Drop Down"),
    SELECTOPDAYS("Operation Days Checkbox"),
    ARRIVALTIME("Arrival Time"),
    DEPARTURETIME("Departure Time"),
    ARRIVEFROM("Arrives From"),
    DEPARTAIRPORT("Departure Airport"),
    DEPARTTO("Depart To"),
    ACVERSION("A/C Version"),
    INSERTVALUEPAXFORECAST("Insert value into Pax Forecast"),
    
    /** Add UOM */
    RC_UNIT_CONVERSION_FACTOR("RC Unit Conversion Factor"),
    CP_UNIT_CONVERSION_FACTOR("CP Unit Conversion Factor"),
    CP_UNIT_UOM("CP Unit UOM"),
    ADD_UOM_TITLE("Add UOM Title"),
    UOM_ID_CHECK_BOX("UOM ID check box"),
    PURCHASE_UOM_DROPDOWN("Purchase UOM Dropdown"),
    
    UNITOFMEASURETITLE("Unit of Measure Page Title"),
    
     /** Classes */
    CLASSES("Classes"),
    CLASS("Class"),
    LAST_UPDATED("last Updated"),
    CCR("CCR Dropdown"),
    PAX_RELATED("PAX Related CheckBox"),
    ON_PROD_PLAN("On Prod Plan CheckBox"), 
    INTERREQORDER("Internal Requisition Order"),
    
    /**Costing&Pricing*/
    COSTINGPRICING("Costing & Pricing"),
    PRODUCTTYPE("Product Type"),
    ADDPRODUCTTYPE("Add Product Type"),
    
    /**Truck & Bay Assignment*/
    DESPATCH("Despatch"),
    CLOSEDATE("Close Date"),
    TRUCKBAYASSIGN("Truck Bay Assignment"),
    PICKASSIGNMENT("Pick Assignment"),
    
    /**Delay Log*/
    DELAYLOG("Delay Log"),
    ADDDELAYLOG("Add Delay Log"),
    DELAYMINUTES("Delay Minutes"),
    ESTIMATEDCOST("Estimated Delay Cost"),
    ACTUALIZATION("Actualization"),
    ACTICON("Actualization Icon"),
    ACTDATE("Actualization Date"),
    REFRESH("Refresh"),
    CREATEACTUALIZATION("Create Actualization"),
    DEPARTURE_DAY("Departure Day"),
    SECTION("Section"),
    DELAY_TIME("Delay Time"),
    DELAY_MIN("Delay Minutes"),
    ESTIMATED_DELAY_COST("Estimated Delay Cost"),
    LEFT_RAMP("Left Ramp"),
    PASSED_SECURITY("Passed Security"),
    ARRIVED_AT_AC("Arrived at AC"),
    ACCESS_TO_AC("Access to AC"),
    CATERING_COMPLETION("Catering Completion"),
    FINAL_COMMENTS("Final Comments"),
    DISPATCHER("Dispatcher"),
    TEAM_LEADER("Team Leader"),
    DUTY_MANAGER1("Duty manager 1"),
    DUTY_MANAGER2("Duty manager 2"),
    DUTY_MANAGER3("Duty manager 3"),
    DUTY_MANAGER4("Duty manager 4"),
    STAND("Stand"),
    TERMINAL("Terminal"),
    MPS_SEARCH("View Flights Search Box"),
    
    
    /**Duty Log*/
    DUTYLOG("Duty Log"),
    ADDDUTYLOG("Add Duty Log"),
    EDITDUTY("Edit Duty Log"),
    WATCHICON("Watch Icon"),
    NOTIFYTIME("Notification Time"),
    ADHOCREQUEST("Adhoc Request"),
    DUTYLOGDATE("Duty Log Date"),
    
    /**Invoice*/
    INVOICE("Invoice"),
    CUSTOMERTURNOVERGROUP("Customer Turnover Group"),
    WHERECTOGUSED("Where CTOG is used"),
    ADDCTOG("Add Customer Turnover Group"),
    ADDCUSTOMER("Add Customer"),
    CTOG("Customer Turnover Group"),
    CTOG_CODE("AAE"),
    CUSTOMERTYPE("Customer Type"),
    
    /** Operation*/
    OPERATION("Operation"),
    AIRCRAFT_VERSION("Aircraft Version"),
    AHA("Active Head Arrow"),
    AIRCRAFT_VERSION_TEXTBOX("Aircraft Version Textbox"),
    TEXTBOX("Textbox"), 
    AIRCRAFT_VERSION_ID("K74QB"),
    AIRCRAFT_TYPE_DROPDOWN("AC Type"),
    EQUIPMENT_TYPE("Equipment Type"),
    CUSTOMER_CODE("Customer Code"),
    REGNUMBER("Registration Number"),
    LOAD_RATIO("LoadRatio"),
    ADD_LOAD_RATIO("Add Load Ratio"),
    ADD_AIRCRAFT("Add Aircraft"),
    AIRCRAFT_ACTYPE("A/C Type"),
    AIRCRAFT_ACVERSION("A/C Version"),
    LOCATION("Location"),
    ID("ID"),
    QTYWITHPAX("Qty With Pax"),
    SEARCHCONTAINER("Search Container"),
    CHANGECUSTOMER("Change Customer"),
    CUSTOMERNAME("Customer Name"),
    AV_SHOWENTRIES("Show Entries"),
    SELECT20("20"),
    SELECT50("50"),
    SELECT100("100"),
    AVDELETE("Aircraft Delete"),
    REGNUMDEL("Registration Number Delete"),
    REGADDNUMBER("Add Numbers"),
    AV_SHOWINGENTRIES("Showing entries"),
    LOADSETUP("Loading Setup"),
    ADDLOADSETUP("Add Loading Setup"),
    LOADRATIOS("Load Ratios"),
    DISTCODES("Distribution Codes"),
    CATERINGSTOWAGEPLAN("Catering Stowage Plan"),
    ROTATIONPLAN("Rotation Plans"),
    MISCELLANEOUS("Miscellaneous"),
    FLIGHTTT("Flight Time Table"),
    ACTYPE("Aircraft Type"),
    AA("A/C Type Head Arrow"),
    CLASS_CONFIG("Class Config"),
    SEARCH_ICON("Search Icon"),
    DELICON("Delete Icon"),
    GENERATEORDER("Generate Order"),
    SEARCHEXISTINGORDER("Search Existing Order"),
    VID("Vendor ID"),
    RESTARTPOPUPTXT("Restart Pop Up Text"),
    /** Combined Classes */
    COMBINED_CLASSES("Combined Classes"),
    COMBINED_CLASSES_TITLE("Combined Classes Title"),
    ADD_COMBINED_CLASS("Add New Combined Class Button"),
    COMBINED_CLASS_CODE_SEARCH_CRITERION("Combined class code search criterion"),
	CLASSES_SEARCH_CRITERION("Classes search criterion"),
	DESCRIPTION_CRITERION("Description Criterion"),
	COMBINED_CLASS_HEADING("Combined Class Heading"),
	COMBINED_CLASS_ID_TEXTBOX("Combined Class Id Text Box"),
	DESCRIPTION_TESTBOX("Description Text Box"),
	DESCTEXT("Description Text"),
	COMBINED_CLASSES_DROPDOWN("Combined Classes Dropdown"),
	APPLY_CHANGES_ICON("Apply Changes Icon"), 
	DELETE("Delete"),
	DELETEPOPTEXT("Delete Pop Up Text"),
	DELETEICON("Delete Icon"),
	MENUITEM("Where is A/C version used"),
	MENUITEM2("Replace where used"),
	CLOSEMONTH("Close Month"),
	 /** Delivery Plans */
	OPERATIONS("operations"),
	DELIVERY_PLANS("Delivery Plans"),
	CUSTOMERCODE_DROPDOWN("Customer Code Dropdown"),

    DEPARTMENTCODE("ATV"),
    MANAGEUNITS("Manage Units"),
    CHECKBOX("CheckBox"),
    AIRCRAFT_VERSION_DATA("K74QB"),
    /**Store**/
    STORES("Stores"),
    INVENTORY_REGISTRATION("Inventory_Registration"),
    INVENTORY_TEXTBOX("Inventory Quantity TextBox"),
    FROMSTORES("From Stores"),
    ADDDELPLAN("Add Delivery Plan"),
    SAP_PRODUCT_CODE("SAP Product Code"),
    NET_PRICE("Net Price"), 
    
    /** Vendor Incidents **/
    VENDOR_INCIDENTS("Vendor Incidents"), 
    VENDOR_INCIDENTS_PAGE("Vendor Incidents Page"), 
    VENDOR_INCIDENTS_TITLE("Vendor Incidents Title"),
    CREATE_VENDOR_INCIDENT_PAGE("Create Vendor Incident Page"),
    CREATE_VENDOR_INCIDENT_TITLE("Create Vendor Incident Title"),
    INCIDENT_TYPE("Incident Type"), 
    INCIDENTDATE("Incident Date"),
    INCIDENT_TYPE_DROPDOWN("Incident Type Dropdown"),
    WITHDRAWALANDTRANSFER("WithdrawalAndTranfer"),
    FROM_SUB_STORE("FromSubStore"),
    REQ_BY_SUBSTORE("RequiredBy"), 
    TRANSACTION_TYPE("TransactionType"),
    ADDINCIDENT("Add Incident Icon"),
    ADDINCIDENTBTN("Add Incident"),
    /** Return To Vendor **/
    RETURN_TO_VENDOR("Return To Vendor"),
    RETURN_TO_VENDORCHK("Return To Vendor Check Box"),
    RETURN_TO_VENDOR_PAGE("Return To Vendor Page"),
    CREATE_RETURN("Create Return"),
    TO_VENDOR("To Vendor"),
    VENDOR_DROPDOWN("Vendor Drop down"),
    STOCK_DATE("Stock Date"),
    ADD_SELECTED("Add Selected"),
    GRID_OF_SELECTED_ARTICLE("Grid Article  Number column"),
    RETURN_QUANTITY("Return Quantity"),
    ISSUE_RETURN("Issue Return"),
    SUBMIT_RETURN_ORDER_POPUP_HEADING("Submit Return Order Popup"),
    ADD_VENDOR_INCIDENT_POPUP_HEADING("Add Vendor Incident Popup"), 
    SEE_MORE_OPTIONS("See More Options"), 
    RELATEDTOCUSTOMER("Related To Customer"),
    PO_NUMBER("PO Number"),
    DELIVERY_NOTE_NO("Delivery Note Number"),
    REMARKS("Remarks"), 
    REMOVESELECTED("Remove Selected"),
    EXISTING_ORDER_BTN("Existing Order Btn"),
    ORDER_FORM("Order form"),
    INFO_BUTTON("Info_Button"),
    TABLE_HEADING("Table_Heading"),
   

    /** Customer Price Agreement **/

    CUSTOMER_PRICE_AGREEMENT_LINK("Customer Price Agreement"),
    START_DATE("Start Date"),
    END_DATE("End Date"),
    
    /** Distribution Codes **/
    DISTRIBUTION_CODES("Distribution Codes"),
    CODE_TESTBOX("Distribution Codes TestBox"),
    GET_LABEL_DROPDOWN("Get Label Dropdown"),
    ADD_LINE("Add Line Btn"),
    PAGER_TOP("Page Number and navigations"),
	SEARCH_GRID_HEADING("Search Result Grid Heading"),
	DISTRIBUTION_CODES_HEADING("Distribution Codes Heading"),
	STOWAGE_FILL_FACTOR_HEADING("Stowage Fill Factor Heading"),
	LABEL_TEXT_HEADING("Label Text Heading"),
	SALES_NUMBER_HEADING("Sales Number Heading"),
	 DISTRIBUTION_CODE_CRIETERIA("Distribution Code Crieteria"),
	 UPDATE_DISTRIBUTION_CODES("Update Distibution Codes"),
	 STOWAGE_FILL_FACTOR("Stowage Fill Factor"),
	 SALES_NUMBER_CRITERIA("Sales number criteria"),
	 SALES_NUMBER("Sales Number"),
	 SALES_NUMBER_POPUP_FIRST_ITEM("Sales number popup first item"),
	 COPY_POPUP("Copy Popup"),
    
    /** Box Codes **/
    
    BOX_CODES("Box Codes"),
    BOX_CODE_TEXT_BOX("Text Box"),
    CUSTOMER_CODE_DROPDOWN("Customer Code DropDown"),
    BASIC_ARTICLE_CHECK_BOX("Basic Article Check box"),
	PRODUCT_CALCULATION_CHECK_BOX("Product Calculation check Box"),
	SALES_NUMBER_CHECK_BOX("Sales Number Check Box"),
    
	ADD_LINE_FOR_BASIC_ARTICLE("Add Line For Basic Article"),
	ADD_LINE_FOR_PRODUCT_CALCULATION("Add Line For Product Calculation"),
	ADD_LINE_FOR_SALES_NUMBER("Add Line For Sales Number"), 
	CHANGE_VENDOR("Change Vendor"),
	SELECT_VENDOR("Select Vendor"),
	SEARCH_EXISTING_ORDER("Search Existing Order"),
	ORDER_NUMBER("Order Number"),
	ORDER_DATE("Order Date"),
	ITEMS("Items"), 
	PENDING_APPROVAL("Pending Approval"),
	SUBMITTED("Submitted"),
	CLOSED("Closed"),
	RECIEVED("Recieved"),
	REJECTED("Rejected"),
	PENDING("Pending"),
	DATE("Date"),
	ORDER_BY("OrderBy"),
	ALIAS("Alias"),
	MARKUPALT1("Mark up Alt. 1"),
	MARKUPALT2("Mark up Alt. 2"),
	MARKUPALT3("Mark up Alt. 3"),
	APPROVEDSTATUS("Approval Status"),
	STRATEGICACCOUNT("Strategic Account"),
	GLOBALCUSTOMER("Global Customer"),
	CUST_ITEM_SLIP("Cust item no on slip E"),
	PAXFIGS("PAX Figs are TOB Figs"),
	
	INVENTORY_ACCOUNT("Inventory Account"),
	GRNI("GRNI"),
	STOCK_ACCOUNT("Stock Account"),
	MATERIAL_ACCOUNT("Material Account"),
	ISSUE_ACCOUNT("Issue Account"),
	INVOICE_ACCOUNT("Invoice Account"),
	STOWINGCONTAINERS("StowingContainers"),
	ADD_STOWING_BUTTON("Add Stowing Containers"),
	SAVE_ICON("SaveIcon"),
	CODE_CONTAINER("CodeContainer"),
	WEIGHT_CHECKBOX("Weight Checkbox"),
	SEAL_CHECKBOX("Seal Checkbox"),
	CAPACITY_CHECKBOX("Capacity Checkbox"),
	CONTAINER_CAPACITY("ContainerCapacity"),
	WEIGHT("Weight"),
	NO_OF_SEALS("No Of Seal"), 
	SPML_TYPES("SPML Type"),
	ADD_SPML_BUTTON("Add SMPL Type"),
	SPML_TITLE("SPML Title"),
	SEQUENCE("Sequence"),
	SPMLTYPE_CHECKBOX("SPML Type CheckBox"),
	SEQUENCE_CHECKBOX("Sequence CheckBox"),
	GRID_HEADING("Grid Heading"),
	
	 /** Loading Setup**/
    
	LOADING_SETUP("Loading SetUp"),
	LOADING_SETUP_CODE("Loading Setup Code"),
	RESTART("Restart"), 
	SALESCODEDECIMAL("Sales Codes Decimal"),
	LOADING_SETUP_CRITERIA("LOADING_SETUP_CRITERIA"),
	DESCRIPTION_CRITERIA("Description Criteria"),
	LINK_TO_UNITS_POPUP("Link To Unit Popup"), 
	WHERE_USED_POPUP("Where LS Used POPUP"),
	WHERE_CTOG_USED_POPUP("Where CTOG Used POPUP"),
	COPY_LOADING_SETUP("Copy Loading SetUp"),
	COPY_LOADING_SETUP_POPUP("Copy Loading SetUp popup"),
	COPY_BUTTON("Copy Button"),
	
	/** Catering Stowage Plans**/
	
	CSP("Catering Stowage Plans"),
	CSP_CODE("CSP Code"), 
	POP_UP_OPEN_BTN("Pop Up Open Button"),
	AC_VERSION_POPUP("AC Version Pop Up"),
	PRINT_MODE("Print Mode"),
	ADDITIONALINFO("Additional Info"),
	 DCODE("DCODE"),
	 DOOR("Door"), 
	 LOAD("Load"),
	 GALLERY("Gallery"), 
	 LOADING_POSITION("Loading Position"), 
	 PRINT_SEQ("Print Sequence"),
	 PRINTER("Printer"), 
	 GALLEY("Galley"),
	 LPOS("LPOS"),
	 PRTSEQ("Print Sequence"),
	 BOXLBL("Box Label"),
	 REMOVE_ICON("Remove Icon"),
	
	
	
	ROTATION_PLANS("Rotation Plans"),
	ROTATION_PLAN_CODE("Rotation plan code"),
	ROTATION_UNIT("Rotation Unit"),
	CHANGE_DAY("Change Day"),
	GENERATE_NEW_CHART_POPUP("generate new chart pop up"),
	ASTRICKS("Astricks Mark"),
	ROTATION_PLAN_CRITERIA("ROTATION_PLAN_CRITERIA"),
	
	SEARCH_LEBEL("Search Label"), 
	VENDORNUMBER("Vendor Number"),
	PURCHASE_UNIT("Purchase Unit"),
	EXISTING_AGREEMENT("Existing Agreement Grid"),

	SELECTEDUNIT("Selected Unit"),
	AGREEMENT_GRID("Agreement Grid"),
	EXPORT("Export"),
	SHOWSOLDQTY("Show Sold Qtys"),
	RELATE_CTOG("Relate Turnover Group to Class DropDown"),
	PRICE_HEADING("Price Heading"),
	START_HEADING("Start Date"),
	END_HEADING("End Date"),
	INFORMATION_FORM("Information Form"),
	PRICE_UNIT("PriceUnit"),
	UPLOAD_POPUP("Upload PopUp"),
	IMPORT("Import"),

	COPY_ICON("Copy Icon"),
	FORMNAME("Form Name"),
	REASON("REASON"),
	TIME("Time"),
	DETAIL_PAGE("Detail Page Table"),
	ISSUED("Issued"),
	QUANTITY_ISSUED("Quantity Issued"),
	LOT_NUMBER("Lot Number"), 

	INFO_POPUP("Information PopUp"),

	CREATE_PICKING_LIST("Create Picking List"),
	RESET("Reset"),
	QUANTITY_REQ("Quantity Required"),

	ISSUE_ORDER("Issue Order"),
	SAVE_ORDER_AS_REQUISITION_FORM("Save order as requisition form"),
	REQUISITION_FORM_NAME("Requisition form name"), 
 
	CLEAR_THIS_MONTH("Clear This Month"), 
	INSERT_THEORETICAL_STOCK("Insert Theoretical Stock"),
	REFRESH_DAY_PRICE("Refresh Day Price"),
	ORDER_RECEIPT("Order Receipt"),
	ORDER_RECEIPT_CORRECTION("Order Receipt(correction)"),
	PRINT_BATCH_CONTROL_FORMS("Print Batch Control Forms"),
	ORDER_RECEIPT_HISTORY("Order Receipt History"),
	SET_ALL_ORDER_QUANTITIES_TO_ZERO("Set all Order quantities to zero"),
	ADD_BOX_CODE("Add Box Code"),
	ADDCSP("Add CSP"),
	ATTENTION_POPUP("Attention PopUp"),
	

	ADD_BASIC_ARTICLE_GRID("Add Basic Article Grid"),
	QTY("Quantity"),
	UNIT("Unit"),
	PRODUCT_CALCULATION("Product Calculation"),
	
	FINANCE("Finance"),
	COPY_BOXCODE("Copy BoxCode"),
	REPLACE_WITH("Replace With"), 
	SALESPRICING("Sales Pricing"),
	ADD_SALES_PRICE("Add Sales Price"),
	MAIN_TURN_OVER_GROUP("Main turn over group"),
	SUB_TURN_OVER_GROUP("Sub turn over group"),
	SERVING("Serving"),
	VAT("VAT"),
	SURCHARGE("Surcharge"),
	ROTATION_PLAN_NUMBER("Rotation Plan Number"),
	FIND_ICON("Find Icon"),
	CUSTOMIZED_STATUS("Customized Status"),
	LPR("SPML Printer Code"),
	RETURN_COUNT("Return Count"),
	T("T"), 
	COPY_DLVPLAN("Copy Delivery Plan"),
	DCODE_HEADER("Distribution Code"),
	SEQ_HEADER("Sequence Number"),
	GRP_HEADER("Group Code Number"),
	RULE_HEADER("Stowing Rule"),
	PRIO_HEADER("Priority Number"),
	DOOR_HEADER("Door Number"),
	GALLEY_HEADER("Galley Number"),
	LPOS_HEADER("Loading Position Number"),
	LPOSWGHT_HEADER("Loading Position Weight"),
	TLS_HEADER("Truck Load Sequence"),
	MSD_HEADER("Meal Service Description"),
	PRTSQ_HEADER("Print Sequence"),
	DRW_HEADER("Drawing Number"),
	PRT_HEADER("Box Label Printer"),
	CONT_HEADER("Stowing Cotainer Number"),
	CAP_HEADER("Stowing Capacity Number"),
	PEL_HEADER("Print Empty Label"),
	STARTDATE_HEADER("Start Date"),
	STOPDATE_HEADER("Stop Date"),
	RETURN_FLIGHT("Return flight"),
	CALENDAR("Calendar"),
	
	NUMBER_OF_ROTATIONS("Number Of Rotations"),
	FREQUENCY_OF_ROTATION("Frequency Of Rotation"),
	EDIT_ROTATION_POPUP("Edit Rotation PopUp"),
	START_ROTATION("START_ROTATION"),
	WHERE_ROTATIONPLAN_IS_USED("Where Rotation Plan used"),
	DOP("DOP"),
	FLIGHT_REMARK("Flight remark"),
	TABLE_ROW("Table Row"),
	ADD_DELIVERY_PLAN("Add Delivery Plan"),
	ADD_CSP_BUTTON("Add CSP"),
	MEAL_SERV("Meal Service"),
	EXCEPTION("Exeception"),
	DEADLINE("Dead-line"),
	DEADLINE_CLOCK("Dead-line Clock"),
	ADD_EXCEPTION("Add Exception"), 
	COPY_TO_TIMELINE_CHECKBOX("Copy to timeline"),
	QUICK_UPDATE_EXCEPTION("Quick Update Exception"),
	POPUP("PopUp"),
	SHOW_ALL_CANCELLATION("Show All Cancellation"),
	CUSTOMER_NUMBER("Customer Number"),
	EXPORT_POPUP("Export Pop Up"),
	
	/** Flight Overview **/
	
	FLIGHT_OVERVIEW("Flight Overview"),
	EXPAND_ARROW("Expand Arrow"),
	TRUCK_COLUMN("Truck Column on Grid"),
	PAX_OVERVIEW_TAB("Pax Overview Tab"),
	FCP("FCP"),
	PRODUCTION_PLANNING("Production Planning"), 
	FORCAST_PLANNING("Forcast Planning"),
	PAX_FORECAST_TAB("Pax ForeCast Tab"),
	ACTUALIZED_DATE("Actualized_date"), 
	SELECTED("Selected"), 
	UPDATE_SELECTED("Update Selected"),
	ADJUST_FIG("Adjust Figure"),
	START_UPDATE("Start Update"),
	SET_SELECTED_TO_ZERO("Set selected to zero"),
	SELECT_ALL("Select all"),
	COSTING_PRICING("Costing Pricing"),
	COSTING_PARAMETER("Costing Parameter"),
	ADD_COSTING_PARAMETER("Add Costing Parameter"),
	PARAMETER_CODE("Parameter Code"),
	MATERIAL_OVERHEAD("Material Overhead"),
	STORAGE_OVERHEAD("Storage Overhead"),
	
	
	
	RETURNS("Returns"), 
	CHECK_OUT("Check Out"),
	EDIT_CHECKOUT("Edit CheckOut"),
	RETURN_ACTUALIZATION("Return Actualization"),
	CHECK_OUT_POPUP("Check Out Popup"),
	HASH_TOTAL_POPUP("Hash Total Pop Up"),
	CHECK_SUM("Check Sum"), 
	RS("RS"),
	OPERATING_DATE("Operating Date"),
	PAX_AND_MEAL_CONTAINER("Pax and meal container"),
	NEW_FLIGHT("New Flight"),
	PAX_RESULTS("Pax Results"),
	RETURN_TO_OVERVIEW("Return To Overview"), 
	LEG_INPUT("Leg Input"), 
	LEG("Leg"), 
	CLASS_INPUT("Class Input"), 
	MAX_PAX_INPUT(" Max Pax Input"), 
	LA24_INPUT("LA24 Input"), 
	FCP_INPUT("FCP Input"), 
	LUP_INPUT("LUP Input"), 
	GGFC_INPUT("GGFC Input"), 
	AIRL_INPUT("AIRL Input"), 
	MAX_PAX("Max Pax"), 
	FIRST_MEAL_ORDER("1st Meal Order"), 
	TOB_INPUT("TOB Input"), 
	FIRST_MEAL_ORDER_INPUT("1st Meal Order input"), 
	MT1_INPUT("MT1 Input"),
	MT3_INPUT("MT3 Input"), 
	TOB("TOB"), 
	GGFC("GGFC"), 
	LA24("LA24"), 
	LUP("LUP"), 
	AIRL("AIRl"), 
	MT2_INPUT("MT2 Input"), 
	MT1("MT1"), 
	MT3("MT3"), 
	MT4_INPUT("MT4 Input"),
	MT4("MT4"), 
	MT5_INPUT("MT5 Input"), 
	MT5("MT5"), 
	MT2("MT2"),
	AIRCRAFT_CONFIG_POPUP("Aircraft Config Popup"), 
	MEAL_LIST("Meal List"),
	FLIGHT_TEXT_INFO("Flight Text Info"),
	DAILY_OPER_PLAN_INFO("Daily Operation Plan Info"),
	FLIGHT_REMARKS("Flight Remarks"),
	INVOICE_REMARKS("Invoice Remarks"),
	AMENDEMNT_RESULTS("Amendment Result"),
	SPML("SPML"),
	SPML_RESULTS("SPML Results"),
	SPML_RESULTS_LEG("SPML Result Leg"),
	PASSENGER_INFO_BUTTON("Passenger Info Button"),
	PASSENGER_NAME("Passenger Name"),
	SEATING("Seating"),
	SALES_ORDER_LINES("Sales Order Line"),
	SALES_ORDER_GRID("Sales Order Grid"),
	SELECTED_MENU("SELECTED_MENU"),
	HOME("Home"),
	CHANGE_RESTITUTION("Change Restitution"),
	CHANGE_VAT_CODE("Change VAT Code"),
	
	CANCEL_FLIGHT("Cancel Flight"),
    GENERAL_OVERVIEW_TABLE("General Overview Table"),
    PRODUCT_COSTING("Product Costing"),
    CREATE_PRODUCT("Create Product"),
    PRODUCT_NUMBER("Product Number"),
    ADD_ITEM("Add Item"),
    NUMBER("Number"), 
    PRODUCT_NUMBER_POPUP("Product Number PopUp"), 
    CPC("CPC"),
    CPC_PAGE("CPC Page"),
    WASH("Wash"),
    N("None"),
    MED_P("Med P"),
    SIMPLE_PP("Sim PP"),
    PREP("Prep"),
    COOK("Cook"),
    SAVE("SAVE"),
    MPS("Master Production Schedule"),
    DAYS("Days"),
    NAME("Name"),
    ADDRESS("Address"),
    EDIT_MAIN_CUSTOMER("Edit Main Customer"),
    GROUP_NAME("Group Name"),
    GATE_STATUS("Gate Status"),
    SALESDESPATCHCOST("Sales and Dispatch Cost"),
    LINK_TO_UNIT("Link To Unit"),
    MANUFACTURING_OVERHEAD("Manufacturing Overhead Column"),
    GAT_FACTOR("GAT Factor"),
    IPT_FACTOR("IPT Factor"),
    PRODUCTIVITY_FACTOR("Productivity Factor"),
    PRODUCTION_RUN_RATE("Production Run Rate"),
    ASSIGN_CATERING_POINT("Assign Catering Point"),
    PRODUCT_DESCRIPTION("Product Description"),
    UNIT_DEFAULT("Unit Default"),
    USER_DEFAULT("User Default"),
    BASICARTICLEWYFACTOR("Basic Article W/Y factor"),
    BASICARTICLEINFLATION("Basic Article Inflation"),
    INDUSTRYCODE("Industry Code"),
    
    POAPPROVALTRANSFER("PO Approval/Transfer"), 
    RECIEVE_DATE("Receive Date"),
    RECEIVE_ORDER("Receive Order"),
    INVOICE_NUMBER("Invoice Number"),
    INVOICE_INFO_POPUP("Invoice Info Popup"),
    ORDER_AMOUNT("Order Amount"),
    GROSS_AMOUNT("Gross Amount"),
    TRANSFER_VENDOR_INVOICES("Transfer Vendor Invoices"),
    TRANSFER_SELECTED_INVOICES("Transfer Selected Invoices"),
    POSTING_DATE("Posting Date"),
    MONTH_END_TRANSFER("Month End Transfers To SAP"),
    FILE_TYPE("File Type"),
    WASTE_REGISTRATION("Waste Registration"),
    SEARCH_BA_POPUP("Search BA POPUP"),
    SUB_STORE("Sub Store"),
    WASTE_REASON("Waste Reason"), 
    ADD_REASON("Add Reason"),
    ADD_REASON_POPUP("Add Reason POPUp"), 
    RETURNS_COUNTING("Returns Counting"),
    RETURN_QTY("Return Quantity"),
    CLOSE_DATE_CORRECTION("Close Date Correction"), 
    REF_NO_CRITERIA("Reference Number Criteria"),
    FLIGHT_CRITERIA("Flight Criteria"),
    OPEN_CRITERIA("Open Criteria"), 
    CANCELLED_CRITERIA("Cancelled Criteria"), 
    CHECKED_OUT_CRITERIA("Checked Out Criteria"),
    KEY("Key"),
    EXCLUDE_RAW_MAT("Exclude Raw Mat"),
    WFY("WFY"),
    CATERING_UNIT("Catering Unit"),
    CLASS_CODE("CLASS_CODE"),
    MENU_TYPE("Menu Type"),
    MEAL_FACTOR("Meal Factor"),
    AIRPORT_FEE_POPUP("Airport Fee PopUP"),
    RECIPE("Recipe"),
    SALESINVOICETRANSFER("Sales Invoice Transfer"),
    INVOICE_PRICE_QUERY("Invoice Price Query"),
    
    SALES_PRICE_GRID("Sales Code Grid"),
    ADD_LINE_HEADINGS("Add Line Headings"),
    NEW_LINE("New Line"),
    SEARCH_POPUP("Search POPUP"), 
    GROUP("Group"),
    SI("Salvage Indicator"),
    DISCOUNT("Discount"),
    OK_BUTTON("OK"),
    MENU_CONNECTIONS("Menu Connections"),
    WASTEDATE("Waste Date"),
    SALES_NUMBER_DESC("Sales Number Description"),
    IS_ACCEPTED("Is Accepted"),
    QUESTION_MARK("Question Mark"),
    TURNOVERGROUP("Turnover Group"),
    DIVISION("Division"),
    CORRECTINVOICEDATA("Correct Invoice Data"),
    CORRECTFLIGHTDATAINVOICES("Correct Invoice Flight Data"),
    CORRECTFLIGHTS("Correct Flights"),
    PRICEUPDATEGROUP("Price and Turnover Group Update"),
    SELECTSOURCE("Select Source"),
    INVOICEGENERATION("Invoice Generation"),
    TRANSFERGOVTAPPROVAL("Transfer for Government Approval"),
    PRINT("Print"),
    DELIVERYSLIP("Delivery Slip"),
    GOVTDELIVERYSLIP("Govt Delivery Slip"),
    SLIPNUM("Slip Number"),
    SLIPNUM_CHK("Slip Number Check Box"),
    SUMMARYDELIVERYSLIP("Summary Delivery Slip"),
    CLOSEFLIGHT("Close Flight"),
    CREATEINVOICE("Create Invoice"),
    JOBSTATUS("Job Status"),
    ACREG("A/C Registration"),
    RETURNPERCENTAGES("Return Percentages"),
    CALC_ADJUSTPERCENTAGE("Calculate Adjust Percentage"),
    ADJUSTPERCENTBY("Adjust Return PErcentages"),
    SUBMIT_FOR_APPROVAL("Submit For Approval"),
    PRODUCT_NUMBER_RANGE("Product Number Range"),
    FROM("From"),
    TO("To"),
    PREPCOOK("Prep Cook"),
    SET_EMPTYFIELDS_NONE("Set Empty Fields To None"),
    BAKE("BAKE"),
    PORTIONING("PORTIONING"),
    TRAYSET("TRAYSET"),
    EQUIPMENT("EQUIPMENT"),
    SALESERVING("SALE/SERVING"),
    TRANSPORT("TRANSPORT"),
    MAKEPACK("MAKE/PACK"),
    ACCLEAN("AC CLEAN"),
    OTHER("OTHER"),
    HIDE_COMPLETED_CPC("Hide Completed CPC"),
    BOM_DETAILS("BOM Details"),
    CPC_ICON("CPC Icon"),
    TOTAL_CPC_POINTS("Total CPC Points"),
    ARROW("Arrow"),
    CALCULATION_DATE("Calculation Date"),
    LOTSIZE("Lot Size"),
    PACKBOWL("Pack Bowl"),
    LOTALLOWANCE("Lot Allowance"),
    CATERINGPOINTS("Catering Points"),
    MARKSAVE("Mark & Save"),
    PORT("Port"),
    CUTSILPAPER("Cut Sil Paper"),
    INTORD("INTORD"),
    CANCELLATION_MATRIX("Cancellation Matrix"),
    SALVAGEINDICATOR("Salvage Indicator"),
    CANCELTIME("Cancel Time"),
    MONDAY("Monday"),
    ADDSUBCUSTOMER("Add Sub Customer"),
    SHIPTO("Ship To"),
    BILLTO("Bill To"),
    PAYER("Payer"),
    LANGUAGECODE("Language Code"),
    CITY("City"),
    STATEPROVINCE("State/Province"),
    TAXREGDID1("Tax Reg ID 1"),
    TAXREGDID2("Tax Reg ID 2"),
    TAXREGDID3("Tax Reg ID 3"),
    CONTACT_ICON("Contacts Icon"),
    CONTACT_NAME("Contact Name"),
    EXT("Ext"),
    CUSTOMER_CLASS("Customer Class"),
    DEFAULTCLASSDESC("Default Class Description"),
    CUSTOMERCLASSDESC("Customer Class Description"),
    SEGMENTS("Segments"),
    SEGMENT_A("Segment A"),
    SEGMENT_Z("Segment Z"),
    SEALTYPES("Seal Types"),
    SEALTYPEOUTBOUND("Seal Type Outbound"),
	SEALTYPEONBOARD("Seal Type Onboard"),
	SEALTYPEINBOUND("Seal Type Inbound"),
	SEALTYPESECURITY("Seal Type Security"),
	INVOICEDISCOUNT("Invoice Discount"),
	ADDDISCOUNT("Add Discount"),
	AMOUNT("Amount"),
	SECONDARY_NAME("Secondary Name"),
	SAP_NUMBER("SAP Number"),
	SUB_CUST_NAME("Sub Customer Name"),
	ADD_CUSTOMER("Add Customer"),
	ADDTURNOVERGRP("Add Turnover Group"),
	SUBGROUP("Sub Group"),
	SAPGLACCOUNT("SAP GL Account"),
	SALESCATEGORY("Sales Category"),
	UPDATE("Update"),
	INFO_ICON("Info Icon"),
	EDIT("Edit"),
	MEALRELATED("Meal Related"),
	BACKTOMODULE("Back To Module"),
	SERVICETAXCHARGE("Service Tax Charge"),
	PROCESS("Process"),
	REPLACESALESNUMBER("Replace Sales Number"),
	ADDSALESNUMBERSTOFLIGHT("Add sales numbers to flights"),
	DELETESALESNUMBERINFLIGHT("Delete sales numbers in flights"),
	INVOICEDATAVATCHECK("Invoice data VAT check"),
	SETVATONSALESLINES("Set vat on sales lines"),
	CORRECTINVOICENUMBERDATES("Correct invoice numbers and  dates"),
	CHANGE("Change"),
	GRID("Grid"),
	INVOICETYPE("Invoice Type"),
	WHOLEROW("Whole Row"),
	EDITINCIDENT("Edit Incident"),
	SET_FIGURE_EQUAL("Set Figure Equal"),
	GRIDSECONDROW("Grid Second Row"),
	COLLAPSE("collapse"),
	MTF("Menu Text File"),
	CHOOSEFILE("Choose File"),
	DOWNLOAD("Download"),
	DISPATCHACTUALIZEDDATE("Dispatch actualized date"),
    DISPATCHFLIGHTFCP("Dispatch Flight FCP"),
    PIC("Price Impact Chart"),
    ADD_PIC("Add Price Impact Chart"),
    GENERATEOPRS("Generate OPRS"),
    DOWNLOADXML("Download XML"),
    SELECTMONTH("Select Month"),
    INVOICENO("Invoice Number"),
    UPF("Update Production Planning"),
    UHPF("Update HTML Production Planning"),
    CPC_UNIT("CPC Unit"),
    
    DOUBLECLICK("Double Click"),
    FLIGHTSEARCHICON("Flight Search Icon"),
    CUSTOMERCODE("Customer Code"),
    DELETEADDLINE_POPUP_TITLE("Action Can not be Performed "),
    DELETEADDLINE_POPUP_DESC("Delete invoice selection line"),
    REMOVE_RECORD("Record is Deleted"),
    INVOICEGENETATION_MENU_SAVE("Menu save batch list"),
	INVOICEGENETATION_MENU_READ("Read batch list"),
	INVOICEGENETATION_MENU_ERASE("Erase batch list"),
	INVOICEGENETATION_MENU_SAVETITLE("Save new batch list"),
	INVOICEGENETATION_MENU_SAVEBATCH("Batch file:"),
	INVOICEGENETATION_MENU_READBATCHLIST("Batch list name"),
	CLICKBATCHFILE("Click on a batch file"),
	SETPLANNEDPAXTOZERO("Set planned pax to zero"),
    IMPORTFROMFILE("Import from file"),
    UPDATESELECTED("Update Selected"),
	SETSELECTEDTOZERO("Set selected to zero"),
	NOOFFLIGHTSORCLASSES("No. of flight/classes"),
	HISTORYSTARTDATE("History start date"),
	HISTORYSTOPDATE("History stop date"),
	IGNORECLASSES("Ignore classes:"),
	ADJUSTFIGURESBY("Adjust figures by"),
	AUTOINSERTINTOMONTHS("Auto insert into months:"),
	INSERTPAXFIGURESTEXT("Insert Pax figures into"),
	INSERTPAXFIGURESINPUT("Insert Pax figures into input filed"),
	USERMAINTENANCE("User Maintenance"),
	DOMAIN("Domain"),
	FIRSTNAME("First Name"),
	LASTNAME("Last Name"),
	EMAILADDRESS("Email Address"),
	DEFAULTUNIT("Default Unit"),
	ADDUSER("Add User"),
	SAPTAXCODE("SAP Tax Code"),
	ADDTAXCODE("Add Tax Code"),
	SUBSTORECODE("Sub Stores"),
	ADDCURRENCY("Add Currency"),
	C("C"),
	CC("CC"),
	HIDEINACTIVELINES("Hide Inactive Lines"),
	SHOWINACTIVELINES("Show Inactive Lines"),
	PAXFORECAST_MENU_SETFIGURESEQUALTODISPATCHFIGURES("Set figures equal to dispatch figures"),
	SETPLANNEDPAXTOZEROFORMONTHS("Set planned pax to zero for month "), 
    SETPLANNEDPAXFORSELECTEDFLIGHTSTOZERO("Set planned pax for selected flight  to ZERO?"),
    DELETEPAXFIGURES("Delete Pax figures"), 
    FLIGHTGROUP("Flight Group"),
    MENUOPTION("Menu Option"),
    PRICEIMPACTCHART("Price Impact Chart"),
    PRICEPERPAXINTERVAL("Prices per pax interval"),
    PRICEIMPACTCHARTSETUP("Price Impact Chart Setup"),
    STARTPAXQTY("Start PAX Qty"),
    CORRECTFLIGHTS_EDITACTYPEAUTO("Correct Flights Edit Auto Results"), 
    PRICEREDUCTIONPERCENT("Price Reduction percent"), 
    INVOICEQUANTITY("Invoice Quantity"),
    PAXINTERVAL("PAX Interval"),
    SEARCH_GRID("Search Grid"),
    REGION("Region"),
    LANGUAGE("Language"),
    CULTURE("Culture"),
    TIMEZONE("Time Zone"),
    CHANGE_VAT("Change VAT"), 
    SELECT_VAT("Select Vat"), 
    REDUCEPRICEBYPERCENTAGE("Reduce price by %"), 
    CHANGEPAXCONFIG("Change Pax Config"), 
    VIEWACTIVELOG("View active log"),
    EDITUSER("Edit User"),
    MANAGEROLES("Manage Roles"),
    ROLES("Roles"),
    ASSIGNROLES("Assign Roles"),
    EXPANDALL("Expand All"),
    COLLAPSEALL("Collaspe All"),
    EXPANDICON("Expand Icon"),
    USERSYMBOL("User Symbol"),
    CALENDERICON("Calender Icon"),
    SUBMODULE("SUBMODULE"),
    ROLEADDED("Role Added"),
    EXCLUDETASKICON("Exclude Task Icon"),
    ALLMODULES("All Modules"),
	ALLSUBMODULES("All Submodules"),
	ALLTASKS("All Tasks"),
	SETCULTURELANGUAGETIMEZONE("Set culture language timezone and default unit"),
	COPYROLESTOUNITS("Copy Roles To Units"),
	COPYACCESSRIGHTSFROMUSER("Copy Access Rights from User"),
	PRODUCT("Product"),
	SAPTAXCODEINPUT("Sap Tax Code Input"),
	SAPTAXCODEINPUTFIRST("Sap Tax Code Input First one"),
	SAPTAXCODEOUTPUT("Sap Tax Code Output"),
	SAPTAXCODEOUTPUTFIRST("Sap Tax Code Output First one"),
	ADDTAXCODEBUTTON("Add Tax Code Button"),
	INPUTACTIVE("Input is Active"),
	OUTPUTACTIVE("Output is Active"),
	SAPTAXCODEDEFAULTSORTING("Sap Tax Code as default Sorting"),
	SEARCHTYPE("Search Using Type"),
	SEARCHCODE("Search Using Code"),
	SEARCHDESCRIPTION("Search Using Description"),
	SEARCHWHTCODE("Search Using WHT code"),
	TYPE_COLUMNHEADER("Type Header"),
	CODE_COLUMNHEADER("Code Header"),
	WHTCODE_COLUMNHEADER("WHT Header"),
	DESC_COLUMNHEADER("Desc Header"),
	ADDFINANCECOMPONENETBUTTON("Add Finance Component"),
	WHEREISSALESNUMBERUSED("Where Is Sales Numbers Used"),
	SALESNUMBERSTATISTICS("Sales Number Statistics"),
	INCURRENCY("In Currency"),
	COPYDETAILLINES("Copy Details Lines"),
	COPYPRICES("Copy Prices"),
	VIEWCOST("View Cost"),
	COSTCALCULATION("Cost Calculation"),
	SUGGESTEDSALESCODES("Sugggested Sales Codes"),
	PRODUCTION_PAPER_PRINTERS("Production Paper Printers"),
	BASICARTICLE_CONN("Basic Article Connection"),
	VALUE("Value"),
	VALUETYPE("Value Type"),
	CATERINGPOINT("Catering Point"),
	DISPOSE("Dispose"),
	COUNTRETURNED("Count Returned"),
	NONE("None"),
	HELP("Help"),
	P("P"),
	P_MED("P Medium"),
	P_COMPLEX("P Complex"),
	P_EXCLUSIVE("P Exclusive"),
	P_FIRST("P First"),
	USEDESPECS("Used Especs"),
	IMPORT_TIMETABLEDATA("Import timetable data"),
	IMPORT_FTT_ADD_DELIVERYPLAN("Import Flight Time Table Additional Delivery Plans"),
	IMPORT_FTT_ADD_CATERINGSTOWAGEPLANE("Import Flight TimeTable CateringStowagePlans"),
	BACKARROW("Back Arrow"),
	MS_MODULEBLOCK("Functions are not Visible"),
	CREATEDDATE("Created Date"),
	SALESNUMBERRANGE("Sales Number Range"),
	SALESNUMBERCONNECTION("Sales Number Connection"),
	CALCULATOR_ICON("Calculator Icon"),
	FAG("Finance Account Group"),
	CALCULATIONONDATE("Calculation On Date"),
	INCLUDEITEMFORUNITS("Include Items For Unit"),
	USEDESCRIPTIONNUMBER("Use Description Number"),
	INCLUDERECEIPTTEXT("Include Receipt Text"),
	INCLUDEVENDORNAMES("Include Vendor Names"),
	INCLUDELOCALDESC("Include Local Description"),
	CREATERECIPECARDS("Create Recipe Cards"),
	HTML_MENU_SPECS("HTML Menu Specifications"),
	INCLUDEINACTIVEPRODUCT("Include Inactive Product"),
	EXCLUDEPRODUCTS("Exclude Products"),
	INCLUDEPRODUCTS("Include Products"),
	EXISTINGMENUFILES("Existing Menu Files"),
	FILE_NAME("File Name"),
	SHOWORDERS("Show Orders"),
	ADDITIONALCOSTS("Additional Cost"),
	CREDIT_DEBIT_NOTE("Credit Debit Note"),
	CREATE_PRICE_INQUIRY("Create Price Inquiry"),
	INVOICEDATE("Invoice Data"),
	COMMENTS("Comments"),
	ORDERNET("Order Net"),
	ORDERGST("Order GST"),
	TOTAL("Total"),
	CALC_INVOICE_AMT("Calculation Invoice Amount"),
	DIFFERENCE("Difference"),
	ORDERLINK("Order Link"),
	PRICE("Price"),
	NET_AMOUNT("Net Amount"),
	GSTVAT("GST/VAT"),
	DIVIDE_SELECTED("Divide Selected"),
	ADD_DEBITCREDIT_ICON("Add Debit Credit Icon"),
	COST_TYPE("Cost Type"),
	VENDOR_PRICE("Vendor Price"),
	LIST_ALL_PRICES("List All Prices"),
	ARTICLE_NUMBER("Article Number"),
	ORDER_PRICE("Order Price"),
	QUERY_DATE("Query Date"),
	POSTING_REPORT("Posting Report"),
	CREATEPOSTINREPOTSFORSELECTEDINVOICE("Create Posting Report For Selected Invoice"),
	RADIO_BTN("Radio Button"),
	CREDIT("Credit"),
	REFERENCE_NUMBER("Reference Number"),
	CHANGEDATE("Change Date"),
	VIEWCORRECTSTOCKDATES("View Correct Stock Dates"),
	INVENTORYDATE("Inventory Date"),
	SELECTPRICES("Select Prices"),
	ADD_INVOICE("Add Invoice"),
	UPDATEOPRS("Update OPRS"),
	CHECK_OUT_SELECTED("Checkout Selected"),
	LOADQTY("Load QTY"),
	WASTEOB("Waste O/B"),
	WASTESTORE("Waste Store"),
	CORRECTSEALNUMBERS("Correct Seal Numbers"),
	CORRECTBARNUMBERS("Correct Bar Numbers"),
	TRANSACTION_ICON("Transaction Icon"),
	BAR_NO("Bar Number"),
	IMPORTBOXCODE("Import Box Code"),
	SALES_ICON("Sales Icon"),
	ENTERSEALNUMBER("Enter Seal Numbers"),
	ENTERBARNUMBER("Enter Bar Number"),
	CDC("Close Dates Correction"),
	MED_PP("Medium PP"),
	COMPLEX_PP("Complex PP"),
	EXCLUSIVE_PP("Exclusive PP"),
	FIRSTCLASS_PP("First Class PP"),
	SIMPLE_K("Simple K"),
	MEDIUM_K("Medium K"),
	COMPLEX_K("Complex K"),
	EXCLUSIVE_K("Exclusive K"),
	FIRSTCLASS_K("First Class K"),
	SIMPLE_KK("Simple KK"),
	MEDIUM_KK("Medium KK"),
	COMPLEX_KK("Complex KK"),
	EXCLUSIVE_KK("Exclusive KK"),
	FIRSTCLASS_KK("First Class KK"),
	SIMPLE_P("Simple P"),
	COMPLEX_P("Complex P"),
	EXCLUSIVE_P("Exclusive P"),
	FIRSTCLASS_P("First Class P"),
	SETACTIVITYGROUP("Set Activity Group"),
	UPDATEOTHERACTIVITIES("Update Other Activities"),
	HELPSELECTCORRECTACTIVITY("Help Select Correct Activity"),
	RECIPETEXT("Recipe Text"),
	NEW_ACTIVITY("New Activity"),
	PRIMARY_CATERING_PTS("Primary Catering Points"),
	COSTING_PURPOSE("Costing Purposes"),
	NO_OF_INGREDIENTS("No Of Ingredients"),
	COOKING_ATTENDENCE("Cooking Attendence"),
	TYPE_OF_INGREDIENT("Type Of Ingredients"),
	BATCHSIZE("Batch Size"),
	DISHWASHING("Dish Washing"),
	ASSEMBLY("Assembly"),
	GAT("GAT"),
	IPT("IPT"),
	PROD_FACTOR("Prod Factor"),
	ASSIGN_WORKCENTER("Assign WorkCenter"),
	WASHED_STD_BOX("WASHED STD BOX"),
	STD_TIME("STD Time"),
	SHOW("Show"),
	PRIMARY_STORE_CODE("Primary Store Code"),
	CALC_ADJUST_PERCANTAGE("Calculate Adjust Percentage"),
	HEADER("Header"),
	BODY("Body"),
	PRINT_DISPATCH_CONTROL_LIST("Print Dispatch Control List"),
	CLOSE_FLIGHT_BY_CUSTOMER("Close Flight By Customer"),
	REOPEN_FLIGHT_BY_CUSTOMER("Reopen Flights By Customer"),
	CREATE_CLOSEDATE_DOCUMENT("Create Close Date Document"),
	FLIGHT_ICON("Flight Icon"),
	VIEW_FLIGHT_ACTIVITY_LOG("View Flight Activity Log"),
	NO_OF_FLIGHTS("No Of Flights"),
	GLOBALDESCRIPTION("Global Description"),
	EMM("EMM"),
	ADD_MAN_MINUTES("Add Man Minutes"),
	SAVEORDERFORM("Save Order Form"),
	CREATE_MULTIPLE_PO("Create Multiple PO"),
	PURCHASE_ORDER_PROPOSAL("Purchase Order Proposal"),
	RESEND("Resend"),
	IN_TRANSIT("In Transit"),
	VIEW_LINK_ORDER("View Link Order"),
	TOTALPRICE("Total Price"),
	AIRLINE("Airline"),
	ENTER_DOCUMENT("Enter Document"),
	VENDORINVOICEENTRY("Vendor Invoice Entry"),
	WHEREBOXCODEUSED("Where Box Code is Used");
	
	
	public String element;
	private ElementNamesEnum(String element){
		 this.element = element;
	 }
	public void SetObjName(String value){
		element=value;
	}
	public String getObjName(){
		return element;
	}
	
}